### ISSUE TITLE
Implement recommendations from RRA for MoFo Hosted Donation pages

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1]
Just noting this here so it's easy to find later: https://docs.google.com/spreadsheets/d/1dwK7TaR4rqgTTgWbB5zNTjXQ-SugzIq2zlkK6KICZ8Q/edit#gid=0 https://bugzilla.mozilla.org/show_bug.cgi?id=1170623

**Comment by adamlofting** [comment]
:+1:

**Comment by adamlofting** [comment]
I think we've filed all these bugs, but let's review when we get to #82

**Comment by alicoding** [comment]
we've filed all the bugs
