### ISSUE TITLE
Create a 'Donations by Language' graph

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1002]
@davidascher had an interesting idea to create a Donation by ~~Currency~~ language visualization on fundraising.mozilla.org.

@jbuck would this be a lot of work? I think it could be really interesting to display this data.

**Comment by edrushka** [comment]
cc @valianttry

**Comment by davidascher** [comment]
No, donations by language.  As useful feedback to localizers.

**Comment by adamlofting** [comment]
We could get pretty decent data quite quickly by matching browser language in Google Analytics to conversion tracking. 

To get the most accurate data we would add the locale field to the transactions database, and include this in the Stripe and Paypal extracts. Stripe definately records locale against a transaction, but we'd need to check if Paypal has this captured too.

I'll work on the simple option this morning, then if we want to and have time we can upgrade to the other version later.

**Comment by adamlofting** [comment]
Data is now available here:
http://transformtogeckoboard.herokuapp.com/eoy/transactionsbylanguage

This is in the same format as the donations by source, so should be able to use the same graph configuration pretty easily.

**Comment by jbuck** [comment]
@adamlofting nice!

**Comment by edrushka** [comment]
Thanks Adam!!!! 
![eagle](https://cloud.githubusercontent.com/assets/4515662/11507915/20026fde-980b-11e5-9db9-01fd2841929f.png)

**Comment by adamlofting** [comment]
I'm not going to have time to work on this. Also, I'm not sure where the fmo codebase lives. 

@jbuck could you add a note in this bug pointing to the repo for fmo homepage?

**Comment by jbuck** [comment]
@adamlofting https://github.com/mozilla/eoy-fundraising

**Comment by stephaniemcv** [comment]
Closing during FR work-week. This is happening somewhere else with data analyst and crm
