### ISSUE TITLE
Add "check your email for confirmation" language after signing up for email

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1008]
We've been getting some emails from some people confused by our ET double opt-in email. We should add language that tells people to expect a confirmation email in their inbox!

**Comment by adamlofting** [comment]
I don't think this will clash, but noting just in case.

The post email opt-in page is the 'share' page. And we're running an Optimizely test on that at the moment. https://app.optimizely.com/results2?experiment_id=4018680415&token=5bb348bb996a46d59eac#view=2

That test will likely be finished before we get to this ticket, but if not let's make sure we coordinate.
