### ISSUE TITLE
Localized Thank You pages not working

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#101]
This is the current DE thank you page (see URL in screenshot):

<img width="720" alt="screenshot 2015-07-28 14 26 46" src="https://cloud.githubusercontent.com/assets/1901816/8932361/91dbbd66-3534-11e5-9fc7-27e2453e7e45.png">

First, it's in English.

Second, we actually don't use the email sign-up form as the thank you page for non-english locales, because we're not able to write localized emails for these audiences.

I think we needed to be generating localized versions of the share page instead. Is this how it's currently setup in BSD?

* http://donate-mozilla.herokuapp.com/share/ < works
* http://donate-mozilla.herokuapp.com/share-de/ < doesn't exist currently

**Comment by alicoding** [comment]
I think this can be closed now and we can just file a bug to improve the thank you page to include share button for non English version.

**Comment by adamlofting** [comment]
I've filed a bug for improving the share in the non-english versions #107 

But don't we still need to do work to get thank-you-{locale} working without the sign-up form?

**Comment by ScottDowne** [comment]
This landed, commit escaped me atm.

**Comment by ScottDowne** [comment]
Ah, here it is: https://github.com/mozilla/donate.mozilla.org/commit/f95d3ae43cd9dbebd3e2a7de26771280360af736
