### ISSUE TITLE
$100/ month donation failed - why?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1015]
cus_7S1ZzvhhfZM0Of

Stripe says it "failed"

His email:

![strange_interaction_flow_for_monthly_donations_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11522882/814097ba-9871-11e5-91af-517628c52bc1.png)

**Comment by jbuck** [comment]
@ScottDowne sounds like the error handling on this page isn't working as expected

**Comment by jbuck** [comment]
@valianttry unfortunately I don't know why the donation failed, just that his bank rejected the charge.

**Comment by ScottDowne** [comment]
Hm, it's this card

4100000000000019: "Charge will be declined with a card_declined code and a fraudulent reason."

But Stripe handles this one. which is similar to the above.
4000000000000002	Charge will be declined with a card_declined code.

All other cards are handled inside the Stripe widget, but for some reason that one is not. Maybe they expected us to handle it? I'll look for any error's we're not handling.

**Comment by ScottDowne** [comment]
@jbuck can I steal this issue from you?

**Comment by ScottDowne** [comment]
This should fix it so a fraudulent error message is displayed: https://github.com/mozilla/donate.mozilla.org/pull/1023

**Comment by ScottDowne** [comment]
Landed on staging.
