### ISSUE TITLE
We might want to do a bit more QA for Firefox for Android

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1016]
Hey @adamlofting 

I was just exploring Google Analytics and noticed our mobile conversion seems better compared to last year (granted it's a smallish sample, but still). It's nearly 3%. The device breakdown suggests iPhone and iPad are converting much better than Firefox for Android, which seems counter-intuitive. Given the higher traffic from FF for Android, maybe we should do a bit more QA in FF for Android?

![devices_-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/11524303/a169ef0c-987e-11e5-81c4-8498e6e55843.png)

**Comment by adamlofting** [comment]
We should keep an eye on QA for the most important devices, but I still think this conversion rate is a combination of context and the end-to-end user experience. 

For the 'context' piece. The setting for using an iPad versus an Android phone affects your likelihood of completing a donation.

But more importantly, the conversion rate for mobile seems to reflect how much reason we've given people to donate. 

This is just for 'mobile' traffic:
<img width="1182" alt="screenshot 2015-12-02 09 55 10" src="https://cloud.githubusercontent.com/assets/1901816/11527918/9f6e8ab6-98db-11e5-8ca4-2d00a5b90a9e.png">

If we have an ask in the Firefox for Android snippet this year, we should expect to see gains from the new 'additional info' page @ScottDowne has been working on.

**Comment by valianttry** [comment]
I broke out the medium / source for mobile giving and it's interesting: https://www.evernote.com/l/AMpWfz734MxPQZ3FJh2sS4ioXbp_la-8hHoB/image.png 

The sample size is pretty small... but our mobile conversion is outstanding for email. I'm so interested to see the impact of our "more info" landing page....

![devices_-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/11553423/6bdfb43c-9943-11e5-9889-a901afea44f1.png)

**Comment by valianttry** [comment]
Nothing to do right now
