### ISSUE TITLE
Our first six disputed charges in Stripe!

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1020]
@valianttry https://dashboard.stripe.com/disputes/overview

I recommend that we "Accept dispute" since a refund is the only thing we can do but I wanted to flag it so we all get an idea of how to handle disputes.

**Comment by ScottDowne** [comment]
Those duplicates I am pretty sure are covered now in https://github.com/mozilla/donate.mozilla.org/commit/b987bbeda3b7902b2f331cf9431f320cafc2caa8

Which landed on the same day but not quite fast enough :(

We can do more to catch this at the server too if we want, but it's not critical anymore.
