### ISSUE TITLE
Example of encouraging monthly giving

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1029]
Check out what happens when you select 'monthly' on Khan Academy's donation form:

<img width="1262" alt="screenshot 2015-12-03 13 51 16" src="https://cloud.githubusercontent.com/assets/1901816/11562290/015b1d40-99c5-11e5-9c2f-10a29113d49a.png">

<img width="1333" alt="screenshot 2015-12-03 13 50 59" src="https://cloud.githubusercontent.com/assets/1901816/11562293/0571bf06-99c5-11e5-9fef-d8a4e1efb34b.png">

The joy!

cc @edrushka @valianttry

**Comment by alicoding** [comment]
Was going to suggest the same for using button instead of radio because it's not really getting the attention when you have a glance at the form. But that joy when you choose monthly is awesome! Maybe our dapper Fox can be there haha.
