### ISSUE TITLE
Synchronous XHR on thank you page

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1030]
We currently use synchronous XHR to load the exchange rates json file. Lets not do this...

**Comment by alicoding** [comment]
Should we setup an API endpoint for this instead?

**Comment by jbuck** [comment]
Possibly! But I'd like to change the code to not use synchronous XHR's first, since that brings the browser to a halt until the file has loaded.

**Comment by jbuck** [comment]
@alicoding will fix this in #1131

**Comment by alicoding** [comment]
Landed \o/
