### ISSUE TITLE
A/B Test: move frequency radio buttons above amount buttons

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#1033]
The following links have the frequency option before the amount buttons. This might help with array position changes and visibility with the frequency radios. It's also more intuitive to pick frequency first if we change amounts based on frequency.

http://www.unicef.org.uk/donate/donate-now/
http://www.oxfam.org.uk/donate
https://donate.wikimedia.org/
https://www.khanacademy.org/donate

These are the ones I have found, I am sure there are others, and there are lots that do it differently too.

I also noticed not many of them have these as radio buttons, but as larger buttons or dropdowns.

**Comment by valianttry** [comment]
@adamlofting seems like a good test. @ScottDowne do you know how much work it would be to set this up on the form?

**Comment by ScottDowne** [comment]
@valianttry minute or two to move it above the amounts, an hour or so to make them buttons or a dropdown. Coul be two separate tests if we wanted.

**Comment by adamlofting** [comment]
This is a great point, and we can run this as two tests.

We can test it on the form and if it helps think about how we apply the same learning to the snippet. 

ps: It' interesting that wikimedia's option is a button-and-a-radio

**Comment by adamlofting** [comment]
Note from Scott in the related bug:
> @adamlofting For what it's worth, we can run a test for this now: https://donate.mozilla.org/en-US/?test=frequency-move-test

**Comment by jbuck** [comment]
@adamlofting if you're not running this test then feel free to Bluesky it!
