### ISSUE TITLE
Launch the "EOY totalizer" on Moz office monitors

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1037]
In past years we've displayed the EOY fundraising campaign "ticker" on office monitors. It is a running total of campaign donations. We've passed $1.2 million. I think it can be a simple website setup. It'll look something like below screengrab (numbers will increase every few minutes). Pinging @potch for helpful guidance.

![mozillafundraising_banner2015_final_ai_-_google_drive](https://cloud.githubusercontent.com/assets/9830371/11577745/164f402c-99d5-11e5-937f-edfd019b4a7a.png)

**Comment by valianttry** [comment]
cc @alicoding since he built the new totalizer for fundraising.mozilla.org.

**Comment by valianttry** [comment]
cc @davidascher

**Comment by potch** [comment]
Does the above page exist? If so this should be pretty easy.

**Comment by alicoding** [comment]
Right now the page doesn't have totalizer on, but hopefully @jbuck can help
push that up tomorrow.

**Comment by valianttry** [comment]
@potch i think we may have created a custom web page with just the totalizer on display. If you visit fundraising.mozilla.org the totalizer @alicoding is building is basically the header. Does that sound right?

**Comment by alicoding** [comment]
@potch the totalizer is now up on https://fundraising.mozilla.org let me know if you need anymore info.

Thanks!

**Comment by davidascher** [comment]
I think we want a URL that isn't the whole blog just the totalizer. That's
what we add to the screens. Or ideally a fork that has the copy from the
mockup aimed at people in offices.

**Comment by potch** [comment]
Just updated the existing TV totalizer here: http://moz-funds.herokuapp.com/

**Comment by valianttry** [comment]
omg @potch that's perfection! :)

How do we disseminate that this exists to the monitor monitors? E.g. how do we "make it so" :rocket:

**Comment by potch** [comment]
@valianttry done! https://github.com/mozilla/moz-corsica/commit/359d9827466d65b21cf1b4ad31dd1324381d6920 Was just waiting for sign-off :)
