### ISSUE TITLE
Localize additional directory tile variants

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1039]
@natalieworth's additional directory tile designs #880 have been finished and approved by MoFo and the tiles team. :clap:

Natalie has exported the assets here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0XzVDQnY5V1c4RGc

@alicoding can you please set this up on Pontoon like you did with #812?

**Comment by edrushka** [comment]
@alicoding any updates?

**Comment by alicoding** [comment]
Sorry, I'm working on it right now and will update here once I have a PR up.

**Comment by edrushka** [comment]
Changing this to a P1 to ensure the designers have time to add the localized strings to the designs and export the files. cc @lovegushwa @natalieworth

**Comment by alicoding** [comment]
This is now up on Pontoon and you can see them on staging as well https://donate.mofostaging.net/directory-tiles/

**Comment by edrushka** [comment]
Yay! Did you sent an email to the L10N list?

**Comment by alicoding** [comment]
Yup :)

**Comment by edrushka** [comment]
Closing this. Natalie has exported the files.
