### ISSUE TITLE
Twitter Card still not updated

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1040]
Would like to eliminate the old Twitter Card from being shared in favor of the red one -- do we know why this keeps happening?

![_mozilla_-_twitter_search](https://cloud.githubusercontent.com/assets/9830371/11580579/af672924-99ed-11e5-9d46-e883bebf23b6.png)

**Comment by valianttry** [comment]
Looks like it's pt-BR also:
![_mozilla_-_twitter_search](https://cloud.githubusercontent.com/assets/9830371/11580630/2d9f503c-99ee-11e5-8164-5810bf59b72b.png)

**Comment by alicoding** [comment]
The URL for the twitter card is definitely updated on production : https://donate.mozilla.org/assets/images/EOY_Twitter_v8_EN.d1bb5d2a5ce35859d038df852d9e6a0a811beaac.png 

Let me check if we can do anything on twitter's side

**Comment by alicoding** [comment]
Updated

https://twitter.com/alicoding/status/672609609752821761

**Comment by alicoding** [comment]
I have also checked for `pt-BR`, `fr`, `de`, `es` and `it` to make sure they get the red image instead.

**Comment by alicoding** [comment]
Closing this. If we still have an issue please reopen and I'm happy to investigate further.

**Comment by valianttry** [comment]
@alicoding what did you do to fix the problem exactly? Just so we have it documented.

**Comment by alicoding** [comment]
Sorry! I totally forgot to mention this. I used this link https://cards-dev.twitter.com/validator to hard refresh / force twitter to fetch new URL for the image now.

**Comment by valianttry** [comment]
:clap: hurray!
