### ISSUE TITLE
Increase in snippet traffic 25% - 50% appears to have had no impact

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1041]
@adamlofting apparently the snippet traffic was supposed to have increased from 25% - 50% on Tuesday. I'm looking at sessions in Google Analytics since then, and there appears to be no impact, which can't be correct. Jean is checking things on her end, but can you check our analytics?:

![all_traffic_-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/11580901/06729a84-99f1-11e5-9c72-ea354fa8da03.png)

**Comment by adamlofting** [comment]
Looking at Snippet data in this spreadsheet (column BG) the number of impressions hasn't increased significantly yet.
https://docs.google.com/spreadsheets/d/1Inh1KSkXSh8cJiCnvwm00JOq85FsPQR5L3pzPzQBBio/edit#gid=9&vpid=AW45
