### ISSUE TITLE
Possible to change a 1x gift to monthly if requested by a donor?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1043]
Stripe ID: ch_17E5vnG8Mmx3htnxHQFWuuK3

![re_donation_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11581630/da138b9e-99f8-11e5-84b9-64be8363337c.png)

**Comment by valianttry** [comment]
I'm going to try Stripe support for this one....

**Comment by jbuck** [comment]
Okay, I've added the subscription according to Stripe support directions. Pretty easy!

@valianttry do you want to email the customer, or do you want me to?

**Comment by jbuck** [comment]
@valianttry also I set a trial period so they'll be billed starting on the 3rd of January

**Comment by jbuck** [comment]
@valianttry have you emailed this donor yet? Would you like me to email them?

**Comment by valianttry** [comment]
I'll email her now!

**Comment by valianttry** [comment]
Done!

**Comment by jbuck** [comment]
:tada:
