### ISSUE TITLE
Possible to offer yearly donation option?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1044]
I'm seeing a few requests to donate "yearly" -- is this possible with Stripe? How hard would this be to do for dev?

![yearly_donation_possible_or_in_euros__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11581888/570c76b2-99fc-11e5-803a-ad7ca6146f91.png)

Sort of like this:
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11581914/b4c69dd2-99fc-11e5-8a29-2f2eaa788376.png)

**Comment by valianttry** [comment]
@adamlofting did WWF offer yearly as an option? Know anything about this practice?

**Comment by ScottDowne** [comment]
I'm pretty sure Stripe makes this easy,

**Comment by adamlofting** [comment]
> did WWF offer yearly as an option? 

We didn't do yearly, but did a yearly renewal campaign each December for people who adopted an animal as a gift with a one-time purchase. 

> Know anything about this practice? 

Technically it's pretty simple, but have heard some concerns about people forgetting after a year and being annoyed/confused when money comes out of their account.

> I'm pretty sure Stripe makes this easy

* Definately worth testing if adding this to the form impacts conversion for other donors.
* This could also be a separate form we don't show to most people, but that we can send in a reply when people as for this

> also

I'm guessing this person was still seeing the sendto form, given they can't see EUR as an option.
