### ISSUE TITLE
Make the new UI the default

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1049]
I'm going to write up the test results for the blog, but the short answer is the new UI had no significant impact on conversion so we should roll it out and simplify another bit of our codebase.

<img width="1065" alt="screenshot 2015-12-04 15 50 55" src="https://cloud.githubusercontent.com/assets/1901816/11593956/1a828954-9a9f-11e5-82e4-d17d03df7936.png">

cc @ScottDowne as you know how this code is wired up.

I've put it in this heartbeat as 'Needs Prioritizing' - even if implementing this gets bumped to next week.

**Comment by ScottDowne** [comment]
I think we'll two this in two tasks.

One, we just add the classname to the code, and it becomes default.

Then we can remove the old css and clean up some things in a followup.

**Comment by ScottDowne** [comment]
@adamlofting Is it fine if I ship these changes to the additional info page too?

It's running a test right now, and I don't want to potentially skew results.

**Comment by adamlofting** [comment]
@ScottDowne yes, thats's fine. The people in the 'additional info' test we're also being split 50:50 into the new versus old UI at the same time.

**Comment by ScottDowne** [comment]
The test in hard coded to on now, but I'll leave this open as a follow up to clean up and remove any artifacts from the old css.

**Comment by ScottDowne** [comment]
The test was completely removed a few weeks ago.
