### ISSUE TITLE
f.m.o minor bugs

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1054]
@alicoding, the new f.m.o. looks great, I'm just seeing a couple of minor issues (definately P2):

- [ ] Blog content column got a bit squished:

<img width="1087" alt="screenshot 2015-12-04 17 13 43" src="https://cloud.githubusercontent.com/assets/1901816/11596004/75960b62-9aaa-11e5-8986-9ecfc4e27fb4.png">

- [ ] Grey text shadow on the heading in the banner is a bit weird on the red background. It's playing tricks on my :eyes: 

<img width="313" alt="screenshot 2015-12-04 17 15 06" src="https://cloud.githubusercontent.com/assets/1901816/11596026/97a5fd34-9aaa-11e5-8a9f-52efb1bc0f3e.png">

**Comment by valianttry** [comment]
The numbers in the box also appear to be slightly higher than center on the vertical:

![mozilla__view_source_fundraising___we_work_in_the_open__we_fundraise_in_the_open__this_site_shows_you_how_we_work__shares_what_we_know__and_challenges_you_to_help_us_do_it_better_](https://cloud.githubusercontent.com/assets/9830371/11598304/f85040c0-9a75-11e5-9425-2da3c47180bf.png)

**Comment by ScottDowne** [comment]
@adamlofting yeah, that text shadow is weird. Kinda makes it look bold.

**Comment by ScottDowne** [comment]
Sometimes I see this.
![total](https://cloud.githubusercontent.com/assets/197334/11599739/821b8c04-9a96-11e5-9545-cc158a6acf90.png)

**Comment by ScottDowne** [comment]
It's also not displaying the cents zero padding.

So, $5.10 is displayed as $5.1

**Comment by alicoding** [comment]
pull request is up here https://github.com/mozilla/eoy-fundraising/pull/21

**Comment by alicoding** [comment]
https://github.com/mozilla/eoy-fundraising/pull/21 merged on the repo. Next up will wait for @jbuck to help push this up on the box.

**Comment by valianttry** [comment]
Found it! @alicoding can you get to this this week?
