### ISSUE TITLE
Design a dev edition snippet

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1060]
As part of the Spectacular Snippet #560 design work, we came up with a couple fun options for a dev edition snippet. This is out of scope for EOY 2015, but parking it here in Bluesky in case a future opportunity arises. 

** Note that everything in the 2 designs below is conceptual only. We did not polish the copy or design.**
![screenshot 2015-12-04 13 53 50](https://cloud.githubusercontent.com/assets/4515662/11602363/8b808072-9a8e-11e5-944d-04464d873575.png)
![screenshot 2015-12-04 13 53 32](https://cloud.githubusercontent.com/assets/4515662/11602364/8d8f2044-9a8e-11e5-9816-322dbed1bbbb.png)

**Comment by edrushka** [comment]
@natalieworth could you please export the AI files and link to them here in case anyone picks this up again in the future? Thank you!

**Comment by edrushka** [comment]
Also, for the archives, credit for these designs belongs to @lovegushwa and @natalieworth with input from @cassiemc  :)

**Comment by natalieworth** [comment]
@edrushka I've uploaded an .ai file for google drive of the draft versions and copy for the dev edition snippet: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0Z0ktM0ROWEVYREU It's got the process versions included too from @lovegushwa
