### ISSUE TITLE
Should we replace MMYY with Expiration Date?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1067]
Got an email from someone in NZ who said they were confused by our form because they didn't know what "mmyy" meant. I looked at Wikipedia's form, and it says "expiration date" with drop downs. I don't know that we need to do a wholesale redesign, but this is something we should consider changing (or testing?) so that field is more localization-friendly:

![make_your_donation_now_-_payments](https://cloud.githubusercontent.com/assets/9830371/11612237/f1b4f79c-9ba6-11e5-9b26-f36d0a29de3b.png)

**Comment by alicoding** [comment]
In term of localization and technical side its actually easy to change to drop down and k agree with the user here that 'mmyy' is not obvious what we are asking unless they have used the same kind of forms before.

Maybe we should test to see if this could bring down the conversion rate and if not we should totally switch to it.

**Comment by adamlofting** [comment]
Are we still managing the expiration date, or is this in Stripe checkout now?

This would be a nice test, but I don't think we're managing this now.

**Comment by jbuck** [comment]
Gooooood point.
