### ISSUE TITLE
Revisit the privacy policy checkbox copy

### ISSUE THREAD

**Issue by kyoshino** [mozilla/donate.mozilla.org#1076]
I have reported the same issue on Bedrock before ([Bug 937986](https://bugzilla.mozilla.org/show_bug.cgi?id=937986), https://github.com/mozilla/bedrock/pull/1448). The current copy on the privacy policy checkbox reads "I’m okay with **you** handling this info as **you** explain in your privacy policy", while the error message reads "To submit this form **you** must agree with our privacy policy". The former is confusing as **you** means Mozilla so it should be revised.

Found in Mozlando.

**Comment by kyoshino** [comment]
How are we handling l10n here?

**Comment by jbuck** [comment]
We'd need to update https://github.com/mozilla/donate.mozilla.org/blob/e2ebb60a97998bb79a3dc55b2e58730d3deaa060/locales/en-US/messages.properties#L33

**Comment by kyoshino** [comment]
Yeah, I'll send a PR.

**Comment by jbuck** [comment]
Actually, weird I wonder why we have two copies of the Privacy Policy
language:
https://github.com/mozilla/donate.mozilla.org/blob/e2ebb60a97998bb79a3dc55b2e58730d3deaa060/locales/en-US/messages.properties#L40

**Comment by kyoshino** [comment]
Looks like `i_am_okay_with` is no longer used. Will remove it.
