### ISSUE TITLE
Test reduced address fields for Stripe checkout form

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1079]
This is the testing ticket.

We'll file a build ticket next.

**Comment by adamlofting** [comment]
This test is live:
* http://app.optimizely.com/l/s3h3UY?token=850ff44f4dcb945fba28#view=2

**Comment by valianttry** [comment]
I just looked at the results and reduced fields is LOSING. I'm in disbelief.

**Comment by adamlofting** [comment]
I was just checking in on this too. I've stopped the test running now. 

I'd have bet on this variation winning! People are so strange :8ball:

**Comment by valianttry** [comment]
@adamlofting is there any way to enable this for mobile? Or can we check results of this test for mobile users? Jean launched the FF for Android snippet....

**Comment by adamlofting** [comment]
We can't do a perfect test in this case because the `mobile-snippet` traffic is pointing to https://donate.mozilla.org/en-US/about/ and the reduced address fields is being testing on the `non-additional-info` version of the form https://donate.mozilla.org/en-US/partial-page/

But I've started up an A/B test comparing those two pages anyway. If there's a winner, we won't know if it's due to the address fields or the additional info, but at least we'll be able to switch the winned live for the remainder of the campaign. :+1:
