### ISSUE TITLE
Build version of form with reduced fields in Stripe Checkout

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1080]
Test ticket is #1079

**Comment by ScottDowne** [comment]
Just a heads up, with stripe checkout, there is no way to remove address and keep the name field that I can see in the docs.

https://stripe.com/docs/checkout#integration-custom

We can turn on zip code without address, and we should.

**Comment by valianttry** [comment]
yes, zip code without address. Make it so! :rocket:

**Comment by ScottDowne** [comment]
@valianttry you only commented on the zip bit, but didn't say anything about name field also going away.

Does that mean you're fine with name being removed as part of address? We don't have a choice in the matter, but I am just making sure it's not a surprise.

**Comment by valianttry** [comment]
It is perfectly fine by me. When someone opts in to our email list right now, they do not provide their name anyway (only email address). That means we can't personalize emails, e.g. "Dear Katie,"

So name is of no use to us at the moment. I would feel better if @adamlofting agreed with me :+1:

**Comment by ScottDowne** [comment]
@valianttry OK perfect.

**Comment by ScottDowne** [comment]
It's cool, stripe checkout doesn't show the zip field until they have entered a few other fields.

It's like "surprise, you have to type more :D".

**Comment by valianttry** [comment]
We should just be sure to watch our fraud velocity on this form variant to make sure we don't get a spike, or at least one so big it becomes a drag.

**Comment by ScottDowne** [comment]
We might be able to look in Stripe to see how many have failed because of address fields and fraud to get an idea.

**Comment by ScottDowne** [comment]
But should still keep an eye open, because once a fraudster see the hole, they might target it, vs now which they would give up.

**Comment by ScottDowne** [comment]
Wasn't too hard: https://github.com/mozilla/donate.mozilla.org/pull/1115

Should be ready way before the current test finishes :D

**Comment by jbuck** [comment]
@valianttry should I remove the "Dear {name}" customization from the email we send out?

**Comment by valianttry** [comment]
Let's just use "Hello," as our salutation.

**Comment by jbuck** [comment]
@valianttry only downside to using that string is that it'd require translation, and while it was being translated users would be presented with the english string

**Comment by valianttry** [comment]
We can omit a salutation altogether for expediency.

**Comment by jbuck** [comment]
okay, solid

**Comment by adamlofting** [comment]
@ScottDowne is there a way to activate this test without adding the parameter? (Like we've done with class names in Optimizely for the other tests)

https://donate.mofostaging.net/en-GB/?billingAddress=partial

(FYI optimizely can get a bit confused by redirecting to the same URL with an added parameter because of the URL matching rules - it's not impossible to setup, but a bit fiddly)

**Comment by ScottDowne** [comment]
@adamlofting no, it's not css, it's a js param passed into stripe, it has to be a param, but there is no delay because it's not rendering anything.

**Comment by jbuck** [comment]
@ScottDowne but we could feature detect based on a CSS class right?

**Comment by ScottDowne** [comment]
@jbuck we could and is an option but is a bit of a hack. As that is not
what classmates are for. I think I would attempt a small new page first.
Might be cleaner as the form is already a component that accepts a param
for this.

**Comment by adamlofting** [comment]
No worries, I just wanted to double check :+1: 

I'll take a look at setting up the Optimizely test using the parameter first of all. If that proves problematic we can set this test up as a new URL which is identical to one-page (aka the root) except for the parameter on that componenet changing.

**Comment by adamlofting** [comment]
Setting up a duplicate page was much easier that hacking optimizely for this test, so I'm going to do it that way.

**Comment by jbuck** [comment]
@adamlofting Scott landed this in https://github.com/mozilla/donate.mozilla.org/pull/1126 I think, but we totally didn't update this bug! :fearful:
