### ISSUE TITLE
Add general Mozilla contact number to our Coinbase profile

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1082]
I forgot my login @jbuck . Can you help?

Email from Rachel, our rep:

A general number would be great. And as it turns out, I am unable to add on behalf of Mozilla. Do you have access to Mozilla's Coinbase account? If you can update there in your merchant profile, when you get back from your retreat, that would be great!

**Comment by jbuck** [comment]
@valianttry done!
