### ISSUE TITLE
Double check Paypal monthly donation flow

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1083]
Following feedback from @bniolet1 I ran through the monthly Paypal flow this morning and see the same issues.

What did happen:
* Paypal checkout flow was for the correct amount, and setup for 'pre-approved payment' mode
* The checkout completed and I ended up on the thank you page with the paypal transaction success parameters in the URL `?frequency=monthly&tx=K6GWWCLX57LQE14497599137.84&amt=2.00&cc=GBP` 

The above *suggests* things are working correctly. But we need to explore the following potential issue:
* I have not yet received a transaction reciept from paypal, or a thank-you email from Sawmill (not in spam folder either)
* Logging into Paypal, the transaction is not showing up in my recent transactions, or in my list of 'My pre-approved payments'

***Possibilities***

1. Something is wrong, and we're not processing these transactions
  * If so, fix urgently.
2. Monthly donations are not processed immediately? 
  * If so, find out when they are processed, and let's inform people. 
  * If so, can we confirm we're sending sawmill emails when these are processed?

cc: @valianttry 

@jbuck - can you start by looking up my transaction in the MoFo Paypal account?
@ScottDowne - any other thoughts on places to investigate right away?

**Comment by adamlofting** [comment]
Something from the Paypal docs that might be relevant:

> The profile may take up to 24 hours for activation.

<img width="1009" alt="screenshot 2015-12-10 10 48 24" src="https://cloud.githubusercontent.com/assets/1901816/11720058/9e818472-9f2b-11e5-91b7-59f3a51beb5c.png">
https://developer.paypal.com/docs/classic/api/merchant/CreateRecurringPaymentsProfile_API_Operation_NVP/

**Comment by jbuck** [comment]
```
{ ADDRESSOWNER: 'PayPal',
  ADDRESSSTATUS: 'None',
  TIMESTAMP: '2015-12-10T16:22:59Z',
  CORRELATIONID: '29e84804c18ed',
  ACK: 'Failure',
  VERSION: '97.0',
  BUILD: '18308778',
  L:
   [ { ERRORCODE: '10004',
       SHORTMESSAGE: 'Transaction refused because of an invalid argument. See additional error messages for details.',
       LONGMESSAGE: 'The transaction id is not valid',
       SEVERITYCODE: 'Error',
       TAXABLE: 'true' } ],
  PENDINGREASON: 'None',
  REASONCODE: 'None' }
```

**Comment by jbuck** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/pull/1084

**Comment by adamlofting** [comment]
Testing since the fix, this showed up as a `Purchase`, but not a `Pre Approved Payment` in my activity feed - can we check that's expected?

<img width="939" alt="screenshot 2015-12-10 12 51 29" src="https://cloud.githubusercontent.com/assets/1901816/11723504/c1446590-9f3c-11e5-951b-bb212ccb984d.png">

`?frequency=monthly&tx=K6GWWCLX57LQE14497695635.68&amt=2.00&cc=GBP`

And it does not appear in my list of Pre Approved Payments (at least not yet).

**Comment by bniolet1** [comment]
So when this is fixed, can we retroactively grab payments? Or would users like me need to re-donate?

**Comment by jbuck** [comment]
This has been properly fixed now.

@bniolet1 Yes, donors will need to redo the payment process since payment tokens are only valid for 3 hours. We're going to follow up with attempted monthly donors in #1088

**Comment by valianttry** [comment]
@bniolet1 this is the related bu: https://github.com/mozilla/donate.mozilla.org/issues/1088 :cry:
