### ISSUE TITLE
Email individual donors whose monthly donation failed + ask them to re-initiate

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1088]
About 1,000 monthly donors believe they donated via PayPal between Nov 1 and December 10, but in fact their transaction was never completed, and the record of their donation is gone. Monthly donors who used a credit card via Stripe were processed normally. We do, however, have the email address of the supporters who made a failed donation. These donors are highly valued and qualified people. 

**Actions:**
- [ ] Pull a list of email addresses for this group. @adamlofting
- [ ] Draft a transactional email we will send from donate@mozilla.org that apologizes and provides them with an easy way to re-initiate a monthly gift using PayPal. (Andrea)
- [ ] Send each email individually from donate@mozilla.org so that replies or responses can be tracked in Desk.com. @stephaniemcv

**Comment by valianttry** [comment]
NOTE: I updated Mark Surman on the loss and the fix. He also offered to sign these emails if we want. Worth considering.

**Comment by adamlofting** [comment]
For the first task, this will need @jbuck to get the emails for the failed transactions from the logs

**Comment by jbuck** [comment]
Unfortunately, I do not have access to the donors emails, only the PayerID
:/

**Comment by valianttry** [comment]
@KevZawacki is going to do an initial draft.

**Comment by adamlofting** [comment]
Based on @jbuck's note,  I don't think we're able to email these people :cry:

**Comment by KevZawacki** [comment]
@valianttry Any other way to get in touch? 

I have a first draft [here](https://docs.google.com/document/d/1Vr0lAPXDW-xrrfOuqrRmilNY-TM7loAN7x52MlHUUPM/edit) -- but will hold off on looping in Scott until we determine if these folks are reachable.

**Comment by jbuck** [comment]
@adamlofting could you pull this information from GA? Like get a list of all people who visited /thank-you/ or /share/?

**Comment by adamlofting** [comment]
No, we filter out any PII in GA (as per the terms). It shows us how many, but not who.

**Comment by jbuck** [comment]
Well, :hankey:

**Comment by jbuck** [comment]
@valianttry I don't think we can contact these people. Should we close this ticket?
