### ISSUE TITLE
sendto.mozilla.org redirects very slowly

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate.mozilla.org#1089]
Should we remove the existing HTML there and replace it with a message about a redirect?

**Comment by adamlofting** [comment]
I'm fine with that. We need to keep the URL 'active' in BSD to keep the recurring donations happening but that doesn't mean we need a form on the front-end.

And we certainly don't want people signing up for recurring donations on the old form.

**Comment by ScottDowne** [comment]
I noticed it is now impossible to cancel previous recurring donations.

If I go here:  https://sendto.mozilla.org/page/recurring/view/ I get redirected instantly to the new form.

**Comment by ScottDowne** [comment]
Also let me know when this is fixed because I have a recurring donation I was using to test deactivating pages, that I cannot cancel...

**Comment by valianttry** [comment]
@ScottDowne you can log into BSD as an admin and cancel it.

**Comment by adamlofting** [comment]
Just some notes for the history of this ticket.

* Front-end re-directs were disabled to keep the recurring donation update page working. 
* I added new front-end re-directs into the individual fundraising pages on BSD (excluding the localized PayPal forms linked from the FAQ).
  * I think these re-directs are quicker than the old ones (set to 0 seconds subject to the speed of js execution)

Going to close this as I don't think we'll invest any more time during EOY, and next year we'll be working on the permanent off switch options.
