### ISSUE TITLE
We are downgrading monthly donors auto-magically :(

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1090]
My amount and the highlighted button location changes when I select an amount, then click monthly. Like this:
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11728937/9c92b1ac-9f5a-11e5-987f-67e2325faa53.png)

Then I click "monthly" and I see this:
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11728960/b6d8cfd8-9f5a-11e5-9a7a-d49f896f653d.png)

This means we are downgrading monthly donors automatically. This is bad.

**Comment by valianttry** [comment]
@adamlofting

**Comment by adamlofting** [comment]
This is the flipside of this earlier thread about moving the selected button: #672

I think we're actually best to work on the test ideas for moving the frequency ask to the top #1033 so that people are making that decision first, and less likely to miss a change in amount.

**Comment by valianttry** [comment]
+1, I think this is a pretty high priority given we're downgrading valuable donors -- i'll leave the test triaging to you tho @adamlofting

**Comment by ScottDowne** [comment]
@adamlofting 

I agree with moving it up, and we can test it, but it'll take time.

While we wait for that test, are we considering reverting https://github.com/mozilla/donate.mozilla.org/issues/672

Or keeping this as is? My 2 cents are we revert it, then test moving it to the top.

**Comment by adamlofting** [comment]
This ticket feels like a bit of a distraction for the last few working days, but on reflection I wanted to note that `$2 monthly` is an *upgrade* from `$3 one-off`. Which makes me feel better about not changing this in a rush. 

I'm going to P2 this for now.

**Comment by ScottDowne** [comment]
@adamlofting For what it's worth, we can run a test for this now: https://donate.mozilla.org/en-US/?test=frequency-move-test

That's a test where the string is injected into the same div as before.

**Comment by alicoding** [comment]
@jbuck is this suppose to be close or assign to me?

**Comment by jbuck** [comment]
I just assigned it to someone, so it doesn't go away~
