### ISSUE TITLE
Finalize design comps for Spectacular Snippet

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1096]
We have 3 designs approved by the fundraising team and the snippet team that we've got the green light to build. @lovegushwa and @natalieworth - can you please create detailed design comps for @ScottDowne to build. (Jordan, you've been great at this so far, so please work your magic!)

The final designs are 4, 6 and 7 from this set: https://redpen.io/p/kgb47de90492f74e6b

For design 6 *only* we need a static version, plus a very lightly animated version where Dapper fox gently tips his hat in the direction of the donate button. 

We'll design and build them in that priority
1) Design 4
2) Design 6 static
3) Design 6 animated
4) Design 7

I'm assigning this to Natalie because she has the files, but @lovegushwa can you please assist to give Scott exactly what he needs for a speedy build? Thanks!

cc @valianttry @cassiemc

**Comment by natalieworth** [comment]
Awesome! I'll get started on these @edrushka and connect with @lovegushwa when everyone's back from Mozlando! :)

**Comment by natalieworth** [comment]
@edrushka @valianttry @lovegushwa @cassiemc I've got the final files for the 3 approved snippets here: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0aldmeWJoNWZ4LVE/view
I can also do an animation mockup for the dapper fox animated version too.

**Comment by cassiemc** [comment]
Beautiful @natalieworth, very nice work incorporating the feedback and still offering three fantastic high-quality options! :boom:

**Comment by edrushka** [comment]
Sounds like @flukeout has already animated Dapper Fox for a different project. Anything we can look at Luke?

**Comment by cassiemc** [comment]
@edrushka – @flukeout mocked up an animated fox for a design team tutorial. Not sure it is production ready, but @flukeout should be available to work with @ScottDowne on whatever needs doing.

**Comment by flukeout** [comment]
I have a project here that can serve as a template for creating an animation here:
https://d157rqmxrxj6ey.cloudfront.net/flukeout/16745/

@ScottDowne - happy to help you implement the animation.
@natalieworth - we can design the animation together in CSS if you'd like.

**Comment by natalieworth** [comment]
@flukeout That would be great! We may have to adjust based on the most recent design. I've got the .ai file here for the version we are hoping to animate with the hat tip: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0TlN6cVphNkRNaVU/view I've separated the arm, fox, and hat onto separate layers.

**Comment by lovegushwa** [comment]
@ScottDowne Build this version first:

 ![spectacular-snippet-annotation-01](https://cloud.githubusercontent.com/assets/12228435/11821452/75ba43fc-a31e-11e5-9cca-a72e6166ce39.jpg)

![spectacular-snippet-horizontal-01](https://cloud.githubusercontent.com/assets/12228435/11821483/9b04cbfa-a31e-11e5-9255-ce2ed29bf478.jpg)

![spectacular-snippet-vertical-01](https://cloud.githubusercontent.com/assets/12228435/11821485/9d3d6dd2-a31e-11e5-8dc4-d0d1b09349bc.jpg)

**Comment by lovegushwa** [comment]
@ScottDowne build these versions second (static fox, animated fox)

![spectacular-snippet-annotation-02](https://cloud.githubusercontent.com/assets/12228435/11821543/eca9994a-a31e-11e5-8511-6a6b0b455a55.jpg)

![spectacular-snippet-horizontal-02](https://cloud.githubusercontent.com/assets/12228435/11821544/f4953d6c-a31e-11e5-95bb-c2bff4c502fa.jpg)

![spectacular-snippet-vertical-02](https://cloud.githubusercontent.com/assets/12228435/11821549/fa821b6e-a31e-11e5-893e-8ec919aa5105.jpg)

**Comment by lovegushwa** [comment]
@ScottDowne Build this version third:

![spectacular-snippet-annotation-03](https://cloud.githubusercontent.com/assets/12228435/11821591/2ff8cb3a-a31f-11e5-8112-d9d230c3271b.jpg)

![spectacular-snippet-horizontal-03](https://cloud.githubusercontent.com/assets/12228435/11821598/34b9daec-a31f-11e5-88ff-82788b3169fa.jpg)

![spectacular-snippet-vertical-03](https://cloud.githubusercontent.com/assets/12228435/11821605/3a95afe0-a31f-11e5-8f09-3bf217274817.jpg)

**Comment by cassiemc** [comment]
Nice annotations @lovegushwa! (and @ScottDowne if you see ways to make the annotation process better, let us know)

**Comment by lovegushwa** [comment]
@ScottDowne @edrushka @valianttry  the spectacular snippets are ready to build.
I'm converting this ticket to a build ticket.

SVG assets:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvNWlBWi05dzJHeEU&usp=sharing

CSS animation code to steal from @flukeout 
https://d157rqmxrxj6ey.cloudfront.net/flukeout/16745/

@natalieworth to consult on how the animation should look / work

**Comment by edrushka** [comment]
Awesome @lovegushwa - really appreciate your detailed annotations. Re-assigning this to Scott.

**Comment by natalieworth** [comment]
@lovegushwa Are we able to export the fox arm, hat, and fox head in separate svg's for the animation? I've got time to export if you link me to the file

**Comment by flukeout** [comment]
@ScottDowne, we'll want the fox split up into three separate pieces, the body, arm & hat. Don't worry about using the animation stuff referenced above, @natalieworth and I will create the animation once the markup is set up and we have a repo to check out from. Let's chat tomorrow.

**Comment by lovegushwa** [comment]
@natalieworth I separated the hat from the fox but not the hat and the arm. Maybe you can work with @flukeout to build exactly whats needed. Also we need to think about making the fox some what responsive (I provided links to a cropped fox and a full body fox based on your artwork.)

The SVG Fox assets are here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvNWlBWi05dzJHeEU&usp=sharing

**Comment by natalieworth** [comment]
@flukeout was able to help us with the awesome CSS animation of Dapper Fox! He sent me a thimble link here: https://d157rqmxrxj6ey.cloudfront.net/flukeout/21102/ — Feedback would be great and any suggestions on adjustments for the animation would be helpful before sending to Scott for development into the live snippet! Luke's still working on adding some looping effects to Dapper Fox (after the initial hat tip animation)—so more to come after this :D
@ScottDowne @lovegushwa @cassiemc @edrushka @valianttry

**Comment by natalieworth** [comment]
And giggle fox https://d157rqmxrxj6ey.cloudfront.net/flukeout/21105/! @ScottDowne @lovegushwa @cassiemc @edrushka @valianttry

**Comment by lovegushwa** [comment]
Yes! The best @ScottDowne @lovegushwa @cassiemc @edrushka @valianttry
I wonder if we could string the two together. Dapper tips his hat, and if you mouse over he giggles.
We should keep the giggle for the static snippet options since it's kind of like a easter gg.

**Comment by edrushka** [comment]
Ha! These are great! Love the giggle on mouse hover!

I just want to clarify that we should get Jean's signoff on the animated version(s) on staging before we build. One we've given feedback and done any tweaks on our end, I'll send to her for review.

**Comment by flukeout** [comment]
@lovegushwa Yeah, you nailed it! That would be ideal - animation on page load, then giggle on hover.

**Comment by edrushka** [comment]
@flukeout could he stop giggling after a moment? After a few seconds, it starts to feel like something is wrong with him!

**Comment by ScottDowne** [comment]
First snippet http://scottdowne.github.io/eoy-snippets/2015-disruptive-snippet-en-US/

**Comment by valianttry** [comment]
These are delightful! Is it possible to make the giggle or animation happen on hover over the donate button? Also he should definitely not giggle maniacally....

**Comment by lovegushwa** [comment]
@edrushka he only giggles when you mouse over him ... but that's an interesting idea, what if a mouse over kicks off a animation that 4sec, pause, 2sec, pause, 1sec. So Dapper kinda builds a giggle tolerance. Until you mouse over fox again and it starts all over.

**Comment by natalieworth** [comment]
@ScottDowne For your reference (colour updates on the arrow and 'donate now' button gradients):
<img width="1435" alt="screen shot 2015-12-17 at 10 34 28 am" src="https://cloud.githubusercontent.com/assets/14876567/11878918/40b1b524-a4ad-11e5-8a38-1f57d0a5fa91.png">
<img width="1432" alt="screen shot 2015-12-17 at 10 37 51 am" src="https://cloud.githubusercontent.com/assets/14876567/11878919/40b3213e-a4ad-11e5-8ad8-02783a8270d2.png">

**Comment by lovegushwa** [comment]
@ScottDowne This is looking good. Two thoughts. 
1. Type is sitting a pixel or two high in the buttons.
2. Not enough visual contrast between "Only a tiny portion of Firefox users give." and "if everyone reading this"... "Only a tiny ..." needs to look a bit lighter so the bold text stands out a bit more.

We could make the regular weight body text light. 
We could make the bold a heaver weight like black. 
We could make the regular weight body text really light red/pink rather than white so it looks lighter.
We could highlight the bold text with a darker red color (kind of like what were doing in the current snippet.)

**Comment by valianttry** [comment]
Just repeating this because I think it's important: **The animation should be a reward for hovering over the donate button, vs. the Fox (or at least one animation).** We want people to put their mouse right on that button. If you want a separate animation for mousing over the fox that's fine, too, but please prioritize mouseover donate button.

**Comment by valianttry** [comment]
Also FYI I'm writing custom snippet copy for the Dapper variants to include a "tip the hat" reference, for example:

Mozilla, the organization behind Firefox, is proudly non-profit, non-corporate and non-compromised. Will you help us work for a free and open Web for all? If everyone reading this chipped in XX, **we tip our hat to you** for supporting us for another year. Donate now.

**Comment by ScottDowne** [comment]
Finished snippet 2, and updated the links:

http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-1/
http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-2/

**Comment by ScottDowne** [comment]
Last one WIP: http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-3/

It has five issues, so far.

1. The mozilla wordmark in the top right is an image, so if I change the colour, I think I need a new one with the new colour. It also has a hover state but it's just opacity, so should work for the orange too.

2. The close button is also just an image, so I'll need a white one for the third snippet.

3. Dapper fox currently cannot cover the white box, it is actually behind the box. Snippets don't make it easy to add elements outside of my little container, so I used background image on the body, which, is going to be behind everything, I think. I might be able to hack something together, but I havn't yet.

4. The heart image is static size and position. Is that what we want?

5. I had to guess at the orange colour behind the heart. I might be off a bit. I came up with #F9B051

**Comment by natalieworth** [comment]
Thanks @ScottDowne 
1. I'm actually okay with the grey colour of the Mozilla wordmark over the white. I think it's more subtle than the white. Alternatively I could do an orange wordmark if we want it to be even more subtle @lovegushwa @valianttry @edrushka 
2. For the close button are we able to use the 'x' icon that is already there now? I'm not sure what's wrong with that one?
3. I'm okay with the layout of the fox not covering the white snippet box if that's more feasible for implementing the snippet. @lovegushwa What do you think about the fox position?
4. I'm also okay with the heart image being static. @lovegushwa Does this work?
5. Orange (background) colour is #F9B050 (so close!)

**Comment by ScottDowne** [comment]
The snippets got an r+ from the snippet service team this morning. That
doesn't mean we cannot iterate but I wanted to get their attention asap.
Wasn't expecting it to be that fast. Win.

**Comment by natalieworth** [comment]
For our animation dapper fox reference: 
* Calmer laugh, could disperse laugh at different times throughout hover
* Add laugh over the 'donate now' button hover
* Possibly add a subtle animation over the fox on mouse hover

**Comment by ScottDowne** [comment]
@natalieworth 

1. Sounds good, I'll leave it as the grey image until told otherwise.
2. We can use that 'x' button, but it's an image, so it's also not going to be what you had in the comps. We would need a new image for that.
3. Sounds good, I'll leave it as is until @lovegushwa says otherwise.
4. Same as above.
5. Updating!

Any other feedback on the third snippet implementation?

**Comment by ScottDowne** [comment]
@lovegushwa 

So for "Not enough visual contrast between "Only a tiny portion of Firefox users give." and "if everyone reading this"... "Only a tiny ..." needs to look a bit lighter so the bold text stands out a bit more."

We are not guaranteed font weights other than regular and bold. So no light font weight that I know of. basically we're stuck with system fonts from what I know about snippets.

I think lightening the text colour makes the most sense as it's easier than adding the background (which is more work than you would think because the browser doesn't highlight inline elements with padding, only newlined elements)

**Comment by lovegushwa** [comment]
@ScottDowne I agree, it's try to lighten the text color. A backup plan could be to choose a different system font that has more contrast between regular and bold weights.

**Comment by ScottDowne** [comment]
Just flagging this copy: https://docs.google.com/document/d/1wQU-7LNZwncc4qDVPN-DHZZFDc2s5ASAbsub6DIT60M/edit

Is this the copy we want to use for these snippets? If so, do we want to add some bold to any of the text? If so, we need to do that before it's translated.

Here is the current pull request for it: https://github.com/mozilla/donate.mozilla.org/pull/1146/files

**Comment by flukeout** [comment]
**Latest versions of animations**
* Giggle - https://d157rqmxrxj6ey.cloudfront.net/flukeout/21105/
* Hat tip - https://d157rqmxrxj6ey.cloudfront.net/flukeout/21430/
* Hat throw - https://d157rqmxrxj6ey.cloudfront.net/flukeout/21102/

@ScottDowne - the markup is slightly different for each of these. Ideally we'll want the same markup and stylesheet for all of these, so once they're approved, we can do that.

**Comment by natalieworth** [comment]
cc @valianttry @edrushka @lovegushwa @cassiemc

**Comment by natalieworth** [comment]
@ScottDowne @lovegushwa For you reference to the colours for fonts: 
![snippet_finals_v3_artboard 12 copy 7](https://cloud.githubusercontent.com/assets/14876567/11909087/528fcfe8-a597-11e5-93fa-8355b5d4ace3.png)
I'm thinking we could either apply a 70% opacity to the "light" Helvetica, or we could use a similar colour—I think this could work #F5BEC4.

**Comment by ScottDowne** [comment]
@natalieworth http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-1/ <- feel right?

**Comment by natalieworth** [comment]
@ScottDowne I think that looks great! @lovegushwa what do you think?

**Comment by ScottDowne** [comment]
We can also consider this for the header copy? I remember it being intended
to be light weight.

**Comment by ScottDowne** [comment]
@valianttry 

This landed this morning and is ready to go to production, all that's left is ensuring Jean gets copy with styling, and a list of locales we plan on shipping/testing.

**Comment by ScottDowne** [comment]
@edrushka Here are the animations as they are now:

* Giggle - https://d157rqmxrxj6ey.cloudfront.net/flukeout/21105/
* Hat tip - https://d157rqmxrxj6ey.cloudfront.net/flukeout/21430/
* Hat throw - https://d157rqmxrxj6ey.cloudfront.net/flukeout/21102/

Ping @flukeout if you have any questions, and probably want to use this ticket for future discussion about the animations.

**Comment by edrushka** [comment]
@natalieworth @lovegushwa @flukeout @ScottDowne  we made a decision with Jean on the animation. We'll go with the giggle when you hover over donate. Thanks! We love it!!

**Comment by lovegushwa** [comment]
@ScottDowne @natalieworth  when the copy get's really long, for all the snippet variation above, it's better if we left align, ragged right rather then center the text. I realize it might be too late to fix this.

**Comment by ScottDowne** [comment]
@lovegushwa I'm seeing if I can get in a configurable variable to change alignment between left and center as we see fit, with center as the default.

@edrushka So to confirm, we're using the giggle when hovering over donate, and that hat flip/tip on a timer, or somewhere else. Or, we're ONLY using the giggle on hover over donate, and not using the hat flip/tip, at all, anywhere, ever, and I only need to build one animation?

**Comment by ScottDowne** [comment]
@lovegushwa the left and center alignment landed this morning, so we can configure it. It's not dynamic.

**Comment by edrushka** [comment]
@ScottDowne we're only using to giggle on hover over donate. You do NOT need to build hat flip or tip.

**Comment by ScottDowne** [comment]
@flukeout @edrushka @valianttry Demos for the giggle when hover on donate.

http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-2/
http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-3/

@flukeout There were a few tricky bits, but, I think I was able to integrate it, without breaking the animation.

There is a pull request under review to land it in the snippet service.

**Comment by edrushka** [comment]
Just clarifying that we will only  use version 2 (plain background). No giggle on the heart background.

**Comment by ScottDowne** [comment]
The giggle is optional in both so let's just not turn it on in the heart
snippet. Also the animations got merged this morning. So Jean should have
what she needs to turn on the animate.

**Comment by ScottDowne** [comment]
Closing this!

Feel free to re-open if I missed something.
