### ISSUE TITLE
Selenium test wasn't working with Travis yet

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#110]
I decided to not do all this in one patch, so Selenium landedas a single manual test.

It's not doing yet:
- [ ] Running on travis.
- [ ] Running via npm test
- [ ] Turning off the server when it passes or fails
- [ ] Displaying console info in a pretty way about the test results

This is basically because this is new to me and I don't know how to do any of that yet, so I wanted to split it up into smaller tasks.

**Comment by alicoding** [comment]
http://testingbot.com/support/other/travis-ci

**Comment by ScottDowne** [comment]
I'm pretty sure we can do this without a paid third party service.

**Comment by ScottDowne** [comment]
I'm actually thinking we close this.

I think the main goal of selenium at this point is manual tests being easy to run.

Because these tests depend on third party services being up, let's not run them in travis.

Closing until we have a need to run a test via travis that we cannot run via karma.
