### ISSUE TITLE
Setup automatic dispute resolution for Stripe

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1105]
Using the API we can automatically resolve disputes.

**Comment by jbuck** [comment]
Lets implement this in donate.mozilla.org.

Implementation steps:

1. Listen for the [charge.dispute.created event](https://stripe.com/docs/api/node#event_types-charge.dispute.created)
2. [Retrieve](https://stripe.com/docs/api/node#retrieve_dispute) the dispute from the API
3. If the charge is refundable (check the is_charge_refundable key on the dispute object) then refund the original charge. Maybe also see if it's a subscription and cancel the subscription?
4. If we're not able to refund the dispute, then we'll just [close](https://stripe.com/docs/api/node#close_dispute) the dispute

**Comment by ScottDowne** [comment]
@cadecairos Didn't you do this? Can we close.

**Comment by cadecairos** [comment]
This is done!

**Comment by valianttry** [comment]
hey Chris, just looked at recent dispute list and seems like many are lost vs. refunded -- is this working as intended?

![disputes](https://cloud.githubusercontent.com/assets/9830371/18566170/d5391f68-7b60-11e6-81ed-732baeb0c185.png)

**Comment by cadecairos** [comment]
Yup, the language is confusing, but disputes closed VIA API are marked "lost" 

"Closed" seems to be an edge case where the card holder's bank closes the dispute.

**Comment by valianttry** [comment]
🍳 selent.
