### ISSUE TITLE
A watermark to test transaction receipt?

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/donate.mozilla.org#1114]
I tried a test transaction on staging site (https://donate.mofostaging.net/) with test mode (https://stripe.com/docs/testing#cards).
I has received email from "The Mozilla Team" donate@mozilla.org via amazonses.com.
I guess it's no different with the real receipts, except for the user fill in information.

I thought maybe it requires a special watermark for test transaction receipt, if it has legal significance.
Unless it just a thanks, or discrimination the test mode is not feasible.

**Comment by ScottDowne** [comment]
I thought staging was using real credentials, and thus, the test cards from stripe shouldn't work.

**Comment by ScottDowne** [comment]
Nope, I am wrong staging uses test credentials.

**Comment by ScottDowne** [comment]
Sorry, not sure what the issue is here.

**Comment by jbuck** [comment]
@ScottDowne it looks like a legitimate receipt from the Mozilla Foundation, so someone could theoretically try to get a tax refund based on our staging site.

**Comment by jbuck** [comment]
@yfdyh000 We had a quick discussion about this on our stand up and we're going to remove the contribution footer when it's a testmode email. Thanks for filing this!

**Comment by jbuck** [comment]
I have a PR in https://github.com/mozilla/webmaker-mailroom/pull/50

**Comment by jbuck** [comment]
And using the updated email in https://github.com/mozilla/sawmill/pull/66

**Comment by jbuck** [comment]
This has landed on staging and production
