### ISSUE TITLE
Write long version of Spectacular Snippet copy

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1116]
Write long version snippet copy for each of these designs:
4 - [Red arrow version] (https://redpen.io/ma5f219d1fa1aa3926)
6 - [Dapper Fox on grey background, static and animated] (https://redpen.io/yt9feda34655c5b827)
7 - [Dapper Fox on orange heart background] (https://redpen.io/szb8d4d153b51acc89)

Need to get Jean's signoff as she has only ok'd text in Redpens. When that's done, please put in the copy doc.

**Comment by edrushka** [comment]
@valianttry this urgently needs to be finished.

**Comment by valianttry** [comment]
Here is copy:
https://docs.google.com/document/d/1wQU-7LNZwncc4qDVPN-DHZZFDc2s5ASAbsub6DIT60M/edit

I added a "tip our hat" phrase to the version we'll use for Dapper Fox.

**Comment by edrushka** [comment]
This has been approved by Jean's team, Tim and Madhava. :dancer:
