### ISSUE TITLE
Confirm donors are being excluded from appeal emails

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1120]
It seems like some monthly donors received the first appeal email (myself, Sean Rich) and others didn't @bniolet1 

Can we confirm we're excluding monthly donors and one-time donors who sent their gift after Nov. 1?

Marking this as a P1 since we need to be sure before we send the second appeal (since we promised not to email people if they donate!)

cc @stephaniemcv @valianttry @adamlofting

**Comment by jbuck** [comment]
@adamlofting We definitely have a bug with monthly Stripe donors, we're not recording the email address...

**Comment by adamlofting** [comment]
I did some digging. The monthly donor emails are recorded in Stripe, but we're not exporting them to our transaction database, so these people have not been supressed from the emails so far. 

*This can be fixed before the next email send*.

**Data re Stripe donations in the transactions database**

has email:
* recurring: 0 
* one-off: 68,122

missing email:
* recurring: 1,831
* one-off: 16

**Next step:**

I can find Sean and Erika's donations via their email address in the Stripe admin. 

@jbuck I poked at the Stripe API, and it seems that charges related to recurring donations return an empty `meta` object. This is an inconsistency in [their API](https://stripe.com/docs/api/curl#retrieve_charge), which is a bit annoying (and not documented). 

So we'll have to perform a second API call to look up the customer object. This can be done using the `customer` property which *is* returned for all charges. https://stripe.com/docs/api/curl#retrieve_customer

https://github.com/mozilla/mofo-transaction-storage/blob/master/lib/stripe.js#L109

We can update this in mofo-transaction-storage, and the rest of the data pipeline will continue to work as it's currently setup.

**Comment by adamlofting** [comment]
Filed a separate ticket to track the implementation.

**Comment by stephaniemcv** [comment]
Got an an email from @bniolet1 that Sean from IT, a monthly donor, got another EOY email even though Erika did not.

**Comment by ScottDowne** [comment]
This was apparently fixed in https://github.com/mozilla/donate.mozilla.org/issues/1123

@jbuck thoughts?

**Comment by ScottDowne** [comment]
@stephaniemcv question, we have not sent an email today, right?

When did Sean get the email? Because maybe it was an email from a previous campaign email after the fix?

**Comment by stephaniemcv** [comment]
We have not sent an email today.
Sean got the email 12/23 we sent EOY #2.

**Comment by bniolet1** [comment]
@ScottDowne good thought but I don't think so: 

Sean's email came: Date: Dec 23, 2015 9:28 AM

Is it possible that the bug was fixed, but we just didn't manually add the missed subscribers to the exclusion?

**Comment by ScottDowne** [comment]
@bniolet1 

According to the bug it was fixed in https://github.com/mozilla/donate.mozilla.org/issues/1123, they get added. "I'm re-running this against the old data now"

**Comment by ScottDowne** [comment]
We've exported a list of customers and we're using that in exact target to filter out the emails so they don't get sent to existing monthly donors.

**Comment by jbuck** [comment]
My current working theory is that new donors who donated via Stripe are not being added to the donor history list, because the SQL code has a bug.

**Comment by jbuck** [comment]
Patch in https://github.com/mozilla/mofo-transaction-storage/pull/12

**Comment by jbuck** [comment]
Landed, and we added another 72k donors to the suppression list. I also tested a bunch of well-known email addresses and they're all on the suppression list: https://bugzilla.mozilla.org/show_bug.cgi?id=1235428#c5
