### ISSUE TITLE
Add email addresses for transaction storage for monthly Stripe donors.

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1123]
Implementation ticket for: #1120 

I did some digging. The monthly donor emails are recorded in Stripe, but we're not exporting them to our transaction database, so these people have not been supressed from the emails so far. 

*This can be fixed before the next email send*.

**Data re Stripe donations in the transactions database**

has email:
* recurring: 0 
* one-off: 68,122

missing email:
* recurring: 1,831
* one-off: 16

**Next step:**

@jbuck I poked at the Stripe API, and it seems that charges related to recurring donations return an empty `meta` object. This is an inconsistency in [their API](https://stripe.com/docs/api/curl#retrieve_charge), which is a bit annoying (and not documented). 

So we'll have to perform a second API call to look up the customer object. This can be done using the `customer` property which *is* returned for all charges. https://stripe.com/docs/api/curl#retrieve_customer

https://github.com/mozilla/mofo-transaction-storage/blob/master/lib/stripe.js#L109

We can update this in mofo-transaction-storage, and the rest of the data pipeline will continue to work as it's currently setup.

**Comment by jbuck** [comment]
@adamlofting nice catch! I'll do up a patch today and re-run the stripe customer db

**Comment by jbuck** [comment]
@adamlofting https://github.com/mozilla/mofo-transaction-storage/commit/16c7fea5c4f109f9442513b6d68acf3378f8f641

I'm re-running this against the old data now
