### ISSUE TITLE
Collect language for Mitchell's EOY appeal

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/donate.mozilla.org#1125]
This ticket will house 2015 quotes and quips from Mitchell that are relevant to the Foundation / fundraising. We can work this language into Mitchell's EOY email appeal — since it's already been said publicly and in her voice, it should shorten the review process.

@valianttry @edrushka @stephaniemcv @HPaulJohnson

**Comment by KevZawacki** [comment]
From Mitchell's [blog on philanthropy](https://blog.lizardwrangler.com/2015/04/27/philanthropy-and-the-health-of-the-internet/):

+ "Building the Internet as an open, global public resource is a social issue in its own right, and a free and open Internet is foundational to advancing all issues."
+ "The philanthropic world has an important role to play [on the Internet]."
+ "The Internet should be a global public resource, open and accessible to all."

From Mitchell's [blog on participation](https://blog.lizardwrangler.com/2015/04/10/participation-at-mozilla/):

+ "Mozilla aims to build openness and choice into the fabric of the Internet.  We see that fabric as including technology and products on the one hand, and the communities of people who understand and build an open Internet on the other hand."
+ "We aim to... to enable more people to know more, do more, and do better in online life."

From Mitchell's [Whistler keynote](https://air.mozilla.org/mitchell-baker/): 

+ “Mozilla’s future has success, leadership and impact in it.”
+ “The Internet should be open and accessible to all — that’s bigger than us.”
+ “I want to build new things that reflect our values.”

From Mitchell's [net neutrality video](https://www.youtube.com/watch?v=I-UPyuW5j9o&feature=youtu.be):

+ "We work to create opportunity and openness online, and build an Internet that has opportunity for all of us." 
+ "Openness and innovation has made online life and the Internet remarkable." 
+ "[Thank you to everyone] who took steps to help promote, preserve and build a stronger open Internet." 

From Mitchell's [net neutrality blog](https://blog.mozilla.org/blog/2015/02/26/a-major-victory-for-the-open-web-2/):

+ "[Net neutrality victory] happened because millions of people — including many hundreds of thousands
in Mozilla’s community — joined together as citizens of the Web
+ "Net neutrality is a key aspect of enabling innovation from everywhere, and especially from new players and unexpected places. Net neutrality allows citizens and consumers to access new innovations and judge the merit for themselves. It allows individual citizens to make decisions, without gate-keepers who decide which possibilities can become real. Today’s net neutrality rules help us protect this open and innovative potential of the Internet."
+ "We are organized as a non-profit so that the assets we create benefit everyone."
+ "This victory... occurred because so many people took action, so many people put their voice into the process. 
+ "Thank you for helping us build openness and opportunity into the very fabric of the Internet."

From Mitchell's [MOSS blog](https://blog.mozilla.org/blog/2015/10/23/mozilla-launches-open-source-support-program/):

+ "Mozilla is a part of the open source and free software movement. We were born out of this movement. We prosper because of the technology and activism which comes from this movement. And we know that open source and free software remains a key part of the Internet and the online life we seek to build." 
+ "I am reminded regularly of how deeply Mozillians identify open source and free software as a critical element of an open Internet and healthy, trustworthy online experiences." 

From Mitchell's [equal rating blog](https://blog.lizardwrangler.com/2015/05/06/zero-rating-and-the-open-internet/):

+ "An increasing number of companies, foundations and non-profit organizations around the world are interested in how we promote social benefit via the Internet."

**Comment by valianttry** [comment]
@KevZawacki Can you find any phrasing or speeches where Mitchell talks about threats to the Web? Maybe about equal rating or what a closed Web would do / look like?

**Comment by KevZawacki** [comment]
@valianttry Most definitely. 

A great resource is Mitchell's [open Internet blog](https://blog.lizardwrangler.com/2014/11/10/mozilla-and-the-future-of-the-open-internet/). It's from November 2014, but has really rich language. It also appeared in re/code as an op-ed, so we'll want to rephrase a bit so it's no completely verbatim.

+ "There is still essential work to do as the Web still faces real threats today — and likely will again in the future."
+ "Many of the principles we associate with the Web — openness, decentralization and the ability of anyone to publish without asking permission from others — are at risk."
+ "It feels like [openness online] is changing: like the ability to act without permission slipping away into 'mobile' or 'social' or 'big data.'"
+ "The possibilities of mobile, social and big data are astonishing. But the current implementation drives all of us into a world of monitoring and control and opportunities determined by others far, far away from our lives."
+ "I don’t want to be owned and tracked by giant multinationals or governments."


From Mitchell's [equal rating blog](https://blog.lizardwrangler.com/2015/05/06/zero-rating-and-the-open-internet/):

+ "[Not actively assisting the next billion] would reinforce the global digital divide; it would keep a large fraction of humanity from benefiting from the possibilities of the Open Internet."
Such an approach would reinforce the global digital divide; it would keep a large fraction of humanity from benefiting from the possibilities of the Open Internet."

+ "[With zero rating,] the parts of the Internet that are available for citizens to choose from is limited, and predetermined by those entities with financial power."

+ "Selective zero-rating is unquestionably bad for the long term opportunities and inclusion for the people it is designed to serve. It pre-selects what’s available, directing people to where others want them to go. It is bad for economic inclusion. It is bad for the ability of new entrepreneurs to grow onto the global scale. It is bad for the long term health of the Internet." 

From Mitchell's [WEF/CNBC op-ed](http://www.cnbc.com/2015/09/08/mozilla-chair-mitchell-baker-on-innovation-at-wef-dalian.html):

+ "When innovation is disruptive, we see stronger efforts to stop it, to harness it, and to reign in its impact in ways that don't challenge or make existing models obsolete."

From Mitchell's MozFest closing keynote (again, this is late 2014 — but still relevant):

+ "Now, today we can see that the web, the net is changing and once again we can feel the openness and opportunity and the ability to act without permission sort of slipping away. As Mark described, we can see them slipping away into these giant empires where you act as you're given permission."

**Comment by edrushka** [comment]
This is done. Closing. Thanks @KevZawacki
