### ISSUE TITLE
Finalize and export addional directory tiles

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1133]
@natalieworth - the additional directory tiles have been localized in almost all the languages. You can see them here:
EN: https://donate.mofostaging.net/en-CA/directory-tiles/
DE: https://donate.mofostaging.net/de/directory-tiles/
ES: https://donate.mofostaging.net/es/directory-tiles/
PTBR: not done yet
IT: https://donate.mofostaging.net/it/directory-tiles/

@alicoding confirming that these strings have gone through the necessary reviews on pontoon and are ready to be used?

**Comment by natalieworth** [comment]
Thanks @edrushka @alicoding! I haven't finalized localized directory tiles before. Is there any difference to when I exported the original EN tiles? Thanks!

**Comment by edrushka** [comment]
The file format should be the same. @lovegushwa did the first set and may have advice.

**Comment by natalieworth** [comment]
@lovegushwa Is this pretty straight forward or do you have time tomorrow to quickly go over this?

**Comment by alicoding** [comment]
Anything that came back to our repo means they've been reviewed, so it is all good here :)

**Comment by lovegushwa** [comment]
@natalieworth yeah it's easy. I'll ping you and we can walk though the process.

**Comment by edrushka** [comment]
French is done: https://donate.mofostaging.net/fr/directory-tiles/

**Comment by natalieworth** [comment]
@edrushka @lovegushwa Here are the first set of localized exported tiles: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NUdrb0VxUFJQSlU&usp=drive_web&ddrp=1#
I triple-checked each tile for spelling/ proper translation, but if anyone wants to check again @alicoding 's links are at the top of this issue to the original localized tile translations for comparison. I'll upload the French versions this afternoon/ evening. :)

**Comment by natalieworth** [comment]
Just going to note here that I'll still have to adjust the Italian translation based on feedback from localization, but the French (FR) versions are now exported and updated: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NUdrb0VxUFJQSlU&usp=drive_web&ddrp=1#
cc @edrushka @lovegushwa

**Comment by natalieworth** [comment]
Italian (IT) versions have been updated with 'Dona Subito' button translations and for reference can be found here:
V1-V2: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2qu3ExKWIlvYXZqT3hjczgzVFE&usp=drive_web&ddrp=1#
V3: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NUdrb0VxUFJQSlU&usp=drive_web&ddrp=1#
cc @jbuck @valianttry @edrushka @flodolo
