### ISSUE TITLE
Test language on additional info page

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1135]
Following the results of the additional language page test:
https://fundraising.mozilla.org/ab-test-additional-ask-for-some-channels/

We're running a follow up test to use some high-performing snippet copy in this space. 

This test has started and can be tracked here:
https://app.optimizely.com/results2?experiment_id=4245891743&token=2c2ed6619439c3457bcb

**Comment by ScottDowne** [comment]
Looks like we had an insignificant difference in the result so we didn't need to take an action.
