### ISSUE TITLE
Localize Spectacular Snippet Copy

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1147]
I filed this in the wrong repo! https://github.com/MozillaFoundation/plan/issues/654 

Please continue discussion here.

**Comment by alicoding** [comment]
These 3 are completed:
https://pontoon.mozilla.org/it/fundraising/Snippets/
https://pontoon.mozilla.org/de/fundraising/Snippets/
https://pontoon.mozilla.org/fr/fundraising/Snippets/
The other 2 locales `es` and `pt-BR` still in progress, so hopefully it will get done soon.

**Comment by edrushka** [comment]
Awesome! Flod warned that those 2 locales might not happen quickly. I've already warned @valianttry to be prepared to ask Kontextor. Thanks @alicoding :dancer:

**Comment by valianttry** [comment]
I've got an email queued and ready to go -- it looks like PTBR is 77% and ES is now at 66%. I can ask kontextor to finish if needed.

**Comment by edrushka** [comment]
@alicoding can you please confirm this text has been localized and reviewed in:
DE, FR, ES, PT-BR and IT and attach a link to where we can find the strings? Then I can close this ticket. Thanks!

**Comment by alicoding** [comment]
https://github.com/mozilla/donate.mozilla.org/blob/master/locales/fr/snippet.properties
https://github.com/mozilla/donate.mozilla.org/blob/master/locales/it/snippet.properties
https://github.com/mozilla/donate.mozilla.org/blob/master/locales/pt-BR/snippet.properties (partially translated)
https://github.com/mozilla/donate.mozilla.org/blob/master/locales/de/snippet.properties
https://github.com/mozilla/donate.mozilla.org/blob/master/locales/es/snippet.properties (partially translated)

**Comment by alicoding** [comment]
So we have 2 that's not 100% completed. I'm not sure if it is good to close or what we do here?

**Comment by edrushka** [comment]
Oh darn. I thought those were 100%. Let's leave this ticket open until they are done.

**Comment by alicoding** [comment]
Just assigning this to @valianttry to email Kontextore to get the other 2 locales done :)

**Comment by jbuck** [comment]
Looks like es is done 100% and pt-BR needs review

**Comment by jbuck** [comment]
pt-BR has been reviewed. This is all done! \o/
