### ISSUE TITLE
IT directory tiles don't have correct translation

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1149]
@flodolo found that the https://drive.google.com/a/mozilla.com/folderview?id=0B20-0lpP23c0LWRhY0J5elVuUE0&usp=drive_web&ddrp=1&tid=0B20-0lpP23c0NUdrb0VxUFJQSlU graphics don't have the correct translation of "Donate now". These graphics are using "Dona ora", which is the shitty Google translation instead of the correct "Fai una donazione" or if space is at a premium "Dona subito".

**Comment by jbuck** [comment]
This ticket may be a dupe of #816

**Comment by flodolo** [comment]
In this specific case `Dona subito` is a better solution for the button label, mostly because `Fai una donazione` is also used in the string right above in at least 2 cases.

That's also why we should try to have separate string IDs for separate contexts. The string `donate_now=Fai una donazione` is also used as title and button label in the main donate form, and in that case is absolutely appropriate.

**Comment by natalieworth** [comment]
@jbuck @flodolo Should I update all the tile designs to the Italian translation "Dona subito"?

**Comment by valianttry** [comment]
@flodolo we don't use Google Translate for any of our assets. At least not knowingly. I am not sure where this translation came from. Thank you for flagging this!

**Comment by flodolo** [comment]
@natalieworth Yes please

@valianttry 
I never implied it was Google Translate ;-)

I suppose a search was done on Google to find similar buttons, it's just that "Dona ora" is not as good as the other alternatives
https://github.com/mozilla/donate.mozilla.org/issues/816#issuecomment-157533676

**Comment by natalieworth** [comment]
Italian (IT) versions have been updated with 'Dona Subito' button translations and for reference can be found here:
V1-V2: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2qu3ExKWIlvYXZqT3hjczgzVFE&usp=drive_web&ddrp=1#
V3: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NUdrb0VxUFJQSlU&usp=drive_web&ddrp=1#
cc @jbuck @valianttry @edrushka @flodolo

**Comment by edrushka** [comment]
Thank you @natalieworth :bouquet:

**Comment by flodolo** [comment]
They look great, thanks :smile:
