### ISSUE TITLE
Expiry Date Validation Seems Broken

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#115]
I'm trying to put through a test Stripe payment on local, or staging, and I get this validation error on the Expiry Date:

<img width="450" alt="screenshot 2015-07-29 12 58 51" src="https://cloud.githubusercontent.com/assets/1901816/8956829/80087dd2-35f1-11e5-95f0-507bcf145ca7.png">

This seems like a valid future expiry date.

On a separate note, the validation message isn't very helpful, but I'll file that as a future enhancement bug. This bug is just to get the transaction working.

**Comment by ScottDowne** [comment]
Very weird.

Maybe for some reason it actually thinks it is empty and has nothing to do with stripe or the future.

**Comment by ScottDowne** [comment]
It happened to me too :confounded:

**Comment by ScottDowne** [comment]
It was working last night, and now it's not. Doesn't matter what I put in there.

**Comment by ScottDowne** [comment]
Seems the pattern="\d{2}" attribute on the input is busted. A FF update of some sort this morning?

I suspect #115 and #116 are the same problem.

**Comment by ScottDowne** [comment]
Agh, this is strange and doesn't make sense!

**Comment by ScottDowne** [comment]
The form on donate.mozilla.org still works, so that's good news.

**Comment by ScottDowne** [comment]
Changing the validation to "\d\d" fixes it!

I want to understand what happened though.

**Comment by ScottDowne** [comment]
If you inspect it, pattern="\d{2}" is being compiled into pattern="d{2}"

Which obviously won't work. One of the compilers is stripping out the slash.

@alicoding thoughts?

**Comment by ScottDowne** [comment]
I bet it's a change to a node module that happened over night, and because we "use what's newest" it took us by surprise.

I'm testing this, and if true, we need to use explicit versions for dependencies and update manually.

Surprises are only fun on Christmas.

**Comment by ScottDowne** [comment]
:gift: surprise!

**Comment by ScottDowne** [comment]
No, doesn't seem to be a node package versions.

**Comment by ScottDowne** [comment]
Fixed: https://github.com/mozilla/donate.mozilla.org/commit/1b7447d86b35af5eaeae3badedc4a29188654eee
