### ISSUE TITLE
Write final copy for Thank You snippet

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1155]
Write final text for the January thank you snippet: https://redpen.io/pzeace74e3e3c235da

A reminder that this will be seen in FR, DE, PTBR and ES only.  EN locales will see the video.

**Comment by valianttry** [comment]
Options for consideration:

A:
To our 3xx,xxx donors from over 200 countries and territories around the world — thank you for supporting Mozilla's mission to !

B.
All of us at Mozilla would like to say "thank you" to the 3xx,xxx people from over 200 countries and territories around the world who donated this year. Your gift will help Mozilla stand up for the principles in the Mozilla Manifesto and protect the Web for future generations.

C. 
Mozilla staff and volunteers would like to say "thank you" to the 3xx,xxx people from over 200 countries and territories around the world who donated this year. **Thank you!**

**Comment by edrushka** [comment]
Here's what MoCo wrote and was shipped to L10N.

Desktop: You made our year! Thanks to your generous donations, Mozilla can work even harder to ensure the Internet is a global public resource, open and accessible to all.

Mobile: Thank you for your generous donations to Mozilla. You made our year!

**Comment by edrushka** [comment]
Decision. We'll try:

- To our 3xx,xxx donors from over 200 countries and territories around the world — thank you for supporting Mozilla's mission!

- You made our year! Thanks to your generous donations, Mozilla can work even harder to ensure the Internet is a global public resource, open and accessible to all.

- Thank you for your generous donations to Mozilla. You made our year!
