### ISSUE TITLE
Review Validation Messages for all Input Fields

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#116]
Let's review and improve our validation messages throughout the donation flow.

Example below:

<img width="450" alt="screenshot 2015-07-29 12 58 51" src="https://cloud.githubusercontent.com/assets/1901816/8956878/dfef6134-35f1-11e5-9e4c-270941402d6e.png">

In this example, these fields are 'completed' so the message doesn't help me as a user to solve the problem.

**Comment by ScottDowne** [comment]
Fixed: https://github.com/mozilla/donate.mozilla.org/commit/1b7447d86b35af5eaeae3badedc4a29188654eee

**Comment by adamlofting** [comment]
Re-opening, just because I want to do a review of our validation messages in general. I'll assign to myself.

**Comment by ScottDowne** [comment]
The thing that's handling the validation is going to be changing more as we component-ize things.

I'm pushing this for now until things are a bit more solid.

**Comment by adamlofting** [comment]
> I'm pushing this for now until things are a bit more solid. Otherwise the work done here might be redone later anyway.

Agreed. I'm going to push it back even further.

**Comment by adamlofting** [comment]
I filed a few P2 bugs following this review where we can add a little extra feedback to make life easier for users who get stuck.
