### ISSUE TITLE
Replace privacy policy checkbox with a statement about 3rd party providers

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#1167]
Once we've completed legal sign-off on the language, we plan to replace the current privacy policy checkbox with a statement about Stripe and Paypal as the processor of our payments.

Link to legal bug for @valianttry https://bugzilla.mozilla.org/show_bug.cgi?id=1210332

This language will need localization, and we'll want to A/B test a short and long version in `en`.

#### Current rationale (language not yet approved)

We noted that our current check-box doesn't make sense because it appears before the data collection, and isn't an decision for Mozilla to validate as the opt-in is part of the user agreement between the donor and the 3rd party payment provider (either Stripe or Paypal).

However, we want to be as clear as possible about what data is stored by who (without confusing our donors), so we propose replacing the check-box with a statement that links to the Stripe and PayPal privacy policies.

We also noted that the Stripe check-out flow now includes links to their Terms and Privacy Policy below the payment form. Which isn't a design feature we control, but which does help our donors.

Following this, we would like to A/B test the following 2 options in place of the current check-box.

--

*OPTION 1 - mozilla values:*

> We care about privacy, your data, and helping you make informed choices. We want you understand that your payment details will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla.

*OPTION 2 - more direct:*

> Your payment will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla.

--

For each option above, the word 'Stripe' links to https://stripe.com/privacy/ and 'Paypal' links to https://paypal.com/privacy

**Comment by adamlofting** [comment]
cc @valianttry @edrushka @alicoding @ScottDowne 

There might not be time to ship this this year, but thought I'd flag it, as it could be high impact.

**Comment by adamlofting** [comment]
Sign-off is complete with slightly improved text:

*Option 1*

> We care about privacy and about helping you make informed choices. We want you to understand that your payment details will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla.

*Option 2*

> Your payment details will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla.

We should 

1. Localize both strings. 
2. Launch with option 1 for all locales
3. Then A/B test both variants in en before choosing which version to use for all locales

**Comment by edrushka** [comment]
In the options above, where do we link to *out* privacy policy?

**Comment by valianttry** [comment]
@edrushka good Q. The first stop in the donation flow includes the standard footer on all Mozilla pages, which links to Mozilla's Privacy Policy. Legal cleared the above copy, and I am assuming the footer link is sufficient.

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11983331/7d773826-a967-11e5-8952-523137780cd6.png)

**Comment by valianttry** [comment]
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11983933/4b0cc02c-a96c-11e5-98b7-44158acb6cdf.png)

**Comment by jbuck** [comment]
PR in #1179

**Comment by ScottDowne** [comment]
For context, you can test this via these urls:

https://donate.mozilla.org/en-US/one-page-policy-a/
https://donate.mozilla.org/en-US/one-page-policy-b/

**Comment by valianttry** [comment]
@ScottDowne the words "stripe" and "paypal" should be hotlinked to their respective privacy policies.

PayPal: https://www.paypal.com/us/webapps/mpp/ua/privacy-full
Stripe: https://stripe.com/privacy/

**Comment by ScottDowne** [comment]
Oops forgot. Another good catch. Not too hard. I'll do it in a quick
follow-up and update this ticket when done.

**Comment by jbuck** [comment]
Scott did the fix in #1183 and I just deployed to production
