### ISSUE TITLE
metrics on recurring payments

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#119]
Not sure how we handle this.

The transaction isn't what we expect for recurring like it is for a single donation.

So the metrics are failing for recurring.

**Comment by adamlofting** [comment]
Thanks. I've got this noted in #16 but I'll leave this open for now, as it might be the last task on that list.

**Comment by adamlofting** [comment]
This is fixed for PayPal in #151 

It's also ready for Stripe, but I'm leaving this ticket open so I remember to check the Stripe recurring payments at a later date.
