### ISSUE TITLE
Copy the 'static' currency pages into the new system

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#12]
Copy the 'static' [currency pages](https://wiki.mozilla.org/Ways_to_Give#PayPal) into the new system

**Comment by ScottDowne** [comment]
Also going to pull in the thank you page when I do this.

**Comment by ScottDowne** [comment]
Done: https://github.com/mozilla/donate.mozilla.org/commit/647d580f5a4a75f5e3df3f2c50b6a7ef421c5b84
