### ISSUE TITLE
"Submitting" donation cycles without resolution

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1202]
Problem reported by user:

Well This is my problem

1. I have tried the donate.mozilla.org 5 times
2. It has no idea what card I want to enter because no place for entering the card has come up what I get is a form which allows me to select between paypal and credit debit card. I indicate credit debit card and it says it is submitting, I have no idea what is submitting however no place to enter a credit or debit card number comes up.
3. I have attached what I see. IT will do the “submitting for at least an hour and get nowhere

Donor attached screen shot (appears she has a black and white printer without grayscale):

![scan0001_original_pdf](https://cloud.githubusercontent.com/assets/9830371/12059562/866c64d2-af12-11e5-9f29-0a6dede993be.png)

**Comment by alicoding** [comment]
Ouch! That looks like a broken form. I wonder if disabling JavaScript can cause this?

**Comment by ScottDowne** [comment]
@alicoding just tried that, with js disabled, we get a white empty screen.

That screenshot is sooo weird.

**Comment by ScottDowne** [comment]
I'm betting whatever is causing the screen to look weird, is what's causing stripe to fail.

Part of me thinks stripe IS displayed, but the weird display is hiding it or moving it or making it all white?

I dunno, but when it looks like that, I would be surprised if things work.

**Comment by ScottDowne** [comment]
Some css is working, so it's not as simple as that. It seems to be selective.

**Comment by valianttry** [comment]
It's an extreme edge case. Who knows what browser, OS; etc they are trying to use.
