### ISSUE TITLE
Reports that "X" Optout doesn't seem to be working for Spectacular snippet

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1203]
![_2653__phil](https://cloud.githubusercontent.com/assets/9830371/12059592/1ca88c82-af13-11e5-82c5-245574dc3ef1.png)

**Comment by ScottDowne** [comment]
I'm not sure what this could be but let's keep our eyes opened for new
reports. Maybe if we get more info we can narrow it down. Did you get any
more reports? You mentioned two in irc but I may have read it wrong.

**Comment by valianttry** [comment]
12 people have emailed about the promo's persistence. I replied to each with instructions to close the promo. I have only seen two replies from those 12 that the "X" did nothing when clicked so far. Hope that helps. I'll drop more in here if they come up.

**Comment by valianttry** [comment]
I am going through Firefox feedback:
https://input.mozilla.org/en-US/?q=donate&date_end=2015-12-30&date_start=2015-12-23&page=3

So far I found one other person reporting the "X" is not working:

![welcome____firefox_input](https://cloud.githubusercontent.com/assets/9830371/12062361/1b7fc144-af50-11e5-9040-01d6251899a1.png)

Still reviewing...

**Comment by valianttry** [comment]
Just got another one in desk.com:

![_2649__ken___karen_parker](https://cloud.githubusercontent.com/assets/9830371/12067969/8c9a90da-afb8-11e5-9f77-83b9727864a7.png)

**Comment by valianttry** [comment]
Another:
---------
Ms. Wood - Thank you for your reply. Yes, I know that I can turn off the message. It does come back immediately, though. 
----------

**Comment by ScottDowne** [comment]
It's Windows 7, 8, and 8.1.

I filed this with bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1236090

**Comment by valianttry** [comment]
Another:
![_3779__judy_wood](https://cloud.githubusercontent.com/assets/9830371/12068833/7dd023cc-afcb-11e5-9a30-1d12866398cf.png)

**Comment by ScottDowne** [comment]
Should be fixed now. Closing, if it starts happening again let's make a new ticket.
