### ISSUE TITLE
Generate a list of donors who gave over $499 for special Thank You

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1206]
@jbuck is it possible to generate a list of donors who gave over $499? We need first name, last name, donation amount, and email address. 

I want to set Mark up to send some personal thank you messages.

**Comment by jbuck** [comment]
I'll be away until Jan 25, so gonna ask Adam to do this

**Comment by adamlofting** [comment]
Done, and shared via another channel. :+1:

**Comment by valianttry** [comment]
@adamlofting some of these appear to be fraudulent, would someone need to check each one in Stripe or PayPal to confirm fraud or is there a way to export that information as well?

e.g. several people donated thousands of dollars across several transactions, which usually indicates fraud.

**Comment by adamlofting** [comment]
I thought that too, so quickly checked a few of the Stripe examples that looked suspicious and of those I checked none had been reversed/cancelled/refunded/etc so I assume those are legit. It would be good to check a few of the Paypal examples too (I don't have login details to hand). 

Some of the email addresses are clearly made by people who want to remain anonymous (e.g. the ...@mailinator.com ones)
