### ISSUE TITLE
Implement winning privacy policy variant

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1207]
Follow-up on https://github.com/mozilla/donate.mozilla.org/issues/1181, we need to implement the winning variant in our main page.

**Comment by ScottDowne** [comment]
@jbuck https://github.com/mozilla/donate.mozilla.org/pull/1208

One note, probably turn off the tests 100% redirect before shipping this, or we'll be sending people to a broken page, which would redirect to where we want, but would lose the query string data.

**Comment by adamlofting** [comment]
I've turned off all remaining Optimizely tests today. So we're safe to implement without complications from re-directs. :+1:

**Comment by adamlofting** [comment]
- [ ] We have a small tweak to make to the language from legal:

> Your payment details will be processed by [Stripe](https://stripe.com/privacy/) (for credit/debit cards) or by [Paypal](https://www.paypal.com/us/webapps/mpp/ua/privacy-full) in accordance with their privacy policies, and a record of your donation will be stored by [Mozilla](https://www.mozilla.org/en-US/privacy/).

^ Note the slightly different text and the addition of a link to the Mozilla Privacy Policy.

- [ ] We can now also the footer text "We use Stripe for credit card processing. For more information see their Privacy Policy."

**Comment by jbuck** [comment]
@ScottDowne looks like we need to make some changes
