### ISSUE TITLE
Setup production hosting, and deployment process

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#121]
Following #14 

- [ ] Setup a Heroku project for our Prod environment
- [ ] Decide how we push from Staging to Prod (is this using another branch in the repo?)
- [ ] Add some docs about how to push to production (README)

We can't point the donate.mozilla.org domain at this yet, but it would be good to document an alternative domain to test the Production environment over the next few weeks. This could be a *.mofoprod... domain, or just use the herokuapp domain.

**Comment by alicoding** [comment]
Should we change our process to use `develop` branch for development and tag it to `master` once we are ready to push to prod? That way we can be sure before we push to prod. I can also add that step to .travis.yml file as well.

**Comment by adamlofting** [comment]
Happy to take guidance on this, but maybe we should have a branch called 'production' to it's more explicit what merging to that branch does?

**Comment by alicoding** [comment]
I don't mind production branch if we want to be explicit, but I just thought that `master` branch is common enough for production when we have `develop` branch.

**Comment by adamlofting** [comment]
That wfm too. Most valuable thing is to make it like other MoFo projects so it's easy for new engineers to pick up. 

(That plus documentation :stuck_out_tongue_winking_eye: )

**Comment by jbuck** [comment]
I've created the Heroku apps and deployed the CDN to production ( https://donate.mofoprod.net ). Need to configure the Heroku apps with the correct config, and push code to them

**Comment by jbuck** [comment]
Now all I need to get is get production deploys working...

**Comment by jbuck** [comment]
Production deploys are working correctly, and I have a PR in progress with documentation

**Comment by jbuck** [comment]
Issue #263 will polish this off
