### ISSUE TITLE
Work out what to do with 'incomplete locales'

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#125]
In old BSD pages, we had two sets of locale strings. See notes in #117 

The new setup builds out the static pages based on the locale files in `/locales/` but we have a bunch of locales (e.g. JP) where we only have a smaller subset of strings which were used for the simple PayPal pages.

If we import these partial locale files, the build will break at the moment.

Let's work out a plan for moving forward with this.

**Comment by alicoding** [comment]
On client side I have implemented something to make sure is not going to fail when partial  strings introduced for that locale. I can implement that for server compilation as well.
