### ISSUE TITLE
Overlay bug with German language

### ISSUE THREAD

**Issue by ftbastler** [mozilla/donate.mozilla.org#1253]
![bug](https://cloud.githubusercontent.com/assets/1853742/12373247/85873d80-bc73-11e5-974e-8e82d40f0e69.PNG)

Using the latest version of Firefox as of 01/16/2016 on Windows 10.

**Comment by jbuck** [comment]
@ftbastler Thanks for filing this bug!

@ScottDowne I think this is a bug that exists with other locales too - Can we add this to the list?

**Comment by ftbastler** [comment]
Still an issue.

**Comment by ScottDowne** [comment]
For the reason that this is likely on other locales, I'm going to propose we clean up this sort of issue this eoy campaign.

**Comment by TheoChevalier** [comment]
This has been fixed at some point, closing
