### ISSUE TITLE
Localize Bitcoin and Share Pages

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#126]

**Comment by alicoding** [comment]
Can we actually localize this? I don't know if this apply to anyone other than the US?

> The Mozilla Foundation is a California non-profit corporation exempt from United States federal income taxation under IRC 501(c)(3) and a public charity classified under IRC sections 170(b)(1)(A) and 509(a)(1). Bitcoin donations Mozilla receives are considered charitable contributions under U.S. federal tax laws, to be used in its discretion for its charitable purposes. If you have questions, check out our FAQ or contact us at donate@mozilla.org.

Should we have more generic one for other locale? What about that `FAQ` URL which links to the Wiki and it's not localized, so I think it might make more sense to have different version for other locales.

**Comment by adamlofting** [comment]
For this particular text, it's important that we 'translate' rather than 'localize'. 

It's important people know the legal status related to their donation. For example, if you're donating from Germany, you should know that Mozilla Foundation is a US organization so that you understand you're not entitled to any local tax relief related to charitably donations.

Also, though it's an edge case. It's possible for someone living in the US who speaks German, or a US citizen who is in Germany, to need to see this text about the US legal status, in German. 

Here's an example of the Mozilla.org terms in French:

<img width="338" alt="screenshot 2015-08-24 09 29 18" src="https://cloud.githubusercontent.com/assets/1901816/9435832/edcb5b54-4a42-11e5-9899-74ad68c7a33b.png">

**Comment by ScottDowne** [comment]
I closed the above bug, because it was good, but I'm not sure if it clears up the questions @adamlofting had. I'm leaving this open and I'll let @alicoding and @adamlofting close it.

**Comment by alicoding** [comment]
I would say this can be closed, but if we have concern regarding the copy we can just file another ticket for that.

**Comment by adamlofting** [comment]
Yep, I think we can close this.

I assume these pages will start working once the strings are localized: https://donate.mofostaging.net/fr/give-bitcoin/
