### ISSUE TITLE
Write copy for Thunderbird 'Standard' and 'With Context' flows

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1280]

**Comment by edrushka** [comment]
Please try to keep close to the original wordcounts, if possible. We should also add a "Interested in making a major gift? Please Contact [email])

**Comment by rkent** [comment]
Do I understand correctly that this is the original content that you would like the Thunderbird content to match:
"We are proudly non-profit, non-corporate and non-compromised. Thousands of people like you help us stand up for an open Web for all. We rely on donations to carry out our mission to keep the Web open and free. Will you give today?"

**Comment by edrushka** [comment]
@rkent Yes. For the "with context" version (which is the version [here] (https://donate.mozilla.org/en-US/about/) that has the additional text on the side), it be great if the copy is close to that character count. That was we won't have to adjust the design too much to accommodate the new text.

Keep in mind that you can also tweak the text in the automatic "Thank You" email message that donors receive after their gift goes through. That's a text-based email, so it's a bit more flexible. I'll create a separate ticket for that.

**Comment by gerv** [comment]
@rkent: are you going to draft something up here?

**Comment by rkent** [comment]
Yes I will work on the details of the donation flow, including the 
wording, this week.

**Comment by davenz** [comment]
I'll take a stab at the "With Context" wording for starters – 223 characters (230 for the original):

We're the leading open source cross-platform email and calendaring client, free for business and personal use. By donating you'll help ensure it stays that way and contribute towards future development. Will you give today?

**Comment by edrushka** [comment]
Thanks @davenz. @rkent @gerv are you both good to ship this copy? I'm a little unclear on who the final decision-maker is on your end.

**Comment by rkent** [comment]
No, we are not ready to ship this copy. I (rkent) am the decision maker. 
I'm going to focus on these issue the rest of today.

**Comment by rkent** [comment]
![mozilladonatestandardflow](https://cloud.githubusercontent.com/assets/1297827/12994121/183bde9c-d0d3-11e5-9fc3-06ec23cc4d48.png)

Here are my notes of changes needed from the Mozilla standard flow.
1. We should use a Thunderbird-specific logo rather than the generic Mozilla logo. How about this: https://assets.mozilla.org/portal/assets/#asset/284
2. We should have a custom FAQ for the Thunderbird campaign. That main difference will be to explain in more detail how the Thunderbird donations will be managed in a designated fund within MoFo, and what kinds of things those funds could be used for.
3. I assume that you will want to create a separate donate email address for questions so that you can distinguish questions about the Thunderbird campaign from the general campaign.
4. This sentence needs changing: "Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to be used in its discretion for its charitable purposes." This needs to be a short sentence that describes that the funds are designated for use with Thunderbird, but makes clear that the donation is ultimately subject to MoFo. It might be better if legal rewrites this sentence.

**Comment by rkent** [comment]
Assuming that these comments are accepted, then we need tasks to deal with each of these specific issues. What else can I do to move this particular page forward?

**Comment by rkent** [comment]
Thanks @davenz for the suggested wording. It makes me realize that we need to think through more carefully what we are trying to say. I assume that this page, the "with context", would be where someone would land if there was a simple link on another page, that said something simple like "donate to Thunderbird".

We need to make clear in the text:

1. The donation will be to a designated fund in Mozilla that is specified for use by Thunderbird (as opposed to general use by the Mozilla Foundation).
2. After the donation, we'll ask donors to subscribe to an email list which we will use to ask donors for feedback on priorities and strategies for Thunderbird in the future.

I'll see if I can fit that into the allowable space.

**Comment by rkent** [comment]
Here's my first draft of the With Context text. Comments?

"Thunderbird is Free Software, but we still have costs. We'll use donations will help maintain and improve Thunderbird. If you subscribe to our donors list, you can help guide priorities for the future. Will you give today?"

**Comment by rkent** [comment]
More on Note 2: I copied the Mozilla donate FAQ page in the wiki to a new link: https://wiki.mozilla.org/Thunderbird/Donate  Is it OK if we modify that page as a Thunderbird customized donate FAQ, and use it as the target of the FAQ in the donate.mozilla.org page for Thunderbird?

**Comment by edrushka** [comment]
> 1. We should use a Thunderbird-specific logo rather than the generic Mozilla logo. How about this: https://assets.mozilla.org/portal/assets/#asset/284

Agree. We have a designer on hand who can give these pages a more Thunderbird feel. It's important donors understand they are giving to TB and not Mozilla. Tickets already filed: #1283 and #1285

> 2. We should have a custom FAQ for the Thunderbird campaign. That main difference will be to explain in more detail how the Thunderbird donations will be managed in a designated fund within MoFo, and what kinds of things those funds could be used for.

Agree - there should be a separate TB FAQ. Customizing the Donate FAQ works for me. We can link to the TB-specific FAQ from the Donate FAQ as you suggested.

> 3. I assume that you will want to create a separate donate email address for questions so that you can distinguish questions about the Thunderbird campaign from the general campaign.

Yes, we can have a separate email but the TB team should manage inquires sent to this address. Just let us know what email address we should put here.

> 4. This sentence needs changing: "Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to be used in its discretion for its charitable purposes." This needs to be a short sentence that describes that the funds are designated for use with Thunderbird, but makes clear that the donation is ultimately subject to MoFo. It might be better if legal rewrites this sentence.

Yes. Please go ahead and file a ticket with legal. We'll swap in whatever wording they suggest.

**Comment by rkent** [comment]
Bug for address thunderbird-donate@mozilla.org for use with "Send us an email": 1248060

**Comment by rkent** [comment]
@edrushka re "Yes. Please go ahead and file a ticket with legal. We'll swap in whatever wording they suggest." I could not figure out a way to do this. Would you mind doing this? (Even a Mozilla directory is above my pay grade :( )

**Comment by edrushka** [comment]
@rkent - I'll see what I can do! :)

**Comment by rkent** [comment]
@davenz I mostly used your laguage in the Thank You email here: https://github.com/mozilla/donate.mozilla.org/issues/1293#issuecomment-183516898

**Comment by ScottDowne** [comment]
Pretty sure copy also landed in: https://donate.mozilla.org/en-US/thunderbird/about/
