### ISSUE TITLE
Brand Thunderbird 'Standard' flow

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1283]
We're creating a version of the 'Standard' donation form https://donate.mozilla.org/en-US/ for Thunderbird. We need to brand this with a Thunderbird logo and colours. 

Dev ticket is #1281 
Copy ticket is #1280

cc-ing Cassie to assign once we have final copy.

**Comment by edrushka** [comment]
Here's some Thunderbird assets: https://events.mozilla.org/portal/events/#category/1067

**Comment by edrushka** [comment]
![simple](https://cloud.githubusercontent.com/assets/1119821/13359668/6cd90f72-dc83-11e5-8700-cad3ff91948f.png)

@Rkent - how does this look?

**Comment by vazquez** [comment]
#### Update

- "Contributions go to..." copy has been changed.
- @edrushka –Is it possible to change the suggested amounts?
- Waiting on @davidascher's decision to change the footer copy to "organization behind Thunderbird"

![screen shot 2016-03-02 at 10 12 50](https://cloud.githubusercontent.com/assets/1119821/13464465/5e6bc8f0-e05f-11e5-9ce8-d2af2c4b4196.png)

**Comment by davidascher** [comment]
That footer copy is purely there to give confidence so I'd say: "
organization behind Thunderbird and Firefox". But if rkent prefers not to
have ff mentioned I'm fine with that.

**Comment by vazquez** [comment]
Thanks @davidascher. @rkent –let me know your preferred copy and I will make the change.

**Comment by rkent** [comment]
OK "behind Thunderbird and Firefox" is fine, let's go with that.

**Comment by valianttry** [comment]
The default amounts on the form have been tested extensively -- average gift for EOY fundraising through Firefox is $9. We've tested order (small > large vs. large > small), odd vs. even numbers, and various amounts. 

This is a different ask related to Thunderbird vs. Firefox+Mozilla, so I suggest we start with these amounts since they are tested, and watch the data and the average to see if we need to edit the amounts in the future.

**Comment by rkent** [comment]
OK let's leave the amounts where they are. I also checked LibreOffice, their average donation is similar to Firefox, so the original numbers make sense.

**Comment by vazquez** [comment]
Footer copy has been changed. This change appears only in the Thunderbird donation flow.

![screenshot 2016-03-02 14 47 27](https://cloud.githubusercontent.com/assets/1119821/13473143/fdc4ef64-e085-11e5-9d18-003c03e9acad.png)

**Comment by ScottDowne** [comment]
https://donate.mozilla.org/en-US/thunderbird/
