### ISSUE TITLE
Brand Thunderbird 'With Context' flow

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1285]
We're creating a version of the 'With Context' donation form https://donate.mozilla.org/en-US/about/ for Thunderbird. We need to brand this with a Thunderbird logo and colours.

Dev ticket is #1282
Copy ticket is #1280

cc-ing Cassie to assign once we have final copy.

**Comment by edrushka** [comment]
![k_93bnfx9rke7vack3hjxd5eqbnzxs1rhqf0kgoc6kc](https://cloud.githubusercontent.com/assets/4515662/13435499/813146ec-df8f-11e5-9d94-04b90d1cedc0.png)

@Rkent what do you think?

**Comment by vazquez** [comment]
#### Update

- "Contributions go to..." copy has been changed.

![screen shot 2016-03-02 at 10 14 46](https://cloud.githubusercontent.com/assets/1119821/13464614/fd373622-e05f-11e5-8d3f-dcd14f790f35.png)

**Comment by vazquez** [comment]
Footer copy has been changed. This change appears only in the Thunderbird donation flow.

![screenshot 2016-03-02 14 47 27](https://cloud.githubusercontent.com/assets/1119821/13473143/fdc4ef64-e085-11e5-9d18-003c03e9acad.png)

**Comment by ScottDowne** [comment]
This was done: :https://donate.mozilla.org/en-US/thunderbird/about/
