### ISSUE TITLE
Set up Exact Target list for Thunderbird donors

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1289]
We're creating some donation flows specifically for Thunderbird donations (see more [here.] (https://github.com/mozilla/donate.mozilla.org/issues?q=is%3Aopen+is%3Aissue+label%3AThunderbird)) We need to create an Exact Target group specifically for these people. 

MoFo will relay messages from the Thunderbird point person so we don't need to set up any new accounts. These messages will be low frequency.

@stephaniemcv can you help set this up?

**Comment by stephaniemcv** [comment]
Unfortunately I don't think I can lead. If we're pulling people out of Stripe and PayPal then they need a Token from Basket before getting into ET, and I don't have the access or authorization to handle Basket yet.

**Comment by edrushka** [comment]
Do you know who has access?

**Comment by valianttry** [comment]
@edrushka when you say "MoFo will relay messages from the Thunderbird point person so we don't need to set up any new accounts. These messages will be low frequency." Does that mean we will be responsible for setting up and sending content provided by Thunderbird staff? And can you define "low frequency"? 1x a month or 3 x a year; etc?

**Comment by edrushka** [comment]
Yes, that's the plan at the moment. @davidascher may be able to estimate frequency.

**Comment by valianttry** [comment]
A couple of important things:
* The number of admins greatly increases risk to the list data, so Steph is working on protocols that will likely lead to a very tiny # of people with the ability to set up, test, and launch emails. This also means she takes on added responsibility for email launching by necessity.
* Small lists in the future with rare send frequency will likely NOT live in ExactTarget -- those emails will be sent using "business email" functionality in Salesforce. The risk is lower and the interface is much simpler/ self serve. Obviously that is not a short-term solution.
* @davidascher is there any reason Thunderbird couldn't use a commercially available solution such as ConstantContact or MailChimp? Adding this list to our database also creates a potential barrier to separation in the future should Thunderbird become more independent.

To be clear, I'm not trying to complicate things -- I understand our desire to throw Thunderbird a bone, but I worry we are taking on more responsibility than is feasible given current capacity and long term planning around email and CRM.

**Comment by davidascher** [comment]
I'm open to other alternatives besides ET. We'd want some process to review
emails but that can be done out of band.

**Comment by stephaniemcv** [comment]
Knight Mozilla Open-News is now using MailChimp, just FYI

@edrushka The only two people I know who have access is Ben N. and Jess D. Both are probably going to be out of pocket for awhile, Ben's on a durable team and Jess is working on the CRM.

**Comment by edrushka** [comment]
@valianttry with our existing donation flow we could simply export a list of names and email addresses from Stripe for the Thunderbird team, correct? 

@davidascher assuming that's possible, does it make sense for the Thunderbird team to own the emailing? They can choose which software they want to use (e.g. MailChimp), and put it through security review.

**Comment by rkent** [comment]
If Knight Mozilla Open-News currently uses MailChimp, I assume it passes security review once. What more is needed?

I would really like to avoid situations where we are asked to use some locked-down system that we have no real access to. That is a problem Thunderbird has throughout Mozilla at the moment, and it create enormous friction to getting things done. So if we could own the emailing that would be great.

**Comment by edrushka** [comment]
@stephaniemcv @valianttry @davidascher  Does this seem like a reasonable solution: when the Thunderbird team wants to send an email, we generate a list of First Name, Last Name, Email address and Donation amount from Stripe and Paypal for them, and they handle the rest? (Note: I'm not familiar with how labour-intensive this exporting would be for our devs, so the frequency would have to be negotiated).

**Comment by rkent** [comment]
@edrushka: So if I understand correctly, Mozilla currently collects contact information from people who have donated (which is available from the payment providers, Paypal and Stripe) and then periodically sends emails to those people. Then you use an email marketing provider (Exact Target) that gets its data from, what, Salesforce? Mozilla must have some process in place to transfer data from Stripe and Paypal to the contact database. If Thunderbird uses a different contact solution, then the data export needs to be done on a periodic basis, not on a per-email basis, correct? (essentially replacing whatever means you use to transfer data from Strip and Paypal to Salesforce/ET)

As for frequency, 2x - 4x per year is probably a reasonable estimate. So if there was a standard process to get monthly data exported from Stripe and Paypal that could be transferred to a contact solution, that would be sufficient.

**Comment by edrushka** [comment]
^ I'll let @valianttry and @stephaniemcv clarify!

**Comment by edrushka** [comment]
@valianttry and @stephaniemcv - pinging again as we'll have to clarify this in order for the TB team to set up their own solution.

**Comment by valianttry** [comment]
Your description isn't quite correct. 

We do not automatically opt all donors into our email list (that violates our privacy policy). Instead, we redirect donors to a Thank You page that invites them to sign up immediately after they submit their donation information. Here is what that page looks like: https://donate.mozilla.org/en-US/thank-you/

On average, 18% of people who donate also opt in to our list.

We can set up a redirect to a similar optin page. Our optin page happens to add people to our ExactTarget instance. An optin page can be branded with Thunderbird branding, and the optin fields can sign people up to any list software I assume (ConstantContact, Mailchimp; etc). That way Thunderbird folks can collect and send emails to their opted in list members in their own system.

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/12997305/d0b968ae-d0ec-11e5-99a5-0ab4aa0dcd0e.png)

**Comment by rkent** [comment]
@valianttry Right I understood that there is an opt-in step, but my description was not very clear.

**Comment by valianttry** [comment]
Just checking back in on this. Managing this list for Thunderbird in ExactTarget would be more challenging than if we simply redirected donors to an optin solution that the Thunderbird team manages, such as ConstantContact signup form. 

Fundamental question: Are we firm on setting Thunderbird's list up in ExactTarget? That requires another layer of dev and data management pieces (we will need to create a new optin form that properly labels people as Thunderbird donors; develop a data transfer schedule/protocol etc). We need to decide now (unless I missed a ticket) and start the work on getting that setup.

**Comment by valianttry** [comment]
Just to clarity @rkent we don't transfer any data from Stripe or PayPal to ExactTarget. When a user submits the optin form data, it is sent directly into ExactTarget.

**Comment by rkent** [comment]
My expectation is that "simply redirected donors to an optin solution that the Thunderbird team manages" is what we will do. I have setup a Mailchimp account and maillist for that purpose, as I understand that Mozilla uses Mailchimp for some other groups.

As for details, it looks like your "Thank you" page above also collects the email address for the optin list. Instead of a Mozilla hosted  "Thank you" page, the redirect could be to a Mailchimp form that we could design in Mailchimp. Could you comment on that approach?

My expectations are that we will not use Salesforce or ExactTarget in any way with Thunderbird to avoid permissions issues for our contributors who will end up managing this.

**Comment by edrushka** [comment]
I'm closing this ticket as we've decided that the Thunderbird team will not use exact target.
