### ISSUE TITLE
Write copy for Thunderbird "Thank You" email

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1293]
People who make successful donations and provide their email address automatically receive a Thank You email receipt (image below).  Please provide the copy you'd like in this email.
cc @gerv @rkent

![thank you message](https://cloud.githubusercontent.com/assets/4515662/12768832/8be92b64-c9c7-11e5-9679-3dbce1aa786e.png)

**Comment by rkent** [comment]
What system is used to create this email?

**Comment by edrushka** [comment]
@ScottDowne is this thank you email generated through Stripe?

**Comment by ScottDowne** [comment]
@edrushka Not Stripe, it's our own thing.

Adding @jbuck

**Comment by rkent** [comment]
So what is the existing data flow from (Stripe, Paypal) into "our own thing" that generates the thank you email?

**Comment by jbuck** [comment]
@rkent I'll lay it out here:

1. Donor completes a donation via Stripe (we don't send customized emails for Paypal, which is something that I'd like to fix)
2. Stripe sends a webhook for the `charge.succeeded` event to [Sawmill](https://github.com/mozilla/sawmill/)
3. [Sawmill server](https://github.com/mozilla/sawmill/blob/4d18b661dc8deb30ce95ecf105835fbd0cb0e9e1/web/server.js#L79-L110) sends the Stripe event into an Amazon SQS queue
4. [Sawmill worker](https://github.com/mozilla/sawmill/blob/4d18b661dc8deb30ce95ecf105835fbd0cb0e9e1/worker/stripe_charge_succeeded.js) renders an [HTML email template](https://github.com/mozilla/webmaker-mailroom/blob/master/templates/stripe_charge_succeeded_2015/index.html) and sends the rendered HTML email into an SQS queue
5. [Lumberyard worker](https://github.com/mozilla/lumberyard/blob/05ca7505a2466f3f059d46b5d80f8fbcb7e629e2/workers/mailer.js) sends the email to the donor via Amazon SES.

To make this better I think we should move all of the sawmill/lumberyard email webooks/rendering/sending directly into donate.mozilla.org . It'll make changes much easier.

**Comment by rkent** [comment]
@jbuck That sounds like a one-time process. How then does the user contact information from Stripe and Paypal populate a database that can be used for contact with donors later (using some combination of Salesforce and ET)?

**Comment by jbuck** [comment]
We send a newsletter subscription to ET via [basket](http://basket.readthedocs.org/en/latest/newsletter_api.html#news-subscribe)

**Comment by rkent** [comment]
How is the basket message triggered? Somehow the data has to get from 
Stripe/Paypal into basket. Since basket is a web service, something is 
sending it a web request. What is that something?

**Comment by gerv** [comment]
Is the underlying confusion here that rkent thinks that everyone who makes a donation will get signed up to a mailing list, when in fact the sign-up-to-a-mailing-list part is a separate, optional form managed by Exact Target?

**Comment by jbuck** [comment]
Ah right, sorry. After the user makes the donation, they get redirected to https://donate.mozilla.org/thank-you/ where they can sign up for the newsletter via Basket

**Comment by gerv** [comment]
jbuck: We'd need a separate list for this one (people specifically interested in Thunderbird stuff). Will that be a problem?

Gerv

**Comment by rkent** [comment]
OK thanks, that clarifies things. I'm trying to understand all of the pieces, so that as we prepare text we understand what they will be used for.

**Comment by edrushka** [comment]
@rkent you may find the PDF's in the last comment helpful: https://github.com/MozillaFoundation/2015-fundraising/issues/23#issuecomment-123630737 

Note that these are from 2014, but from a user perspective, it's still more or less the same. I'd be happy to meet and walk you through this if it would be helpful.

**Comment by rkent** [comment]
That's not a valid link (or it is hidden from me). Could you try to find 
one that I can view, or email the PDF to me directly?

**Comment by edrushka** [comment]
Sure thing. Just emailed to the address associated with your GH account. You can reach me at erikad@mozillafoundation.org if that didn't work (I couldn't find you in the Moz phone book).

**Comment by valianttry** [comment]
FYI @rkent out-of-the box Stripe sends an automatic receipt to donors with the amount they donated -- but it was built primarily for carts / purchases. Stripe limits your ability to customize that email. We opted to build a separate flow in order to include legally required information about tax status; donor email for Qs etc.

**Comment by rkent** [comment]
So with your separate flow, does the donor also get the automatic 
receipt from Stripe or did you suppress that?

BTW I've used Fastspring for my own purposes as a payment processor and 
have been very satisfied with them, so I have a little experience myself 
here (but of course with a volume a couple of orders of magnitude lower).

**Comment by jbuck** [comment]
We disabled the automatic Stripe receipt

**Comment by rkent** [comment]
Here is copy for the text:

Thunderbird is the leading open source cross-platform email and calendaring client, free for business and personal use. By donating you've helped ensure it stays that way and contributed towards future development. Every gift is so important. On behalf of all of us, thank you so much for your donation to Mozilla Thunderbird.

- The Thunderbird Team

Also, changes from the Mozilla email:
1) From: The Thunderbird Team <thunderbird-donate@mozilla.org>
2) Subject: Thank you for your gift to Mozilla Thunderbird
3) donor FAQ link: https://wiki.mozilla.org/Thunderbird/Donate
4) If you still need help .... address: thunderbird-donate@mozilla.org
5) TODO: How to cancel a recurring donation? Our team will not have the power to do this.
6) Text at bottom beginning "Contributions go to ..." needs to follow whatever language is agreed in issue #1322

**Comment by edrushka** [comment]
:ok_hand:  I think we're ready to hand this over to the dev, @rkent. Hopefully we can get something up on staging this heartbeat (by Feb 26). Thanks for getting all this copy together!

**Comment by wsmwk** [comment]
Suggest modify "By donating you've helped ensure it stays that way and contributed towards future development." to "By donating, you've contributed towards product development, and helped ensure Thunderbird stays free and open."

**Comment by davenz** [comment]
That results in a double-up on the words "open" and "free", when all put together.

**Comment by wsmwk** [comment]
Agree, the repetition may be substandard writing style.  But I dislike the use of "that way" as a means of emphasis because it is somewhat confusing/non-specific, and the change does emphasize what seems to be important points.  Doesn't seem to overbearing to me. But I defer to Kent.

**Comment by rkent** [comment]
How's this for a compromise:

Thunderbird is the leading open source cross-platform email and calendaring client. By donating, you've contributed towards product development, and helped ensure Thunderbird stays free and open. Every gift is so important. On behalf of all of us, thank you so much for your donation to Mozilla Thunderbird.

**Comment by davenz** [comment]
Sorry about the delay – I think the compromise reads fine.

**Comment by ScottDowne** [comment]
Anyone know the status on this? Sounds like a dev was needed but it doesn't look like that ever happened?

Does this need me to do anything?

**Comment by gerv** [comment]
It seems like someone needs to make sure that the thank you email sent out when someone donates (via Stripe) matches what rkent says in his comment just above. jbuck seemed to suggest this mail was generated by Sawmill?

**Comment by ScottDowne** [comment]
Yeah, this makes sense now.

@cadecairos is this something you can do? I'm not sure how @alicoding has the donation configured to be flagged for thunderbird or not, or how to send the webhhook in a way that sawmill can distinguish between two templates.

Thoughts?

**Comment by cadecairos** [comment]
https://github.com/mozilla/webmaker-mailroom/blob/master/templates/thunderbird_donation/index.html
