### ISSUE TITLE
Only show Bitcoin footer to EN-US for now

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#130]
This string has not been translated yet, and links out to English only content. So for now, let's only show this if the language is EN.

https://github.com/mozilla/donate.mozilla.org/blob/master/pages/sequential.jsx#L1286-L1287

I tried to add this but ran into issues with i18n.js error messages:

```bash
/Users/alofting-10317/Sites/donate.mozilla.org/locales/messages.js:4
var req = require.context('./', true, /\.json.*$/);
                  ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/alofting-10317/Sites/donate.mozilla.org/locales/messages.js:2:19)
```

@alicoding if you get time after the thank you pages, it would be great if you can look at this `i18n.js` issue. But it's a P2.

**Comment by ScottDowne** [comment]
My thoughts ATM.

I want to avoid doing checks and conditions against locales inside the components.

I would rather the build step handle this, and create a prop in the component for what it's removing.

Example, in build step, check if we're english, if we are, we pass in "showBitcoin" or something to the component.

This is kinda how we did it before. https://github.com/mozilla/bsd-forms-and-wrappers/blob/7499bfd4b5a2ce5ed930bf0522c2d2b1a03a9b47/0-donation-forms/EOY-donation-form-sequential/above-form-content.html#L508

It was a flag created and passed into the template.

**Comment by adamlofting** [comment]
I like the sound of doing this in the build step. Might be something we can hack on next week.

**Comment by adamlofting** [comment]
Going to investigate more holistic issues next week.
