### ISSUE TITLE
Clear language with legal for Thunderbird

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1322]
Currently, the text on the donate page reads: "Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to be used in its discretion for its charitable purposes." 

For the Thunderbird-specific donate pages, this needs to indicate the funds are going to Thunderbird.

@davidascher I'm assigning this to you to flag with legal.

**Comment by davidascher** [comment]
I asked abigail.

**Comment by abigailphillips** [comment]
Is Thunderbird now a project of MoFo? In other words, will MoFo be receiving the Thunderbird funds?

**Comment by davidascher** [comment]
Yes, MoFo will be receiving (& disbursing) the Thunderbird funds.

**Comment by abigailphillips** [comment]
I'd include language along the lines of: "Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to support Thunderbird." Or "Mozilla Thunderbird", or whatever it is officially called. But please send mocks of the flow when you have them in case this should look different in the context. Thanks.

**Comment by edrushka** [comment]
Thanks @abigailphillips! I'll ping you when we have something to look at on staging.

@rkent what's the official name? Thunderbird or Mozilla Thunderbird?

**Comment by davidascher** [comment]
Legally I believe it's Mozilla Thunderbird.

**Comment by rkent** [comment]
Yes I would use Mozilla Thunderbird in any official language such as this.

**Comment by edrushka** [comment]
OK. We'll use:

Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to support Mozilla Thunderbird.
