### ISSUE TITLE
Impact of L10N on the fundraising campaign

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1334]
Hi @adamlofting --

Theo on the L10N team reached out to me by email. He inquired about how we can celebrate the impact of localization on our EOY fundraising campaign. Have you had any time to do analysis on how adding currencies + localizing testing impacted our revenue? Would this be something you could get to anytime soon? I think it would be an incredibly useful analysis, and prove some of our theories about investing in more localization, but I realize you're overstretched as it is. :1234:

**Comment by adamlofting** [comment]
I'm probably not going to spend time on this this heartbeat, but in that email Theo already had the data and was checking it was ok to talk about it. I'll reply to say that's fine.

We can save the rest of this task for the new hire once that role gets approved. It will be a good chance for that person to get up to speed with our data.
