### ISSUE TITLE
Move domain names into environment vars

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#138]
Let's dig around the repo and move some of these into environment vars:

References to our staging / prod domains
* https://github.com/mozilla/donate.mozilla.org/blob/master/server.js#L65

References to Paypal sandbox
* https://github.com/mozilla/donate.mozilla.org/blob/master/server.js#L80

And then let's document these vars in the README

The existing values are good defaults for developers to work with for local dev.

**Comment by ScottDowne** [comment]
This is all I could find that is left: https://github.com/mozilla/donate.mozilla.org/commit/71ee920214933f0d60772108ff939ad497764652

**Comment by adamlofting** [comment]
There's a couple in here: 
* https://github.com/mozilla/donate.mozilla.org/blob/master/components/simple-paypal.jsx#L162

And a coinbase one here:
* https://github.com/mozilla/donate.mozilla.org/blob/master/pages/give-bitcoin.jsx

And this for email sign-up here (we don't have staging ATM, but will do once we move to Basket):
* https://github.com/mozilla/donate.mozilla.org/blob/master/routes/index.js#L9

**Comment by ScottDowne** [comment]
Another pass: https://github.com/mozilla/donate.mozilla.org/pull/320

I think that got all of them.
