### ISSUE TITLE
Images missing from fundraising.mozilla.org posts

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1384]
@simonwex 
Images have disappeared from several blog posts, including this one:

https://mozfundraising.wpengine.com/ab-test-new-ui-no-news-is-good-news/

![a_b_test__new_ui_ _no_news_is_good_news___mozilla__view_source_fundraising](https://cloud.githubusercontent.com/assets/9830371/13621238/d48a9206-e54a-11e5-93c9-40a9dcbe4a16.png)

Not sure what is happening (maybe related to our CMS blog system upgrade?)

**Comment by simonwex** [comment]
Thanks for the heads-up, @valianttry! 

@jbuck looks like we have a few issues with the move to wp-engine.

**Comment by jbuck** [comment]
That blog post was using http images, which are blocked by mixed content filtering. I modified the post to use https urls and it's looking good again!

**Comment by valianttry** [comment]
YAY thanks @jbuck !
