### ISSUE TITLE
Build process allows different locales per page

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#139]
This ticket follows on from the conversation here: https://github.com/mozilla/donate.mozilla.org/pull/129#issuecomment-126386399

I think we should modify the build step so that we can say something like:

* Build `form-a` in locales `[ a, b, c, d ]`
* Build `form-b` in locales `[ c, d, e, x, y ]`

E.g. Build sequential form in some locales, and build simple paypal form in others.

But we should write this in a way that works when we're testing new landing pages in multiple locales.

**Comment by adamlofting** [comment]
There's a good chance that how we want to do this might change after our work next week. So we can review after we spend time looking at the forms in more detail.

**Comment by ScottDowne** [comment]
Right now building all the forms isn't ideal, but it works, so pushing.

**Comment by ScottDowne** [comment]
We're at the point where getting everything translated or building the forms is easy enough to do for all.

Before we had legacy forms for multiple languages, but not for the primary language to handle currencies we could only use with paypal. Now all our forms can handle all currencies, so there is not really a point to not have all pages in all languages.

Until we have a use case where a locale needs this, let's keep this issue closed.

**Comment by adamlofting** [comment]
:+1:
