### ISSUE TITLE
Setup staging environment (and auto deploy)

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#14]
With auto-deploy to staging when code is merged to the repo.

**Comment by alicoding** [comment]
right now I have it up on https://donate-mozilla.herokuapp.com just so we can see the site live...

**Comment by adamlofting** [comment]
@jbuck @ScottDowne 

How should we handle deployment to Staging and Prod? Should we use a `develop` branch which auto pushes to Staging, and a `master` branch which auto pushes to Prod?

**Comment by adamlofting** [comment]
Can we use https://donate.mofostaging.net please?

I'll start setting up a GA staging profile on the assumption that will be our staging domain.

**Comment by adamlofting** [comment]
- [x] Heroku environment setup for staging
- [x] Project auto deploys on merge to `master` branch

Remaining tasks
- [ ] Make sure this heroku project is in the Mozilla account
- [ ] Setup https://donate.mofostaging.net to point to it

**Comment by jbuck** [comment]
This is an easy-to-fix blocker #204

**Comment by jbuck** [comment]
Okay, I have a working cloudformation script that's now deployed: https://donate.mofostaging.net Things to look at before I commit:

- [ ] Do we want a switch for dedicated IP's (support very old browsers/operating systems that don't support SNI) https://aws.amazon.com/cloudfront/custom-ssl-domains/
- [ ] Are there any custom error pages we want to display?

**Comment by jbuck** [comment]
Once the associated PR is landed, lets close this.
