### ISSUE TITLE
Bitcoin - broken URL

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1406]
@simonwex @jbuck @valianttry 
While QAing a list of forms that had been switched over from BSD to Basket I ran into this, it's not redirecting anywhere.

https://sendto.mozilla.org/page/content/give-bitcoin/

And it's linked on the Bitcoin FAQ: https://wiki.mozilla.org/Donate_Bitcoin

**Comment by jbuck** [comment]
@ScottDowne @alicoding

**Comment by ScottDowne** [comment]
Let's just update the wiki?

**Comment by alicoding** [comment]
I think we need to redirect that URL to our d.m.o/bitcoin too

**Comment by alicoding** [comment]
I couldn't find the URL in BSD, so I just updated the URL in the wiki to what's in the donate.mozilla.org instead.

Thanks for reporting @stephaniemcv
