### ISSUE TITLE
Paypal Error running latest master branch

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#141]
I'm just testing out donation flow, and ran into this issue for PayPal using one-off or monthly donations:

<img width="1002" alt="screenshot 2015-07-31 13 43 12" src="https://cloud.githubusercontent.com/assets/1901816/9007527/1465f0d8-378a-11e5-8ee1-9bbd2f7c5ae7.png">

I have copied the latest `.env` variables from `sample.env` but I might have missed some other configuration?

**Comment by ScottDowne** [comment]
Staging should be working now: https://donate-mozilla.herokuapp.com

Stripe and paypal test accounts should work as defined in the readme.

**Comment by ScottDowne** [comment]
I think I'm just going to close this as I'm *pretty* sure it's resolved, but if you're still having issue don't hesitate to reopen or file a new one :)
