### ISSUE TITLE
High chargeback rate on Stripe Visa charges

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1412]
@jbuck can you check on this? I thought we required CVC and zip check already?

@simonwex this is an important task we should transfer smoothly from @jbuck . If our chargeback numbers don't get reduced we run the risk of losing our ability to process gifts. 

---

Hi John,

I'm out of the office today but looping in Andrea who heads up the fundraising program.

Thanks
A

Sent from a tiny portable computer capable of making and receiving phone calls

> On 21 Mar 2016, at 14:56, John Haddock jhaddock@stripe.com wrote:
> 
> Hi Adam,
> 
> Mozilla has been flagged by Visa for having an unusually high chargeback rate (15%) in the last month. Is this something that Mozilla has been tracking? As a way to reduce its chargeback rate, I would suggest taking a look at our guides here and requiring CVC and zip check in the dashboard: https://support.stripe.com/questions/how-can-i-avoid-chargebacks.
> 
> We'd like to help you get chargeback rates under 1%. A failure to do so generally results in fines from the card networks as part of their chargeback monitoring program.
> 
> Please let me know if you have any questions.
> 
> John

**Comment by cadecairos** [comment]
I'll look into this, @jbuck is moco now + he's on vacation!

**Comment by jbuck** [comment]
@valianttry We do require both checks to pass, but apparently the fraudsters have those bits of info already...

**Comment by cadecairos** [comment]
We've definitely enabled CVC and Zip checks

**Comment by simonwex** [comment]
@cadecairos, @alicoding, @ScottDowne could you three put your heads together and figure out what we should do here?

**Comment by cadecairos** [comment]
I filed this: https://github.com/MozillaFoundation/mofo-devops/issues/293

But there are some privacy implications that need to be carefully thought out

**Comment by ScottDowne** [comment]
Maybe we should consider integrating Kount with Stripe?

**Comment by cadecairos** [comment]
@valianttry Could you go set up a meeting with Stripe to discuss further fraud prevention measures?

**Comment by jbuck** [comment]
Previously: https://github.com/mozilla/donate.mozilla.org/issues/1184

**Comment by valianttry** [comment]
Meeting is confirmed: Andrea's Vidyo Room || 3/30 || 10:30am PST
Invited so far:
Eric Lasker and Tara [last name unknown] from Stripe
@simonwex 
@cadecairos 
@ScottDowne 
@alicoding

**Comment by cadecairos** [comment]
I put together some q's, dumping them here

* Beyond stripe's fraud detection, how can we stop further fraud?
* Fraudsters seem to use the same email over and over again; Does the fact that we generate a new customer record for each donation affect the effectiveness of Stripes fraud detection? Would relating multiple charges to one customer record be a help?
* What External fraud prevention services integrate well with Stripe?
* If we were to build the means to detect fraud ourselves, what kind of things should we look for as indicators of fraud?

**Comment by valianttry** [comment]
NOTES from our meeting with Stripe (Eric and Tara):
Fraud shield: 
Machine learning based system: Fraud Shield trained across all Stripe charges. 
Static + dynamic factors that score charges based on a scoring system
User dashboard
End of January: blocking 10K charges (25% of total charges)
Stripe: set of upgrades planned, more visibility and information to customize shield is a feature that’s coming
Stripe: We need Mozilla to pass through as much intel as possible
Red yellow green in dashboard = risk levels (likelihood of ending in dispute)
Yellow = suspicious
Changes: Part of core Stripe (not an added cost)
But, could add cost later
Through Dec 31 2016 it will be free
Will the machine learning models to detect fraud be customizable by org or industry?
Customizable for industry (Tara)
General models operate across all Stripe clients

NEXT STEPS:
Stripe will turn on Fraud Shield as soon as we’re ready (no dev work required)
Tara will send docs over and we have to review and give a thumbs up
Will have red, yellow, green tags
Look at yellow charges - what’s a marker of fraud and hit a button in dashboard “report”
Provides top reason why the system believes a charge is risky “top factor” for score.

**Comment by valianttry** [comment]
Follow up from Eric at Stripe:

Hi Andrea, 

Thanks again for chatting with us today. Two follow ups from our end:

1. Your team will want to confirm that they send us: cardholder's name, CVC,
cardholder's billing and shipping address, customer's device ID,
customer's IP, and customer email address. Also, to confirm, are you using Stripe.js or Stripe Checkout?

2. Also, you can read a bit more about the fraud beta here: stripe.com/docs/fraud-beta

Let me know when your team is ready for Tara and I to flip that on, and do feel free to reach out with any other questions that you have. 

Thank you!

**Comment by alicoding** [comment]
Customer's device ID and IP... Interesting hmm...

**Comment by ScottDowne** [comment]
@valianttry we're sending everything but decive id and ip. We can send those along, and it should be fine (BSD and Kount did this in our previous systems) but the privacy nature of that I want the go ahead from someone like @valianttry @simonwex or @davidascher

**Comment by simonwex** [comment]
It's fine to send this info. They have been through our review process and we trust them with more sensitive data than this, already.

**Comment by davidascher** [comment]
Seems logical to me that IP would be incredibly useful to Stripe to detect
fraud.  BTW: I don't know what a device ID is on the web -- I'm sure it'd
be useful too, but likely not that relevant for us today.

Question, @valianttry: does our contract w/ Stripe specify the specific
data that we entrust Stripe with, or is the language generic?  Assuming the
latter, I'm fine w/ adding IP address to the list of things we rely on them
to keep secure.

**Comment by ScottDowne** [comment]
@valianttry 

1. are you using Stripe.js or Stripe Checkout: checkout
2. I cannot find docs on sending in device id or ip. I'm not sure where they want me to put this when I make a charge. I didn't see anything in stripe.com/docs/fraud-beta

**Comment by cadecairos** [comment]
Stripe Radar has solved this.
