### ISSUE TITLE
Description and Metadata missing from Stripe charges

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate.mozilla.org#1429]
In the Stripe dashboard, I'm seeing many charges that are missing the description (currently a localized string - "Mozilla Foundation Donation") and charge metadata (we set email and locale)

I'm not sure why this is happening, but it must be investigated, because the metatdata is crucial to sending localized receipts for donations.

**Comment by ScottDowne** [comment]
I wonder if and how this is reproducible from just clicking around the UI?

**Comment by cadecairos** [comment]
> I wonder if and how this is reproducible from just clicking around the UI?

Can you expand on what you mean here?

**Comment by ScottDowne** [comment]
Can we trigger this to happen on staging or locally?

**Comment by ScottDowne** [comment]
I wouldn't mind poking around and trying to reproduce this.

**Comment by cadecairos** [comment]
It is reproducable on staging

**Comment by ScottDowne** [comment]
steps?

**Comment by cadecairos** [comment]
All I did was send a donation!

**Comment by ScottDowne** [comment]
Hmm, does it happen every time or only sometimes?

I'm going to test locally and see if I can understand what you mean better.

**Comment by cadecairos** [comment]
if you take a look at the stripe dashboard, you'll see what I mean.

When you list all the latest payments, some will show "Mozilla Foundation Donation" and others will show "ch_blahblahblahblahblah" - the latter also don't include metadata.

**Comment by cadecairos** [comment]
False alarm! The charges without a description or metadata are monthly subs. the metadata is contained in the subscription object.
