### ISSUE TITLE
Make it clearer when you're setting up a recurring donation

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#143]
On the last screen when setting up a recurring gift by card, the button should say something like:

`Give $5 / month` 

Currently it says `Donate $5 now` which isn't very clear.

<img width="642" alt="screenshot 2015-07-31 14 19 18" src="https://cloud.githubusercontent.com/assets/1901816/9008040/2df5e94a-378f-11e5-8a93-46c370d2246f.png">

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/245

I talked a bit with Ricardo, and he suggested to use the button text "Donate $3 monthly" but we can totally AB test this at some point.

**Comment by adamlofting** [comment]
That works for me :+1:

**Comment by ScottDowne** [comment]
Landed
