### ISSUE TITLE
Validation of month field

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#145]
In this scenario, the validation message doesn't explain the real error, and I think we could just add the leading `0` automatically.

<img width="394" alt="screenshot 2015-07-31 14 42 36" src="https://cloud.githubusercontent.com/assets/1901816/9008436/4de716cc-3792-11e5-9c97-c2faf5dcd418.png">

**Comment by ScottDowne** [comment]
I wanted to point out that it now doesn't error on the single digit.

However, I wanted to make sure that it properly submits the single digit. We may need to pad it with a 0 before we submit.

**Comment by ScottDowne** [comment]
It seems to work fine with single digit.

I did make sure only number keys are valid, and it does some basic range checking. Month must be between 1-12 and year must be above 15.

I'm sure we could go even further with this, but stripe is going to catch anything we missed, and display an error anyway. Any more validation we want to do is totally a P2.

**Comment by adamlofting** [comment]
:+1:
