### ISSUE TITLE
Memory hike because of using babel in run-time

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#1458]
We just landed a patch https://github.com/mozilla/donate.mozilla.org/commit/636053ac1691fe75439760c71db8b43fc24a9337 which uses Babel on the server side to convert React code that uses for `React-router` to render the page. The problem here is that Babel is not meant or recommend for production since it's memory expensive and probably the best way to use Babel is to build and use that on production instead.

I don't know what's the best way to do this, but filing this issue to make sure we don't push to prod until we get this fix, or back this patch off if we need to push something to prod.

cc @cadecairos @ScottDowne

**Comment by ScottDowne** [comment]
Closing this for now. We backed it out, and we have an idea that avoids doing babel run time.

We're going to build a dist from src as a build step with babel, then webpack can just package that up without parsing it with babel.
