### ISSUE TITLE
Review Stripe notification text with legal

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#146]
See #85

**Comment by adamlofting** [comment]
Pushing to next heartbeat while we finalize legal bits.

**Comment by valianttry** [comment]
@adamlofting how is this going? Anything I can do to be helpful with legal stuff?

**Comment by adamlofting** [comment]
Stripe account / legal paperwork is still back and forth between the two orgs.

This ticket is to review the text we use to inform the user that their data will be handled by Stripe as part of the process. I've filed that bug to check with legal. https://bugzilla.mozilla.org/show_bug.cgi?id=1210332

**Comment by valianttry** [comment]
Looks like Legal approved the language you proposed @adamlofting :clap: :clap: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1210332

**Comment by adamlofting** [comment]
:tada:
