### ISSUE TITLE
Add recurring payments to Stripe

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#147]

**Comment by ScottDowne** [comment]
Odd, seems recurring payments are connected to plans, with fixed prices.

We have two options. Either using their API create a custom plan per monthly stripe donation.

Or, create a plan for 0.01 and charge then for multiple plans. https://support.stripe.com/questions/how-can-i-create-plans-that-dont-have-a-fixed-price

It seems option 2 is the suggested option, but option 1 seems less prone to issues. Option 2 scares me a bit when it comes to conversion rate and math related bugs. Feels more complex.

I'll try option 1 first, and see if it starts to piss me off.

**Comment by adamlofting** [comment]
I think if we go for option 2, we'd need to setup a plan in each currency we want to accept. We'd also need to cross check minimum donation amounts for each currency, but that's something we can do.

But all currencies can still be set to 0.01 (because we don't accept any [non-decimal currencies](https://en.wikipedia.org/wiki/Non-decimal_currency))

My only hesitation with Option 1 is ending up with thousands of custom plans in the Stripe admin, and whether that makes it hard to do admin work like go in and cancel a recurring donation for example.

**Comment by adamlofting** [comment]
> Option 2 scares me a bit when it comes to conversion rate and math related bugs.

I think we can avoid this by setting up plans in each currency, then the only maths would be `x 100` or `/ 100`

**Comment by ScottDowne** [comment]
I went with the `quantity: amt / 0.01` base plan of 0.01.

I decided this was better because Stripe has pretty good display for this and figures out to display a total to the user without making it confusing.

https://github.com/mozilla/donate.mozilla.org/pull/153/files
