### ISSUE TITLE
Tokens for Monthly donors to send an email

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1516]
Hey @ScottDowne 
I have about 16 monthly donors that I need to assign Tokens too in Basket so I can sent them an email regarding us shutting down Blue State Digital. 

Can you assign random UII tokens to these 16 people?

Below is from Jess D.:

Any new tokens are just generated on the fly. I usually just make them in a local python script[0] as it runs. It uses the UUID4 function[1] in Python's standard lib. I can do it when Jen says, but if you need to knock it out it really isn't hard and I'm sure uuid4-style random tokens can be made in any programming language.

 
 

[0] https://github.com/pmclanahan/basket_tools/blob/master/get_tokens.py#L20-L21

[1] https://docs.python.org/2/library/uuid.html#uuid.uuid4

We don't check for dupes or existing Tokens b/c:

The whole purpose of using such tokens is that they are extremely unlikely to be the same as any other token generated ever. From the link[0]:

"To put these numbers into perspective, the annual risk of a given person being hit by a meteorite is estimated to be one chance in 17 billion, which means the probability is about 0.00000000006 (6 × 10−11), equivalent to the odds of creating a few tens of trillions of UUIDs in a year and having one duplicate. In other words, only after generating 1 billion UUIDs every second for the next 100 years, the probability of creating just one duplicate would be about 50%."

https://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates

**Comment by ScottDowne** [comment]
@stephaniemcv I'm a bit confused.

Do you just need 16 UUIDs generated? Happy to do that.

Or do you need me to do something with them? Which is the confusing bit.

**Comment by stephaniemcv** [comment]
I just need the 16 UUID's generated. 
Thank you!

**Comment by ScottDowne** [comment]
This should work: https://www.uuidgenerator.net/

You can hit 16 and pick your type. As an example I came up with these, which you probably want to generate your own if they need to be hidden:

```
edcecd77-1566-4ad6-b0ae-c4305921936b
0cae3c89-c4e7-4abf-8122-ca6dfb4e7776
2b079c5f-31c5-4329-b2ba-695a023141f1
b078890b-500d-4af5-9832-e73f05606755
b92cbadc-ccf8-412b-ae2a-06a2e619a93c
d055b653-e336-4c5e-bcbc-642342fc93ad
ba8cf4f2-8dc5-4bb7-bcfb-c1610fc4e4d0
bfa2c28f-9cf0-4f42-a31d-69d30238f541
63325ca7-fe3b-461d-9e46-6461085f83c9
62959539-8041-450d-a6c0-b590758c4bce
86bf3798-e0b6-4403-b7cb-21e553524e83
4364ba05-d876-4762-a37b-b164d9cb2ddb
fa96eac2-c2ed-4e14-885b-ea2d3a0356c0
9cc0d8ce-cb80-44a4-80e9-e7e742733df8
1e68f251-25ac-47aa-a692-129ab03d0219
5c69e45f-24f5-4f98-8f81-4c7e9b7241d3
```

**Comment by ScottDowne** [comment]
@stephaniemcv is there anything else I can help with/am I blocking anything here?

**Comment by valianttry** [comment]
@ScottDowne FYI @stephaniemcv is traveling to a conference in Atlanta this week. ✈️

**Comment by stephaniemcv** [comment]
@ScottDowne Nothing more needed here! You're not blocking a thing. Thanks for the assist!
