### ISSUE TITLE
Look at capabilities of the Paypal REST API

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#152]
This is Paypal's newest API. Here's the node SDK: https://github.com/paypal/PayPal-node-SDK

Before we settle on the Express Checkout API, I think it's worth looking at this one, particularly since it seems to be much better documented & have SDKs available for most platforms.

**Comment by adamlofting** [comment]
Let's discuss this again next week.

**Comment by ScottDowne** [comment]
I think we're pretty invested with what we have at this time.

In the far future, if we want to explore this, we should just open a new issue.
