### ISSUE TITLE
Cancel Thunderbird donation in paypal sends user back to Mozilla donation page instead of Thunderbird donation page

### ISSUE THREAD

**Issue by wsmwk** [mozilla/donate.mozilla.org#1569]
From https://donate.mozilla.org/en-US/thunderbird/about/ I start a donation for paypal and am sent to https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&useraction=commit&token=EC-2LC32813TA104134A#/checkout/login

If I then click "Cancel and return to Mozilla Foundation" which is https://donate.mozilla.org/?token=EC-2LC32813TA104134A ... I then get sent to https://donate.mozilla.org/en-US/

Desired results - I should be returned to https://donate.mozilla.org/en-US/thunderbird/about/

**Comment by ajomadlabs** [comment]
Can I take up this issue ?
