### ISSUE TITLE
Send Thunderbird all macros from desk.com related to donor support

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1602]
@rkent at Thunderbird is responding to incoming donor questions as a result of launching a new donation form for Thunderbird supporters. Many of the questions are "standard." We have a set of canned responses for common questions that he could use, that would save that team some time and effort. 

@stephaniemcv can you prepare a Google doc with all our macro responses (text) and share with @rkent ?

**Comment by rkent** [comment]
The last time I received a Google doc it refused to authenticate it so I could not use it. If you do use a Google doc with restricted access, please direct to my gmail address rkentjames@gmail.com

**Comment by valianttry** [comment]
@rkent I forgot to ask: How are you responding to non-english inquiries? Do you speak DE (given Germany is where most of your users are)? We have resorted to Google Translate, which while imperfect, is definitely adequate for 95% of our correspondence with donors.

**Comment by rkent** [comment]
I do not speak DE, but we have a few German speakers as part of our
active team. I'm pretty confident that I could get a DE response if I
needed one and Google translate was not adequate. JP would be more
difficult.

Me experience with ExQuilla (my paid addon using Fastspring) is that
Google translate is adequate for understanding requests, typically with
responses written in English.

**Comment by stephaniemcv** [comment]
I have sent the sheet to you both. Let me know if there are any issues.

**Comment by rkent** [comment]
Thanks, I got that and am using the appropriate templates in my
responses now.

Our European translations just went live a few days ago, and I am
suddenly getting about 10 messages per day from Europe asking to donate
via bank transfer. Do you see a similar volume with Firefox? Is there
any hope of solving this issue?

Kent James

**Comment by valianttry** [comment]
@rkent: TL;DR it's complicated and won't happen anytime soon.

We are exploring what it will take. We are connecting with other nonprofits based in the US that accept international bank transfers. They confirm it's complicated. We may need to switch the Foundation's bank to make transfers possible. And even then, we may have to open an satellite account in the EU.  That brings up a lot of jurisdiction / legal questions for us. 

Also FYI, we don't fundraise for Firefox, we fundraise for the Mozilla Foundation. Firefox does just fine without us :)
