### ISSUE TITLE
DE donation form is a little borked

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1610]
In preparation for #1608 I checked our DE donation form. It's a little borked. @ScottDowne can you fix?

![donate_mozilla_org___spenden_sie_noch_heute_an_mozilla](https://cloud.githubusercontent.com/assets/9830371/17764624/48ded392-64d5-11e6-93b5-b2517f89b940.png)

**Comment by ScottDowne** [comment]
This is fixed and on production now.
