### ISSUE TITLE
Dutch donate page for Firefox and Thunderbird defaults to dollars

### ISSUE THREAD

**Issue by rkent** [mozilla/donate.mozilla.org#1615]
The nl pages (Like https://donate.mozilla.org/nl/about/ and https://donate.mozilla.org/nl/thunderbird/about/) default to dollars, while the equivalent de pages default to Euros. Why is that, and can it be fixed? I've had some questions from donors on this.

**Comment by ScottDowne** [comment]
Should be good now! Sorry for the delay.
