### ISSUE TITLE
Add ability to pass in gift array tests via url parameters

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#162]
In order to tailor our fundraising asks based on source, we want to add the ability to pass in 'gift array' amounts via URL parameters.

For example, in an email ask to somone who's highest previous gift (HPC) was $200, we don't send them to a default form asking for $20. 

To keep our page flexible and to avoid generating too many separate pages to maintain we want to be able to pass these values in via the URL.

Similar example from Adam Klaus: Controlshiftlabs.com
* https://takecharge-donations.github.io/
* https://takecharge-donations.github.io/?seedamount=100&seedvalues=50,100,200&seedcurrency=SEK&currencyconversion=choose
* https://takecharge-donations.github.io/?seedamount=100&seedvalues=50,100,200
* https://takecharge-donations.github.io/?currencyconversion=none
* https://action.shareaction.org/page/content/donate/ 

Uses GeoIP to guess the correct currency

**Comment by ScottDowne** [comment]
I did this in here: https://github.com/mozilla/donate.mozilla.org/pull/322

The pull request includes an example.

**Comment by adamlofting** [comment]
:boom: :+1: 

Can we put the example in the docs, and then close this ticket :smile:

**Comment by ScottDowne** [comment]
Needs docs, doing that in next heartbeat.

**Comment by ScottDowne** [comment]
Docs landed, closing.
