### ISSUE TITLE
Test just asking for email address (not address)

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#163]
On current sequential form, we would like to test removing the address fields for people who are paying by CC.

**Comment by adamlofting** [comment]
P2'd as this might be superceeded by #368

**Comment by ScottDowne** [comment]
Right now we can remove city and address, example: donate.mofostaging.net/?test=address-test

I want to leave country and postal code in for now, for fraud/signup related reasons. We can remove them later but I consider that another test we can run after we are confident in our fraud control.

**Comment by jbuck** [comment]
Switch to Stripe checkout means we can't do this test, so closing
