### ISSUE TITLE
The Polish form appears to be broken 

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1639]
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/20044350/e6f6c678-a44c-11e6-9fb9-06b273ca26e8.png)

**Comment by ScottDowne** [comment]
Looking in pontoon, it looks like we've never had this setup to be translated? I swear we did, but there is no evidence we ever had it. However, our primary locales in the past have been es, fr, de, en-US, it, and for a bit, id. So it's possible we never pushed to have this setup? On top of that, the locale file in the repo has only one commit, from Nov 25, 2015, when Ali initially created the locale folder...

**Comment by TheoChevalier** [comment]
The Polish team doesn’t work on Pontoon, they make Pull-Request. It’s probably that no one reached out to them, stealing the issue ;)

**Comment by TheoChevalier** [comment]
Reached out to the Polish community, they should be able to help us! Closing the ticket since we can’t do much more
