### ISSUE TITLE
Add notice about wire transfer not being possible to German page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/donate.mozilla.org#1645]
The Mozilla Berlin office gets regular calls from people who'd like to donate but ask for a bank account they can wire-transfer the money to. Credit cards are by far not as common as in the US.

Could we please add a notice to the German donate page to clearly state that a wire-transfer into a bank account is currently not possible?

Our office coordinator Martyna Sobczak is happy to answer any questions around this. I'm filing this issue on her behalf she doesn't have a GitHub account.

**Comment by TheoChevalier** [comment]
Hi,
We are building a new page with a localized FAQ, work can be tracked here https://github.com/MozillaFoundation/Advocacy/issues/621

The new FAQ is being reviewed by Legal https://docs.google.com/document/d/16ofBfNadmTOd_MwKmvpY7VcsQuBVU_l-dhAwsfhWRNw/edit#

> Bank Transfer
All the donations via wire transfer are subject to a $15 USD charge imposed by Mozilla’s bank.
Therefore, please keep this in mind when deciding to donate to us via wire transfer.
For further information on how to make a bank transfer to Mozilla, please email donate@mozilla.org.

**Comment by wagnerand** [comment]
Hi,

thank you for the quick reply.

I am not sure that helps us. The FAQ link is quite small and not barely visible. Also, I think it's safe to say that German users would most probably not do an international wire-transfer.

Can we add a note to the main description either way, please?

**Comment by TheoChevalier** [comment]
I know we plan to add specific answers to German and French FAQs and highlight them, bank transfer is probably part of that? @valianttry knows more, but I assume the current design on the main form can’t really be changed

**Comment by wagnerand** [comment]
For the sake of simplicity, could we extend https://github.com/mozilla/donate.mozilla.org/blob/832b3416b55fa3eb711daf7f210f6f6e347bd771/locales/de/messages.properties#L138 with a note?

That wouldn't involve any code changes and would be restricted to the German page only.

**Comment by TheoChevalier** [comment]
It’s doable on the technical side, but it needs to be approved by Legal. 
Also, work from https://github.com/MozillaFoundation/Advocacy/issues/600 probably need to be taken into account before extending this section. I will let Andrea comment on this
