### ISSUE TITLE
Safari unable to open donate.mozilla.org

### ISSUE THREAD

**Issue by jpetto** [mozilla/donate.mozilla.org#1659]
One of the devs on mozilla.org noticed that Safari is unable to open donate.mozilla.org (both on OS X and iOS) due to too many redirects (see [bug 1316541](https://bugzilla.mozilla.org/show_bug.cgi?id=1316541)).

Filing an issue as well to make sure it's seen, as this could have an impact on donations.

**Comment by ScottDowne** [comment]
Looking, thanks for the heads up :)

**Comment by ScottDowne** [comment]
Issue was our list of supported locales was an object, with keys that are in case sensitive format.

Some browsers return en-US locale codes, so it worked. Safari thinks it's special and is returning en-us, which means it doesn't match any of the locales we have translations for, and instead says "en-us" isn't a locale, so I'll assume it's a pathname, then tries to redirect to a locale, which gets en-us again, which again thinks en-us/en-us is a pathname, and keeps redirecting.

I have a patch that makes this case insensitive..

**Comment by ScottDowne** [comment]
@jpetto Should be fixed here: https://donate.mofostaging.net/ mind testing real quick?

It turns out Safari also fudges up the es-MX locale code, and instead uses es-XL, which is supposed to be Latin America.

**Comment by jpetto** [comment]
Looks good on my end!

**Comment by ScottDowne** [comment]
Thanks, closing. 🚀 🚀
