### ISSUE TITLE
Test a further monthly ask before completing a donation for one-time donors

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#166]
If a user is making a one-time donation, test someway of asking or prompting: 'would you consider giving a regular gift instead'.

E.g. if about to make a $20 donation, ask if they can donate $5 / month instead.

Talk about how this helps with long term planning, and our long term comitment to the web.

**Comment by adamlofting** [comment]
@edrushka I think the next step on this ticket would be to schedule some design time, and to get the copy we want to use into the L10N queue as early as possible.

**Comment by edrushka** [comment]
@adamlofting, I don't understand quite where this ask comes in. In a pop-up?

**Comment by adamlofting** [comment]
Yes, I can't find the article @valianttry shared before the fundraising work-week, but that example was a pop-up that appeared for people making a one-time donation when they clicked the donation button.

**Comment by edrushka** [comment]
@lovegushwa have you designed this variant already? I remember seeing some popups in one of your early redpens.

**Comment by ScottDowne** [comment]
What about a single checkbox for monthly on the final step if they didn't select monthly on the first step.

They would not see it if they already selected monthly.

Seems less disruptive than a popup (it's also a bit less dev than a popup, but a popup isn't too bad to do, if it's worth it), although maybe we're going for disruptive, which is fine. Either way, there's another option.

**Comment by adamlofting** [comment]
I think it's intended to be more disruptive to the flow.

**Comment by adamlofting** [comment]
Just saw an example of this on the link Lynn shared:
<img width="646" alt="screenshot 2015-10-27 13 59 02" src="https://cloud.githubusercontent.com/assets/1901816/10760145/fda61d78-7cb2-11e5-86a1-4e2c9188b6bf.png">

* http://www.nptechforgood.com/2015/10/12/15-lessons-learned-from-donating-online-to-32-nonprofits/

**Comment by edrushka** [comment]
+1 it's supposed to be disruptive. Here's an example Jordan mocked up for accepting payments right on the snippet: https://redpen.io/nb59dfbb743a108d28

**Comment by edrushka** [comment]
I made a design ticket for this: #638. Given its potential impact, I'll put this high in Jordan's queue for post-MozFest. Design deadline is currently Nov 20, so the build for this will be late Nov.

**Comment by jbuck** [comment]
I've started the Optimizely test (thanks @adamlofting!) and I'm just waiting for people to start appearing in my GA dashboard to confirm that everything is hunky-dory

**Comment by jbuck** [comment]
I've started seeing people donating in GA and Optimizely, so I think we're golden. Here's hoping we have a winning test for once! :P

**Comment by adamlofting** [comment]
This test hasn't found statistical significance yet, but as we're about to start the finale of the campaign I've paused this to keep everything else running as simply as possible.

We can carry on exploring this upgrade ask during year round fundraising work in 2016.

<img width="1162" alt="screenshot 2015-12-28 10 45 32" src="https://cloud.githubusercontent.com/assets/1901816/12017556/2b1f7c7c-ad50-11e5-93db-30f6bd2ca6c0.png">

cc @valianttry
