### ISSUE TITLE
Fixing some links

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate.mozilla.org#1667]
Let’s fix the following links for all locales:

faq.properties
- in faq_item_3_paragraph, ` <a href="https://www.mozilla.org/privacy/principles/">Privacy Policy</a>` should be ` <a href="https://www.mozilla.org/privacy/">Privacy Policy</a>`
and `<a href="https://sendto.mozilla.org/page/contribute/Give-Now">via Paypal</a>.` should be `<a href="https://donate.mozilla.org/paypal-donate">via Paypal</a>.` (I guess)

messages.properties
- in `problems_donating` and `donation_notice_bitcoin`, replacing the wiki link with the new FAQ.

**Comment by ScottDowne** [comment]
Good catch, I can confirm that `<a href="https://donate.mozilla.org/paypal-donate">via Paypal</a>.` makes the most sense. I considered using the default link, but, if they are this concerned with Privacy, having an as simple and clear a form as possible makes sense.

🚀

**Comment by TheoChevalier** [comment]
Fixed with https://github.com/mozilla/donate.mozilla.org/commit/47d12d5d776e45d897afd364a0c71012fef180c6
