### ISSUE TITLE
Attach GA events to email signup and social shares

### ISSUE THREAD

**Issue by vojtechmzl** [mozilla/donate.mozilla.org#1676]
With new thank you page design in the pipeline, we want to test its impact on engagement on the thank you page. In order to do that we need to attache custom Google Analytics events to the email signup, as well as to the share buttons. @ScottDowne, would you be able to help with this?

Thanks.

**Comment by ScottDowne** [comment]
I figured we could just look at bunch rate changes. That page just does one
thing, right? So bounce rate might be enough?

**Comment by ScottDowne** [comment]
Bounce rate*

**Comment by vojtechmzl** [comment]
Ideally we would want to track this with events, as we want to optimize the user flow (sign up -> share or share -> sign up). How much effort would it be to add ga events to onclick @ScottDowne ?
