### ISSUE TITLE
Improve Facebook share content

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#168]
- [ ] Design image
- [ ] Write copy suitable for social context
- [ ] Add FB meta tags etc into the donation form (with localization)

**Comment by edrushka** [comment]
Let's do this in 2 stages:
1) a quick fix now to make it more appealing
2) later, another update to integrate it with the overall design

**Comment by lovegushwa** [comment]
We need benchmarks for similar social shares.
(Maybe I need to do some more donation funnels to dig them up.) 

What are the restrictions and constrains of a Facebook share? @mmmavis 
What typical of a share like this? @valianttry 
Any other considerations, what kind of an opportunity is this?

CC @adamlofting @edrushka

**Comment by valianttry** [comment]
@lovegushwa I just donated to an indiegogo campaign and noticed their social share page was pretty good. I realized too late I should take a screenshot or two #fail 

If you want to make a test donation, might I recommend this awesome campaign that I just donated to:
https://www.indiegogo.com/projects/votervox-the-first-app-for-human-centered-voting/x/3106703

**Comment by lovegushwa** [comment]
@valianttry lol, yes I will do.

**Comment by lovegushwa** [comment]
![screen shot 2015-08-19 at 2 57 14 pm](https://cloud.githubusercontent.com/assets/12228435/9370250/b794bcaa-4683-11e5-8dca-e9db846dbda5.png)

**Comment by edrushka** [comment]
ohhhh that's nice! @mmmavis - do you recall if there would be anything stopping us from doing something similar? Was there a reason we couldn't include a photo?

**Comment by valianttry** [comment]
I especially like that it says "CLICK HERE to support" -- so the ask is embedded even if the user doesn't write a post. The image could be something really cool and sharable...

**Comment by mmmavis** [comment]
@edrushka 
Our current one does show an image (we can change that Mozilla wordmark to something else) 
<img width="958" alt="screen shot 2015-08-19 at 3 37 34 pm" src="https://cloud.githubusercontent.com/assets/2896608/9370834/4e2e36ba-4688-11e5-915d-9557a45a499e.png">

It's just that super wide full-width box we will need to fix.

**Comment by mmmavis** [comment]
Facebook's share dialog doc: https://developers.facebook.com/docs/sharing/reference/share-dialog
We'll need to register and pass in the App ID in order to make this to work.

**Comment by alicoding** [comment]
Note for our dev that currently we are seeing this photo because there is a
redirect as well that's why we are seeing this photo which is a favicon if
I recall correctly

**Comment by lovegushwa** [comment]
@edrushka 
Going tackle this to next week. It makes sense to design alongside funnel and snippet UI.

**Comment by lovegushwa** [comment]
@edrushka @alicoding @valianttry @adamlofting  @HPaulJohnson 

Hi everyone. Check out these facebook share options. We need to develop copy to support the image or graphic we end up using (see example of VoterVox above). For example, image 11 could talk about how donating directly impacts contributors/community.  ... Any thoughts on how to move forward?


1.
![eoy_facebook_01](https://cloud.githubusercontent.com/assets/12228435/9843201/fd1be1f2-5a6c-11e5-92ec-d725a599f3b2.jpg)

2.
![eoy_facebook_02](https://cloud.githubusercontent.com/assets/12228435/9843229/1fd8ba4e-5a6d-11e5-8b38-b4e1f800457d.jpg)

3.
![eoy_facebook_03](https://cloud.githubusercontent.com/assets/12228435/9843233/2742637a-5a6d-11e5-904b-5efae3d6c7b8.jpg)

4.
![eoy_facebook_04](https://cloud.githubusercontent.com/assets/12228435/9843249/374f995e-5a6d-11e5-8aeb-caeb65709e03.jpg)

5.
![eoy_facebook_05](https://cloud.githubusercontent.com/assets/12228435/9843254/3d683364-5a6d-11e5-8241-d1bdd29feee9.jpg)

6.
![eoy_facebook_06](https://cloud.githubusercontent.com/assets/12228435/9843280/581a8702-5a6d-11e5-9f5b-748aedc069c3.jpg)

7.
![eoy_facebook_07](https://cloud.githubusercontent.com/assets/12228435/9843282/618fc2d4-5a6d-11e5-8ebd-d9b38cd14aa6.jpg)

8.
![eoy_facebook_08](https://cloud.githubusercontent.com/assets/12228435/9843284/6af288f2-5a6d-11e5-8f89-0fed16cd3d0b.jpg)

9.
![eoy_facebook_10](https://cloud.githubusercontent.com/assets/12228435/9843292/78a51dac-5a6d-11e5-8bad-27541fe738fe.jpg)

10.
![eoy_facebook_09](https://cloud.githubusercontent.com/assets/12228435/9843287/72e4da06-5a6d-11e5-8a9a-271cb4cbe395.jpg)

11.
![eoy_facebook_11](https://cloud.githubusercontent.com/assets/12228435/9843294/7f3cf126-5a6d-11e5-8a98-76d0b3c9ae46.jpg)

12.
![eoy_facebook_12](https://cloud.githubusercontent.com/assets/12228435/9843304/9e78e4a0-5a6d-11e5-8046-7b3c15223eaa.jpg)

13.
![eoy_facebook_13](https://cloud.githubusercontent.com/assets/12228435/9843308/abf59470-5a6d-11e5-9893-7021a6d6009e.jpg)

14.
![eoy_facebook_14](https://cloud.githubusercontent.com/assets/12228435/9843310/b29b8f78-5a6d-11e5-8cef-38626e5991e4.jpg)

**Comment by alicoding** [comment]
I like number 5 the most. I can see the message just from looking at the photo there. The rest is not bad, but it's too specific in my opinion plus the refugee crisis and the photo can be somewhat misleading.

**Comment by edrushka** [comment]
I def. like the group shots as opposed to the individual portraits (these might make sense in another context). So 4, 6, 7 and 9. I like the little heart in the corner on 14, too.

Overarching themes for EOY will include 1) user control, 2) Moz is non-corporate 3) importance of individual leaders in growing universal web literacy, so the group shots of people teaching others are spot on.

@valianttry do we want *any* share capacity for the German FR campaign? Previously I believe we discussed nixing social shares for this campaign to avoid competing with refugee crisis. Can you confirm? This will dictate when we need to finalize copy.

**Comment by lovegushwa** [comment]
Hi @alicoding @edrushka, I think good copywriting could make any of these images work for 1) user control, 2) Moz is non-corporate 3) importance of individual leaders in growing universal web literacy.
We need to develop a brief for Kevin or a fundraising copywriter and use these images as prompts for copyrighting.

I think the portraits are more visually engaging (closer crop, direct eye contact). Can we test both a group working shot and a tight cropping of a person?

**Comment by edrushka** [comment]
I don't think we have a way to test this. AFAIK, there's no tool to see who actually follows through and posts. @adamlofting, please correct me if I'm wrong.

For the EOY campaign, we'd talked about giving people the option to choose from a selection of images. @mmmavis or @alicoding, do you think this is possible with Facebook's API, or was this just wishful thinking?

**Comment by adamlofting** [comment]
> I don't think we have a way to test this. AFAIK, there's no tool to see who actually follows through and posts. @adamlofting, please correct me if I'm wrong.

There's not enough volume to run meaningful tests on this, so fine to go with our best judgement at the moment.

**Comment by edrushka** [comment]
@lovegushwa I'll let you make the judgement call. Maybe you can shortlist to 3 and we can ask Kevin to help draft the copy?

**Comment by edrushka** [comment]
Draft copy from Kevin from #353 

    Tell the world you helped defend the Web
    Let your friends know the Web needs their help
    Spread the word and help Mozilla protect the Web

**Comment by lovegushwa** [comment]
@valianttry the last image show DE copy.

1,3,5 are currently being used on twitter ... https://twitter.com/mozilla?ref_src=twsrc^google|twcamp^serp|twgr^author
5 had the most one time retweets 






1
![eoy_facebook_01](https://cloud.githubusercontent.com/assets/12228435/10088516/44ce32a0-62d0-11e5-80a0-feeb714d2287.jpg)

2
![eoy_facebook_02](https://cloud.githubusercontent.com/assets/12228435/10088526/5b0d59a6-62d0-11e5-9dd4-0bc959414655.jpg)

3
![eoy_facebook_04](https://cloud.githubusercontent.com/assets/12228435/10088532/671956aa-62d0-11e5-97d2-a607d4f5f773.jpg)

4
![eoy_facebook_05](https://cloud.githubusercontent.com/assets/12228435/10088533/6c34dc04-62d0-11e5-81f4-0e2ea72f672e.jpg)

5
![eoy_facebook_03](https://cloud.githubusercontent.com/assets/12228435/10088528/60899f8e-62d0-11e5-889d-4cee05d9f223.jpg)

6
![eoy_facebook_de](https://cloud.githubusercontent.com/assets/12228435/10088600/c4a3ed08-62d0-11e5-996d-cc22bc7661d0.jpg)

**Comment by lovegushwa** [comment]
Yay! This will work for the DE campaign. Calling this closed.
