### ISSUE TITLE
Send all donors a big impact message

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#173]
![impact](https://cloud.githubusercontent.com/assets/1901816/9119542/15531ff6-3c2c-11e5-8962-16deda65277a.jpg)

**Comment by edrushka** [comment]
Is this the same as https://github.com/mozilla/donate.mozilla.org/issues/185? Either way, it should correspond with https://github.com/MozillaFoundation/2015-fundraising/issues/30

**Comment by adamlofting** [comment]
I suspect this one is the same.

Also, feel free to close any of these as dupes/wontfix. I just wanted to make sure we didn't miss anything from the idea sessions.

**Comment by edrushka** [comment]
@valianttry @rebsd and I are meeting on Wed about the impact piece. Hopefully we can narrow down if it's a drip or a one-time email. I'll close the appropriate ticket when I know.

**Comment by edrushka** [comment]
Closing this for now but will leave #185 open.
