### ISSUE TITLE
Paypal locale codes are pretty busted

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#1738]
@TheoChevalier So I found something that's not good.

Paypal has what seems to be their own unique locale codes. See here: https://developer.paypal.com/docs/classic/api/locale_codes/

We initially handled this conversion here: https://github.com/mozilla/donate.mozilla.org/blob/master/intl-config.js#L4

However, as we added new locales, we never turned them on in paypal properly.

What this means is the login screen won't be in the right language for a lot of our locales. Once the user logs in, they get their user set language.

To test, try making a paypal donation in /de/ the paypal login screen should be in german. Then try in /pl/ and the login screen is in English, and should be in Polish.

**Comment by TheoChevalier** [comment]
Crap. Good catch :/

Looked only quickly, but it seems we’re missing at least the following locales:
es, ru, ko, ar (when we add it), pl, zh, no, nl

I’ll try to have a look today or tomorrow
