### ISSUE TITLE
PayPal “Go back” link always redirects to donate.mozilla.org root

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate.mozilla.org#1742]
STR: 
- Try to make a PayPal donation on https://donate.mozilla.org/thunderbird
- Click “Go back to Mozilla Foundation" link at the bottom
- You’re redirected to the homepage while you should be redirected to https://donate.mozilla.org/thunderbird

**Comment by ajomadlabs** [comment]
@TheoChevalier Can I take up this issue

**Comment by TheoChevalier** [comment]
@ajomadlabs sure!

**Comment by TheoChevalier** [comment]
Just noticed an issue was already open for that: #1569 
So closing this one, but you are still welcome to work on it
