### ISSUE TITLE
Is basket-queue.js doing anything with basket

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#1747]
This file: https://github.com/mozilla/donate.mozilla.org/blob/master/lib/basket-queue.js

and this pull request: https://github.com/mozilla/donate.mozilla.org/commit/40f6eecd6ea7cca4ede2b47fbe3b25f3afaf15ab

Seems kinda oddly named? Does this have anything to do with basket? Is basket a thing outside of mozilla salesforce land? Does basket mean something in SQS land?

@cadecairos thoughts?

**Comment by ScottDowne** [comment]
After poking around a bit, I suspect this is being used to put donation info into salesforce.

**Comment by cadecairos** [comment]
This puts donation info into an sqs queue. Basket has a worker process that polls the queue for messages and sends them off to salesforce.

**Comment by cadecairos** [comment]
this is the code that processes the messages generated here: https://github.com/mozmar/basket/blob/e613dc4335314ca3c2219a017ad87c349a562728/news/management/commands/process_donations_queue.py

**Comment by ScottDowne** [comment]
Cool cool. We can close this. Thanks for confirming that.
