### ISSUE TITLE
Define design of refund vs rejected flag or status in Salesforce

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1754]
What fields can we use (or create) to track refunded or rejected donations on the Opportunity object

**Comment by hannahkane** [comment]
Scope is: system design in Salesforce; kicking around ideas on how we track stuff; *not* the config

Estimate: 1 day

**Comment by desiree-mofo** [comment]
The design and config of the rejected and refunded data has been completed in SFDC as of October 2017, closing this issue.
