### ISSUE TITLE
Build refund/rejected fields on Opportunity object design in Salesforce sandbox

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1755]

**Comment by hannahkane** [comment]
Get a signoff on the design from @pmclanahan and @cadecairos and @vojtechmzl  and configure it!

This is limited to Salesforce, no outside data

Estimate: 1 day

**Comment by desiree-mofo** [comment]
These fields are done and are in Production as of October, 2017. Closing this issue.
