### ISSUE TITLE
Design what webhooks/queue is looking at between Basket and Stripe

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1756]

**Comment by hannahkane** [comment]
Will be looking at several pieces: e.g. changes to Basket, donate server, integrate webhooks, build the queue.

There's a chance we can use our existing queue.

Likely won't need outside input beyond @pmclanahan and @cadecairos.

Have Andrew and/or Desiree present to sign off / answer any SF implementation questions.

Estimate: <1 day

**Comment by desiree-mofo** [comment]
@stephaniemcv - I think we can close this one out b/c it was related to disputes and refunds?

**Comment by stephaniemcv** [comment]
Agreed.
