### ISSUE TITLE
QA that refund and rejected data is flowing correctly between Stripe - Basket - Salesforce

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1758]

**Comment by hannahkane** [comment]
Track down existing QA scripts? Or write one.

Could be distributed across several people; needs to include ppl who didn't build it (trying to break it).

Estimate assumes there are no bugs discovered: 1 week

**Comment by desiree-mofo** [comment]
Uploaded SFDC report export from 2/1/18 to 3/27/18 to Brick from what is stored in SFDC. @stephaniemcv  is pulling the same data from Stripe so we can compare and assess.

**Comment by stephaniemcv** [comment]
This is the same as #1954. Let's track it there and close this one.
