### ISSUE TITLE
Push Salesforce sandbox changes to production

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1759]

**Comment by hannahkane** [comment]
Order of operations:
 1. Salesforce
 2. Basket
 3. Donate

Estimate includes the coordination and risk-mitigation: hours (< day)

**Comment by desiree-mofo** [comment]
I believe this is closed? @stephaniemcv, comments?

**Comment by stephaniemcv** [comment]
Yup, closing
