### ISSUE TITLE
Give users the ability to change currency on the form

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#178]
Needs Design.

**Comment by adamlofting** [comment]
To work on functionality before the design is ready, our plan was to make the currency switchable via a URL parameter.

Also, here's an example of one of the wireframes for the currency selector which is a good starting point.

<img width="837" alt="screenshot 2015-08-28 10 55 10" src="https://cloud.githubusercontent.com/assets/1901816/9543761/521ec9a0-4d73-11e5-982e-1c127e7afc92.png">

**Comment by ScottDowne** [comment]
Merged: https://github.com/mozilla/donate.mozilla.org/commit/7b72151a89775616b2ff522bfd5b436f72735980
