### ISSUE TITLE
New lines are removed on mobile

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate.mozilla.org#1792]
@ScottDowne Do you remember what this is used for? https://github.com/mozilla/donate.mozilla.org/blob/master/less/shared.less#L93-L97

It doesn’t work with FAQ and Ways to Give :/ 

![capture d ecran - 2017-10-04 a 10 44 16](https://user-images.githubusercontent.com/1294206/31167128-48dca7dc-a8f1-11e7-8437-11229b5acef8.png)

![capture d ecran - 2017-10-04 a 10 43 42](https://user-images.githubusercontent.com/1294206/31167131-4eef3fb8-a8f1-11e7-9ea9-1dc602b5e89a.png)

**Comment by ScottDowne** [comment]
Looking.

**Comment by ScottDowne** [comment]
Yeah, I'm not sure why we turn off `br` in the first place. I tracked that line back to the first usage, and it looks like it was always there via a pasted template css file: https://github.com/mozilla/donate.mozilla.org/commit/ca9213f3a76173e9c1d77ae0f00010ad53b62ff6

I'll try to dig a bit more to see if I can figure out what it's trying to fix. I assume most weird things are attempting to fix a real problem and have good intentions.

**Comment by ScottDowne** [comment]
@TheoChevalier I'm still not 100% sure why that was originally there. I did a patch ages ago that put it into a media query to handle some nonsense design issues with a string not breaking exactly where they wanted. That is a string we no longer use though, so the media query around the style is no longer needed. That said, I still don't know why someone would do that in the first place.

**Comment by TheoChevalier** [comment]
Alright, thanks for digging into that! It seems safe to get rid of it then.

The only place where I’ve seen a similar thing is on mozilla.org, for mostly the same use case: we want to break a title at a specific place on Desktop (and we want locales to be able to move the tag), but we don’t want any line breaks on mobile.
However it was done with a CSS class like `<br class="wide-br"/>`, so that it only removes this specific br.

**Comment by ScottDowne** [comment]
Yeah, nuke it, it's a terrible way to do anything and if we're still relying on it in any way we're also terrible ;). It was there in the initial commit, so it was probably blindly copied from some framework or repo and no one noticed it being an issue.

**Comment by TheoChevalier** [comment]
Fixed with https://github.com/mozilla/donate.mozilla.org/commit/384f4284c470388ae852afc0035bf1cb9a8a1541
