### ISSUE TITLE
Test: Second chance to opt-in to email updates on thank you page

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#180]
This test assumes we capture the email address before the thank you page as part of the donation flow.

If we do offer email opt-in at that point, then we could consider offering a second chance to opt-in on the thank you page for people who don't opt-in during the donation flow.

![jordan](https://cloud.githubusercontent.com/assets/1901816/9119859/da4115ce-3c2d-11e5-89ad-72df8bd5f56f.jpg)

**Comment by ScottDowne** [comment]
We can do this now, using this test url: https://donate.mofostaging.net/en-US/?test=signup-test

This also works via a classname "signup-test" via optimizely.

**Comment by adamlofting** [comment]
:+1:

**Comment by edrushka** [comment]
Clarifying: This test would be if the email signup is included in step 3 of the form (as in Scott's staging link above), but not checked. The thank you page would be the same as if there was no signup in step 3 -- aka the current/baseline thank you -- which prompts people to enter their email. Is this correct?

**Comment by ScottDowne** [comment]
@edrushka Yeah, so:

1. if the signup checkbox is included and not checked -> ask again in the thank you
2. if the signup checkbox is included and is checked -> don't ask again in the thank you
3. if the signup checkbox is not included and thus cannot be checked -> ask in the thank you

**Comment by edrushka** [comment]
Yes. So this doesn't need any additional design, and just needs dev work to create the correct flow for each of those instances, correct? No new things need to be written, designed or built?

**Comment by ScottDowne** [comment]
We just need to turn on the urls in optimizely at this point, everything looks to be good to go when it's time to test.

**Comment by edrushka** [comment]
Ok. I removed the L10N needed flag from the testing spreadsheet.

**Comment by adamlofting** [comment]
Doesn't apply when we switch to Stripe checkout.
