### ISSUE TITLE
QA Design of "Thank You" page with ask for monthly donations

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1810]
The amounts will vary based on the one-time donation amount

**Comment by gideonthomas** [comment]
@flukeout just wanted to mention here that the UX we are currently basing it on was this demo: https://cstage-zz.trilogyinteractive.com:10444/test-upsell.html?show_amount=true.

Feel free to suggest simple changes.

**Comment by flukeout** [comment]
For reference, here's what process from the previous link displays:

![image](https://user-images.githubusercontent.com/25212/32862735-f2ab3eda-ca0d-11e7-94fa-45b15e85c4ad.png)

**Comment by flukeout** [comment]
@gideonthomas Do we have any copy for this modal / step?

**Comment by gideonthomas** [comment]
Nope, my guess is that you can be creative here. @WillatMozFdn do you have any suggestions for the copy in the modal?

**Comment by WillatMozFdn** [comment]
yes -- @ScottDowne and I worked this out yesterday .... settled on this ... 
![image](https://user-images.githubusercontent.com/23637882/32895419-02558354-caae-11e7-8c8b-cf34c02a8d99.png)

**Comment by gideonthomas** [comment]
@flukeout ^

**Comment by flukeout** [comment]
@ScottDowne has already implemented this in #1864 - once it lands I'll take a styling pass at it.
