### ISSUE TITLE
Implement thank you message on donate page, encouraging monthly donations

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1813]
After users donate, we will offer them a link back to the main donate page with a different message and monthly amounts pre-filled. This ticket is to capture that work which needs to be done on the main page.

**Comment by gideonthomas** [comment]
@ScottDowne to talk to Stripe and see if we can reuse the source token after making a one-time payment to make another transaction that is monthly and recurrent.

**Comment by ScottDowne** [comment]
Things I'm still doing in the above demo:

- [ ] Delay the first donation by a month.
- [ ] Some styling on the error validation messages.
- [ ] Proper upsell amounts.
- [ ] Proper upsell targets. (en-US, eur, etc)
- [ ] Refactor some reusable functions for amount validation.
- [ ]  Some sort of tests.
- [ ] Pass proper values from the upsell to the thankyou page so it gets tracked.

**Comment by gideonthomas** [comment]
@ScottDowne the first thing "Delay the first donation by a month." should be a nice-to-have. Let's prioritize all the other tasks below that first.

**Comment by gideonthomas** [comment]
Link to currency conversions: https://github.com/mozilla/donate.mozilla.org/issues/1811
