### ISSUE TITLE
Identify where video will be hosted and upload it

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1815]
Output of this ticket: a link to the video(s)

Partially blocked by video's current lack of existence

**Comment by cadecairos** [comment]
I believe the best place for this is the `advocacy-media-uploads-s3bucket-1bksegc8ljpyd` S3 Bucket, which is served by the CDN `d24kjznqej0s8a.cloudfront.net`

**Comment by cadecairos** [comment]
Blocked on actually having a video to upload.

**Comment by gideonthomas** [comment]
This is done, thanks @cadecairos :)
