### ISSUE TITLE
Research Stripe Elements

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1818]
We need to figure out how Stripe Elements (https://github.com/stripe/react-stripe-elements) work so that we can implement SEPA donations

**Comment by cadecairos** [comment]
Implementing this should actually be pretty straight forward.

Here's the order of events we'll be taking:

Prerequisite: we've designed a form. The following details the behaviour of the form

1. The donor inputs payment info. (They also must accept the [SEPA Direct Debit Mandate](https://stripe.com/docs/sources/sepa-debit#prerequisite), which might be automatic, according to Stripe: "When your customer confirms the payment they are making, they are also accepting a mandate. Their acceptance authorizes you to collect payments for the specified amount from their bank account via SEPA Direct Debit." - we'll need the proper legal text that Stripe has provided in the documentation linked earlier... **also, we might need to get the legal team involved here**)
2. The donor presses submit. A handler function uses `Stripe.js` to [create a Source object in our Stripe account](https://stripe.com/docs/sources/sepa-debit#create-source). (this is made using our public Stripe API key) **NOTE:** The payment information never touches our systems.
3. The response from Stripe will contain a Source ID, which we can then pass to our server via XHR. We will also want to pass some additional information such as email address, locale, and currency. (actual data requirements TBD)
4. The server will take the Source ID and make an API call to stripe (using the private Stripe API key) to [create a Customer object](https://stripe.com/docs/sources/sepa-debit#attaching-the-source-to-a-customer), associating the source with it. 
5. The resulting Customer ID will then be used, along with the source ID, to [create a charge](https://stripe.com/docs/sources/sepa-debit#making-a-charge-request).
6. send a success message back to the client... or redirect, or w/e it is we do.

There might be opportunity here to completely re-use our existing routes, howerver there will be some modification or special casing. Therefore I recommend we write SEPA specific route handlers.

things to note:

- [Notifying customers of recurring payments](https://stripe.com/docs/sources/sepa-debit#notifying-customers-of-recurring-payments) **we might want to limit this to one-time donations only and deal with this next year.**
- [SEPA charges are async](https://stripe.com/docs/sources/sepa-debit#charge-confirmation), and can take up to 14 days before changing to a successful state. We might want to wait for that successful state before issuing a donation receipt. (**ask a lawyer**)
- [Refund rules to educate our support staff about](https://stripe.com/docs/sources/sepa-debit#refunding-payments)
- [Dispute process](https://stripe.com/docs/sources/sepa-debit#disputed-payments)

**Comment by gideonthomas** [comment]
@cadecairos that's awesome documentation; very helpful to refer to! One last question I have is would you happen to know what stripe elements are required to make a SEPA source object?

**Comment by gideonthomas** [comment]
Filed #1841 and #1853 as implementation issues.
