### ISSUE TITLE
Get design feedback for SEPA form

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1819]
Once a barebones implementation of the SEPA form is completed, let's get design input on the form for what it should look like.

**Comment by gideonthomas** [comment]
QA issues filed: https://github.com/mozilla/donate.mozilla.org/labels/QA

Next step is to triage them and see what we can (or want to) accomplish in this milestone

**Comment by flukeout** [comment]
Closing as feedback has been provided & issues filed.
