### ISSUE TITLE
Decide how SEPA option will be made known on landing page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1824]
This is partially a design question, partially a stakeholder question:

Do we add a third button on the landing page?
Do we replace PayPal button with SEPA, and make Paypal less significant?
Is this decision region specific?

cc @WillatMozFdn

**Comment by WillatMozFdn** [comment]
From the stakeholder perspective:
a) and c) Display it as a third & equivalent button on the landing page, for specific countries only (https://www.ecb.europa.eu/paym/retpaym/paymint/sepa/html/index.en.html  -- all three of the lists under "National authorities in SEPA countries that issue bank identifiers used in IBANs" 
b) leave PayPal as is; many Europeans do in fact use PayPal.

**Comment by alanmoo** [comment]
Ok, that's something useful to start with then. Perhaps we'll do more with A/B tests in #1825.

**Comment by gideonthomas** [comment]
Migrating to an implementation ticket
