### ISSUE TITLE
Transaction ID - prevent duplicates

### ISSUE THREAD

**Issue by desiree-mofo** [mozilla/donate.mozilla.org#1828]
Either make the transaction ID unique in Salesforce or add code to Basket to check for existing ID before inserting new record.

We need to prevent duplicate transactions from being imported into Salesforce

**Comment by desiree-mofo** [comment]
Notes: did some research on this in the ADVO sandbox and we'll need to clean up the duplicates before making this change in Production. 

@cadecairos  - I have a question on the uniqueness, should the unique value be based on a case sensitive value or case insensitive values 

Treat "ABC" and "abc" as duplicate values (case insensitive)
Treat "ABC" and "abc" as different values (case sensitive)

**Comment by cadecairos** [comment]
Let's make it case sensitive, I'm not sure what character set Stripe/Paypal use for their ID strings.

**Comment by desiree-mofo** [comment]
@cadecairos - this change is currently in Production (PMT Transaction ID is unique, case sensitive). We need to send some test duplicates through so that @pmac can see what the error message will look like so he can amend his code to trap it and disable retries if it fails due to a duplicate issue. I'll book time on our calendars to do a slack testing session.

**Comment by desiree-mofo** [comment]
Duplicate transactions were updated to unique transaction ID's or removed from SFDC production and the configuration to enforce unique transactions (case sentitive - Treat "ABC" and "abc" as different values (case sensitive)) was moved to the SFDC Production instance. This closes Issue #1828
