### ISSUE TITLE
Create a custom form for accepting SEPA donations

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1841]
Build a form with the required fields that can process a SEPA donation. This will be a barebones implementation of the form without any specific UI/UX.

This will need to happen on a separate page ~~so that we can A/B test this and not break existing functionality~~ so that we can enforce strict CSP rules.

~~This form will use Stripe Elements to build out the SEPA form~~

**Comment by gideonthomas** [comment]
Details on what needs to be implemented based on @cadecairos' research can be found here: https://github.com/mozilla/donate.mozilla.org/issues/1818#issuecomment-341563113

**Comment by gideonthomas** [comment]
@Pomax, @cadecairos and I were talking about what we can do to make sure that the form is secure and we determined that since we don't have great CSP rules on the main donate page, let's make the SEPA form a page that is sent as a separate network request so that we can tighten up the CSP rules for that route.

The ideal workflow for this would be:
1. Go to donate.mozilla.org (Bad CSP)
2. Select amount and one time / monthly and click on Pay with SEPA.
3. The Pay with SEPA button is an anchor link to donate.mozilla.org/{locale}/sepa (or whatever)
4. Server returns the SEPA form which has info about the amount/frequency of the donation (maybe as hidden input elements?)
5. User types in SEPA information and the form interacts with stripe to get the necessary info that we can send to the server to finish processing the SEPA charge
6. XHR POST to /sepa (or whatever) the data to process the SEPA charge and the server returns the output.
7. Another network request to the server to load the thank-you page.

We aren't going to enable GA on this stripe form nor optimizely so that we can add our strict CSP rules.

One thing to consider when loading this form is l10n (we can also do this as a separate issue). Right now we load localeData for the form (number formats, etc.) in an inline script element. We can do that on the stripe form as well if we generate a nonce on the server and render it into the inline script element as well as including it in our CSP script-src. The other option is to just have a route that dynamically serves the localedata we need for the form. I say go with whatever you think is easier.

Feel free to suggest something different (or ask questions) and definitely mention if you need help with this.

**Comment by alanmoo** [comment]
If we're not going to enable GA or Optimizely, how are we going to A/B test?

**Comment by gideonthomas** [comment]
what are we A/B testing on the form? (we can enable GA I think if we do a network request for it instead or generate the SHA for the GA script and hardcode that into the CSP rule)

Either way, IMO let's not worry about the A/B testing of the SEPA form itself for now. For After EOY, we can try to switch to the more secure wrapper of optimizely that MoCo uses so that we don't have these issues, then we can A/B test this.

**Comment by alanmoo** [comment]
I was referring to the original post, in which A/B testing was mentioned.

**Comment by gideonthomas** [comment]
ah damn, yeah that's outdated now, fixing.

**Comment by alanmoo** [comment]
Doesn't seem like this is happening again this year. We can open another one if needed.
