### ISSUE TITLE
Localize new strings for monthly "upgrade" ask

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1843]
Meant to be a placeholder of the work that needs to be done, so it's visible to us as we review our progress.

**Comment by TheoChevalier** [comment]
@gideonthomas Thanks for the details! This ticket should be enough to track the l10n work.

Just make sure to flag me for review before it’s merged to master, I will need to check the l10n implem and copy before it’s exposed to localizers. (Won’t review the code itself, just the l10n aspects)

**Comment by gideonthomas** [comment]
I think this is done right? Feel free to close @TheoChevalier

**Comment by TheoChevalier** [comment]
Yup, all good!
