### ISSUE TITLE
Show SEPA donation button only if Euro is selected

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1849]
We should only show SEPA as an option for the countries listed under "National authorities in SEPA countries that issue bank identifiers used in IBANs" on this page: https://www.ecb.europa.eu/paym/retpaym/paymint/sepa/html/index.en.html

Countries that are a part of that list:
- Austria
- Belgium
- Bulgaria
- Croatia
- Cyprus
- Czech Republik
- Denmark
- Estonia
- Finland
- France
- Germany
- Greece
- Hungary
- Ireland
- Italy
- Latvia
- Lithuania
- Luxembourg
- Malta
- Netherlands
- Norway
- Poland
- Portugal
- Romania
- Slovakia
- Slovenia
- Spain
- Sweden
- Switzerland
- United Kingdom

Locales that we need to enable for SEPA based on that list (and what we have enabled on Pontoon):
- de
- sq
- ast
- ca
- hr
- cs
- da
- nl
- en-GB
- et
- fr
- fy-NL
- de
- el
- hu
- it
- lv
- nb-NO
- nn-NO
- pl
- pt-PT
- ro
- sk
- sl
- dsb
- hsb
- es
- sv-SE

@TheoChevalier would you be able to check to make sure I haven't missed locales?

**Comment by TheoChevalier** [comment]
@gideonthomas German is twice in the list, but the list looks good to me 👍

**Comment by gideonthomas** [comment]
Looks like we should show/hide the button based on currency instead of locale, i.e. we would only show the "Donate via SEPA" button if euro is the selected currency.

**Comment by TheoChevalier** [comment]
Yes, probably the same way as for “No American Express support”, or “No PayPal support“

**Comment by alanmoo** [comment]
Implemented in #1882
