### ISSUE TITLE
Drip campaign about Mozilla impact prior to end of year

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#185]
See second row in this photo:

![andrea](https://cloud.githubusercontent.com/assets/1901816/9120114/4e4b3d2c-3c2f-11e5-9b44-c06f7cfa3f45.jpg)

**Comment by edrushka** [comment]
Need to connect to make sure this corresponds with https://github.com/MozillaFoundation/2015-fundraising/issues/30

**Comment by edrushka** [comment]
Closing this. Detailed ticket here: https://github.com/mozilla/donate.mozilla.org/issues/570
