### ISSUE TITLE
Design donation-ask modal for MoFo sites

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1855]
We want to design a popup modal...
> ...similar  to our current modal that asks site visitors for an email subscription, we need to build one to ask site visitors to donate to Mozilla

We want to add this to the following sites (for now):
- https://advocacy.mozilla.org/privacynotincluded/
- https://advocacy.mozilla.org/net-neutrality
- https://changecopyright.org/
- https://internethealthreport.org/

Ideally we would want to design a single modal that we can sorta reuse for all four sites (maybe with minor tweaks), however, if that is not possible, a simple design donation modal for each would work too.

One consideration for design is that https://internethealthreport.org is a wordpress site so we might be confined in terms of what we can add to it in terms of modal functionality (maybe a banner might be easier?).

The current copy that we want to show is:

---

**We all love the web. Join Mozilla in defending it.** 
Let’s protect the world’s largest public resource for future generations. Just a few times a year, Mozilla asks for donations. If everyone reading this chipped in, we could wrap this fundraiser in under an hour. Together we can keep the web healthy, wonderful and welcoming to all.

\<donation form\>

---

(we might just want to add a "donate now" button instead and link to the donate site if that is easier)

MoCo is currently working on the same thing for mozilla.org so we might be able to borrow some of their work. I can post updates here from the MoCo project for this.

@natalieworth, did you work with MoCo on the design/copy for this? If so, do you have any pointers for us on keeping this simple? If not, feel free to ignore.

**Comment by gideonthomas** [comment]
Note about the existing modal on https://advocacy.mozilla.org/privacynotincluded/ : https://github.com/MozillaFoundation/Advocacy/issues/1079#issuecomment-342604834

**Comment by flukeout** [comment]
@gideonthomas - Will the content for the popup basically be the same as what we are currently showing on https://donate.mozilla.org/en-US/? As in, it will have a currency, amount UI etc?

**Comment by gideonthomas** [comment]
This probably won't need design yet @flukeout. I think we might just go with what MoCo has (I pm'd you the link) for all the sites (IHR.org tbd).

**Comment by flukeout** [comment]
Roger, thanks.

**Comment by flukeout** [comment]
Just checking in @gideonthomas - I'm holding off on doing any kind of work here pending the MoCo work. Secondly, it would def be easier to just add a donate now button that links to the existing form. I'll un-assign myself for now.

**Comment by gideonthomas** [comment]
yep thanks @flukeout

**Comment by flukeout** [comment]
Closing this, as we are limiting the work to the Buyer's Guide, tracked in issue #1919
