### ISSUE TITLE
Copy for SEPA donation receipt

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1861]
Once a SEPA payment has been completely processed (5-14 days), we send the donor an email with their donation receipt.

I'm thinking that we can use the same copy that we use for Visa/Mastercard payments (please correct me if I'm wrong). The information in that email right now is:
1. Is the donation monthly or one-time
2. Transaction ID
3. Date of payment
4. Legal text:
```
Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to be
used in its discretion for its charitable purposes. They are tax-deductible in
the U.S. to the fullest extent permitted by law. Mozilla did not provide any
goods or services in return for this donation.

Mozilla Foundation Tax ID 20-0097189
```

As per Stripe, we also need to include the URL to the SEPA mandate that the donor accepted when making the payment. Since it's just a URL, any suggestions for copy that we can use? Something like?:
```
You can find the SEPA Direct Debit mandate that you have accepted here: <mandate url>
```

cc @WillatMozFdn

**Comment by WillatMozFdn** [comment]
Hey Gideon, yes, same text as a donation via credit card will work fine.  (Note that cade and I recently revised this and it now includes a little more info -- links to three thank-you videos, choose-your-own-adventure style.)  We might even think about using the same template file -- https://github.com/mozilla/webmaker-mailroom/tree/master/templates/stripe_charge_succeeded_2015 -- if that's possible?  Might not be if we need to include a link to the SEPA mandate, or maybe that could be conditionalized?

That boilerplate text sounds fine for the SEPA mandate link, I can't think of a way to make that any more interesting.  :-)  Do we know the URL that we need for that?  Or do we need to build a page?

**Comment by gideonthomas** [comment]
Awesome! Yeah we would just use the template you mentioned above and show the mandate on the condition that it is a SEPA receipt.

The url for the mandate is generated by Stripe for us (I think it's unique for each donor) so we would get that information (and put it in the email before sending it) when the SEPA payment is made through stripe.

Thanks for the info @WillatMozFdn, I'm going to move this to the implementation ticket.
