### ISSUE TITLE
Update Stripe/Paypal ownership information

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1866]
Here "ownership" refers to just updating the contact information.

TODO:
- [x] Switch ownership of Stripe to current executive.
- [ ] Switch ownership of Paypal to current executive.
- [x] Check statement descriptor on Stripe to make sure it is compliant with legal requirements and SEPA.

cc @WillatMozFdn

**Comment by gideonthomas** [comment]
Statement descriptor was changed from "mozilla.org" to "Mozilla Foundation". This is what will be seen on credit card statements for donors and on the SEPA mandate that we show (and must be accepted by donors) before accepting a SEPA payment from a donor.

**Comment by WillatMozFdn** [comment]
Nice work, Gideon, thank you -- that's definitely an improvement!  I'm guessing that you want either Angela or Ashley to be the executive contact, right?  (Angela seems best, as she has the financial system responsibilities, I think.)

**Comment by gideonthomas** [comment]
Yep, I'm working with her on updating that. Will post and update once that's done.

**Comment by gideonthomas** [comment]
Paypal ownership is what's left -- tracked in https://github.com/MozillaFoundation/mofo-devops-private/issues/72
