### ISSUE TITLE
Donate Form QA: Update copy below payment options to address SEPA?

### ISSUE THREAD

**Issue by flukeout** [mozilla/donate.mozilla.org#1871]
Based on [this deployment](https://donate-mozilla-org-us--pr-1867.herokuapp.com/en-US/).

There is copy below the payment options, but it only seems to address Paypal & Stripe. Now that SEPA will be an option, do we need to update this?

![image](https://user-images.githubusercontent.com/25212/32744430-5367c226-c864-11e7-966e-01f46239375d.png)

**Comment by gideonthomas** [comment]
Yeah, it should be changed to "Your payment details will be processed by Stripe (for credit/debit cards and SEPA Direct Debit) or Paypal, and a record of your donation will be stored by Mozilla.

**Comment by gideonthomas** [comment]
Fixed in #1891
