### ISSUE TITLE
Donate form QA: Un-needed padding on SEPA input fields.

### ISSUE THREAD

**Issue by flukeout** [mozilla/donate.mozilla.org#1873]
If you select the SEPA option and click on one of the two input fields, you'll notice that there is some extra left padding...

![image](https://user-images.githubusercontent.com/25212/32745104-8c9c5fd2-c866-11e7-89f3-a0daeb0a3560.png)

Let's get rid of it.

**Comment by gideonthomas** [comment]
Fixed in #1883
