### ISSUE TITLE
Donate form QA: Focus the Name field on the SEPA form by default.

### ISSUE THREAD

**Issue by flukeout** [mozilla/donate.mozilla.org#1874]
Based on [this deploy](https://donate-mozilla-org-us--pr-1867.herokuapp.com/)

When a user selects the SEPA payment option, and the form changes to reflect that, we should focus the Name field so that they can start filling it out right away.

The field in question...
![image](https://user-images.githubusercontent.com/25212/32745227-f306140c-c866-11e7-9e85-fc253b16291a.png)

**Comment by gideonthomas** [comment]
Fixed in #1883
