### ISSUE TITLE
Donate form QA: Update left-side design?

### ISSUE THREAD

**Issue by flukeout** [mozilla/donate.mozilla.org#1877]
Currently we are displaying the following...

![image](https://user-images.githubusercontent.com/25212/32745555-e920d142-c867-11e7-9866-5eddfa6214f0.png)

* Is this a finalized design?
* If not, is there a design effort underway to update it?

**Comment by gideonthomas** [comment]
I don't think we want to update any of the existing designs yet since we're reusing what was done last year. If we have time, we can possibly experiment with changes (and A/B test them) once the top 4 features are done.

**Comment by flukeout** [comment]
Oh okay. So what's currently there is a placeholder? I'll close this issue then.

**Comment by gideonthomas** [comment]
nope not a placeholder. For now, it's the "final design". We're intentionally not updating it. We can probably revisit if we want to update it later on.
