### ISSUE TITLE
Remove `/glassroomnyc` donation page and redirect to main donation page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1878]
Since the Glass Room NYC event is done, let's remove the code that is served for https://donate.mozilla.org/en-US/glassroomnyc and instead have that url redirect back to https://donate.mozilla.org/

**Comment by ScottDowne** [comment]
Closed in https://github.com/mozilla/donate.mozilla.org/pull/1935
