### ISSUE TITLE
QA: SEPA mandate should appear on the SEPA donation form

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate.mozilla.org#1885]
In the SEPA form, we need to show the legal mandate (probably above the Submit button).

The mandate copy is:

By providing your IBAN and confirming this payment, you are authorizing Mozilla Foundation and Stripe, our payment service provider, to send instructions to your bank to debit your account and your bank to debit your account in accordance with those instructions. 
You are entitled to a refund from your bank under the terms and conditions of your agreement with your bank. A refund must be claimed within 8 weeks starting from the date on which your account was debited.

**Comment by flukeout** [comment]
@gideonthomas Should we just add it the bottom of the SEPA form only? Might be easier.

**Comment by gideonthomas** [comment]
Fixed in #1891
