### ISSUE TITLE
Test a big visual background design

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#189]
![awesomevisual](https://cloud.githubusercontent.com/assets/1901816/9120309/650af042-3c30-11e5-9452-da01bf290894.jpg)

Largely inspired by...

<img width="1130" alt="screenshot 2015-08-06 11 45 52" src="https://cloud.githubusercontent.com/assets/1901816/9120315/7593ddfc-3c30-11e5-8cd4-e81612b99668.png">

**Comment by adamlofting** [comment]
@edrushka this is another test that needs design work up front. Is this already captured somewhere? Or should we file it as a new task?

**Comment by edrushka** [comment]
This work is the Spectacular Snippet, ticketed here: https://github.com/mozilla/donate.mozilla.org/issues/560 unless you mean a background on the form itself, which is not ticketed and out of scope.

**Comment by adamlofting** [comment]
Yes, this test idea was for the form itself.

I'll move it to the Bluesky milestone and take it off the test plan for now.

**Comment by edrushka** [comment]
EOY 2016!!!

**Comment by edrushka** [comment]
Closing this, but we'll pitch this big visual background as a variation of the spectacular snippet #560.
