### ISSUE TITLE
Design alternate version payment options

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1906]
(Note that this ticket assumes we can't do the upsell functionality with Paypal)

In the interest of showing more users the monthly upsell screen, we should see what we can do to get more users to pay with Stripe. Let's design an alternate version of the Payment Options buttons that prioritizes Stripe donations over Paypal. We'll implement them for A/B testing to see if there's any impact on the amount of money donated and payment provider used.

For example: Instead of being a 50/50 split for the buttons, we might want something like a full width Stripe button with "or use Paypal" link text below it.

**Comment by flukeout** [comment]
Few quick options...

**Option A** - Width only

![image](https://user-images.githubusercontent.com/25212/32911038-c854e49e-cabf-11e7-9167-fda8adee3a1e.png)

**Option B** - Width  & Color

![image](https://user-images.githubusercontent.com/25212/32911115-0ad99eae-cac0-11e7-8e8a-f9383890f2f1.png)

**Option C** - Link below CC button

![image](https://user-images.githubusercontent.com/25212/32911260-876862d4-cac0-11e7-8698-54b905209a15.png)

@alanmoo Here are some options.

**Comment by flukeout** [comment]
I think **Option C** is probably the best bet for testing.

**Comment by TheoChevalier** [comment]
Option C will also be the easiest for localization (pretty sure we will get truncations for A and B)

**Comment by alanmoo** [comment]
Agreed. Let's go with C; I'll file an implementation ticket. Thanks!
