### ISSUE TITLE
Implement alternate payment options design (with A/B functionality)

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1907]
from https://github.com/mozilla/donate.mozilla.org/issues/1906#issuecomment-345034685

We should build the following as an alternate version to show users when their locale accepts both Stripe and Paypal. The version used (the below or the existing styles) should be set via A/B test loading.

![](https://user-images.githubusercontent.com/25212/32911260-876862d4-cac0-11e7-8698-54b905209a15.png)

**Comment by alanmoo** [comment]
Once we implement this (see the original comment in #1906 for context) should we do a 50/50 split or will we be able to get useful data from something like a 90/10 (in favor of the old version)? @WillatMozFdn @vojtechmzl?

**Comment by ScottDowne** [comment]
This should probably do it. https://github.com/mozilla/donate.mozilla.org/pull/1925
