### ISSUE TITLE
Test a single page form

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#191]
This work is underway already. 

![singlepage](https://cloud.githubusercontent.com/assets/1901816/9120448/25252e24-3c31-11e5-9cd7-5f22536c7f6f.jpg)

**Comment by ScottDowne** [comment]
What's left to make this work is plugging in the stripe widget, and plug submit into the amount button's validation code.

Paypal button should already work once #199 lands.

**Comment by adamlofting** [comment]
Is there anything left on this ticket?

**Comment by ScottDowne** [comment]
Just QA.

I don't think we need to keep this open for that.

**Comment by adamlofting** [comment]
:+1:
