### ISSUE TITLE
Update Hapi and dependencies

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate.mozilla.org#1913]
It's out of date. let's update!

At the time of filing, hapi is at 16.6.2 and we're on 13.3.0

**Comment by gideonthomas** [comment]
If we're updating to 17.x at some point, it will be a pretty big lift due to the switch to async-await and other Node 8 features that seem to break some of the Hapi plugins.

**Comment by cadecairos** [comment]
This was done in #1959
