### ISSUE TITLE
Amend logging of failed Donation updates to include error msg

### ISSUE THREAD

**Issue by desiree-mofo** [mozilla/donate.mozilla.org#1915]
I'd like to amend the data extension logging of failed donation record updates from Basket to SFDC in the Donation_Diff SFMC extension. Can we capture the error message thrown as to why the record was unable to be updated?

**Comment by desiree-mofo** [comment]
@pmac - I may need your help with this - is this possible?

**Comment by pmac** [comment]
We can do that. Just add a non-required text field to the DE and I can update basket to include it

**Comment by desiree-mofo** [comment]
@pmac - I think this may be completed. Can we verify and/or close if that's the case? (cc: @stephaniemcv)

**Comment by pmac** [comment]
I believe it is. Basket now updates a field in that data-extension called `Error_Text`. Should be working now.

**Comment by stephaniemcv** [comment]
Confirmed as of 11/28/17 there is error message text associated with each charged failed in the data extension.
