### ISSUE TITLE
Test a complete single page donor form directly in the snippet

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#192]
Routing donors directly to PayPal or Stripe.

![snippetform](https://cloud.githubusercontent.com/assets/1901816/9120467/3c3720d6-3c31-11e5-8c25-79c3dd73cade.jpg)

**Comment by adamlofting** [comment]
This would bring a form UX similar to https://donate.mofostaging.net/en-US/one-page/ directly onto the snippet.

<img width="395" alt="screenshot 2015-10-23 15 13 25" src="https://cloud.githubusercontent.com/assets/1901816/10694899/a77cd6ac-7998-11e5-9d31-7751d5a8ae2f.png">


This may be too much content and/or require a more careful design pass before we implement.

From an engineering point of view, we would not build the Stripe / Paypal processing into the snippet. Instead clicking the CC or PayPal button on the snippet would bring the user to our one-page form and then route the user along to the appropriate payment flow (Stripe or PayPal).

@edrushka have you seen any design tickets or tasks that capture this yet? If not, could we file this as a new one. I think it's a potentially high-value test for EOY, but is likely to need extra time for review and feedback from MoCo product and engagement team.

**Comment by edrushka** [comment]
Andrea and I agreed we can't currently prioritize any radical snippets, but I filed a design ticket in case that situation changes: https://github.com/mozilla/donate.mozilla.org/issues/620

**Comment by edrushka** [comment]
Closing this, as #620 won't be tackled this year.
