### ISSUE TITLE
South Korean Won -- plan not supported?

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1938]
Email from a knowledgeable donor this morning...

Hi.
First of all, thank you Mozilla for working so hard to make a web better place.

I’m trying to sign up for monthly 11,160 KRW pledge, however payment fails over and over again.
Stripe shows me the green check icon, but after the popup is closed below error message is shown.

The transaction could not be completed. Please email donate@mozilla.org for assistance with your donation. [Bad Request]

Below was the request payload to stripe-checkout api.

Name

Name

{
"frequency":"monthly”,
"amount":"11160”,
"stripeToken”:”**redacted**”,
"currency":"krw”,
"locale":"en-US”,
"email": "**redacted**"
"code":”**redacted**”,
"description":"Mozilla Foundation Monthly Donation”,
"country":"Korea, Republic of”,
"address":"**redacted**”,
"city":"**redacted**”,
"first":"**redacted**"
}

The request was done in Chrome 62.0.3202.94 and macOS High Sierra.

Could you fix this or let me know the other way to sign up for monthly donation?
Thank you.

Best regards,
Heejong._______________

I'm seeing five donation attempts over the past couple weeks, all blocked by the same 400 error ...

Stripe says:

{
  "error": {
    "type": "invalid_request_error",
    "message": "No such plan: krw",
    "param": "plan"
  }
}

We have no "plan" for KRW -- ??

**Comment by cadecairos** [comment]
+@ScottDowne

**Comment by cadecairos** [comment]
Confirmed issue on Staging:

![screenshot-2017-12-20 support mozilla](https://user-images.githubusercontent.com/438003/34214818-8c99e0ea-e571-11e7-86f7-e309b19d588e.png)

**Comment by cadecairos** [comment]
The solution here seems to be "create a monthly plan for KRW" @ScottDowne you have done this before, right?

**Comment by cadecairos** [comment]
I took the initiative and used other plans as a model, and created the plan in our test environment. works perfectly now on staging.

**Comment by cadecairos** [comment]
And also on production - @WillatMozFdn monthly KRW donations should now get accepted.

**Comment by cadecairos** [comment]
I wonder what other currencies might have this same issue?

**Comment by cadecairos** [comment]
I found at least one: LBP - I suspect there are many others without plans defined in Stripe.

**Comment by ScottDowne** [comment]
@cadecairos thanks!

I'm looking into one thing around this, but I might be imagining it, so give me a sec. If I'm imagining it, we likely have others.

**Comment by ScottDowne** [comment]
@cadecairos I suspect something happened to break this https://github.com/mozilla/donate.mozilla.org/blob/afa86a02c9e93b64c52dca068d95d068e6a41fce/ops/stripe_plans.js

**Comment by cadecairos** [comment]
Is this something that is supposed to get run automatically somewhere?

**Comment by cadecairos** [comment]
@WillatMozFdn Scott and I updated and automated the running of a script that will keep our monthly plans in sync every time we deploy. so if we add more currencies or need to change plan details (like statement descriptors) we can do so in bulk, and in an automated fashion.
