### ISSUE TITLE
Copy test - German donate page

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1939]
German localizers are proposing a new (they think better) landing page text for German donors.  I'd like to test that, optimization is super-important to make max $$$!)

Current control is ... 

"Wir sind gemeinnützig, nicht kommerziell, nicht kompromittiert und stolz darauf. Tausende von Menschen wie Sie unterstützen uns dabei, für ein offenes Internet für alle einzutreten. Für unsere Mission, das Internet offen und frei zu halten, sind wir auf Spenden angewiesen. Spenden Sie heute?"

We would like to test ...

"Als Non-Profit-Organisation sind wir unabhängig und frei. Unser Handeln wird nicht durch die Interessen anderer Unternehmen bestimmt. Darauf sind wir stolz. Gemeinsam mit tausenden von freiwilligen Helfern weltweit treten wir für ein offenes Internet ein. Unterstützen Sie uns jetzt, damit das Netz auch in Zukunft weiterhin für alle offen and zugänglich bleibt. Vielen Dank für Ihre Spende!"

(In English/googleTrans), those are ...
"We are charitable, not commercial, not compromised and proud of it. Thousands of people like you support us in advocating an open internet for all. For our mission to keep the Internet open and free, we depend on donations. Donate today?"
vs.
"As a non-profit organization, we are independent and free. Our actions are not determined by the interests of other companies. We are proud of that. Together with thousands of volunteers worldwide, we are committed to an open internet. Support us now so that the network will continue to be accessible to all in the future. Thank you for your donation!"
)

**Comment by alanmoo** [comment]
Makes sense @ScottDowne. Let's set the assignee as the person responsible for the next action on the ticket. If people need to be informed, we can mention them in comments.

**Comment by ScottDowne** [comment]
@vojtechmzl ok, it's been sent to production, and soon this should be updates: https://donate.mozilla.org/de/?test=de-copy

Then you can setup the test.

**Comment by TheoChevalier** [comment]
Will didn’t notice any significant difference between the two copy, so I’ve just pushed the new copy through Pontoon. I think we can close this!
