### ISSUE TITLE
Take Rose Regina Lawrence off Stripe Notifications

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1943]
We get a lot of bouncebacks (into the donate@mozilla.org box) for notifications sent to rose@mozillafoundation.org from Stripe.com.

We need to take her off those notifications, as she does not work with us anymore ... please replace her email address with mine for those.

Thanks!

**Comment by shikhar-scs** [comment]
@WillatMozFdn If @cadecairos is not working on this issue then can I fix it ?
If yes, can you tell me where to make the required changes.

**Comment by WillatMozFdn** [comment]
@shikhar-scs -- pretty sure that @cadecairos did in fact get this one knocked out the other day, but thanks for checking on it!

**Comment by cadecairos** [comment]
yes, this is done
