### ISSUE TITLE
React development is being served in production

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1955]
https://twitter.com/Siilwyn/status/958023148321959936

**Comment by cadecairos** [comment]
We should fix this - I don't have a clue how to do so at this time. I can research how webpack + react + redux works, but it might be faster to have a front end developer familiar with the tools do it.

**Comment by alanmoo** [comment]
Considering it's been like this for a while and everything does work, @ScottDowne can take a look when he's back from PTO
