### ISSUE TITLE
Donation form URL - change type

### ISSUE THREAD

**Issue by desiree-mofo** [mozilla/donate.mozilla.org#1963]
Need to update the Donation Form URL Field definition to change it from URL to Long text field b/c URL fields are limited to 255 characters and we cannot change that. Per @pmac, this will not be enough for the URL values that will be passed through via the donation process. 

Donation_Form_URL__c on Opportunity is the field name that needs to be re-defined as a long text area type.

**Comment by cadecairos** [comment]
@desiree-mofo #1965

**Comment by cadecairos** [comment]
Gotta clarify one thing: this data isn't from Stripe, it's the full URL someone entered the donation page with. We'll be getting it for Stripe and Paypal donations.

**Comment by pmac** [comment]
Basket PR is merged and deployed to dev and stage. We can test in the sandbox anytime.

**Comment by desiree-mofo** [comment]
Code pushed to Production; closing issue
