### ISSUE TITLE
Look at enabling node cluster module usage

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#197]
Heroku recommended looking into using the node cluster module. This basically lets you run multiple instances of a node app listening to the same port. This is especially required for PX dynos.

**Comment by jbuck** [comment]
And specifically they linked me to https://devcenter.heroku.com/articles/node-concurrency

**Comment by adamlofting** [comment]
Next step:

- [ ] Decide if we're going to do this? If yes, action.

**Comment by jbuck** [comment]
Yeah, it's a requirement for doing load testing with bigger instances. You need multiple node processes to take advantage of the resources offered
