### ISSUE TITLE
Update Donor FAQ

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#1976]
Need to add a question/answer to the FAQ: 

Why does Mozilla use reCaptcha?
Nonprofit organizations are a common target for online credit card fraud. Use of reCaptcha is one way we’re working to protect against automated abuse and prevent fraudsters with stolen card information to test these numbers on our donation forms. We care about your privacy. When Mozilla (that's us) collects information about you, our [Mozilla Privacy Policy](https://www.mozilla.org/en-US/privacy/) describes how we handle that information.

Use of the Invisible reCAPTCHA is governed by the Google [Privacy Policy](https://www.google.com/intl/en/policies/privacy/) and [Terms of Use](https://www.google.com/intl/en/policies/terms/).

@WillatMozFdn for FYI.

**Comment by WillatMozFdn** [comment]
Can I make a slight grammar edit?  
"... prevent fraudsters with stolen card information to test these numbers on our donation forms..."
to
"... prevent fraudsters with stolen card information **from** test**ing** these numbers on our donation forms..."

**Comment by stephaniemcv** [comment]
FYI @cadecairos

**Comment by TheoChevalier** [comment]
Side note, we probably want to use those links instead, which are redirecting to localized versions of Google pages https://policies.google.com/privacy/ https://www.google.com/policies/terms/

and definitely this one for ours https://www.mozilla.org/privacy/

**Comment by PunkChameleon** [comment]
This looks complete on donate.mozilla.org -- can this be closed?

**Comment by ScottDowne** [comment]
Yes this does look like it happened, I probably did it when doing the main recaptcha integration, and didn't close this too.
