### ISSUE TITLE
Edits to donation home page (requested by Legal) - one dynamic based on recurring vs. one-time

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1986]
1. The simple one ... text change in the footer of the page, for everyone, to add our location:
OLD: Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to be used in its discretion for its charitable purposes. They are tax-deductible in the U.S. to the fullest extent permitted by law.
... to ... 
NEW: Contributions go to the Mozilla Foundation, a 501(c)(3) organization based in Mountain View, California, to be used in its discretion for its charitable purposes. They are tax-deductible in the U.S. to the fullest extent permitted by law.

2. The not-so-simple one ... when (and **only** when) the "Monthly" radio button is selected, the verbage below the blue donation buttons needs to change (and probably font size reduced?) to ... 

"Your payment details will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla.   Monthly donations are charged each month on the same day that you donate today, and will continue until you cancel. To cancel, email us at donate@mozilla.org."

**Comment by ScottDowne** [comment]
Yeah, I can do this today, probably won't take long.

**Comment by ScottDowne** [comment]
Changes are here https://github.com/mozilla/donate.mozilla.org/pull/1988

Guessing we can get this live Monday.

@TheoChevalier any concerns/mind giving it a review?

**Comment by TheoChevalier** [comment]
@ScottDowne Thanks, it looks good. Just spotted a small typo in a variable name, but that’s not blocking of course
