### ISSUE TITLE
Change email subject line of Stripe transaction confirmations based on recurring vs. one-timer

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1987]
Per a request from Abigail in Legal, we need to change the subject line of outgoing emails that acknowledge Stripe donations, to include the fact that it is a recurring donation.

So, for a one-time donation, we stick with the current one, which is "Thank you for your gift to Mozilla."

New subject line, for when it is a **recurring** donation: "Thank you for your recurring donation to Mozilla."

Chris says that this magic is possible, by making some tweaks here...

"Rendering the donation email: https://github.com/mozilla/sawmill/blob/master/worker/stripe_charge_succeeded.js#L81-L90
using the subject: https://github.com/mozilla/sawmill/blob/master/worker/stripe_charge_succeeded.js#L97

We can insert a conditional in between the two there to customize the subject line."

**Comment by alanmoo** [comment]
@ScottDowne or @cadecairos can one of you grab this when you have a chance?

**Comment by TheoChevalier** [comment]
Since this is a legal requirement, we will need to update the localized versions of the email too.
The copy is the previous one, but it’s starting with something similar “Thank you so much for your donation to Mozilla.”
I could expose this new string “Thank you so much for your recurring donation to Mozilla.”, and we could then run an update to localized emails in a few days? They were needing an update anyway, so this is a good opportunity

**Comment by cadecairos** [comment]
@TheoChevalier I'm pretty sure our current Stripe donation email is not localized: https://github.com/mozilla/webmaker-mailroom/tree/master/locale/en_US -> there's no "stripe_charge_succeeded_2015.json", and the template itself isn't using any l10n tags

**Comment by TheoChevalier** [comment]
@cadecairos This is the one we’re currently sending to other languages https://github.com/mozilla/webmaker-mailroom/blob/master/locale/en_US/stripe_charge_succeeded_2014.json Can we do some conditioning with this one by any chance?

**Comment by WillatMozFdn** [comment]
@cadecairos circling back to this one to see where we are ... I'd like to give Abigail an update before we propose a May fundraising email that explicitly asks for recurring donations.  Is there a solution you could recommend here?

**Comment by ScottDowne** [comment]
From my understanding of the convo up to this point, we have a solution to the 2015 email templates, but those are only in English, and the 2014 templates couldn't get the same solution?

If so, isn't there still value in doing this for just English? Like, would that still solve the issue for a May fundraising email if it was only in English (not sure what languages we're tar targeting here)

**Comment by WillatMozFdn** [comment]
Thanks Alan!  Yes, it would get us further down the road, which would be a good thing.  (Was planning on other languages for May fundraiser, too, but we may have to scale those plans back depending on what Abigail says.)  So ... can we go ahead and implement on the 2015 templates for now?

**Comment by ScottDowne** [comment]
@TheoChevalier and @cadecairos I think this should do it?

Any thoughts?

https://github.com/mozilla/sawmill/pull/86
https://github.com/mozilla/webmaker-mailroom/pull/66

**Comment by TheoChevalier** [comment]
@ScottDowne I think this would work, but in case the string IDs in `stripe_charge_succeeded_2014.json` need to match the ones in the l10n file, the current ID for the subject line is `your_gift_help_us` instead of `stripe_charge_succeeded_2014_subject` https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/email.properties#L14

**Comment by TheoChevalier** [comment]
Let me know if we can keep `your_gift_help_us` as string ID, then we can expose the new string here: https://github.com/mozilla/donate.mozilla.org/pull/1996 (I’m also removing some obsolete strings at the same time in a separate commit)

**Comment by ScottDowne** [comment]
@TheoChevalier this fell off my radar. I'm not sure if I'm following your requests.

**Comment by TheoChevalier** [comment]
@ScottDowne Those are the two IDs for the subject lines https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/email.properties#L1-L4
I think my ask here is just to use those in the code, since I can’t update them without invalidating the translations

**Comment by alanmoo** [comment]
Closing this as it'll be superseded by SFMC donor receipts as soon as the donation locale fields hit SalesForce, which is the next thing Chris is working on.
