### ISSUE TITLE
donating broken

### ISSUE THREAD

**Issue by mkmelin** [mozilla/donate.mozilla.org#1992]
Just noticed that if you go to https://donate.mozilla.org/en-US/ and click $50 and then donate by credit card, it still asks you to fill in the sum. 

Trying to fill in the sum, it still doesn't work. By paypal - doesn't work either.

I do get this in the console

TypeError: window.grecaptcha.render is not a function

TypeError: window.grecaptcha.render is not a function[Learn More] main.9ab407170138948d74c5.js:15:1311749
	setupRecaptcha/< https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1311749
	expectRecaptcha https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1311600
	expectRecaptcha self-hosted:992:17
	setupRecaptcha https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1311717
	setupRecaptcha self-hosted:990:17
	componentDidMount https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1311060
	notifyAll https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:26912
	close https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1207401
	closeAll https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:64509
	perform https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:63962
	l https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:38423
	perform https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:63882
	batchedUpdates https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1204964
	n https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:29209
	_renderNewRootComponent https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:39602
	_renderSubtreeIntoContainer https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:40584
	render https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:40711
	<anonymous> https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1155232
	<anonymous> https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1154528
	a https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:96
	<anonymous> https://donate.mozilla.org/main.9ab407170138948d74c5.js:15:1154473
	a https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:96
	<anonymous> https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:451
	<anonymous> https://donate.mozilla.org/main.9ab407170138948d74c5.js:1:2

**Comment by mkmelin** [comment]
Seems to be working again today. 
But maybe it can give some clues on why there are occasional complaints that the page doesn't work

**Comment by dyorgio** [comment]
Hi, I have same issue on my own application, and looking for help I found this issue.
To solve my problem I add a extra verification on my reCaptcha render logic:

Before:
```javascript
var render = function() {
 if (window.grecaptcha) {
   myCallBack(window.grecaptcha.render(recaptcha, parameter));
 } else {
  setTimeout(render, 50);
 }
};
render();
```

After:
```javascript
var render = function() {
 // Include extra verification (maybe a new async reCaptcha behavior)
 if (window.grecaptcha && window.grecaptcha.render) {
   myCallBack(window.grecaptcha.render(recaptcha, parameter));
 } else {
  setTimeout(render, 50);
 }
};
render();
```

Maybe it can help others ;)

**Comment by cadecairos** [comment]
Yes, we identified the same problem and implemented a similar solution.

**Comment by cadecairos** [comment]
Here's the PR: https://github.com/mozilla/donate.mozilla.org/pull/1993
