### ISSUE TITLE
Fix post-donation email subscription ask

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1998]
Currently, everyone who donates (either platform) is asked to subscribe to Mozilla newsletters (even if they are already subscribed), and there is no way to escape or close that modal (?) -- you're stuck in a dead-end.

![image](https://user-images.githubusercontent.com/23637882/40489226-a02a939a-5f36-11e8-9cb1-656e5f8c148e.png)

So, two fixes proposed.

1) If you come into the donation flow with "subscribed=1" in your querystring (which we will start adding to all email campaigns), we notice that fact up front in the process, and we do NOT ask you to subscribe to our emails after the donation -- i.e., we skip this step entirely, and move them on to the sharing options on the next page.  (This won't entirely fix the problem -- some folks who contribute from snippet, let's say, are in fact subscribed and will see an ask that's kind of pointless.  However, it does fix the problem of us showing an irrelevant email subscription ask to people who we just drove to the site using email, which is a very sizeable percentage.)

2) To give donors an option that lets them move forward without subscribing, we place a smaller-font "No thanks" link, centered under the red "Sign up now" button.  That link lets them move forward to the next page, social sharing, without subscribing to our newsletters.

**Comment by alanmoo** [comment]
Design needs: 

* Updated design for "subscribe" page to be in line with new design language, with "no thanks" link
* Updated design for "share" page

**Comment by alanmoo** [comment]
Closing this ticket in favor of the separate tickets linked above. Tracking everything at https://github.com/mozilla/foundation.mozilla.org/projects/9
