### ISSUE TITLE
New fundraising modal after petition signing

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#1999]
Background: When someone signs a petition on foundation.mozilla.org, we want to immediately (upon submit) display a modal box that asks for a donation to the Mozilla Foundation.

 - approximate size 400 x 400; modal should be close-able with an X at upper right
 - we'd like the ability to turn the modal on/off, or change copy and graphics, without developer assistance
 - copy and design TBD, but will probably look something like this:
![image](https://user-images.githubusercontent.com/23637882/40495604-9e46e812-5f45-11e8-971e-28d7b7a0102c.png)

**Comment by alanmoo** [comment]
What about the ShareProgress links for a campaign? Will they stay where they are, in the spot formerly occupied by the petition form?

**Comment by WillatMozFdn** [comment]
yes, good question, SP links over there on the right will stay exactly as they are currently.

**Comment by WillatMozFdn** [comment]
^^ on that one, Alan, I'm not locked in on what parameter tracks what, but I do know that we'll want to track with utm parameters: a) what variant of the modal is used (i.e., one-button, four-button, copyA vs. copyB -- that kind of thing) and b) which petition the modal followed (which could potentially be auto-set as equivalent to the petition name, i.e., "facebook-and-european-parliament" OR we could just do it manually).

**Comment by WillatMozFdn** [comment]
@kristinashu -- here's some more accurate placeholder test to use ... a little longer, hope it can fit?  

(headline:) Thanks for signing!  While you're here, we need your help.

Mozilla is a nonprofit organization fighting for a healthy internet, where privacy is included by design and you have more control over your personal information.  We depend on contributions from people like you to carry out this work.  <bold>Can you donate today?</bold>

(Button:) Yes, I'll chip in

<link> No, I'll share instead </link>

**Comment by alanmoo** [comment]
Moved this conversation over to https://github.com/mozilla/foundation.mozilla.org/issues/1589
