### ISSUE TITLE
[Donate] Implement modern reskin

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#2008]
Placeholder for work to be described in https://github.com/mozilla/foundation.mozilla.org/issues/1534

@kristinashu Please update this comment when everything is ready.

**Comment by kristinashu** [comment]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1534

All comps are here: https://redpen.io/p/thbfb2535f83162d2d
- Colors and font styling is from https://foundation.mozilla.org/style-guide/
- Icons are from current https://donate.mozilla.org/en-US/
- Nav should function like and link to foundation site [zenmode style](https://foundation.mozilla.org/campaigns/facebook-update/) (footer should be the same too)
- Redlines for desktop and hover states
![donate x-large 2x](https://user-images.githubusercontent.com/1068783/41006536-ca16005a-68d6-11e8-84cf-8a4ad5b32947.jpg)

**Comment by ScottDowne** [comment]
Adding a few more possible thunderbird people @ryanleesipes and @sancus

Thoughts?

**Comment by ScottDowne** [comment]
@kristinashu have the changes to the order of the disclaimers been run by legal? They have been very particular in the past on the positioning of the stripe/paypal bit. I'm also not sure what they'll think about making it lighter in colour.

**Comment by kristinashu** [comment]
Also, I didn't include the reCAPTCHA logo (bottom right) in my comp but we should keep that.

<img width="88" alt="image" src="https://user-images.githubusercontent.com/1068783/41786810-589ef904-75fb-11e8-8523-541c53f834d9.png">

**Comment by kristinashu** [comment]
Updated:

![donate x-large copy 9 2x](https://user-images.githubusercontent.com/1068783/41787538-9327f04c-75fd-11e8-94c5-6072dc950042.jpg)

**Comment by ScottDowne** [comment]
Here is where I am currently https://donate-mozilla-org-us--pr-2020.herokuapp.com/en-US/

**Comment by ScottDowne** [comment]
I figure another day, and another day of qa/reviews?

**Comment by kristinashu** [comment]
Sweet!

**Comment by alanmoo** [comment]
Nice. You’re probably aware, but it definitely needs some mobile love.

**Comment by ScottDowne** [comment]
@kristinashu updates https://donate-mozilla-org-us--pr-2020.herokuapp.com/en-US/

**Comment by kristinashu** [comment]
P1
- Zen mode nav (because without there is no mozilla logo)
- balance size of Credit Card vs PayPal logos (Credit Cards seem a little too small and PayPal seems too big) (because I worry there are politics around this...)

P2
- Fonts should follow [Style Guide ](https://foundation.mozilla.org/style-guide/)
- Foundation site footer

 P3
- I'll wait until you have done another pass

**Comment by ryanleesipes** [comment]
Looks good and scales well!

**Comment by mkmelin** [comment]
Looks good to me. The navigation is neat, but yeah, I wouldn't add that to the Thunderbird page.

**Comment by TheoChevalier** [comment]
Heads up that I’ve removed the email link from the footer before it gets deployed to production, see https://github.com/mozilla/donate.mozilla.org/pull/2046 for the details
