### ISSUE TITLE
Minor copy change to donate main page

### ISSUE THREAD

**Issue by jessevondoom** [mozilla/donate.mozilla.org#2014]
In the sentence "Thousands of people like you help us stand up for an open Web for all." We should change "an open Web" to "a healthy internet" — change has been cleared already.

Unsure how this affects localization but starting the change on English-language strings for now is acceptable. @ScottDowne do you think we can slip this is during the reskin?

**Comment by TheoChevalier** [comment]
We can quite easily add a conditional to expose the new string in English only while it’s being translated in other languages. That’s what we usually do for highly visible strings.

Updated string ready to be sent to localizers: https://github.com/mozilla/donate.mozilla.org/pull/2015

**Comment by jessevondoom** [comment]
@TheoChevalier YOU ARE AWESOME. TY!

**Comment by ScottDowne** [comment]
@jessevondoom should "a healthy internet" be "a healthy Internet"?
