### ISSUE TITLE
Updates from legal

### ISSUE THREAD

**Issue by kristinashu** [mozilla/donate.mozilla.org#2029]
Updates from Abigail

(1) https://donate.mozilla.org/en-US/ways-to-give

Add: "Please remember that donations are deductible for U.S. income tax purposes only."
(text can go under the "New! We are now able to accept donations in Euros..." paragraph")

(2) https://donate.mozilla.org/en-US/thunderbird/

Add: "While Thunderbird is now an independent project separate from Mozilla, Mozilla has agreed to collect donations on our behalf."
(text can go on the left side, under "We’re the leading open source cross-platform email and calendaring client...,")

Update: "Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to support Mozilla Thunderbird" to say instead: "Contributions go to the Mozilla Foundation, a 501(c)(3) organization based in Mountain View, California, to support Thunderbird. They are tax-deductible in the U.S. to the fullest extent permitted by law."

**Comment by WillatMozFdn** [comment]
That verbage sounds good to me!  adding @TheoChevalier for localization into all other languages that we support on the donation pages (both T-bird and Mozilla).
