### ISSUE TITLE
Test photos on donation landing page

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2033]
In place of the white heart at the upper left of the current donate.mozilla.org page, we would like to test one, or possibly two if TrafficCop will let us, **photos**.  Text there should stay the same (likely, moved down some on the page to accommodate the photo.)

Raw images are attached -- we have the rights to use these and they can be cropped however we need.
![img_mozfest_sticker](https://user-images.githubusercontent.com/23637882/43011233-daa051c0-8c10-11e8-97fb-32c6a8551717.jpg)
![img_jvds_kids](https://user-images.githubusercontent.com/23637882/43011234-daad6090-8c10-11e8-86ae-b4f1dd9d5f7d.jpg)

**Comment by xmatthewx** [comment]
@taisdesouzalessa - can you connect with Will about this next week? 
 - This will be a simple swap of the donate page's heart for an image. no other changes to the page. 
 - Will has supplied two image options that can be modified to fit. 
 - Please use the proportions that are best for the page (we can bend foundation site standards to benefit fundraising)
 - Ping me on Slack next week with any questions from a design perspective. 
 - Have a great weekend!!

**Comment by WillatMozFdn** [comment]
I'm technically on PTO next week but for most of Monday through Wednesday, will be VERY available on slack (sitting in the Netroots Nation conference room, organizing volunteers over email), so please don't hesitate to ping me!  I really want to keep this project moving forward.  Thanks! :-)

**Comment by taisdesouzalessa** [comment]
Hey @WillatMozFdn let me know what time window works the best for you on Monday so I can ping you in Slack? I am on PST time.

**Comment by taisdesouzalessa** [comment]
@WillatMozFdn, here are the proposals. Let me know which ones you prefer.
cc: @xmatthewx 

- Proposal 1A:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/22157921/43429258-4358f1f0-9417-11e8-92b0-d1d466718fab.png">

RedPen (use keyboard side arrows to see individual desktop and mobile pages): https://redpen.io/doa1fcb24c04d2a72f


- Proposal 1B:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/22157921/43429292-7fd4cb5e-9417-11e8-9ca0-7830598fd2a9.png">

RedPen (use keyboard side arrows to see individual desktop and mobile pages): https://redpen.io/dp2522ebc9cb27a10f

- Proposal 2A:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/22157921/43429313-98ed55de-9417-11e8-9ebf-5c0fdedb5254.png">

RedPen (use keyboard side arrows to see individual desktop and mobile pages): https://redpen.io/qsdfec94118dbecde3

- Proposal 2B:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/22157921/43429333-ab4120ee-9417-11e8-914a-eeea7064a38e.png">


RedPen (use keyboard side arrows to see individual desktop and mobile pages): https://redpen.io/cxa18bd16f1d690c0f


###  Comps starting with "3" are a suggestion of picture for series "2" (with people)

**IMPORTANT Note:** I am not sure this image is clear to be used in the donation page. The image is ours (from MozFest) and in the Flickr page it says it is ok to use as long as it is not for commercial use. I am not sure if donation fits into this category.

- Proposal 3A:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/22157921/43429372-dc9e8c6c-9417-11e8-89b0-0f82fac9ff51.png">

RedPen (use keyboard side arrows to see individual desktop and mobile pages): https://redpen.io/sz3a8fb434d9b5bbe7

- Proposal 3B:
<img width="991" alt="image" src="https://user-images.githubusercontent.com/22157921/43429384-f0578c5e-9417-11e8-8116-ab9b058a0e93.png">

RedPen (use keyboard side arrows to see individual desktop and mobile pages): https://redpen.io/bf477448f2d568b521


**All comps that have "B" in the name could be are a little bit more complex from the implementation standpoint and we should check with Engineers about time of completion if we go for those ones.**

**Comment by WillatMozFdn** [comment]
Thanks @taisdesouzalessa  Have checked these out -- would like to go with 1A and 3A as the two variants we test against the current control.  (I like the "B" versions, but given that they might take more time ... let's keep it simple and first see if images work at all ... then maybe we can test into those other variants.)  Thanks again and feel free to ping me back with any questions!
cc: @xmatthewx

**Comment by taisdesouzalessa** [comment]
Cool! Thanks @WillatMozFdn - about the image 3A, do you know if that image can be used on a donate page? The image is ours (from MozFest) and in the Flickr page it says it is ok to use as long as it is not for commercial use. I am not sure if donation fits into this category. Just want to double check with you :).

**Comment by taisdesouzalessa** [comment]
Closing this ticket. Design phase is done. Implementation ticket for engineers is being tracked here:  #2045 - feel free to reopen the ticket if necessary,
