### ISSUE TITLE
Prefix all server-side routes with /api

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#204]
@adamlofting @alicoding @ScottDowne To make configuring the CDN easier, I'd like to prefix all of our serverside routes with `/api`. That way I only need to have two behaviours handled in the following order:

1) If url begins with `/api` then pass through directly to node server
2) Caching for static files, which should be everything else on the server

**Comment by adamlofting** [comment]
Sounds totally sensible. 

- [ ] Also, note this in the README so that people making new routes know why it's this way

**Comment by alicoding** [comment]
Time estimate to do all this:
* 0.5 day for converting + create script to change from .yml/json to .po vice 
* 1-2 day for integrating pontoon with our donation 
* 0.5 day for sending email and file bugs with the mozilla 
* 0.5 day updating the staging server
