### ISSUE TITLE
Add Mozilla logo to header for non-English locales

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#2042]
Right now, non-English locales only have the Mozilla logo in the footer. It should appear in the header as it does for English, but without the navigation to the Foundation site pages, since those pages aren't localized. Blocked by #2041

**Comment by richa031** [comment]
please tell me the details of this one

**Comment by alanmoo** [comment]
Sorry, we've addressed this and just forgot to close the issue. Feel free to check out [the Foundation site](https://github.com/mozilla/foundation.mozilla.org) or [Mozilla Pulse](https://github.com/mozilla/network-pulse)
