### ISSUE TITLE
[Implementation ticket] Test photos on donation landing page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/donate.mozilla.org#2045]
_Tagging @alanmoo for triage_

Based on discussion here: #2033

Here are the implementation specs for the 2 chosen variations:
### Variation 1 (comp):
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/22157921/43611796-2db94c10-965f-11e8-9d3c-2737ff344e6b.png">

RedPen: https://redpen.io/doa1fcb24c04d2a72f

### Variation 2 (comp):
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/22157921/43615159-3463f6a8-966b-11e8-9354-9c11db0ee1b5.png">

RedPen: https://redpen.io/sz3a8fb434d9b5bbe7

### For both of them, here are the specs:
Spec screenshot: https://redpen.io/bj9f0108a7be1c330b
- [ ] DESKTOP: image has 16:9 proportion and it is the width of the text column. Margin bottom = 32px (same as implemented version)
- [ ] MOBILE: image has a different crop from desktop (smaller height because we don't want to take too much space from the already tiny mobile screen), width is the same as the one from text column, height is proportional as it scales. Margin bottom = 32px (same as implemented version)

### Cropped pictures here (ready to use):
![image_i-believe_desktop 2x](https://user-images.githubusercontent.com/22157921/43615441-8077b1b4-966c-11e8-8f7e-010ba350c03e.jpg)
![image_i-believe_mobile 2x](https://user-images.githubusercontent.com/22157921/43615442-808f4c34-966c-11e8-985c-fcaaa876c62c.jpg)
![image_teaching_desktop 2x](https://user-images.githubusercontent.com/22157921/43615443-80a4913e-966c-11e8-8f4e-34840f8603aa.jpg)
![image_teaching_mobile 2x](https://user-images.githubusercontent.com/22157921/43615444-80b6e24e-966c-11e8-8de1-3c6bead602ac.jpg)

### Notes:
Please connect with @WillatMozFdn to set up the A/B test with him. Also, please keep me in the loop of when it is implemented (so I can do a design review) and when the test launches :). I am curious to see the results of this test.

**Comment by WillatMozFdn** [comment]
Just checking in briefly -- this all looks good to me!  Thanks @taisdesouzalessa !!

**Comment by WillatMozFdn** [comment]
Hey team -- can we please pull image B (the "I believe in the open internet" sticker one) OUT of the rotation, and continue testing the control vs. the other image?  I ran some numbers yesterday and that one's a clear loser ... the other two are basically neck and neck.  Let me know when you get a chance, thanks!  cc @alanmoo

**Comment by alanmoo** [comment]
I can do that, but please file a new ticket and tag me in it- the request from the original comment has been met, so this ticket should remain closed.
