### ISSUE TITLE
Is there a way to test a donation?

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2049]
When running the site locally are there values to use to test a donation?

**Comment by TheoChevalier** [comment]
Yes! You can use Stripe’s test values: https://stripe.com/docs/testing#cards
You just need the card number to be one of these, all the rest can be dummy data.

And this works on staging, too.

**Comment by TheoChevalier** [comment]
Closing the issue, but feel free to ping me if you have trouble testing donations!

**Comment by ryanleesipes** [comment]
I had success testing with the aforementioned values. I do think that and the staging website should be detailed in the README. Any thoughts on that?
