### ISSUE TITLE
PayPal is still using a Symantec certificate 

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate.mozilla.org#2050]
Starting next week, Symantec certificates won’t be trusted anymore on Nightly. It turns out PayPal uses one, so with `security.pki.distrust_ca_policy` set to 2 on Nightly, I’m getting a security warning on sandbox.paypal.com preventing me from donating via PayPal.

More info here: https://blog.mozilla.org/security/2018/07/30/update-on-the-distrust-of-symantec-tls-certificates/

I’m pretty sure they will fix this before it hits the release channel in October, but if we have contacts at PayPal, we may want to flag it to them, just in case. I’m sure you’ve seen this Chris, but I’d better be safe than sorry

CC @cadecairos @WillatMozFdn

**Comment by TheoChevalier** [comment]
Because it can’t hurt, asked on Twitter https://twitter.com/t_chevalier/status/1027674574568206336

**Comment by WillatMozFdn** [comment]
Thanks Theo!  I'll ping our Paypal account manager, and let y'all know if/when I receive a response.

**Comment by TheoChevalier** [comment]
Spotted this slightly more helpful reply on Twitter: https://twitter.com/AskPayPal/status/1026113237522116609 At least their IT department seem to be aware

**Comment by TheoChevalier** [comment]
(Chrome 70 goes to Beta on Sept 13. Firefox 63 should go to beta around that date, too)

**Comment by TheoChevalier** [comment]
They finally updated their cert! Closing this
