### ISSUE TITLE
stripe dialog - terms and privacy links 404

### ISSUE THREAD

**Issue by mkmelin** [mozilla/donate.mozilla.org#2051]
On the donate page once you click credit card donation and get the stripe popup to fill in your personal details (email, address etc.) - on the bottom there are two links: Terms and Privacy. These links do not work, they lead to https://checkout.stripe.com/-/terms and https://checkout.stripe.com/-/privacy which are 404.

[reported to thunderbird-donate by a donor]

**Comment by TheoChevalier** [comment]
Thanks for reporting, this code is owned by Stripe.
I’ve reached out to Stripe customer support, I’ll update this issue once I hear back from them

**Comment by TheoChevalier** [comment]
After multiple exchange with Stripe support, they reported the issue internally and deployed a fix today. Links are now redirecting properly, yay!
