### ISSUE TITLE
Requested Singapore Currency

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2053]
Had a donator ask why Singapore wasn't listed on the options for currency selection. I saw #455 but was unsure is SGD wasn't a supported currency and that's why it didn't get implemented.

**Comment by TheoChevalier** [comment]
It may be there was issues at the time, or specific requirements. Or simply that we forgot to add it.
Taking this one, I think we should be able to support SGD

**Comment by ryanleesipes** [comment]
Thank you.

**Comment by TheoChevalier** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/pull/2059
