### ISSUE TITLE
Issues with Post Codes from UK donors

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2054]
Have you seen any reports from UK donors in regards to their zip codes not being accepted? I have one user who attests to this being an issue for them.

**Comment by TheoChevalier** [comment]
Checking with Stephanie if she’s seen anything recently.
FWIW, I have no issue donating using my own UK postcode

**Comment by TheoChevalier** [comment]
Stephanie is not seeing more issues than usual, so it doesn’t seem to be a recent regression from Stripe at least. She said there are “postcode doesn't match” issues from time to time, but it can also happen with U.S addresses

**Comment by ryanleesipes** [comment]
After troubleshooting I can't seem to figure out what the issue is here. I guess this can be closed.
