### ISSUE TITLE
Requested TND (Tunisian Dinar) Currency

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2057]
Another request from potential Tunisian donors, asking for support for the dinar (TND). Is this possible?

**Comment by TheoChevalier** [comment]
Unfortunately neither Stripe or PayPal currently support this currency: 
https://stripe.com/docs/currencies#currencygroup1
https://developer.paypal.com/docs/classic/api/currency_codes/#paypal

If one day they support it, it will be easy to add, but until then we can’t really fix this

**Comment by ryanleesipes** [comment]
Thank you for looking into this @TheoChevalier!
