### ISSUE TITLE
Combine Paypal processing logic

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#206]
Looking at https://github.com/mozilla/donate.mozilla.org/blob/ac810639a009ac33266efeacde771379c12770aa/server.js#L197-L264 the only difference between the two routes is that `PAYMENTREQUEST_0_DESC` is changed to "Mozilla Foundation Monthly Donation", `L_BILLINGAGREEMENTDESCRIPTION0` is added, `L_BILLINGTYPE0` is added, and `returnUrl` is modified based on the type of request.

Could we combine these two routes into a single route?

**Comment by ScottDowne** [comment]
Landed
