### ISSUE TITLE
Edit to Donor FAQ

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2066]
In order to improve our rating with Charity Navigator (and thus potentially be able to post a four-star rating on our site if we want), we need to make a couple changes to our FAQ (to satisfy a standard from Charity Navigator that we explicitly say do not ever swap or sell donors' personal info.)

The change below has been approved by Legal team (Abigail and Alicia).

https://donate.mozilla.org/en-US/faq#item_2, "How does Mozilla ensure my personal information is protected?"

**OLD**: (delete)

"We care about the privacy of our donors and take our Privacy Principles seriously. Mozilla believes individuals should be in control of their data, and maintains multi-layered security controls and practices. To learn more, read the Mozilla Privacy Policy.

When you donate to Mozilla via a third party like PayPal or Stripe, those organizations also collect user data."

**NEW**: (add) (yes, it's very long, that's fine)

"When you donate to the Mozilla Foundation, we receive personal information from you.  We use this data to acknowledge your donation, provide you with donation receipts, and correspond with you through newsletters or email. You can read more about what information we receive, the purposes we use that information for,  and how we handle it in our [Privacy Policy](https://www.mozilla.org/privacy/).

We work hard to protect your information.  We believe in, and practice, multi-layered security controls and practices, including both technical and organizational methods.  We have agreements with third parties and have adopted other security measures to protect against the loss, misuse and/or unauthorized alteration of the information under our control or under the control of our service providers. The vendors receiving your information are contractually obligated to handle the data in ways that are approved by Mozilla. The vendors we use to send emails or other marketing materials to you aren’t permitted to use your information for their own direct marketing purposes.   They also aren’t allowed to share your data with anyone else for direct marketing purposes.  In addition, we will keep your personal data only for as long as we need it to provide you services, manage our business or as required by law or contract.  You can find more information in the [Privacy Policy](https://www.mozilla.org/privacy/) section titled _“What else should you know?_   

Except as disclosed in our [Privacy Policy](https://www.mozilla.org/privacy/), we do not share any personal data unless you expressly agree that we may do so. More specific information is available in our Privacy Policy in the section titled _“When do we share your information with others?"_

Finally, when you donate to Mozilla through a third party like [PayPal](https://www.paypal.com/webapps/mpp/ua/privacy-full) or [Stripe](https://stripe.com/us/privacy/), those organizations also collect your data.  Their collection and use of your data is governed by their respective privacy policies.

**Comment by TheoChevalier** [comment]
This is now live
