### ISSUE TITLE
Should we start splitting up docs?

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#207]
@adamlofting @alicoding @ScottDowne I love that we have documentation in our repo! However the README file seems to be getting a bit unwieldy. Could we start moving the docs in the README into separate files in a `docs/` directory?

**Comment by adamlofting** [comment]
Fine with me, so long as we link from the root. 

Lower priority though. Scrolling really isn't too hard :smile:

**Comment by ScottDowne** [comment]
I wouldn't mind taking a pass on our docs and see if we can optimize them without losing content first.

**Comment by ScottDowne** [comment]
I totally want to push this.

**Comment by jbuck** [comment]
Yeah we're gonna do this
