### ISSUE TITLE
Thunderbird download banner is broken, "&test=" GET conflict.

### ISSUE THREAD

**Issue by Sancus** [mozilla/donate.mozilla.org#2071]
It looks like you guys started using "test" for the GET variable for an a-b-c test, unfortunately that's the one that Thunderbird was using for "tbdownload" as well. This results in the donate URL sometimes redirecting to things like `https://donate.mozilla.org/en-US/thunderbird/?utm_source=thunderbird.net&utm_medium=referral&utm_content=post_download&test=tbdownload&test=no-img` which produces a page with no banner at the top. Here was the original PR for TB: https://github.com/mozilla/donate.mozilla.org/pull/2039/files#diff-7018dfc2ff7641275e2f5d96b0788369

If "test" is likely to be used again in this manner it seems most reasonable to just rename the Thunderbird get variable, I can easily change it on our side as well. Otherwise it's likely this will reoccur when someone else forgets.

**Comment by alanmoo** [comment]
Ah, sorry about that! Where does your testing query string get injected? We're running Traffic Cop [here](https://github.com/mozilla/donate.mozilla.org/blob/gh-2066/assets/js/ab-tests.js#L12), so I didn't think to check elsewhere for Thunderbird. (Also, @ScottDowne, who has been more familiar with the donate repo, is no longer at MoFo so apologies for the growing pains)

**Comment by alanmoo** [comment]
After some further digging, we've been running tests using that query param since [June](https://github.com/mozilla/donate.mozilla.org/commit/65843b8a8f4025499b756afb197a1a6cac4e2337). I also can't seem to easily change the name of the parameter for some reason. If it's easy enough for to do so on your side, can you resolve this with that approach for now? Next time we do a test I'll encourage namespacing.

**Comment by alanmoo** [comment]
Another update: The reason I can't change it is #2072, but I unfortunately don't have anyone to work on that right now.

**Comment by Sancus** [comment]
That's OK, it's a [1 line change for us](https://github.com/thundernest/thunderbird-website/blob/master/helper.py#L303), we just set it on download hrefs only on thunderbird.net.

In the donate code, all lines in `/src/pages/thunderbird/about.js` referencing `this.props.test` should be changed. I assume this.props is automatically populated with any get variables? Not super familiar with node/react.

I suggest we just use `?tbdownload=tbdownload`... we could just use `?tbdownload=true` , but https://github.com/mozilla/donate.mozilla.org/blob/master/src/pages/thunderbird/about.js#L35 adds the contents of the variable as a class to that element... not exactly sure why that's needed, so it could possibly be just removed. I don't see any styling for a 'tbdownload' class.

**Comment by mkmelin** [comment]
How about using &source=download-page or something - so that it's extensible for other use cases?

**Comment by Sancus** [comment]
> How about using &source=download-page or something - so that it's extensible for other use cases?

Well the variable determines whether the banner and 'thanks for downloading' text appears or not, that's all it does.. it doesn't imply anything about a source. That's covered by the utm variables, which are separate. I was preserving the name because I'm not sure if the class is used for anything. I do think we should keep "tb" in the name for name spacing reasons. I don't think we should try to predict future use cases though, it's not hard to add new variables.

**Comment by Sancus** [comment]
Ya sorry I was confused and thought @alanmoo was gonna fix this on the donate side, I missed the assignment change. I have a PR up to fix this here: https://github.com/mozilla/donate.mozilla.org/pull/2078

Once it goes live on donate.mozilla.org, we can modify thunderbird.net, which will only take a few minutes to do.

**Comment by alanmoo** [comment]
The update for this has been deployed.

**Comment by Sancus** [comment]
Thanks. This is also fixed on our side.
