### ISSUE TITLE
More clearly indicate that monthly donations are monthly

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#2074]
We want to make sure donors are aware that they're donating monthly. Let's add the appropriate indications when the "monthly" radio button is selected.

![image](https://user-images.githubusercontent.com/1682681/46496742-cf5a3080-c7e6-11e8-9cc6-a901f1f6052a.png)
(Add the text inside each of the fields, not just the one)

Make sure to build this such that it can be localized.

**Comment by alanmoo** [comment]
Still some questions about design- this will be updated when ready.

**Comment by mmmavis** [comment]
@alanmoo in terms of text alignment, do you know if we want to

1. center align `$5` with the button and align `per month` to the right of `$5`?
2. OR make `$5` and `per month` one block and center align it?

**Comment by alanmoo** [comment]
2 sounds easier/more flexible. Go with that.

**Comment by alanmoo** [comment]
Good question, Theo. @jessevondoom?

**Comment by alanmoo** [comment]
This landed!
