### ISSUE TITLE
Update text on homepage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#2075]
`Your payment details will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla. Monthly donations are charged each month on the same day that you donate today, and will continue until you cancel. To cancel, email us at donate@mozilla.org. Other ways to give: Wire Transfer or SEPA | Check`

adds the phrase `We are able to provide refunds up to one year after a donation is processed.` in the middle

`... To cancel, email us at donate@mozilla.org. We are able to provide refunds up to one year after a donation is processed. Other ...`

(Keep in mind localization, this may need to be a new string entirely. @TheoChevalier can help with that)

**Comment by TheoChevalier** [comment]
I’m going to steal this if you don’t mind, as this primarily impacts l10n and I will probably need to do some cleaning…
