### ISSUE TITLE
Pass last 4 digits of credit card from Stripe to Basket

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#2076]
Basket isn't actually ready to accept this yet, but we should get it queued up once it is. We eventually want to be able to use those last 4 digits in email receipts.

**Comment by desiree-mofo** [comment]
@alanmoo - pls make sure you get this on the radar for the CRM team to add the field in Salesforce as well so we can make sure this is available for receipts, which are either sent from Marketing Cloud or Salesforce directly

**Comment by desiree-mofo** [comment]
@stephaniemcv - cc:ing you on this

**Comment by stephaniemcv** [comment]
Can I add this to the project I submitted "2018 Q3 New Fields for Donation Infrastructure", that would increase the fields I requested from 4 to 5.
