### ISSUE TITLE
Need access to the donate@mozilla.org inbox

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate.mozilla.org#2081]
To finish our Desk.com migration we need to start forwarding donate@ to Service Cloud from Desk.com. I had access a long time ago, but I stopped accessing due to all the email forwarding into Desk.com and now I can't remember how to get in.

**Comment by cadecairos** [comment]
The login process is pretty weird. I had to log in at https://webmaker.desk.com/login/new and then manually change the URL to https://webmaker.desk.com/agent (because after logging in it says "Access Denied"

**Comment by cadecairos** [comment]
I don't appear to have any admin rights

**Comment by cadecairos** [comment]
@stephaniemcv did you need access to desk, or to the Google Group?

**Comment by stephaniemcv** [comment]
To the Google Group. Apologies for being as clear as mud.

**Comment by cadecairos** [comment]
I don't seem to have access to that Google Group. You'll need to get in touch with the Service Desk to find out who's the admin.

**Comment by stephaniemcv** [comment]
Ok, will do!
