### ISSUE TITLE
Ensure string is always visible

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#2082]
`We are able to provide refunds up to one year after a donation is processed.` Should be visible even if the user is only donating one time, not hidden behind the monthly radio item as it currently is.

**Comment by TheoChevalier** [comment]
Woops, didn’t get that! This should be fixed now with https://github.com/mozilla/donate.mozilla.org/commit/bc7c494a27d183069e3053792f38034d075cab2e
