### ISSUE TITLE
Remove Paypal for Singaporean dollars

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2125]
Getting reports from donors in Singapore that their paypal attempts are failing.  We should just remove this option, it's apparently a conflict between PayPal and singaporean authorities.  Hopefully an easy fix, per Chris?  

![image](https://user-images.githubusercontent.com/23637882/49304312-f86f0880-f499-11e8-80c8-f25c80fcc727.png)

**Comment by TheoChevalier** [comment]
Hm, I remember we were wondering if SGD had been forgotten or if there was a specific reason, seems like the latter… 
It’s been added in https://github.com/mozilla/donate.mozilla.org/issues/2053 I can fix this shortly

**Comment by TheoChevalier** [comment]
Should be live in a few minutes
