### ISSUE TITLE
April 2019 updates to donate pages (timely) for where to send checks

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2143]
As of April 15th, we're changing up how we process check donations.  Checks will be sent to Merkle response management group in DC for processing and acknowledgment, so we need to change (for both Thunderbird and Mozilla) our postal address on the website.  A total of three changes -- 2 Moz and 1 T-bird (because T-bird does not have a "ways to give" page).  

1) on the Mozilla ways to give page, https://donate.mozilla.org/en-US/ways-to-give, in the "Check (via postal service)" section.  Please replace ...

331 E. Evelyn Ave
Mountain View, CA 94041
USA

...with ...

PO Box 98223
Washington DC  20090-8223
USA

 2) On the Mozilla FAQ page, https://donate.mozilla.org/en-US/faq#item_4 ...
a) please add "(Updated April 2019)" to the section header of "Where do I send a check?"
b) same address swap as above ... replace ...

331 E. Evelyn Ave
Mountain View, CA 94041
USA

...with ...

PO Box 98223
Washington DC  20090-8223
USA

3. On the Thunderbird FAQ page, https://donate.mozilla.org/en-US/thunderbird/faq#item_4 ...

same address swap as above ... replace ...

331 E. Evelyn Ave
Mountain View, CA 94041
USA

...with ...

PO Box 98223
Washington DC  20090-8223
USA

...all other information there remains the same.

Ideally, these changes will go live on Friday, April 12th or Monday, April 15th.

Some checks are inevitably going to continue to land in the MTV office, and we have a procedure designed for that.  However, we do want to get the website updated as close as possible to our cutover date for Merkle, which is April 15th.

These changes should be carried over to localized pages as well; however, this work is low priority.  We receive very few checks from foreign donors.

**Comment by TheoChevalier** [comment]
> These changes should be carried over to localized pages as well; however, this work is low priority. We receive very few checks from foreign donors.

Those addresses are not exposed to localization (partly for that very use case), so updating English will update all locales as well :)

I can get a PR lined up, and then hit merge/deploy at the most appropriate time

**Comment by TheoChevalier** [comment]
Merged the new string "(Updated April 2019)" here, so that it’s being translated: https://github.com/mozilla/donate.mozilla.org/pull/2144

Pending PR to be merged when it’s time: https://github.com/mozilla/donate.mozilla.org/pull/2145

**Comment by TheoChevalier** [comment]
This is live :)

**Comment by alanmoo** [comment]
Thanks, Theo.
