### ISSUE TITLE
Add Charity Navigator and Guidestar seals to our donate page (timely)

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2146]
We've recently earned a four-star (the highest) rating from Charity Navigator, and later today shuld have Gold from Guidestar later today (we're currently at Silver level).

I'd like to get these graphics up on our donate page (ALL languages - no localization needed) as soon as possible, but no later than Friday April 26 when we launch our big post-IHR fundraising campaign.  This will provide a critical boost for our H1 OKR 2.1 around unrestricted donations.

Kristina has mocked up a design ("Donate 02") in redpen here: https://redpen.io/xj1a12801a7580aed1 .

Charity Navigator four-star logos can be found here: https://www.charitynavigator.org/index.cfm?bay=content.view&cpid=138#.VDa8M_ldXX9 .

Pasting in the guidestar silver logo below for placement purposes -- later today I should be able to add the Gold one for realz.

![image](https://user-images.githubusercontent.com/23637882/56431473-cb2fc500-6297-11e9-835b-60df335bd58d.png)

**Comment by mtochi** [comment]
Hi, I would love to work on this issue.

**Comment by alanmoo** [comment]
Hi @mtochi, thanks for the interest. You're welcome to open a PR for this over the weekend if you don't need any help, but if it's not the right approach or needs more work, someone on staff is going to have to take it over during the week since this needs to be deployed on a short timeframe.

**Comment by alanmoo** [comment]
@WillatMozFdn where are we on the gold status?

**Comment by WillatMozFdn** [comment]
Goal status is achieved.  Here's the logo we should use: https://www.guidestar.org/App_Themes/MainSite2/images/PUT_Seal_Images/put-gold2019-seal.png .

Guidestar logo should be clickable and linked -- in new window or tab -- to https://www.guidestar.org/profile/20-0097189 .

Charity Navigator four-star logo (same thing -- in new window or tab please) -- to https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=16300 .

thanks!

**Comment by kristinashu** [comment]
@mmmavis here are the two seals at size:
![seal-charity-navigator](https://user-images.githubusercontent.com/1068783/56696338-6366e900-66a0-11e9-8696-b46c88aa8e8f.png)
![seal-gold-guidestar](https://user-images.githubusercontent.com/1068783/56696339-6366e900-66a0-11e9-8ab6-083694706404.png)

The comp has been updated slightly and approved by Will in slack https://redpen.io/xj1a12801a7580aed1.

**Comment by WillatMozFdn** [comment]
CLOSED, WORK IS DONE, THANKS!
