### ISSUE TITLE
Create a list of questions for the German community

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#215]
We want to create a more localized donation experience for DE donors.
We need a list of questions we can pose to the Germany Mozillian community to help us understand giving and giving culture for DE speakers, such as:

* What month of the year is most popular for making donations?
* Do Germans prefer 1x or recurring giving? If recurring, do they prefer to give weekly? Monthly?
* How do Germans like to give online -- using Mastercard? Visa? AMEX? PayPal? Bank transfer? in-person? Personal check? What other ways?

Please add questions @alicoding @adamlofting

**Comment by adamlofting** [comment]
As well as:
> Do Germans prefer 1x or recurring giving? If recurring, do they prefer to give weekly? Monthly?

I'd also suggest asking 
* How do the main charities / NGOs ask for gifts. Yearly, Monthly, One-off?

(On the grounds that 'how people say they will give', often doesn't match up with how fundraisers find people give when they test it.)

And

* If Bank Transfer isn't available, would people use PayPal? 

(To try and glimpse if we're losing a lot or a little by missing Bank Transfer)

**Comment by alicoding** [comment]
I'm removing Aug 28 milestone off of this one. Please assign future milestone or close the ticket if it has been resolved.

**Comment by jbuck** [comment]
Our DE-specific campaign is finished
