### ISSUE TITLE
Update to donate FAQ (EN-us only)

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2151]
Very last item in our en-US FAQ needs updating please.

OLD

I’m in the United States. Can I support Mozilla through the Amazon Smile Program?

Yes! You can direct a small portion of what you spend on Amazon.com to support Mozilla by visiting this link to choose Mozilla in the Amazon Smile program. Please remember to initiate all your purchases by starting at smile.amazon.com. (Unfortunately, this program is limited to U.S. residents only.)

**New:**

I’m in the United States. Can I support Mozilla through eBay for Charity or the Amazon Smile Program?

Yes! The Mozilla Foundation is enrolled in both [eBay for Charity](https://www.charity.ebay.com/charity/Mozilla-Foundation/1409428) and the [Amazon Smile Program.](https://smile.amazon.com/ch/20-0097189)  On eBay, you can add us as your favorite charity, shop for items where a portion of the sale benefits the Mozilla Foundation, or sell your own items and direct a percentage of the sales price to benefit the Mozilla Foundation.  On Amazon.com, please remember to initiate all your purchases by starting at [smile.amazon.com](smile.amazon.com).

**Comment by alanmoo** [comment]
@TheoChevalier If this is just en-US, I'm not positive what approach you might want to take here. Can you handle this one?

**Comment by TheoChevalier** [comment]
Sure! Going to add a PR soon (Pretty sure we simply hardcoded this one in the template)

**Comment by TheoChevalier** [comment]
https://donate.mofostaging.net/en-US/faq#item_amazon looks good, deploying to prod
