### ISSUE TITLE
Add request for email addresses in memo field of checks to non-US pages

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2154]
For donors in the US, on both the "Ways to give" page and the FAQ item #4, we do ask that they write their email address on the memo field of the check -- that gives us a unique identifier to add the donation to the right person in Salesforce.  This phrase after the mailing address ("... and please include your email address on the memo line.") is unfortunately NOT present in the ways to give/FAQs for other locales, i.e. ... 

https://donate.mozilla.org/en-GB/faq#item_4
https://donate.mozilla.org/en-gb/ways-to-give#check

**We need to (please) go ahead and add that for all other locales, on both pages.**  We still do get checks from other locales, and having their email address will save us money on postage for a thank you letter (with an email, we can acknowledge electronically instead) AND help us better track our donors.

For non-EN locales, we'll need some verbage for this in different languages.  Google Translate should be fine for this if volunteer localizers are not available.

**Comment by alanmoo** [comment]
@TheoChevalier think you can take care of this?

**Comment by WillatMozFdn** [comment]
also @alanmoo can we add Stephanie Lowry to this d.m.o repository?  She's ready to start submitting/handling smaller issues like this that she finds.  Thanks!!

**Comment by alanmoo** [comment]
It's a public repo, as long as she has a github account she can file issues.

**Comment by TheoChevalier** [comment]
Sure I can handle that, but note that we decided to specifically show this message to en-US and en-CA only, because they have memo lines on checks, which is not necessarily the case elsewhere (French chèques or UK checks don’t have memo lines, for instance).

@WillatMozFdn What do we want to ask people instead, when they don’t have that field? Write the email address on the back?

**Comment by WillatMozFdn** [comment]
How about, "please include a note with your email address" -- ??  Would
that be weird?

 - W

**Comment by TheoChevalier** [comment]
That should be fine, that’s what we are already doing for Thunderbird checks outside US/Canada:
>Please send a check <strong>with a separate note marked “Thunderbird”</strong>, and payable (payee) to “Mozilla Foundation”

**Comment by TheoChevalier** [comment]
(Didn’t mean to close this)

Should we also mention the payable, like for Thunderbird? We currently don’t say anything.

So, proposed string:

>Please send a check <strong>with a separate note including your email address</strong>, and payable (payee) to “Mozilla Foundation”

**Comment by WillatMozFdn** [comment]
Is there a way I can add Stephanie Lowry as a CC to this bug?  Anyone know?

**Comment by alanmoo** [comment]
@stephanielowry

CC'd :)

**Comment by TheoChevalier** [comment]
This is now live, and localized in most major locales
