### ISSUE TITLE
Turn off webmaker/sawmill-mailroom receipts completely

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2156]
The SFMC journey-based receipts have been live for several months now for Paypal donations, and working well.  With a simple change I can enable them for Stripe donations as well, so we can finally retire the old system that sends receipts for Stripe transactions.

This will require careful timing - expanding the SFMC journey as we turn off the old system - so that we don't miss sending a receipt, or duplicate with two thank-you messages.

Suggest we plan to implement Wednesday 6/26 or Friday 6/28 when fundraising emails will not be actively sending.

**Comment by alanmoo** [comment]
I know virtually nothing about this; @patjouk do you understand the scope of this?

**Comment by patjouk** [comment]
I don't have more context but my guess is that we should remove the [related worker in sawmill](https://github.com/mozilla/sawmill), as [I did here](https://github.com/mozilla/sawmill/pull/89/files).

**Comment by WillatMozFdn** [comment]
@patjouk let's plan on making the changeover sometime the week of July 15th.  I'm on PTO most of next week to take care of some family stuff out in Santa Barbara, and then ALL of the following week (Netroots Nation in Philadelphia, my annual volunteer commitment to progressive politics.)  Sound good?  That should give you enough time to figure out the right piece of duct tape or baling wire to yank out. :-)

**Comment by patjouk** [comment]
That's sound perfect. Thanks for your patience!

**Comment by patjouk** [comment]
Ok, I think I got it. We need to:
- Delete the worker and email templates from sawmill (PR opened mozilla/sawmill#98),
- Remove the sawmill webhook from stripe staging and prod accounts.
@alanmoo Can you confirm?

**Comment by alanmoo** [comment]
This makes sense to me; I don't actually have any experience with this. If you want more concrete confirmation, you may be able to check in with Scott or JBuck.

**Comment by patjouk** [comment]
We did that Today. @WillatMozFdn can you confirm we're good and that I can delete the sawmill webhook on stripe?

**Comment by WillatMozFdn** [comment]
Yes, we're all good, donation receipts seem to be flowing normally, for both stripe and paypal now.  (And in all languages, both Moz and t-bird.)

**Comment by patjouk** [comment]
Done!
