### ISSUE TITLE
Confirm 'go live' dates for snippet: DE

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#216]
I need to confirm what circulation we have for our fundraising campaign for DE snippet (desktop + FF for Android). Also tile?

**Comment by valianttry** [comment]
Snippet allocation for DE snippet (from Chelsea Novak in Community Engagement):
September: 28 million impressions
October: 28 million impressions

**Comment by edrushka** [comment]
Still planning to start the week of Sept 28.

**Comment by valianttry** [comment]
Confirmed: Go Live is likely October 4 at earliest, possibly October 5.

The First snippet will be the highest performing from 2014 campaign in order to collect ~1000 donations and establish a baseline of data.

**Comment by valianttry** [comment]
Upcoming DE campaigns by Foundation:

now - Oct 1: Data retention campaign
(Oct 1 - Data retention campaign comes down)

October 5: Fundraising begins (launch Snippet #1)
October 5 - 7:

    Running last year's best performer to get ~1000 donations for benchmarking
    Monitoring social media for any negative reaction (humanitarian crisis reaction)

October 8: Launch test Snippet #2 with new back-end platform (Stripe vs. PayPal)
