### ISSUE TITLE
Changes to verbage on /donate page (all languages)

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2163]
Hi all, two changes we need to make to the "small print" on the right-hand side of the donate page, in all languages.  These have been cleared by Legal team (Abigail).

1) Delete the sentence "We are able to provide refunds up to one year after a donation is processed."

(Our refund policy will now be included on emailed receipts ... and perhaps, pending Abigail's research, in mailed acknowledgment letters as well.  Both those are outside the scope of this request.)

2) Move the "Other ways to donate" sentence into its own separate paragraph, and apply bold styling to it (leaving all the links as-is, of course).  So the whole block should now read as follows:

Your payment details will be processed by Stripe (for credit/debit cards) or Paypal, and a record of your donation will be stored by Mozilla. 

**Other ways to give: Wire Transfer or SEPA | Check**

Problems donating? Visit our FAQ for answers to most common questions. Still have problems? Send us an email.

Contributions go to the Mozilla Foundation, a 501(c)(3) organization based in Mountain View, California, to be used in its discretion for its charitable purposes. They are tax-deductible in the U.S. to the fullest extent permitted by law.

(Context on this is that it's pretty hard to find those other ways to give right now, buried in the middle of the small print there, so we want to give them a little more visibility.)

**Comment by TheoChevalier** [comment]
![image](https://user-images.githubusercontent.com/1294206/65283865-0298eb00-db30-11e9-94f6-3d93ebd355c9.png)

Does this work for you @WillatMozFdn ?

**Comment by WillatMozFdn** [comment]
yes, perfectly.  Thank you Theo!

**Comment by alanmoo** [comment]
@TheoChevalier Are these strings going to be re-used for the new site or will we have to redo this before it launches?

**Comment by TheoChevalier** [comment]
This PR has actually no impact on localization (no need to translate/retranslate anything), we will just need to port the new formatting over to the new website. 

Details here: https://github.com/mozilla/donate.mozilla.org/commit/022cddbdde8769f99eaf264d0160f1db4a57685e

**Comment by WillatMozFdn** [comment]
@alanmoo Theo is right on that one - no new strings.  These newer strings should be the version we port over to the new site ... but also, we'll need to change "Stripe" there (obvs) in all languages to Braintree ... and hoping to be adding a Bitcoin link in the "Other Ways" section sometime soon too (still pending but we're very close to executing an agreement with them.)

**Comment by TheoChevalier** [comment]
To clarify, there still **could have** been new strings here, even without a copy update. We were just lucky they were already split in a way that allowed us to just remove that sentence, and wrap the other one separately

**Comment by TheoChevalier** [comment]
Looks like PR #2164 didn’t get deployed to staging https://donate.mofostaging.net/en-US/
It works locally and the change is very simple, but promoting to prod without a last check on staging feels very wrong.

@cadecairos @patjouk Would you mind having a look?

**Comment by TheoChevalier** [comment]
Closing, as this has been deployed over the weekend
