### ISSUE TITLE
Delete incorrect SEPA/BACS fee information from donate Ways to Give (and, move a sentence up to reduce confusion)

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2167]
We've just found out that for quite some time that we've been very significantly over-stating fees for SEPA/BACS donations on our Ways to Give page at https://donate.mozilla.org/ways-to-give#wire .  Drats, but, easy to fix going forward.  

1) We need to fully **delete** the sentence "(All the donations via wire transfer are subject to a $5 USD charge imposed by Mozilla’s bank. Therefore, please keep this in mind when deciding to donate to us via wire transfer.)" (In all languages.)  We're not under any mandate to disclose transaction fees to our donors so this (rather discouraging) sentence can be fully removed.

2) Unrelated, but in the same section on the same page, let's move the statement "If your bank requests our physical address, it is 331 E. Evelyn Ave, Mountain View, CA 94041 USA." ... UP on the page, to immediately precede (and be a part of the same paragraph with) "Please remember that donations are deductible for U.S. income tax purposes only."  Reason for this is that where it is now, at least one donor has interpreted it as applying only to BACS ... which is incorrect.  It applies to all wire transfers, and so belongs at the top of that section.

**Comment by TheoChevalier** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/pull/2168

Fix will be live in ~10 mins: 
https://donate.mozilla.org/ways-to-give#wire
https://donate.mozilla.org/thunderbird/faq#item_2
