### ISSUE TITLE
Enable Bitcoin donations through BitPay

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2169]
We have a signed and sealed agreement with BitPay now, so let's move to the implementation stage.  Much work has already been done, but, last steps we need to accomplish:

- [ ] Final edits to hosted Bitpay page (Will)
- [x] add legalnotices@mozillafoundation.org as a user (Will or Chris) (Chris & Phia accomplished 10/10)
- [X] connect to our bank account for deposit (Will or Chris)
- [ ] test transactions from insiders, verify deposit (Will)
- [ ] edit Mozilla Wiki (Will and Kevin)
- [x] edit Ways to give and FAQ pages (Will and Theo)
- [x] edit main donate page (Will and Theo) PR: https://github.com/mozilla/donate.mozilla.org/pull/2170

**Comment by TheoChevalier** [comment]
Quick note on localization: those changes won’t be localized, as I plan to start localizing the new website tomorrow and put this one in read-only mode in Pontoon. We will need to port these changes over to the new stack, and localization will happen there instead

**Comment by TheoChevalier** [comment]
We’re live, closing
