### ISSUE TITLE
Change address & instructions for mailing in a donation check

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2172]
1. Two places we need to change both instructions and the address:

https://donate.mozilla.org/faq#item_4
https://donate.mozilla.org/ways-to-give#check

Old instructions (please delete):
"Please send a check **including your email address on the memo line**, and payable (payee) to “Mozilla Foundation”

New instructions (please add):
"Please send a check **including your email address on the memo line**, and payable (payee) to “Mozilla Foundation."  Please note that the Mozilla Foundation can only accept checks in US dollars drawn on a US bank.  Please do **not** send cash.”

Old address (please delete):
Mozilla Foundation
PO Box 98223
Washington DC 20090-8223
USA

New Address (please add):
Mozilla Foundation attn: Donor Care
2 Harrison Street, #175
San Francisco CA 94105
USA

2. For Thunderbird, on https://donate.mozilla.org/thunderbird/faq#item_4 ... please leave the instructions the same, for now, but change the address to be:

Mozilla Foundation attn: Thunderbird Donor Care
2 Harrison Street, #175
San Francisco CA 94105
USA

@TheoChevalier can we please put the new strings in the new instructions out for localization and then implementation  (on localized pages) as they become available?

**Comment by TheoChevalier** [comment]
Thanks Will, updates are here: https://github.com/mozilla/donate.mozilla.org/pull/2173

I figured you also wanted to update `(Updated April 2019)` into `(Updated November 2019)`

I’ve disabled this project on Pontoon weeks ago, as community focus must remain on the new stack. We shouldn’t ask people to translate this for just the few hours/days it will stay online, then ask them to translate again on the new stack.

For the avoidance of the doubt, the updated content **will** appear right away on all localized pages, it will just appear untranslated. We will localize this properly on the new stack.

**Comment by TheoChevalier** [comment]
Changes are live, closing!
