### ISSUE TITLE
Design wireframes for donation form variations

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#227]
@lovegushwa will design some "lego brick" variations this heartbeat. Jordan, please post your iterations here so @ScottDowne and @alicoding can see what you're thinking.

**Comment by lovegushwa** [comment]
@adamlofting  @ScottDowne @valianttry @edrushka @alicoding @mmmavis 
Good morning everyone. Please checkout and comment on the 1st draft of Donor Funnel wire-frames for Germany: https://redpen.io/p/tm0b6abe8e72e320c8

I'm looking to refine these ideas and create new variations to test. Also, after comments will work through mobile versions.

**Comment by lovegushwa** [comment]
@adamlofting Can you explain these wireframes again? Think there is a great idea here but I can't remember exactly what we discussed.

![_img_20150806_121115](https://cloud.githubusercontent.com/assets/12228435/9446006/171e0212-4a44-11e5-8fad-9b9ac1a0d99e.jpg)

**Comment by adamlofting** [comment]
> @adamlofting Can you explain these wireframes again? Think there is a great idea here but I can't remember exactly what we discussed.

Sure :+1: 

Currently, we have a much higher conversion rate for a colder audience responding to our ask on the snippet than we do for many referrals from our closer more engaged audienced.

See these two flows as an example.

![snippetconversionmozorg](https://cloud.githubusercontent.com/assets/1901816/9464634/590b94d0-4b1d-11e5-91ce-e91d9bbd813a.jpg)

When comparing the two flows above, the biggest difference from a fundraising point of view, is that the second flow misses out the text where we explain to the potential donor why they should donate (the 'case for support' in the sketch above).

In some situations where we have links or asks on sites like Mozilla.org, we don't have space to include the same 'ask' as we do on the snippet, so I'm suggesting that for these users we offer a variation of the landing page that includes a case for support on it:

![snippetconversionmozorg copy](https://cloud.githubusercontent.com/assets/1901816/9464635/593d1866-4b1d-11e5-9aec-facadc1217b3.jpg)

n.b. Snippet users would still use the existing flow, as they don't need further content on the page that might be distracting.

**Comment by lovegushwa** [comment]
Hi @adamlofting  @valianttry 

Please checkout the revised wire-frames, I'm shooting to wrap these up by Friday so please leave feedback by tomorrow noon if possible so I can knock out a revised version.
https://redpen.io/p/xjf27a709ae42c6392

Also check out an older version here if you want to see a bit of prior discussion.
https://redpen.io/p/tm0b6abe8e72e320c8

**Comment by lovegushwa** [comment]
@adamlofting brilliant point above about a customized landing page. I will add this to the wireframes.

**Comment by valianttry** [comment]
@lovegushwa do you plan to show the form in another language, e.g. DE soon?

**Comment by edrushka** [comment]
We can use placeholder text from our current German form. Translations for any additional strings will be ready Sept 21.

**Comment by valianttry** [comment]
FYI I have filed a legal bug to get final, approved opt-in language for our email signup form:
https://bugzilla.mozilla.org/show_bug.cgi?id=1199414

**Comment by lovegushwa** [comment]
@valianttry @edrushka @adamlofting 
Any possibility of crafting a single click opt-in ? (both privacy bit with email signup opt-in in one sentence).
It seems like it's not super useful if people give you a name and email address but don't want any email. Why not agree to both with one click?

![screen shot 2015-08-27 at 1 20 27 pm](https://cloud.githubusercontent.com/assets/12228435/9532105/6abbda4e-4cbe-11e5-8ce1-d0836bb8031a.png)

**Comment by edrushka** [comment]
@lovegushwa I'm not clear on where this popup would appear in the flow. On your image above, it looks like it's over the snippet? Can you clarify?

**Comment by lovegushwa** [comment]
@adamlofting @valianttry @ScottDowne @edrushka @alicoding @mmmavis

Check out the final donation form variations (for Germany). Please leave your feedback about which version we should try + final tweaks and I'll build them into the localized versions next week.

https://redpen.io/p/ah1d913b7edf5c17ed

CC @cassiemc @flukeout

**Comment by cassiemc** [comment]
Cool, some great iterations! Left a bit of feedback and some ideas. The intention is to test multiple versions, right @lovegushwa?

**Comment by cassiemc** [comment]
(also, did you mean to close this @lovegushwa?)

**Comment by lovegushwa** [comment]
yes :)
