### ISSUE TITLE
Make snippet graphic decisions for Germany campaign

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#228]
We need to consider what snippet designs we want to run in Germany, and whether or not we need some new designs.

@adamlofting do we have any data on which EOY snippets worked best last year? Did we test design variations with the same copy?

@valianttry what are you thinking? Static icons? Animated icons? Donation buttons right in the snippet?

cc @lovegushwa

**Comment by lovegushwa** [comment]
@adamlofting @valianttry 
I'm interested in hearing hunches about what kind of snippet will perform best. What do we want to test and what should I put time towards for Germany.

I'm proposing a few categories, for the sake of discussion. Please add to, modify or delete:

- Static Icon (the kind of snippet seen most often)
- Animated Icon (made last year, would like to do, is it worth it because these will take time?)
- Banner (wiki style)
- Big Impact (changing the background to an image or color)
- Hybrid Banner/Impact (last years big performer)
- Hybrid Banner/Impact/Icon (has this been tried?)
- Video (yes these exist, not for Germany but maybe?)
- Game (impractical but would be rad)

**Comment by valianttry** [comment]
@lovegushwa animated icon beats static icon. But pulling the "amount" buttons beat the animated icon significantly (this is why we abandoned the animated icons last year, despite their adorableness). We were only able to execute the "select amount" buttons on the English version of snippet last year. This year we should execute on our localized snippets as well. Here is a great post by Adam describing our non-EN snippets last year, and the [limited] amount of testing we were able to do:
https://fundraising.mozilla.org/when-testing-meets-localization/

And this describes the winning snippet (in EN): https://fundraising.mozilla.org/saving-the-best-for-last/

A "disruptive" snippet experience, for instance a snippet with a completely different background color, should be used very sparingly (e.g. the final days / hours of the campaign, or if we want to follow Wikimedia's lead -- launch day!)

I am intrigued by your idea of using a "banner" -- do you see this as being "stuck" at the very top of the snippet window, leaving the search bar and essential snippet text intact? Or do you see the banner placed where an icon/text normally goes on the snippet (below search bar)? A banner might be interesting!

**Comment by adamlofting** [comment]
> We were only able to execute the "select amount" buttons on the English version of snippet last year. This year we should execute on our localized snippets as well.

Just a small correction on this one. We did roll out localized version of the donation amount buttons on the snippet mid Dec and they worked well (a screenshot of the DE version is in that blog post)

**Comment by adamlofting** [comment]
> @adamlofting do we have any data on which EOY snippets worked best last year? Did we test design variations with the same copy?

There's not a huge amount of info in here related to the designs (and I don't have quick access to screenshots of all the variants... we should take time to record them this year) but this is the data for all the snippets that ran during EOY 2014: https://docs.google.com/spreadsheets/d/1ucVHxkkBXsChInDr1YK7FhWXzQKksskyrLZ6yso638E/edit#gid=9

Across the top you can see the snippet IDs, and if you scroll down to row 81 you can see the average results for each snippet. 

Mostly though, we tested copy.

**Comment by edrushka** [comment]
Update: @lovegushwa spent this heartbeat on wireframes and will tackle snippet design next heartbeat. Meeting with Michelle Thorne and Barbara Hueppe on Monday to discuss snippet concepts specific to German culture. Moving this to the Sept 11 milestone.

**Comment by edrushka** [comment]
@lovegushwa can you update this when you have a sec. If I remember correctly, we decided not to create any new/special German snippet icons. Instead, we can re-use the envelope, the coin etc.

**Comment by alicoding** [comment]
Can you please move this to the next milestone or close the ticket if it has been resolved?

**Comment by edrushka** [comment]
@valianttry do we need to dig up the bouncing coin and envelope, or does the MoCo team take care of that?

**Comment by edrushka** [comment]
[This bug] (https://bugzilla.mozilla.org/show_bug.cgi?id=1076019) contains both the static and animated snippet files including:
- plain coin
- 3 coin
- 5 coin
- lock

**Comment by ScottDowne** [comment]
I think we can close this now. Snippet is designed and developed like this: http://scottdowne.github.io/eoy-snippets/2015-snippet/

No icon needed.
