### ISSUE TITLE
Write a pitch for L10N community

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#234]
There are hundreds of Mozilla projects seeking help from our L10N community. We need to draft a short pitch for @alicoding to share about why FR deserves their attention :)

**Comment by edrushka** [comment]
@alicoding can you dig up an example of what this email should look like (can be from another project) and I'll craft one specifically for FR? Thanks!

**Comment by alicoding** [comment]
I don't think we've ever done this before, but the idea here is that we just want to make sure we cover this facts:

1. What is the project about
2. If they help us localize the app what will it help the project
3. How important this app to Mozilla
4. Any timeline or deadline or when is our launch

**Comment by edrushka** [comment]
What do you think of this, @alicoding 

Hello Mozilla localizers,

Thank you for continuing to support the Mozilla project. It’s because of you that we are able to help build the open web on a global scale.

We have a new and exciting localization project we hope you’ll consider helping us with: fundraising! 

Mozilla is a non-profit organization and we rely on contributions to promote openness, innovation and opportunity on the Internet in ways that will benefit everyone. Together, [we’ve accomplished a lot] (https://intangibleblog.files.wordpress.com/2015/03/fundraising-infographic-2014.png) over the past five years.

Now, we need your help to reach [our fundraising goals] (https://docs.google.com/document/d/1h97toJWErgYKv5w_Wpc2SdOQvEYWxCoH-SbpkZWjU70/edit) by the end of 2015.

Specifically, we’ll need help localizing:
- different variations of the snippet
- emails
- our donation forms
- our Facebook and Twitter posts
- our FAQ

The money we raise will enable Mozilla to continue current activities that support our mission,and will allow us to develop new programs that will support the Mozilla community, the open Internet and to increase web literacy.

[Learn more about fundraising at Mozilla] (http://fundraising.mozilla.org/), and please don’t hesitate to contact us if you have any questions [Ali, should they email back? contact us on Github? What is the best mechanism for this audience]?

**Comment by alicoding** [comment]
This is really good Erika! I think they will probably reply on the mailing
list itself but leaving a better way to communicate like github would also
be a good choice for seeing their interest in the project publicly

**Comment by edrushka** [comment]
email sent!
