### ISSUE TITLE
Finish brainstorming the January Thank You

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#235]
We brainstormed a lot of great ideas in San Francisco. Now we need to decide on one of them :)

Here's the pad: https://fundraising.etherpad.mozilla.org/FR-meetup-Session7

It seems like we were leaning towards a video, perhaps localized according to IP (if we can even do that). Does anyone have further thoughts?

@valianttry @rebsd @adamlofting @hpauljohnson @lovegushwa

**Comment by adamlofting** [comment]
Our email sign-ups are currently only in English, so that's simple re localization.

We'll add a DE list soon, and we'll be able to target those emails separately. Though we should think about whether a January email is right for them, as we'll be talking to them earlier in the year, and potentially not at all during EOY if we hit our targets.

**Comment by edrushka** [comment]
In my mind, that January Thank You was for the EOY push. Ideally we'd localize the email in our top non-US-EN languages, but I agree we might want to have a different strategy for the September Germany donors.

**Comment by valianttry** [comment]
+1 on a thank you strategy for Germany that is less robust than a video, but still more awesome than what we've done in the past. E.g... more than a text-only auto-reply. :crying_cat_face:

**Comment by adamlofting** [comment]
Just to clarify...

> Ideally we'd localize the email in our top non-US-EN languages

We only need to do this if we also start building email lists in those languages.

**Comment by edrushka** [comment]
Erika to follow up with Rainer to see if MoCo can help us with video.

**Comment by valianttry** [comment]
@adamlofting we are beginning to do advocacy in DE language, so I believe we can start  collecting DE optins for a limited email schedule.

**Comment by adamlofting** [comment]
> @adamlofting we are beginning to do advocacy in DE language, so I believe we can start collecting DE optins for a limited email schedule.

That's great news. Some initial work has been done on this as part of the donation pages, but this will also need to be built into the brief for the advocacy work this week (as that will be built in BSD).

**Comment by alicoding** [comment]
I'm removing Aug 28 milestone off of this one. Please assign another milestone or close the ticket if it has been resolved.

**Comment by edrushka** [comment]
Closing this and writing a proper design ticket.
