### ISSUE TITLE
Identify components of start-to-finish design experience

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#236]
First step in designing a comprehensive experience is to identify the different parts of the flow, and which of them we can control the look of. @lovegushwa can you take this one?

**Comment by lovegushwa** [comment]
@edrushka yep, good thinking. This can be done in parallel with wireframing the donation funnel.

**Comment by lovegushwa** [comment]
<img width="1055" alt="screen shot 2015-08-28 at 7 45 15 pm" src="https://cloud.githubusercontent.com/assets/12228435/9560211/63385d88-4dbd-11e5-8028-e106f3261c72.png">


The map above logs key points of the donation experience. At each point we can control:

- Composition
- Content
- Typography
- Color
- Button and form style
- Background (image or color)
- Animation


Ideally we will build and test the following experiences:
- Efficient / short step
- Guided / multi step
- Storytelling focus 
	"Here is the good we do with your money."
- Fun focus
	"You’re so cool, thank you!"
- Urgency focus
	"Give now, it’s serious, we need your help!"


In addition it would be great to develop and test snippet copy round the following issues:
- Net Neutrality
- Privacy
- Learning
- Product features and customization
- Product value
- Mozilla manifesto values
