### ISSUE TITLE
Plan domain name transition process

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#239]
Current donation pages live on sendto.m.o
donate.m.o currently redirects to sendto.m.o
intention is to use donate.m.o as canonical URL going forward

**Comment by jbuck** [comment]
I think for the Germany campaign we should run our donate.m.o side-by-side with BSD-hosted sendto.m.o. When we're confident in our platform, that's when we should change sendto.m.o to be a redirect to donate.m.o.

**Comment by adamlofting** [comment]
> I think for the Germany campaign we should run our donate.m.o side-by-side with BSD-hosted sendto.m.o. When we're confident in our platform, that's when we should change sendto.m.o to be a redirect to donate.m.o.

Possibly, but let's work on the implications of this WRT complexity of testing and not wanting to put donors into BSD if we don't have to.

Snippet is planning to run at 10% (not 100% so volume at a given moment in time shouldn't be crazy).

My inclination is to use the new form for DE traffic, but have the old one available as a back-up if something goes wrong.

**Comment by valianttry** [comment]
@jbuck is there a next step on this? Moved to next milestone. 

cc @adamlofting

**Comment by jbuck** [comment]
@valianttry I think on my part I should ensure that I have SSL certificates for donate.mozilla.org and sendto.mozilla.org and file bugs for MoCo IT to prepare for DNS transition. On @adamlofting's part I think we need to have some sort of a timeline of work. We discussed using client-side redirects to redirect specific pages from sendto.m.o on the call today, bit we should get a ticket open for what pages we need to redirect for the DE campaign, if any.

**Comment by adamlofting** [comment]
This is how I see us shipping the new forms:
- [ ] 1. Close P1s and setup Stripe Account (All)
- [ ] 2. Deploy project to donate.mofoprod.net (Any Engineer)
- [ ] 3. Test live donations via Stripe and Paypal (Fundraising Team QA)
- [ ] 4. Update DNS for donate.mozilla.org to point to new server (@jbuck)
- [ ] 5. Setup / Update all server monitoring (@jbuck)
- [ ] 6. BSD forms continue to operate at sendto.mozilla.org (info)
- [ ] 7. Switch to new DE snippet (euros version), which sends donors to dondate.mozilla.org (Fundraising Team in collaboration with MoCo team)
- [ ] 8. Monitor for several days (@jbuck @adamlofting)
- [ ] 9. Once happy with performance, setup front end redirects on all live BSD donation forms (Engineers)
- [ ] 10. Update any external links to BSD donation forms at source (e.g. @valianttry work with MoCo to update mozilla.org and tabzilla links)

Later 
- solve for switching off BSD forms with linked recurring gifts
- switch off BSD forms (after all other BSD cases are solved - e.g. petitions)

-- 

@jbuck @ScottDowne @alicoding @valianttry Please let me know if you spot any issues in this plan. 

Otherwise if it's OK, I'll file this list as a follow ticket / launch checklist.

**Comment by jbuck** [comment]
@adamlofting This sounds good to me!

**Comment by adamlofting** [comment]
Converted into #492
