### ISSUE TITLE
5 min presentation: Code Structure / Build & Deployment / Developer Experience

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#242]
For tech review on 24th Aug (mid-heartbeat)

> If you can explain your topic less than 5 minutes, even better.

> Your target audience are David, Simon, and an imaginary contributor who is looking at our project for the first time.

> Please use visuals. Systems Diagrams and Flow Charts are great. And, add these into the documentation before the call.

> How quickly we can explain what we've done (and why) is an indicator of how easy it is for a new engineer to get up to speed with the project.

**Comment by ScottDowne** [comment]
Most of this is about react, how we implemented it and why. What is different with our implementation compared to others and why ours is different. A bit about node. Correct?

It might be hard to drive the react sell home seeing how the form is not fully broken down into components yet. That is on me for this heartbeat, and I already started, so should be fine. (It doesn't leave much time to prep a presentation if I finish the react stuff Friday, though.)

**Comment by adamlofting** [comment]
Just some thoughts from me, about what I think would be useful to a dev looking at the project for the first time (even if some of this is still things we need to do):

1. We've used React for consistency with all MoFo projects (this is a huge improvement on where we were with BSD)
1. The repo has all the credentials needed to get started on local dev without blockers
1. Development flow is documented (or will be)
1. Most of the app is front-end code and pre-compiled at build time (for simplicity and performance)
1. We run a simple node server for some interaction with payment providers
1. We push as much of the payment process as possible out to the providers to reduce the amount of code we maintain
1. We've broken our forms into React components to reduce duplication of code. This will be especially useful as we A/B test more form variations in the future.
1. We've removed X, Y and Z which were bad in our old system
1. We have auto deploy to staging (we have staging! :stuck_out_tongue_closed_eyes: )
1. We have test coverage for X, Y, Z (also note what coverage we'll have before launch)
1. We use travis to check PRs
1. etc...

**Comment by alicoding** [comment]
@adamlofting I like that and at least there is no overlap with my presentation here :P

**Comment by ScottDowne** [comment]
Feels good to close this one.
