### ISSUE TITLE
Create thank you strategy for Germany campaign

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#258]
This ticket is specifically for the Sept/Oct German donors. We should have a specific strategy here, and it should be separate from the January EOY thank you #235.

We won't have time for a video, but we could do an email with some integrated bells and whistles. Any suggestions?

@adamlofting @valianttry @lovegushwa

**Comment by valianttry** [comment]
This might be a cool way to get the community involved -- maybe we can ask some Germany community members to hand-write a thank you and we'll show donors an image of the handwritten note on the thank you page. Or we can show a video of someone sealing the envelope, dropping it into a mailbox in Berlin or German town, then we have some animation of it opening to reveal a handwritten thank you (in DE of course). @adamlofting maybe George Roter could help put brain power to this as well?

**Comment by adamlofting** [comment]
> @adamlofting maybe George Roter could help put brain power to this as well?

Do you mean via the Participation team, or just picking George's brain WRT his work with EWB?

At a high level, the [Participation](https://wiki.mozilla.org/Participation) team exists to help us (any Mozilla team) build meaningful engagement with community rather than act as a gatekeeper to any community. I think it would make more sense to engage them at the level of 'how do we engage community in our fundraising work?' than the specific 'DE thank you message' level.

**Comment by lovegushwa** [comment]
@valianttry @adamlofting cool idea about localizing the German thank you note. Just thinking about criteria for the message, and that it would be great to develop the copy in tandem with the visual approach to maximize impact. 

- personal / heartfelt
- reaffirms contribution, what’s at stake
- memorable
- delight

CC @edrushka

**Comment by edrushka** [comment]
For reference, here is the Thank You email sent in January to people who donated in the EOY campaign: 
![screenshot 2015-08-19 10 54 07](https://cloud.githubusercontent.com/assets/4515662/9364447/3e65db1a-4661-11e5-955b-5ed4c291ffce.png)

**Comment by valianttry** [comment]
@adamlofting that's really helpful. I think I was stuck in the old community paradigm, and you shook me out of it just then.

**Comment by edrushka** [comment]
FYI: George, @rebsd and I had a great chat today about engaging the German community in our DE fundraising campaign. This would be in addition to whatever thank-you mechanism the FR team designs. More to come on this after the workshop in Toronto.

**Comment by edrushka** [comment]
Decision: we'll have a localized email with an image. Simple.
