### ISSUE TITLE
Localize Social.jsx

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#260]
* https://github.com/mozilla/donate.mozilla.org/blob/master/components/social.jsx

E.g. On the German thank you page, the Facebook share link should share `donate.mozilla.org/de` rather than just `donate.mozilla.org`
* https://github.com/mozilla/donate.mozilla.org/blob/master/components/social.jsx#L12

And the pre defined tweet should be localized too:
* https://github.com/mozilla/donate.mozilla.org/blob/master/components/social.jsx#L19

We'll need to encode the twitter string after it's been localized as part of our build process.

**Comment by alicoding** [comment]
Note to self: This should be part of YAML/JSON file.

**Comment by alicoding** [comment]
There is a good practices for putting OG tag for sharing content on Facebook, but I don't think we have copy for those, or we do? 

cc @edrushka 

-------

This is the example of what we need to put:


#### Title

A clear title without branding or mentioning the domain itself.
```
<meta property="og:title"
content="Workday Sets Price Range for I.P.O." />
```
#### Site name

Provide a site name, e.g. "My Favorite News"
```
<meta property="og:site_name" content="My Favorite News"/>
```
#### URL

A URL with no session id or extraneous parameters. All shares on Facebook will use this as the identifying URL for this article.
```
<meta property="og:url"
content="http://www.myfavnews.com/2013/1/1/workday-price-range" />
```
#### Description

A clear description, at least two sentences long.
```
<meta property="og:description" content="Workday, a provider of cloud-based
applications for human resources, said on Monday that it would seek to price
its initial public offering at $21 to $24 a share.  At the midpoint of that
range, the offering would value the company at $3.6 billion. Like many other
technology start-ups, Workday, founded in 2005, will have a dual-class share
structure, with each Class B share having 10 votes. Its co-chief executives,
David Duffield, the founder of PeopleSoft, and Aneel Bhusri, who was chief
strategist at PeopleSoft, will have 67 percent of the voting rights after
the I.P.O., according to the prospectus." />
```
#### Facebook App ID

A Facebook App ID that identifies your website to Facebook.
```
<meta property="fb:app_id" content="[FB_APP_ID]" />
```
#### Object Type

The type of object:
```
<meta property="og:type" content="article" />
```
#### Localization

This article has some translations:
```
<meta property="og:locale" content="en_US" />            <!-- Default -->
<meta property="og:locale:alternate" content="fr_FR" />  <!-- French -->
<meta property="og:locale:alternate" content="it_IT" />  <!-- Italian -->
``
#### Author and Publisher

This article has an author and a publisher:
``
<meta property="article:author" content="https://www.facebook.com/fareedzakaria" />
<meta property="article:publisher" content="https://www.facebook.com/cnn" />
``

**Comment by alicoding** [comment]
Few more things for this ticket

**Comment by alicoding** [comment]
will resolve in #334
