### ISSUE TITLE
Fix server error-handling

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#270]
The current server error-handling looks like this: ¯\_(ツ)_/¯

We should fix it such that it's actually handling errors in a sensible fashion.

**Comment by simonwex** [comment]
I love this description

**Comment by ScottDowne** [comment]
Stripe errors got their own error overhaul yesterday, but I'm sure there are non stripe errors we still need to fix.

**Comment by ScottDowne** [comment]
I think we can close this. Mostly all server side paths pass back errors or success, and most client side displays something useful to the client and nothing not useful.

If I missed something, we should open a ticket for the case that is missed with some STRs.
