### ISSUE TITLE
Determine who will localize copy for Germany campaign

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#271]
@valianttry we need to decide (for certain) who will do L10N. Is Sebastian the DE crew available? Do you want to hire someone?

We need to ship English and have a L10N connection confirmed by Aug 28.

cc @alicoding

**Comment by alicoding** [comment]
I think we have the answer for this now. Correct me if I'm wrong, but we decided to try to use our Mozilla L10N as much as possible and make sure we give them enough time, but if we need something quick will use our contractor to do our translation needs.
