### ISSUE TITLE
Understand new Snippet opt-out functionality

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#272]
@lovegushwa @edrushka @adamlofting @ScottDowne this functionality may impact how we design and test snippets. I have a few questions for Jean and the team, let's collect those in this tix: 
* Can we track the number of people who X?
* Can we exclude opt outs from slightly modified versions of the snippet or from a class of snippet designs that resemble the one they Xed?

**Description of the functionality (and links to view it) from Jean Collings:**

Hi Andrea,

Thanks for your patience, we are still working on the kinks of this but I wanted to share with you the gist of our plan. Please see this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1184718 (or look at: http://invis.io/UN3NVORWD)

for the flow and user experience. (FYI, this opt-out mimics the +tab Tiles experience for consistency).

To answer your questions, once a user "x" out - that specific snippet will go away forever even if they start a new session (restart Firefox). It wouldn't make sense anyways to control it with time given that same snippets are usually out there for no more than a week.  I don't think it'll affect our testing too much because the opt-out is for a specific snippet (not about:home in general). Users will still be able to see other variants or different snippets.

Once a user "x" out a specific snippet, they will see a new snippet that's in queue. However, if they keep on "x"ing until all snippets run out, they will get our default snippets (these ones they cannot "x" out).

Now, this is the complicated part. This functionality basically needs to be coded in with every "template" we use. So essentially for EOY when we build special templates, the opt-out code will need to be built in each time.

I know there's going to be questions on this so I'm more than happy to walk you through this anytime.

**Comment by adamlofting** [comment]
Not really an extra question, as it's hinted at in the email, but:

* Where can we see docs on how to code this functionality into our new snippets?

**Comment by adamlofting** [comment]
And scope creep, but:

* Could we build similar functionality into the snippet somehow for people who *do* engage? (so that we can somehow try to stop showing the ask to people after they have donated)

**Comment by valianttry** [comment]
* Could we present a simple popup survey for those who X, that would say something like: "Why are you closing this?: a) it's not relevant to me; b) it's annoying; c) i've already donated

**Comment by valianttry** [comment]
Just got an email update from Jean Collings, Giorgos is leading the dev on this:

Hi Andrea,

Great questions! I know Germany fundraising won't happen until October but I wanted to provide answers so we can all have this in our back pocket as we prepare.

Testing the opt-out functionality
**We are currently using this functionality on users who are on Windows 10 and do not have Firefox as their default. I've attached two screenshots (When a user hovers anywhere over the area below the search bar the 'X' shows up on the upper right. When a user hovers over the 'X', it turns red and a gray box outlines the entire snippet.)

**We have only seen a few days worth of data but so far CTR to the button is about 1% and to the 'X' out is about .17%. I need a bit more data and more time to dig into what this means.

Can we track the number of people who X?
**Yes we can track the number of 'opt-outs'

Can we exclude opt outs from slightly modified versions of the snippet or from a class of snippet designs that resemble the one they Xed?
**I think I understand the question but if not, let me know. If a user decides to "x" out snippet A, users can still see snippet B and C (that have similar designs to snippet A). But snippets B and C would still have the opt out functionality.

Where can we see docs on how to code this functionality into our new snippets?
**Giorgos is currently documenting this but I've included him in the email chain so you can reach out directly.

Could we build similar functionality into the snippet somehow for people who do engage? (so that we can somehow try to stop showing the ask to people after they have donated)
**This is a functionality we would need to have a discussion with Giorgos about on the feasibility.

Could we present a simple popup survey for those who X, that would say something like: "Why are you closing this?: a) it's not relevant to me; b) it's annoying; c) i've already donated
**This is a functionality we would need to have a discussion with Giorgos about on the feasibility as well a discussion on a strategy behind this.

**Comment by valianttry** [comment]
Follow up on timing of broader rollout beyond Windows10 // Jean:

**Yes once we see how it's doing with Win 10, we are planning on rolling it out with every snippet we publish (I imagine by mid-September).

**Comment by glogiotatidis** [comment]
>    Where can we see docs on how to code this functionality into our new snippets?

https://github.com/mozilla/snippets/blob/master/templates/simple-snippet.html

Technical info on how blocking snippets works can be found in [snippets documentation](http://abouthome-snippets-service.readthedocs.org/en/latest/developing.html#snippet-block-list). 

Blocking snippets is practically calling a javascript function. You can do so by making your own calls to `addToBlockList` or use `class="block-snippet-button"` on a DOM element that's acts as the block button / link. You're responsible to make your own UI (e.g. integrate the X button in the snippet). We do have visuals from bug 1172579  and an example snippet that you can use as reference https://github.com/mozilla/snippets/blob/master/templates/simple-snippet.html



> Could we build similar functionality into the snippet somehow for people who do engage?

Yes you can call `addToBlockList()` js function after an event, e.g. after user clicks on a link.

> Could we present a simple popup survey for those who X, that would say something like: "Why are you closing this?: a) it's not relevant to me; b) it's annoying; c) i've already donated

It's all javascript so yes. I would first sync with the Firefox team to check if that's acceptable.

> Can we exclude opt outs from slightly modified versions of the snippet or from a class of snippet designs that resemble the one they Xed?

Template designers are responsible to include the X on their designs. So if you don't code the template / snippet to have an X button there will be no X button. In other words snippets by default to do feature an X button.


I believe this answers all your questions. Feedback on documentation is appreciated :)

Thanks!

**Comment by valianttry** [comment]
@glogiotatidis can you let our developer working on snippets, @ScottDowne know whether he should be building this opt-out functionality into all snippets starting now? He is beginning to code snippet content for an advocacy campaign and planned fundraising campaigns launching within 2 weeks. Thanks!

**Comment by ScottDowne** [comment]
@glogiotatidis I had issues setting up the snippet service locally to do testing.

I wonder if it would be easier to give me access to the staging service so I can test things?

**Comment by valianttry** [comment]
We will be launching a contract with Kontextor -- and they need some info to fire up our contract process:

·        How many words per language or strings per week do you appoximately expect? Will the translation requests arrive daily?

·        Are we talking about a translation or a localization/adaption?

·        We normally use word counts to calculate the efforts. As this is not automatically possible in Pantoon, we could also agree on an hourly basis payment. What do you think?

·        Our standard procedure with other customers includes an assignment in the morning with all information what needs to be done during the day. Would that be a procedure that would work for you, too?
(As we are based in Europe we could work while you sleep.)

·        Are there additional/included tasks or steps that you expect/wish us to do (apart from the pure translation)?

**Comment by glogiotatidis** [comment]
> @glogiotatidis can you let our developer working on snippets, @ScottDowne know whether he should be building this opt-out functionality into all snippets starting now?

The opt-out functionality is already in production for other snippets, therefore yes you can use it. I recently landed https://github.com/mozilla/snippets/blob/master/templates/logo-swap-close.html which is a better example.

**Comment by glogiotatidis** [comment]
> I wonder if it would be easier to give me access to the staging service so I can test things?

sure. ping me on irc (giorgos)

**Comment by ScottDowne** [comment]
@glogiotatidis @valianttry @lovegushwa Thoughts on it so far? http://scottdowne.github.io/eoy-snippets/2015-snippet/

@glogiotatidis Source for snippet is here:https://github.com/ScottDowne/eoy-snippets/blob/gh-pages/2015-snippet/snippet.html

**Comment by adamlofting** [comment]
@ScottDowne is there another ticket where I can file some notes/questions about the rest of the snippet? - I didn't want to confuse the thread here which is specifically about the opt-out.

**Comment by glogiotatidis** [comment]
@ScottDowne can you please PR so I can comment on the code?

**Comment by ScottDowne** [comment]
@glogiotatidis Sure thing: https://github.com/mozilla/snippets/pull/55

@adamlofting This is where I have been putting my snippet work: https://github.com/mozilla/donate.mozilla.org/issues/333

**Comment by ScottDowne** [comment]
I do understand the new opt out, and have a patch.

I think moving conversation to my pull request and closing this to reduce noise is helpful for me.
