### ISSUE TITLE
Will lose locale in the transition from /de/#page-01 to /thank-you if `de` is not default locale

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#277]
If you force locale within the URL and try to donate you will lose the locale code after completed the transaction which is a bug, obviously. This needs fixing and the end result it should preserve the locale from the URL over the locale in the browser, or maybe not? This is a good question, but also needs to be fixed.

**Comment by alicoding** [comment]
@ScottDowne I think this is a bug caused by server-side redirect after each success transaction or after signup for email to /share page.

Is there a good reason not doing this client-side? or we have to do it server-side only? If I can get around with BSD problem that you've mentioned before client-side would that be okay? or is there more than just that problem?

**Comment by ScottDowne** [comment]
For PayPal, yes, needs to be server side. That's communication between us and PayPal.

However, really easy to pass the locale along.

**Comment by ScottDowne** [comment]
Or wait, can we... grr, not sure.

**Comment by ScottDowne** [comment]
The only place we don't do this is server side paypal (the one with 100% redirect).

The reason is there are so many redirects, we just lose the info. We need an easy way to pass it along.

**Comment by ScottDowne** [comment]
Landed: https://github.com/mozilla/donate.mozilla.org/pull/424/files
