### ISSUE TITLE
Compile EN documents for L10N

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#278]
1. Compile all the 2014 EN docs (noted on this [etherpad] (https://fundraising.etherpad.mozilla.org/FR-writing-needs) by green asterix)
2. @KevZawacki will review for quality 
3. Maybe Natalie from MoCo will also review and give suggestions
4.1 Put in format that Flod wants
4.2 Send to Flod's team for L10N (they need 3 weeks)
5. Additional L10N we can't get to Flod's team by next week will be done by a contractor

cc @alicoding

**Comment by valianttry** [comment]
Launched a new google doc here to collect draft English content in one place:
https://docs.google.com/document/d/1DMILjOMor2RIxJPC2uJCefUZ6vsuL2G19N0faVfUT34/edit

**Comment by valianttry** [comment]
@thornet @edrushka do we have any Germany event photos or other imagery that a German donor audience could relate to? We could use a nice image in an auto-reply to donors.

**Comment by edrushka** [comment]
FF in Berlin: https://www.flickr.com/photos/mozillaeu/albums/72157631306811270

**Comment by edrushka** [comment]
@alicoding our google doc is coming together. Can you please tell me what format this needs to be in for Flod's team?

**Comment by alicoding** [comment]
It needs dev to do this work or I have to show someone how to do it, Erika.
I'm not sure what option you want to go here ...

**Comment by edrushka** [comment]
@alicoding we have the strings compiled in this gdoc: https://docs.google.com/document/d/1DMILjOMor2RIxJPC2uJCefUZ6vsuL2G19N0faVfUT34/edit#  Can you tell me what we do next in the L10N process?

**Comment by edrushka** [comment]
@KevZawacki - we're ready for your :eyes: on our final set of wireframes: https://redpen.io/p/ah1d913b7edf5c17ed Can you let us know if you have any suggestions for improving the copy? Thanks! cc@hpauljohnson

**Comment by alicoding** [comment]
Erika, so we need to either make a web page for email or strings that
doesn't have a place in any of our existing pages like social, banner,
snippets and then dumb them there for people to see and translate. When I
say dumb them of course I meant putting them into the appropriate format
that Pontoon expect as well

**Comment by edrushka** [comment]
thanks @alicoding - so should I file a separate ticket for that an assign it to you?

**Comment by alicoding** [comment]
Sure :)

**Comment by thornet** [comment]
+1 to the pics Erika identified.

On Fri, Aug 28, 2015 at 1:52 AM, Ali Al Dallal <notifications@github.com>
wrote:

> Sure :)
> On Aug 27, 2015 7:46 PM, "Erika Drushka" <notifications@github.com> wrote:
>
> > thanks @alicoding <https://github.com/alicoding> - so should I file a
> > separate ticket for that an assign it to you?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mozilla/donate.mozilla.org/issues/278#issuecomment-135585660
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/donate.mozilla.org/issues/278#issuecomment-135586461>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by KevZawacki** [comment]
@edrushka Just dropped some suggestion in the Red Pen. Looks great! I might suggest tweaking the "Hello there" copy like so:

Hello there. We know you love Firefox, but did you know a nonprofit called Mozilla built Firefox? Thanks to donations, Mozilla does a lot more than build this awesome browser. We teach people to code, fight for online privacy and protect the Web for future generations. Mozilla asks for donations just a few times a year, and tens of thousands of people all over the world give. If they didn't, we couldn't do all this good stuff. If everyone reading this chipped in just a few dollars, we could wrap up this fundraiser in less than an hour.

**Comment by valianttry** [comment]
@edrushka "dollars" should be "euros" in our language

Also -- @thornet do we have any photos of Maker Party or other things our donations support? Pics of the FF suit... hrm not sure if that sends the "here's an image of impact" message that would be best for donors... you could argue they are FF users and donate out of love of the browser... but it might be good to show our nonprofit work as an education opportunity. Thoughts @edrushka @thornet @KevZawacki ?

**Comment by KevZawacki** [comment]
For solid photos you may want to check out:

Laura's research
https://www.flickr.com/photos/laura_nk/albums/with/72157649814415541

MozFest
https://www.flickr.com/photos/mozillaeu/albums

**Comment by edrushka** [comment]
@KevZawacki thanks so much! your keen eye was exactly what we needed.

@valianttry I don't know what you mean by "dollars" should be "euros" in our language

**Comment by edrushka** [comment]
@alicoding I've added as much as I can to the google doc: https://docs.google.com/document/d/1DMILjOMor2RIxJPC2uJCefUZ6vsuL2G19N0faVfUT34/edit#heading=h.i5ozyq2akd7r

Can you please go ahead on #334 and any additional strings we'll take to the contractor? Thanks!

**Comment by valianttry** [comment]
@edrushka in sample copy and form copy for the DE campaign, we list "dollars" -- our primary currency for this campaign will be "euros". E.g. in https://github.com/mozilla/donate.mozilla.org/issues/278#issuecomment-135819822 the copy says "dollars". Should be "euros".
