### ISSUE TITLE
    Ensure validation of attributes like address aren't overly strict in locales we don't understand

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#294]
(Goal should be to help the user and ensure they aren't surprised by a payment gateway error)

**Comment by ScottDowne** [comment]
The validation I'm doing on address is that they have typed something.

Province/state/etc is only required if they have a country selected that has these. This works the same as it did last year, so if there is an issue with our country/province data, we should file a bug specifically for that.
