### ISSUE TITLE
Investigate and Agree: if we're compiling static HTML, why run our own app server?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#295]
Discussion: if we're compiling static HTML, why run our own app server? (node) - wex

    Why not S3? -wex

    A: doesn't support custom HTTP headers. HSTS, CSP, Link pre-loading, etc

    re: http headers, it does

    show me the docs, because I really really wish this existed

    [i believe] it's done using x-amz-meta- prefix, will find docs later

    If you do that, you get x-amz-meta-content-security-policy: default-src: 'none'

For @jbuck & @simonwex 

Let's find the docs discussed above, and if this is a thing we can do, file the follow up ticket to implement.

**Comment by jbuck** [comment]
@simonwex I haven't found any docs that say we can set custom HTTP headers on S3 except for the ones listed on http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html . Testing with the `x-amz-meta-` prefix shows that it uses the x-amz-meta header in the object response. If AWS changes this in the future we can do this, but for now I'd recommend not hosting on S3
