### ISSUE TITLE
Do we have dashboards for the engineering metrics we care about?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#296]
... what are those? (page load time from X regions? total page size?)

This question is from the tech review.

We have bits of this data in various places. 

- [ ] Team decide which metrics we care about and list in this bug
- [ ] Adam to build dashboard, or a central doc with links to the necessary places (depending on effort vs value)

**Comment by jbuck** [comment]
http://techblog.netflix.com/2015/02/sps-pulse-of-netflix-streaming.html

is a neat read in the context of this

**Comment by adamlofting** [comment]
Let's keep the scope of this small.

add to mofo-transactions

Stripe donations:
* last 10 mins
* last 30 mins
* last 60 mins


Paypal donations:
* last 10 mins
* last 30 mins
* last 60 mins

**Comment by ScottDowne** [comment]
cc @vojtechmzl
