### ISSUE TITLE
Decide on alert process

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#299]
Following this discussion in tech review:

>* What is the alert process? How do we know if something goes wrong?
  * I think we need to implement some proper monitoring first, but I imagine we'll start with a manual process such as "page jbuck" and eventually move to automated fixes like failing over to another region, stop using a payment provider, that sort of thing

Let's make some decisions and document process.

**Comment by alicoding** [comment]
add @jbuck

**Comment by jbuck** [comment]
"page @jbuck" is the current response mechanism
