### ISSUE TITLE
Integrate mozilla-l10n tooling for localizations

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#3]
Rather than using Transifex for translating pages, we should integrate with mozilla-l10n for translations of snippets, donation pages, and thank you pages.

**Comment by adamlofting** [comment]
Lots of value in being able to demo this at Whistler. 

But it's a P2 versus the basic 'get the pages live' work.

**Comment by alicoding** [comment]
So, our stuff is mostly translated and this didn't happen in Whistler work week. When I say this I'm referring to the conversation that suppose to happen with the Mozilla L10N team to work with them to move all of our translation effort for the donation related stuff to be with their current system.

I would say this week at least I'm going to connect with flod or someone in their team to really understand what is the right process here if we want to stop using Transifex for donation stuff and use Mozilla-L10N instead.

**Comment by alicoding** [comment]
I've emailed flod to video chat with him next week. I will update once I have more details here.

**Comment by adamlofting** [comment]
Ali shared notes from his call with flod here:
https://fundraising.etherpad.mozilla.org/FR-mozilla-l10n

@alicoding can you 
- [ ] spend some time estimating how much development work this will take to do.

**Comment by alicoding** [comment]
Time estimate to do all this:
* 0.5 day for converting + create script to change from .yml/json to .po vice 
* 1-2 day for integrating pontoon with our donation 
* 0.5 day for sending email and file bugs with the mozilla 
* 0.5 day updating the staging server

**Comment by adamlofting** [comment]
We'll start this heartbeat, but expect this work to rollover to Aug 28

**Comment by alicoding** [comment]
https://github.com/unho/yaml2po

**Comment by adamlofting** [comment]
This ticket has been open for a while now. Can we break this down into smaller tickets for the next steps and assign those for next week please.

**Comment by alicoding** [comment]
Right now, we need to make sure Pontoon can communicate with our server and we need to (maybe) allow iframe for Pontoon to display our site for translation.

Then we can (hopefully) start the translation.

**Comment by alicoding** [comment]
I don't know if we can call this done, but here it is! https://pontoon.mozilla.org/de/donations-form/

Closing this ticket, and will file an issue we we find anything from now on.
