### ISSUE TITLE
Static backup donate page that links to PayPal and Stripe

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#302]
### The page
- [x] This should be as simple as possible, and should operate without any server side.
- [x] Single page, with ability to enter and amount and frequency (just in USD) and link out to PayPal to process the transaction.
- [x] Design is not a high priority here, as this page is just for emergencies.
- [x] This page should be built as part of the existing repo / build process

### Devops
- [ ] This page should be deployed to a separate S3 bucket when the project is deployed
- [ ] In the case of a Heroku outage, we would update the DNS for the domain to point to the static form instead. 
- [ ] Ideally this failover is automated, as it is on the current setup.
- [ ] If the failover state is live, all URL paths should route to this page rather than 404.

**Comment by ScottDowne** [comment]
In order to do this, Stripe cannot be used, because it requires server side.

PayPal can still be used, but we have to go with the old PayPal flow. New flow also uses the server.

The current simple paypal page we have is very close to what we need.

**Comment by jbuck** [comment]
@ScottDowne I think we can actually. If we have the the server POST to a queue instead of to our application server we could continue to use Stripe.

**Comment by adamlofting** [comment]
Given the plan that this page should never be seen, I'm happy for V1 to be just PayPal, and to the old PayPal flow. That will still allow people to donate. Let's just say on the page that PayPal accepts visa, etc. 

The most important piece is how this deploys and is readiness to be used in an emergency.

We can file a V2 bug to add in queues and work with Stripe if we get time, but I think there will be more valuable work to do on the rest of the campaign.

**Comment by ScottDowne** [comment]
@jbuck I'm worried about waiting to accept money when we could accept paypal right then and there.

Also I'm also worried about payment tokens expiring but I'll admit I have not looked into that yet. Maybe it's not an issue and Stripe tokens can support this? It's worth investigating but I'm totally fine with just paypal.

**Comment by ScottDowne** [comment]
I am unassigning myself, as this is a very meta ticket.

I turned the initial comment into a list.

**Comment by adamlofting** [comment]
I'll refile this as a more specific ticket with smaller scope.

**Comment by adamlofting** [comment]
note to self
https://donate.mofostaging.net/en-US/paypal-donate/
get this to deploy to alternative hosting

**Comment by alicoding** [comment]
* https://www.paypal-notify.com/eventnotification/search?eventSearchType=PayPalSiteStatus
* https://status.stripe.com/

**Comment by adamlofting** [comment]
I've filed the follow up ticket to this thread.
