### ISSUE TITLE
Decide on QA process for localization

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#303]
This is a big challenge. 

If we can't find a perfect solution, what are smaller steps we could implement now that improve the quality of our translations?

This might be about process and documentation rather than code.

**Comment by ScottDowne** [comment]
Is this about quality of the translation, or about UI issues caused by things like strings with varied lengths, or both?

**Comment by alicoding** [comment]
translation quality @ScottDowne
