### ISSUE TITLE
With the changes to client-side i10n, what browser coverage do we have?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#304]
From the tech-review. Can we confirm the answer to this question:

>* With the changes to client-side i10n, what browser coverage do we have?
  * (Old browser support?)
    * it only detects locale if a locale is NOT in the url (I think...)

**Comment by alicoding** [comment]
Right now it works with Safari, Firefox and Chrome, but not IE < 11. We need to fix some of the bug on IE and if we can make it just work on IE =< 8 then we should pretty much have coverage for most of the browsers that React supported.

**Comment by ScottDowne** [comment]
How broken is this on IE < 11?

If the form doesn't load at all on IE 10 because of l10n, this is a P1.
