### ISSUE TITLE
Are we using accept-language.org/polyfill.js ?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#305]
Discussion from tech-review:

> * We can do language detection via https://accept-language.org/polyfill.js
  * What does downtime there look like?
    * bug: decide if we're doing this or not?

**Comment by ScottDowne** [comment]
I don't fully understand the scope of this ticket yet, so, questions are following.

accept-language just gives us the ability to detect the browser set locale?

If so, the accept-language polyfill would allow use of that on things like IE? How many other browsers?

If both of those are true, and there is some issue/blocker on the polyfill, I say we can P2 this. Those older browsers can type their locale in the url if they need to.

I guess it really depends on the list of browsers, and how hard this is to fix.

**Comment by alicoding** [comment]
@ScottDowne it is for IE and Safari and older browsers. Typing URL wouldn't really work because we are using some of the features that's not available in those browsers, so we need to either polyfill or do something about it.

**Comment by alicoding** [comment]
I'm going to close this bug until we are ready to work on Safari and IE then we will start implementing what needs to be added to fix any error we encounter.
