### ISSUE TITLE
Alternative way to pre-populate a donation amount via URL

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#308]
We're looking at removing this older code, but we'll need a suitable replacement.
https://github.com/mozilla/donate.mozilla.org/pull/307

Hopefully we can write this in a nicer way as part of the new select amount component.

The requirement is to be able to pass a donation amount (and I guess currency) in via the URL and for the form to prepopulate. If the amount matches one of the buttons, we preselect that button, but if it doesn't we fill the 'other' amount box instead.

This functionality is used by the snippet. Where the user selects the amount off-site and is then routed into our donation flow.

**Comment by adamlofting** [comment]
From @ScottDowne :

> We should do something like this: "?amount=5&type=cc" in that case, it'll need to be smart enough to navigate to the proper page if there are pages.

**Comment by ScottDowne** [comment]
I did this in here: https://github.com/mozilla/donate.mozilla.org/pull/322
