### ISSUE TITLE
Switch from YAML to PO to make it work with Pontoon

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#312]
Pontoon currently doesn't support YAML, but it does support .PO which is another great format for l10n in general. The switch shouldn't be too hard here.

**Comment by ScottDowne** [comment]
Landed: https://github.com/mozilla/donate.mozilla.org/commit/4770516a7594f60ed327d6e88447825970101e34

Then moved from PO to .properties because it's better and still works with Pontoon: https://github.com/mozilla/donate.mozilla.org/commit/8236ed77c5e81929a647a3479826294208195f8e
