### ISSUE TITLE
virtual page tracking still uses #page-n

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#318]
@adamlofting thoughts?

In #283 we' re re adding the virtual page tracking. We also are moving away from the #page-n concept.

The tracking is still assuming this and not sure the implications of just passing in a new type of data.

Would be nice to not need to pass in the page number as #page-n as that might be confused with navigation.

**Comment by adamlofting** [comment]
The `#page-n` format isn't important in GA. We can pass in any value, so long as each page gets a unique and identifiable string. :smile:

**Comment by ScottDowne** [comment]
@adamlofting 

I'm wondering if this should be an event, and not a page view?

Feels weird to me to pass it a url that isn't actually the url.

Examples that feel off to me:
`/en-US/page-one`
`/en-US/#page-1`
`/en-US/?page=1`

They all have the same issue, they are not real and we're hacking in data for the purpose of tracking an event, essentially.

I'm thinking:

```
ga.event( { category: 'Navigation',
                  action: 'Page Navigation',
                  value: 2 } );
```

**Comment by adamlofting** [comment]
The benefit of the pageview in GA is you can build funnel reports to show drop-off at each step. 

The event data on the other hand isn't as easy to review in a sequential flow as the pageviews.

**Comment by ScottDowne** [comment]
OK, going to leave this as is for now then. Moving to a P2 as this'll just reduce confusion in the code but not actually provide a direct benefit to a user.

**Comment by ScottDowne** [comment]
This just doesn't seem to be creating any confusion.

Closing.
