### ISSUE TITLE
add a favicon

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#324]

**Comment by alicoding** [comment]
We do have this.

**Comment by jbuck** [comment]
But there are a significant number of requests for one that isn't in the current location:

```
select path, count(*) from access_logs where path like '%favicon.ico' group by path;
                   path                    | count
-------------------------------------------+--------
 /favicon.ico                              | 199554
 /page/contribute/firefoxtshirtfavicon.ico |      4
 /images/favicon.ico                       | 917217
(3 rows)
```

I think we should move the path of the favicon

**Comment by alicoding** [comment]
Aha! I see the problem now. I will fix this asap.

**Comment by jbuck** [comment]
@alicoding fwiw, it might be worth adding a file handler for /favicon.ico... I imagine there's a bunch of dumb software that expects it to exist there
