### ISSUE TITLE
Snippet Test 01 "This really helps us" placement

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#333]
Goal: See if adding "this really helps us" prompt near monthly donor button increases monthly donations. 

Copy to be finalized during build.

![snippet test 01a](https://cloud.githubusercontent.com/assets/4515662/9536143/905c4db4-4cdd-11e5-94ca-b01f0cbd3114.jpeg)
![snippet test 01b](https://cloud.githubusercontent.com/assets/4515662/9536146/950860f0-4cdd-11e5-8ad9-3b817a8d237f.jpeg)
![snippet test 01c](https://cloud.githubusercontent.com/assets/4515662/9536150/9b8c1368-4cdd-11e5-87c2-a96f25cc8566.jpeg)
![snippet test 01d](https://cloud.githubusercontent.com/assets/4515662/9536152/9ddbd07c-4cdd-11e5-846c-703da5d97cc9.jpeg)
![snippet test 01e](https://cloud.githubusercontent.com/assets/4515662/9536153/a235d2b2-4cdd-11e5-911a-7d749275be52.jpeg)

**Comment by edrushka** [comment]
@adamlofting this is my first attempt at breaking @lovegushwa's wireframes into individual tickets for testing. Can you let me know if this is how I should do it? :bow:

**Comment by adamlofting** [comment]
That's perfect :+1: :sparkles:

**Comment by ScottDowne** [comment]
One question I have about monthly set as default.

This question doesn't block me from building.

Obviously, the weight of the donation for monthly vs single is not the same.

Single donation: 20$ vs monthly donation: 3$ which do we consider better?

**Comment by edrushka** [comment]
Monthly donations are preferable to us for a variety of reasons: having a continual flow of money helps us plan our activities; it helps us grow steadily and reliably (which other donors and funders notice), and retaining donors is critical to building a stronger base of advocates and growing as an organization. 

The benefit to donors is that we ask them for money less often when they give monthly.

**Comment by adamlofting** [comment]
> Single donation: 20$ vs monthly donation: 3$ which do we consider better?

I see what you're getting at, and this will be a decision for @valianttry

Most orgs ask for smaller amounts for a recurring gift. E.g. $2 /month is preferable to $10

And this would usually be informed by an understanding of long term donor retention rates, but we don't have much historic data here because we haven't don't much around monthly giving.

**Comment by edrushka** [comment]
Clarifying: the wireframes are examples only. The final versions to build for testing will be determined my @lovegushwa's UI work next week.

**Comment by adamlofting** [comment]
There are two parts to the work scoped in this wireframe:

1. We need to add the `monthly` vs `one-time` selector to the snippet regardless
2. We can A/B test the layout of the buttons (in a line or square) and we can A/B test the effect of pointing at the monthly amount with an extra prompt

I don't think we should be using `A 1.0 v1` at all. Because last year we didn't get the monthly amount option included on the snippet, which means all snippet traffic bypassed the opportunity to setup a monthly gift.

**Comment by adamlofting** [comment]
For the DE campaign, this test will need to be run on the snippet rather than the form.

The snippet will account for almost all the traffic in this campaign, and donors will select the `one-off` or `monthly` option on the snippet. Therefore, most of the audience for this campaign will completely by-pass the first page of the donation form.

**Comment by edrushka** [comment]
@adamlofting - agreed that if we have the donation amount directly on the snippet we don't need to have page 1 of the form. However, MoCo might want to try a standard (i.e. text only) snippet for Germany so to play it safe, I suggest we prep page 1 of the form with a version for testing. This can be a P2 for both design and build until we hear definitively from MoCo.

**Comment by adamlofting** [comment]
>  I suggest we prep page 1 of the form with a version for testing. This can be a P2 for both design and build until we hear definitively from MoCo.

Good plan :+1:

**Comment by lovegushwa** [comment]
@ScottDowne @edrushka @adamlofting    ... Hi folks, here is version we plan to run against the baseline. (last years)

This also needs to go through design review. R? @cassiemc @sabrinang 

A note for design review: It might be a little stripped back, but this design includes the exact content Fundraising has decided to run to run against last years baseline. We will build and run more tests time permitting (developer attention has shifted to the Germany advocacy campaign.)


<img width="1316" alt="v1-snippet" src="https://cloud.githubusercontent.com/assets/12228435/9918988/f03e04ba-5c7e-11e5-8a8c-370446625d4e.png">

<img width="1316" alt="v1-snippet-measure" src="https://cloud.githubusercontent.com/assets/12228435/9918972/dac0958a-5c7e-11e5-9225-089acaf41e0b.png">

<img width="1316" alt="v1-snippet-type color" src="https://cloud.githubusercontent.com/assets/12228435/9918978/e2473e12-5c7e-11e5-926f-0125aa0bc2b4.png">

**Comment by sabrinang** [comment]
This is looking great! and thanks for contextualizing it @lovegushwa 

I'm wondering what if the "make my donation monthly" with "this really helps us!" section came after the donation form buttons to hang below it instead of above ... would that help the transition from reading the text to donation form flow better? It may make this middle section less trapped/busy and they can read amounts first and decide after if it's a monthly contribution if they read top down. Other than this consideration it is looking good to me.

**Comment by lovegushwa** [comment]
@sabrinang good thinking, here are a couple other options.

<img width="1116" alt="screen shot 2015-09-16 at 3 41 19 pm" src="https://cloud.githubusercontent.com/assets/12228435/9920506/90320674-5c89-11e5-93a5-1abfc823c75e.png">

<img width="1182" alt="screen shot 2015-09-16 at 3 41 09 pm" src="https://cloud.githubusercontent.com/assets/12228435/9920508/96d460a8-5c89-11e5-90e9-c79e425ad5bf.png">

**Comment by sabrinang** [comment]
@lovegushwa - I'm liking these options over the previous. :+1: 

Hmm... I prefer the grey bg option as it helps visually to group it all together. It also frames the text beneath it so it doesn't get lost and gives a bit of contrast to the small white checkbox.

**Comment by ScottDowne** [comment]
WIP prototype http://scottdowne.github.io/eoy-snippets/2015-snippet/

I figured seeing something working and close to done might make everyone feel a little more at ease :) I know it made me feel better.

**Comment by ScottDowne** [comment]
@lovegushwa Snippet container is width 470px, this is not something we define, you have your layout assuming 465px; We have 5 more pixels to work with, for now I'll add a single pixel to each button width.

**Comment by ScottDowne** [comment]
@lovegushwa What are the top most and bottom most colour codes on the gradients?

**Comment by ScottDowne** [comment]
@lovegushwa Updates: http://scottdowne.github.io/eoy-snippets/2015-snippet/

**Comment by ScottDowne** [comment]
@lovegushwa Just need to add the svg, and do any more QA.

**Comment by valianttry** [comment]
@lovegushwa We need to ask the snippet / product teams to make sure, but changing the background color on snippet from the default is actually a huge ask because it's disruptive for users. In short, we should use sandstone, or what is standard for the snippet background color.

**Comment by valianttry** [comment]
Also, the default at 20 is something we should talk about. @adamlofting can confirm if we tested a higher amount, but choosing an amount that much higher than the average (roughly $8) doesn't always go well.

**Comment by valianttry** [comment]
"Donate now" appears to be a few pixels lower in vertical alignment than the other buttons:

![about_home_snippet_preview](https://cloud.githubusercontent.com/assets/9830371/10006760/db8fcc7a-6074-11e5-9714-d49b44890e29.png)

**Comment by lovegushwa** [comment]
Hi @valianttry , we are using the default snippet background color. Can you confirm @ScottDowne ?
Good catch on the alignment, @ScottDowne and I have not done QA for this (we will do once I get him the this really helps us svg tomorrow.)

**Comment by ScottDowne** [comment]
Also, anyone know where the translated copy lives for this? I would feel like we're one critical step closer if I had that.

**Comment by ScottDowne** [comment]
@valianttry @adamlofting @lovegushwa 

Good catch on the alignment, I'll fix.

Yeah, the current background is the default.

The default amount being raised to 20 is a good point. I'll make the default selected configurable. Right now the amounts are configurable, but the default is always the left most amount.

What was the decision thought to adding a fourth amount button?

**Comment by ScottDowne** [comment]
@lovegushwa The alignment issue is due to the amounts being 21px and the donate now being 20px.

What happens is the browser centers these in the spaces, which depending if it's retina or not, we get different results. For me, they are aligned. I suggest we make them the same size, thus the browser is going to center them the same.

**Comment by ScottDowne** [comment]
K, updated. The button alignment should be fixed, and I set it to preselect 10 eur instead of 20, but we can configure it (or even run tests at some point).

**Comment by lovegushwa** [comment]
Hey @ScottDowne please see a link to the svg and button hex values.

SVG:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlveGxjR1FmeGVKaHc/view?usp=sharing




Button gradient color values (darker color is hover):

![snippet-button-colors](https://cloud.githubusercontent.com/assets/12228435/10030643/a33603bc-612d-11e5-939d-980ec3d04f07.jpg)




I think @sabrinang suggestion of moving the check box under is the best option

![screen shot 2015-09-22 at 1 29 57 pm](https://cloud.githubusercontent.com/assets/12228435/10030733/1d0e90aa-612e-11e5-8d51-bf95779bb992.png)

**Comment by lovegushwa** [comment]
@adamlofting @ScottDowne @valianttry 
Hi folks, here are some options for the placement of the opt out button. Top right makes the most UX sense. However placing the button further down the page (next to or under the donate button) gives the user a bit more of a chance to soak in the copy and may make the choice to donate or opt out feel more deliberate. 

What should be do? 

1.
![screen shot 2015-09-22 at 3 58 06 pm](https://cloud.githubusercontent.com/assets/12228435/10034123/fc21ba1a-6142-11e5-9a2a-48fb64ecfb5a.png)

2.
![screen shot 2015-09-22 at 3 58 25 pm](https://cloud.githubusercontent.com/assets/12228435/10034139/0aa0e11a-6143-11e5-8b08-931db5f3a5ce.png)

3.
![screen shot 2015-09-22 at 3 58 19 pm](https://cloud.githubusercontent.com/assets/12228435/10034142/126212a2-6143-11e5-92e3-8af5b266e039.png)

4.
![screen shot 2015-09-22 at 3 58 13 pm](https://cloud.githubusercontent.com/assets/12228435/10034144/1591b252-6143-11e5-9bdf-a71dfc51fefe.png)

**Comment by ScottDowne** [comment]
I kinda like it floating in the outside of the main container, like it is in the third comp, but maybe floating next to the main text, but not inside. So a mix of 1 and 3?

**Comment by lovegushwa** [comment]
@ScottDowne @valianttry 

Hi all, here is the final DE snippet. The copy is taken from @adamlofting post on the last years best performing DE text. My preference would be a bit longer paragraph and "Make my donation monthly" ranther than "Monthly." I think we should go with an opt out on the top right, aligned to the right edge of the search button. 

![final-german-snippet](https://cloud.githubusercontent.com/assets/12228435/10084609/3e429028-62b9-11e5-8aa3-004a62b55912.jpg)

**Comment by lovegushwa** [comment]
@valianttry if this is good to go @ScottDowne can implement.

You can download the updated .svg here:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvQmZKYzI5TG5NSE0/view?usp=sharing



<img width="1031" alt="screen shot 2015-09-30 at 8 32 58 am" src="https://cloud.githubusercontent.com/assets/12228435/10197826/43c994da-674e-11e5-9e6e-3db116d966f0.png">

**Comment by lovegushwa** [comment]
@ScottDowne just saw the note saying it's ok to make the opt out button smaller. It should be 20x20px.

**Comment by lovegushwa** [comment]
Jean commented on redpen the translation for remove is "Entfernen"

**Comment by ScottDowne** [comment]
K, I'll add the remove bit tomorrow, should still be time.

**Comment by lovegushwa** [comment]
@ScottDowne ... updated png.
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvS08tMXU0RDRlRG8/view?usp=sharing

**Comment by ScottDowne** [comment]
Code to do this is in their snippet servie.

https://github.com/mozilla/snippets/commit/57f65829a7545b368493b68bf7eed6d2f87efa4d

I'm not closing, because we have not run the test, but the dev is done. So I'm unassigning me.

**Comment by adamlofting** [comment]
This ticket ended up tracking the build of the new snippet (which is great), but I'm going to file a new ticket to track the specific test around the language 'this really helps us'.
