### ISSUE TITLE
Create a Creative Brief about our Fundraising Message and Design strategy

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#343]
@lovegushwa I'm going to take a first crack at a Creative Brief outline. Jascha (new CMO) would like to see this type of brief to help get aligned on our testing and messaging strategies.

I've never made a Creative Brief, I found some examples:
* https://www.evernote.com/l/AMpuDHIK-gpAga5JAgYkp6-g3Vo2aQ6SRBkB/image.png
* https://www.evernote.com/l/AMoDndm0UmlNRK7wGovkrcaq0UGOKS12eRcB/image.png
* https://www.evernote.com/l/AMo7hev2K5VAWLWJGeAFhZSEdsCJN3ZkCyIB/image.png

If you have other examples or even a template, please share!

cc @edrushka

**Comment by lovegushwa** [comment]
@valianttry the design studio is actually working creating a standardized brief. It's currently a draft and very product focused, but it's a good opportunity to dial it in a bit, we can connect next week on which questions are relevant if you like? See https://github.com/MozillaFoundation/Design/issues/20

CC @edrushka

**Comment by alicoding** [comment]
Can you please move this to the next milestone or close the ticket if it has been resolved?

**Comment by valianttry** [comment]
Creative Brief draft is here:
https://docs.google.com/presentation/d/1Tpkf6CUX9xcoPU-m-5otdJTvrU7PeHX9JJCU8raJwFw/edit#slide=id.ga39cad493_0_10
