### ISSUE TITLE
Add Facebook Open Graph back

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#346]
It seems like we've lost all the OG tags from the header after the migration from BSD.

We need to put them back for sharing the page on Facebook.

There is a good practices for putting OG tag for sharing content on Facebook, but I don't think we have copy for those, or we do? 

cc @edrushka 

-------

This is the example of what we need to put:

#### Title

A clear title without branding or mentioning the domain itself.
```
<meta property="og:title"
content="Workday Sets Price Range for I.P.O." />
```
#### Site name

Provide a site name, e.g. "My Favorite News"
```
<meta property="og:site_name" content="My Favorite News"/>
```
#### URL

A URL with no session id or extraneous parameters. All shares on Facebook will use this as the identifying URL for this article.
```
<meta property="og:url"
content="http://www.myfavnews.com/2013/1/1/workday-price-range" />
```
#### Description

A clear description, at least two sentences long.
```
<meta property="og:description" content="Workday, a provider of cloud-based
applications for human resources, said on Monday that it would seek to price
its initial public offering at $21 to $24 a share.  At the midpoint of that
range, the offering would value the company at $3.6 billion. Like many other
technology start-ups, Workday, founded in 2005, will have a dual-class share
structure, with each Class B share having 10 votes. Its co-chief executives,
David Duffield, the founder of PeopleSoft, and Aneel Bhusri, who was chief
strategist at PeopleSoft, will have 67 percent of the voting rights after
the I.P.O., according to the prospectus." />
```
#### Facebook App ID

A Facebook App ID that identifies your website to Facebook.

``` 
<meta property="fb:app_id" content="[FB_APP_ID]" />
```

#### Object Type

The type of object:
```
<meta property="og:type" content="article" />
```
#### Localization

This article has some translations:
```html
<meta property="og:locale" content="en_US" />            <!-- Default -->
<meta property="og:locale:alternate" content="fr_FR" />  <!-- French -->
<meta property="og:locale:alternate" content="it_IT" />  <!-- Italian -->
```
#### Author and Publisher

This article has an author and a publisher:
```
<meta property="article:author" content="https://www.facebook.com/fareedzakaria" />
<meta property="article:publisher" content="https://www.facebook.com/cnn" />
```

**Comment by edrushka** [comment]
I'm not sure if we have copy. @KevZawacki?

**Comment by KevZawacki** [comment]
Is this the social copy that displays when someone wants to share their donation?

Currently, we have this on Twitter: I donated to @mozilla today because I #lovetheweb. Join me and help build + protect the Web forever: https://sendto.mozilla.org/page/contribute/givenow-1page …

**Comment by edrushka** [comment]
yes, that's the current share text.

**Comment by ScottDowne** [comment]
Maybe this can be a P2.

**Comment by alicoding** [comment]
@lovegushwa question: do we have that Facebook sharing image ready?
