### ISSUE TITLE
Snippet Test 02 Indicating monthly donation on final page

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#351]
Goal: --> I AM ACTUALLY UNCLEAR ON THIS GOAL <-- are we testing whether people go back and change their donation from monthly to/from one-time (I don't think we can even know this). @adamlofting @lovegushwa can you fill in what we're testing here?

![snippet test 02a](https://cloud.githubusercontent.com/assets/4515662/9633274/f93cf16e-5159-11e5-80c7-62e32506c1dd.jpeg)
![snippet test 02b](https://cloud.githubusercontent.com/assets/4515662/9633276/fae98a7c-5159-11e5-8e0a-7e5a1387243f.jpeg)

**Comment by adamlofting** [comment]
This was actually just a bug on our existing form we noticed this year (that on the last page it said "Donate $X" even if you were commiting to a monthly gift. We've already fixed this on the new system so that it's more explicit if you've clicked the monthly option.

So I'll close this ticket.
