### ISSUE TITLE
Social share test - CTA text variations

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#353]
Goal: Increase social shares 

![social share test 01a](https://cloud.githubusercontent.com/assets/4515662/9634750/24f21df0-5161-11e5-8aec-c766c197734e.jpeg)
![social share test 01b](https://cloud.githubusercontent.com/assets/4515662/9634749/24f13908-5161-11e5-9684-24e81a9ab0b7.jpeg)

**Comment by adamlofting** [comment]
I really don't like the `sad` version, but as an A/B test it will be simple to run. 

I'm happy to be proven wrong by the numbers :stuck_out_tongue_closed_eyes:

**Comment by edrushka** [comment]
We can alter the copy. This was just example text. 
@KevZawacki, any ideas here?

**Comment by edrushka** [comment]
It'd be awesome to have 4 or 5 different copy variations we could have on standby in case we unexpectedly get extra time on the snippet.

cc @lovegushwa

**Comment by KevZawacki** [comment]
Hmm, some ideas:

+ Tell the world you helped defend the Web
+ Let your friends know the Web needs their help
+ Spread the word and help Mozilla protect the Web

**Comment by alicoding** [comment]
Can you please move this to the next milestone or close the ticket if it has been resolved?

**Comment by adamlofting** [comment]
Let's roll this ticket along to EOY testing. 

We have a few variations suggested in this ticket but can we gather up a final list.

**Comment by valianttry** [comment]
We also now have a nice selection of graphic share images! We should test and try at least one if possible.

**Comment by edrushka** [comment]
Final share images here:
[Facebook] (https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvU3o0dzV4cGhIMVk&usp=sharing)
[Twitter] (https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvOXVBaFJFN3dYU0k&usp=sharing)

@adamlofting do you need me to create an build/implementation ticket?

**Comment by adamlofting** [comment]
In this test we're going to track whether different language affects people clicking either of the share buttons. 

The share *images* will appear out in the wild on fb and twitter and we won't be able to factor them into the Optimizely test. 

> @adamlofting do you need me to create an build/implementation ticket?

I think this test is simple enough to run in Optimizely without any upfront dev work.

**Comment by adamlofting** [comment]
I've started setting up this test in Optimizely, but have run into a possible snag to do with how the pages are built. Need to investigate before I can finish setting up this test. 

Blocker: #991

**Comment by adamlofting** [comment]
This test is live and can be tracked here:
https://app.optimizely.com/results2?experiment_id=4018680415&token=5bb348bb996a46d59eac

* Control
* Tell the world you helped defend the Web (Variation 1)
* Let your friends know the Web needs their help (Variation 2)
* Spread the word and help Mozilla protect the Web (Variation 3)

**Comment by adamlofting** [comment]
Stopping this test as it wasn't finding anything significant.

<img width="1157" alt="screenshot 2015-12-16 16 10 19" src="https://cloud.githubusercontent.com/assets/1901816/11846219/8e118464-a40f-11e5-8944-945d2e01c9de.png">
