### ISSUE TITLE
Form test 03 - Monthly prompt

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#357]
Goal: Increase monthly donations with a prompt. 

![form test 03a](https://cloud.githubusercontent.com/assets/4515662/9645599/b06e8cb8-519a-11e5-8577-84885b8faf57.jpeg)

@lovegushwa is this always present, or does it pop up if people select one-time?

**Comment by lovegushwa** [comment]
This version is for a 2 step form. I think we use the 3 step form from option A. (for a general ticking on testing prompting monthly donations.)

![red-pen-677170b2-c54f-4242-efb8-cc2bfd793a98](https://cloud.githubusercontent.com/assets/12228435/9645872/6739b624-5183-11e5-9bce-39daabc5704e.jpg)

**Comment by edrushka** [comment]
I don't like how I wrote this ticket so closing this one and starting over. :fire::fire::fire:
