### ISSUE TITLE
Custom thank you email for Paypal donors

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#359]
This is important, but it's an enhancement rather than a blocker so I'm filing it as a P2 rather than a P1.

On our old system we send a thank you email for Credit Card donors via BSD, and the majority of donors using PayPal only receive the PayPal default transaction email.

We should use our Sawmill infrastructure to send a nicely worded nicely designed thank you email / receipt to all donors regardless of which payment processor they choose.

**Comment by ScottDowne** [comment]
In total they would only receive one email?

Stripe receipt with a thank you or paypal receipt with a thank you?

**Comment by adamlofting** [comment]
> In total they would only receive one email?

* Paypal users will end up receiving two emails
* with Stripe we can choose if they receive one or two

Whatever we do, they'll receive a paypal reciept if they use paypal because we can't switch that off.

But that PayPal receipt isn't in an official tax-record/donation format, and doesn't give us a chance to add a nice thank you message. So we want to send a nicer thank you email from Mozilla as well.

Once we're sending our own thank-you, we can decide if we still want to send the default Stripe receipt.

**Comment by valianttry** [comment]
Related, but probably not a duplicate: https://github.com/mozilla/donate.mozilla.org/issues/686

The email draft I wrote in #686 was a FAST bandaid action to replace the Stripe automated receipt. That's because Stripe's automated receipt was REALLY bare bones!

Worth revisiting + localizing.

**Comment by adamlofting** [comment]
The last comment still captures the task here: 

- [ ] enabling the sawmill thank you email for PayPal donors because it's a nice message we should be sending

**Comment by valianttry** [comment]
We are working on an integration between PayPal and Salesforce. Once a donor record is updated or created in Salesforce, we should be able to set up automated triggers for donors using SFMC.
