### ISSUE TITLE
Post donation sign up page not redirecting to new share page

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#36]
Right now we're using BSD for signups, and we post the data to them.

However, the page we post to controls the redirect after the post, so we cannot point to our local or new share page yet.

Not sure how to fix this.

Probably can do a xhr via js and then do a redirect ourselves, but either way, this can probably post whistler.

**Comment by adamlofting** [comment]
Just copy pasting my comment from the old ticket, but we're thinking the same thing:

> If you're posting to the BSD form, we can simply update the 'thank you redirect URL' in the config for that form in BSD. 

> I think you can also submit the post as an xhr request, then check the thank you page content if you want to manage the redirect. I think that's what happens [here](https://welcome.webmaker.org/pledge/teach-the-web/)

We could also duplicate the existing form in BSD, and just update the redirect URL in the duplicate copy.

**Comment by ScottDowne** [comment]
Going to try the xhr first, that way we can have it redirect to localhost while doing local dev.

**Comment by ScottDowne** [comment]
Had to do this server side, because client side xhr was hitting cors issues, but it works now.

**Comment by ScottDowne** [comment]
It also works locally.

**Comment by adamlofting** [comment]
:sunglasses:
