### ISSUE TITLE
Test one-page form against existing three-step flow

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#368]
Goal: See if combining donation amount and payment info into one page increases donations.

![form test 03a](https://cloud.githubusercontent.com/assets/4515662/9673400/b793c076-5258-11e5-8f3d-1b617505d88f.jpeg)

**Comment by edrushka** [comment]
The "This really helps us" pop-up doesn't necessarily have to be a part of this test.

**Comment by adamlofting** [comment]
This is test is in scope, and we have a version of the 3-step vs 1-page forms ready on our current staging site:

https://donate.mofostaging.net/en-US/
https://donate.mofostaging.net/en-US/one-page/

<img width="705" alt="screenshot 2015-09-04 10 17 53" src="https://cloud.githubusercontent.com/assets/1901816/9680377/5ae6dcaa-52ee-11e5-92a4-85a8f8ff595b.png">
<img width="732" alt="screenshot 2015-09-04 10 17 58" src="https://cloud.githubusercontent.com/assets/1901816/9680376/5ae59110-52ee-11e5-904a-1989f96de6b8.png">

**Comment by edrushka** [comment]
cc @lovegushwa

**Comment by adamlofting** [comment]
We're ready to do a first pass of this test once the new platform is live.

Staging URLs for the two variants are:
* https://donate.mofostaging.net/en-US/
* https://donate.mofostaging.net/en-US/one-page/

**Comment by adamlofting** [comment]
https://fundraising.mozilla.org/ab-test-three-page-vs-one-page-donation-flow/ :sparkles:

**Comment by valianttry** [comment]
@adamlofting I tested the new 1-page form today and realized it does not require a Privacy Policy optin. The 3-step form did. First, I wonder if we need the option (probably a legal question). Second, do you think the results of the test still stand?

In the short term @ScottDowne added the checkbox to the 1-page form:

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11449958/fb72d696-953e-11e5-9444-7305b5cf3d4a.png)

**Comment by ScottDowne** [comment]
One thing I think is weird is how the checkbox has to come before the info is entered.

For both stripe and paypal, the info is going to our server, so I'm pretty sure we need that checkbox.

Finally, we don't have the "We use Stripe for credit card processing. For more information see their Privacy Policy." on this page like we did on the sequential page.

**Comment by adamlofting** [comment]
@valianttry 
> @adamlofting I tested the new 1-page form today and realized it does not require a Privacy Policy optin. The 3-step form did. First, I wonder if we need the optin (probably a legal question). Second, do you think the results of the test still stand?

Good catch, and was happy to see Scott ship this fix so quickly :+1: 

The privacy policy does apply so it's good to include this. In fact, we probably should have had this before the PayPal button on the old form anyway, now that we're looking at this more critically. Given that, I think we can say this test still applies. 

Also tactically, I don't want to use another week of traffic re-running a test that wasn't finding any conversion gains given the list of ideas we have to test. Let's push on with the test plan now.

> Finally, we don't have the "We use Stripe for credit card processing. For more information see their Privacy Policy." on this page like we did on the sequential page.

Good catch @ScottDowne - I'll file this now.
