### ISSUE TITLE
Snippet Test : input CC right on snippet

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#369]
Goal: See if giving the option to add CC details right on the snippet (or in a pop-up) increases donations.
![snippet test 03a](https://cloud.githubusercontent.com/assets/4515662/9673509/b58136a0-5259-11e5-9f89-71b678e21dcf.jpeg)
![snippet test 03b](https://cloud.githubusercontent.com/assets/4515662/9673510/b582eae0-5259-11e5-9c21-1b8e4eb3fa33.jpeg)

**Comment by adamlofting** [comment]
I think this is out of scope for DE campaign given complexity and need for security review etc.

**Comment by edrushka** [comment]
Agree. Let's plan to investigate this for EOY.

**Comment by edrushka** [comment]
cc @lovegushwa (we'll save this one for later)

**Comment by ScottDowne** [comment]
Need to look into remote resources for this, in relates to the stripe widget, and doing network stuff in the snippet.

**Comment by ScottDowne** [comment]
Moved to https://github.com/MozillaFoundation/Advocacy/issues/398
