### ISSUE TITLE
Implement l10n as it is in the existing donation forms using formatJS

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#37]

**Comment by ScottDowne** [comment]
Here is an example that might save time implementing it: https://github.com/mozilla/webmaker-android/pull/2239

**Comment by adamlofting** [comment]
Is this ticket still open? :cat2:

**Comment by alicoding** [comment]
Implementation of this ticket is done but we need to heavily test to see if
it works the way we expect it to be.

**Comment by adamlofting** [comment]
:+1: thanks!
