### ISSUE TITLE
Form test 04 - Copy on form for non-snippet traffic

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#370]
Goal: People that visit the form through channels other than the snippet don't get any contextual copy. See if adding text to the form for non-snippet sources (e.g. Mozilla.org links, tiles) increases donations.

![form test 04a](https://cloud.githubusercontent.com/assets/4515662/9673567/70d0774a-525a-11e5-9761-afd460005100.jpeg)

**Comment by adamlofting** [comment]
For prioritization discussion, is the DE campaign just snippet? (if so, we can push this for later)

**Comment by edrushka** [comment]
@valianttry can you confirm what channels we'll get for the DE FR campaign?

Regardless, I don't think we'll get enough traffic from other sources to warrant prioritizing this for the DE campaign. I'm fine with pushing this until later.

**Comment by edrushka** [comment]
@lovegushwa (we'll test this later)

**Comment by adamlofting** [comment]
Copying across sketch from duplicate ticket.

![f6bd0670-3c2f-11e5-923e-22f7cb0b2dae](https://cloud.githubusercontent.com/assets/1901816/10690147/d5503dba-7977-11e5-866b-38c894db6a4e.jpg)

**Comment by adamlofting** [comment]
Design work is being tracked in #550

**Comment by adamlofting** [comment]
This ranks as a high priority test for EOY campaign:
https://docs.google.com/spreadsheets/d/1DCRW-zC3Uae5V0ubbHvFD2GCoIiS6nWItQOXKzCChe4/edit#gid=0

- [ ] After the design work is done we should file a follow up ticket for the engineering part of this.

**Comment by valianttry** [comment]
Copy ticket is in https://github.com/mozilla/donate.mozilla.org/issues/633 and the included Google doc has suggested variants ready to plug into design.

**Comment by adamlofting** [comment]
This test is live for directory-tiles and mozilla.org referrals:
http://app.optimizely.com/l/vZoWvL?token=5a73439381ec88de0297#view=2

**Comment by adamlofting** [comment]
The first version of this test has been concluded and written up here:
* https://fundraising.mozilla.org/ab-test-additional-ask-for-some-channels/

We're running a follow up test with alternative language in the ask.
