### ISSUE TITLE
https://donate.mofostaging.net/ doesn't work on Firefox for Android

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#375]
It doesn't redirect

**Comment by alicoding** [comment]
But works on Chrome for Android. We should figure this out why. I can't debug right now but will do once I have access to my computer

**Comment by alicoding** [comment]
Bug filed 

https://github.com/Financial-Times/polyfill-service/issues/477

The error was

```
ReferenceError: Intl is not defined
```

**Comment by ScottDowne** [comment]
@alicoding is there a workaround?

**Comment by alicoding** [comment]
The bug on polyfill service got assigned to someone to work on, so hopefully will get the fix soon.

**Comment by alicoding** [comment]
I'm moving this to the next heartbeat since we are still a bit blocked on polyfill-service to land a PR that should hopefully fix this.

**Comment by ScottDowne** [comment]
Plan for this.

We'll give the polyfill-service until the end of this heartbeat to fix it, if they don't get to it, we'll push to next heartbeat and implement a workaround, and if they happen to fix the polyfill before launch, bonus.

**Comment by ScottDowne** [comment]
Is this a P1?

I question this because snippet is only for desktop, right?

**Comment by alicoding** [comment]
@ScottDowne Actually there is a snippet for mobile too, but I don't know if we are getting the snippet enable for that one or not, and if we do then we have another problem I think? Copy is not ready for that? OR we have them in the doc?

**Comment by alicoding** [comment]
@valianttry can you confirm if we are going to get any mobile snippet at all?

**Comment by alicoding** [comment]
We should consider switching from using the external api to npm package of this polyfill service instead.

**Comment by valianttry** [comment]
@alicoding Firefox for Android = <500 donations for all of 2014 campaign. DE is no doubt tiny % -- Please focus on other P1s and bump this to P2 at highest prioritization.
