### ISSUE TITLE
Get a list of default donation prompts for priority locales

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#381]
Based on average asks by existing charities who have fundraising experience in those countries.

**Comment by ScottDowne** [comment]
Once we have the data and the currency drop down patch lands, updating the preset form values is a matter of changing the values in this data file: It'll work something like this: https://github.com/ScottDowne/donate.mozilla.org/blob/currency-drop/data/currencies.js

**Comment by adamlofting** [comment]
@ScottDowne Here's a list of `one-off` and `monthly` donation ask arrays for all the currency / locales currently in that file, based on research of WWF & Unicef donation flows in each of those countries.

https://docs.google.com/spreadsheets/d/14RsrZZ9V9Tx3jvYoYT5fYQYW1hETJkCRVVGxR7U65TU/edit?usp=sharing

cc @valianttry @edrushka - for info re donation amounts

In the future we can research and optimize for individual locales, but until then this gives us a good starting point for the kind of donation asks people in each of these locales will be used to receiving.
