### ISSUE TITLE
How to rebuild the site after changing env var in Heroku

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#385]
For example, config var to disable Optimizely is used at Build time not Runtime.

**Comment by ScottDowne** [comment]
I would say let's just document the manual process for this, instead of making something.

Making the automatic should be a P2.

**Comment by ScottDowne** [comment]
Looking at their rest api, I think we can do this dynamically server side.

Detect if there is a test to run, if so, script is included, otherwise, script is not.

We could then have an env to override this where we can turn it off or on regardless if there is a test or not. (for testing and debugging purposes)

Thoughts?

**Comment by adamlofting** [comment]
Sorry, my original ticket title was misleading. I've updated this now.

Example use case is that I log into heroku and set `OPTIMIZELY_ACTIVE` config var to 'no'. How do I then rebuild the site from the existing latest version of the repo? Normally the site is built when a PR is merged. 

> I would say let's just document the manual process for this, instead of making something.

Agreed.

**Comment by adamlofting** [comment]
As an aside: re this idea about Optimizely...

> Detect if there is a test to run, if so, script is included, otherwise, script is not.

...the optimizely tag has to be present in the live site in order to setup a new experiment via the editor. So there are times for this to be enabled when there are currently no active tests.

**Comment by jbuck** [comment]
This also applies to staging/production public API keys for Stripe

**Comment by jbuck** [comment]
I looked at the build times for various parts of the build on my local machine:

* build:* - 34s
* build:* --parallel - 25s
* build:l10njson - 1s
* build:js - 25s
* build:exchangerates - 1s
* build:css - 2s 

Looks like I need to focus on the js build-time steps!
