### ISSUE TITLE
Teach Ben Github

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#387]
Ben N needs to learn Github. I will train him!
@bniolet1 aren't you excited?!

**Comment by bniolet1** [comment]
I sure am. This is so awesome. @edrushka

**Comment by edrushka** [comment]
I heard you like dogs. What do you think of this guy?
![cute_dog_2_1024x768](https://cloud.githubusercontent.com/assets/4515662/9797500/4fe3c3e2-57b0-11e5-815e-9e2e4ff649b0.jpg)

**Comment by bniolet1** [comment]
this is a fox. 

![qc6f7x8](https://cloud.githubusercontent.com/assets/14222130/9797576/e06228e6-57c9-11e5-80f9-5dab66576be4.jpg)

**Comment by edrushka** [comment]
This is valuable work. Let's make sure we have labels and milestones. Can you please assign as necessary.

**Comment by edrushka** [comment]
Excellent. I think we can call this done.
