### ISSUE TITLE
Detect for unsuported IE versions and redirect to simple form

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#391]
Follow up from  #336

Supporting IE < 11 has an estimated donation value ~$40k

For now, let's sniff the browser and route users of older IE to a simpler donation page that doesn't rely on react-router. 

I think the [paypal-donate](https://donate.mofostaging.net/en-US/paypal-donate/) forms meet this criteria, but please double check that pages works for older IE as part of this bug.

**Comment by alicoding** [comment]
Can you link me to the page where IE users donated from the old form? I checked all of our old forms and it is not usable/can't donate at all.

**Comment by adamlofting** [comment]
I'm not sure who managed the build of those pages (and what level of browser support we offered) but here's the GA data showing users of IE who made donations and their landing pages:

<img width="1048" alt="screenshot 2015-09-28 12 13 53" src="https://cloud.githubusercontent.com/assets/1901816/10134021/687cf33c-65da-11e5-9423-c330b8afd145.png">

**Comment by alicoding** [comment]
Yeah, I've tested it on the old form and IE8 was totally broken and now we have better support for IE on this new form.. IE9 - Edge

**Comment by alicoding** [comment]
I'm closing this issue unless we want IE8 fix as well.

**Comment by adamlofting** [comment]
We do want to solve for IE8, and if we have to we can redirect these users to a simple one-page form. We can take it out of this milestone though.

**Comment by alicoding** [comment]
I got IE8 to the point where it also works with react router but there is a
problem that I couldn't figure out since it doesn't respond to any of the
click or sometimes it will throw an error.

The least I can do here is to create a new page with one field and a button
to donate through PayPal to make it really work for ie8. One-page
definitely doesn't work here.

What do you think?

**Comment by ScottDowne** [comment]
Killing this. We're deciding to not support anything under IE 11.

cc @stephaniemcv just an fyi, if you get this question.

**Comment by valianttry** [comment]
![cursor_and_browser___os_-_analytics](https://cloud.githubusercontent.com/assets/9830371/18565071/5854e1ac-7b5c-11e6-9e53-b0b97fd87181.png)
