### ISSUE TITLE
Some currency amounts don't fit into the amount buttons

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#394]
<img width="440" alt="screenshot 2015-09-11 15 16 54" src="https://cloud.githubusercontent.com/assets/1901816/9816995/42082e3c-5898-11e5-95cd-b2d80d9bad59.png">

Can we adjust font size based on max string length? Or something similar?

**Comment by ScottDowne** [comment]
@lovegushwa Is changing the font size dynamically like that a common solution? I feel like it's solving the symptom for now, but not really solving the issue which is our buttons are rigid and don't really work all that well with different values.
