### ISSUE TITLE
Currency selector list isn't sorted

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#395]
<img width="174" alt="screenshot 2015-09-11 15 19 13" src="https://cloud.githubusercontent.com/assets/1901816/9817041/8375efe4-5898-11e5-91c4-afa288727296.png">

Let's sort this alphabetically so it's easier for people to find their currency.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/commit/e197fbf830a68cc6d29669e810c6c68d788ae783

**Comment by adamlofting** [comment]
:+1:
