### ISSUE TITLE
Wrong currency passed to PayPal

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#396]
Test donation in GBP

<img width="455" alt="screenshot 2015-09-11 15 21 39" src="https://cloud.githubusercontent.com/assets/1901816/9817101/dcbec094-5898-11e5-854d-0a69adbe7342.png">

Paypal in USD

<img width="889" alt="screenshot 2015-09-11 15 21 29" src="https://cloud.githubusercontent.com/assets/1901816/9817114/ec4212b4-5898-11e5-826d-5efb4240d9c4.png">

**Comment by ScottDowne** [comment]
Came across this while doing this fix: https://support.stripe.com/questions/which-currencies-does-stripe-support

**Comment by ScottDowne** [comment]
Fix: https://github.com/mozilla/donate.mozilla.org/pull/401

**Comment by ScottDowne** [comment]
Landed
