### ISSUE TITLE
Allow spaces in CC field

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#398]
I was trying to QA the site using the test card data and found I couldn't paste in a string including spaces: `4242 4242 4242 4242`.

Most people won't be copy pasting CC data, but should we open up the validation to allow spaces, and then auto trim this before submitting?

My other concern was that the strictness of this validation might break autocomplete style functionality people may use via their browser or add-ons.

<img width="452" alt="screenshot 2015-09-11 15 25 50" src="https://cloud.githubusercontent.com/assets/1901816/9817218/75ba8bf2-5899-11e5-8977-9f73292976ea.png">

cc @ScottDowne @jbuck @alicoding 

The P1 here is to discuss. We might decide the implementation is a P2.

**Comment by jbuck** [comment]
I think we should loosen the input validation on the credit card number for sure

**Comment by ScottDowne** [comment]
Yeah, def we should allow spaces. It's likely stripe is fine with spaces too so we don't even need to strip them out. I'll test.

I don't know if there are other areas we need to change though, that should be enough?

**Comment by adamlofting** [comment]
Let's just allow spaces in this field for this bug.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/400

Anything more complex than this, we should consider a lib that does this. For now I'm fine without.

**Comment by ScottDowne** [comment]
Landed.
