### ISSUE TITLE
Fraud protection for stripe

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#40]
I'm not sure how this all integrates, or if anyone has any thinking on this yet, but it's a huge deal.

I think one question we need answered is how stripe integrates with fraud, and how much fraud protection stripe offers by default, if any. If not, we need to integrate with Kount, likely.

**Comment by adamlofting** [comment]
We're currently hoping we can manage this with settings within Stripe, but we're going to have to monitor and evaluate this. We'll test this in our mid-year campaigns, so we'll be confident by the time we go into EOY.

Dropping some links in here:
* https://stripe.com/docs/fraud
* https://support.stripe.com/questions/avoiding-fraud-and-disputes 

Stripe's fraud protection is made even easier if we use their checkout flows (which we should consider from a UX point of view too). But even if we build our own forms there are things we can configure.

**Comment by ScottDowne** [comment]
At the least it looks like Stripe offers something very very similar to Kount.

I'm happy to close this for now until there is something actionable.

**Comment by ScottDowne** [comment]
Still not sure what we need to do here, assigned to myself to figure out what we have to do as a first step.

**Comment by ScottDowne** [comment]
Also probably good info to track in this bug: https://support.stripe.com/questions/how-does-stripe-handle-chargebacks

**Comment by jbuck** [comment]
Relevant: https://github.com/mozilla/donate.mozilla.org/issues/449
