### ISSUE TITLE
Validate URL amount field

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#411]
Currently it's possible to pass strings into the 'other' amount box via the `amount` query string, and then progress to the next screen with `NaN` as the donation amount.

<img width="678" alt="screenshot 2015-09-14 13 46 30" src="https://cloud.githubusercontent.com/assets/1901816/9849946/41650ab2-5ae7-11e5-9c84-34c8dc852868.png">

<img width="533" alt="screenshot 2015-09-14 13 46 39" src="https://cloud.githubusercontent.com/assets/1901816/9849951/48be34b4-5ae7-11e5-8a6c-dfeee5431b69.png">

**Comment by ScottDowne** [comment]
This got fixed.
