### ISSUE TITLE
Add a validation message on 'Personal' screen

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#413]
In this scenario, let's add a simple validation message: "Please complete the required fields" and put this message in the same color as the input box highlight (currently red).

<img width="478" alt="screenshot 2015-09-14 13 56 38" src="https://cloud.githubusercontent.com/assets/1901816/9850134/7b505668-5ae8-11e5-87ec-079c56f5f921.png">

**Comment by ScottDowne** [comment]
Closing this in favour of #673 because it has a bit more info than this.
