### ISSUE TITLE
Display a loading indicator after clicking on Paypal

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#415]
<img width="535" alt="screenshot 2015-09-14 14 06 23" src="https://cloud.githubusercontent.com/assets/1901816/9850339/d73f9672-5ae9-11e5-82b1-407f284042f0.png">

Currently, it's not obvious to the user that the system is doing something.

**Comment by ScottDowne** [comment]
This has a spinner right in the button now.
