### ISSUE TITLE
Snippet string that may need to be translated

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#431]
Been working on http://scottdowne.github.io/eoy-snippets/2015-snippet/

and wanted to insert the german text, and I cannot find it. Did it get missed?

I also wanted to double check that it's the correct up to date copy?

**Comment by ScottDowne** [comment]
@valianttry @adamlofting @edrushka thoughts? Am I missing something or can we get this translated?

**Comment by ScottDowne** [comment]
The strings that need to be translated are: 

`<b>Hello there:</b> We know you love Firefox, but did you know a non-profit called Mozilla built Firefox? Thanks to donations, Mozilla does a lot more than build this awesome browser. We teach people to code, fight for online privacy, and protect this amazing thing called the Web for future generations. Just a few times a year Mozilla asks for donations, and tens of thousands of people all over the world give. If the didn't, we couldn't do all this good stuff. <em>If everyone reading this chipped in just a few dollars we could wrap this fundraiser up in under an hour. You can make a donation here. Thank you.</em>`

and

`Make my donation monthly`

**Comment by alicoding** [comment]
Please also note that when I got the final document for copy that needs to be translated for the snippet this was the text:

```
Mozilla is the nonprofit behind Firefox and we are proudly non-corporate. You have stood with us for user choice and privacy - thank you! Will you help Mozilla? If everyone reading this chipped in a few euro, we would be supported for another year. Donate now.
```

**Comment by ScottDowne** [comment]
Yeah, that's another point on process, at some point the english was changed, but nothing went into motion to get the translated text changed.

@alicoding Think if we just drop this text into donate.mozilla.org pontoon can have it translated in a few days?

**Comment by alicoding** [comment]
@ScottDowne we might or we might not, but either way we need to update that on Pontoon/our repo anyway. These updated strings can't live on a design page if it will ever goes to production.

**Comment by adamlofting** [comment]
Screenshot of best performing DE snippet text from last year is included in this blog post: https://fundraising.mozilla.org/when-testing-meets-localization/

**Comment by jbuck** [comment]
These are the snippet translations from last year:

;Mozilla, the maker of Firefox, is a non-profit and we rely on donations. If everyone reading this gave $3, we would only have to fundraise 1 day a year. Donate today.
Mozilla, die Entwickler von Firefox, sind gemeinnützig und auf Spenden angewiesen. Wenn jeder, der das liest, 3&nbsp;$ spenden würde, müssten wir nur an einem Tag pro Jahr Spenden sammeln.


;Share the love. Donate to Mozilla, the non-profit organization behind Firefox. If everyone reading this gave Mozilla just $3, our fundraiser would be over within a day. Thank you!
Teilen Sie die Liebe. Spenden Sie an Mozilla, die gemeinnützige Organisation hinter Firefox. Wenn jeder, der das liest, nur 3&nbsp;$ an Mozilla spenden würde, wäre unser Spendenaufruf innerhalb eines Tages vorbei. Vielen Dank! 


;Dear Firefox users: If you use Firefox, take a minute to support the nonprofit and volunteers that built it. If everyone reading this gave $3 Mozilla’s fundraiser would be over within a day. Donate today.
Liebe Firefox-Nutzer: Wenn Sie Firefox verwenden, nehmen Sie sich eine Minute Zeit, um die gemeinnützige Organisation und die Freiwilligen, die ihn entwickeln, zu unterstützen. Wenn jeder, der das liest, 3&nbsp;$ an Mozilla spenden würde, wäre unser Spendenaufruf innerhalb eines Tages vorbei. Spenden Sie noch heute.


;Love Firefox? Take a minute to support the nonprofit and volunteers that built it. If everyone reading this gave Mozilla $3, our fundraiser would be over within a day. Donate today.
Lieben Sie Firefox? Nehmen Sie sich eine Minute Zeit, um die gemeinnützige Organisation und die Freiwilligen, die ihn entwickeln, zu unterstützen. Wenn jeder, der das liest, 3&nbsp;$ an Mozilla spenden würde, wäre unser Spendenaufruf innerhalb eines Tages vorbei. Spenden Sie noch heute.

**Comment by ScottDowne** [comment]
The german copy in the blog post doesn't match any of the copy jbuck found.

**Comment by lovegushwa** [comment]
@ScottDowne @jbuck here is the copy from the blog post.

Mozilla, die gemeinnützige Organisation hinter Firefox, ist auf Spenden von Leuten wie Ihnen angewiesen. Falls jade Person, die das liest, ein paar Dollar spendet, so wäre unsere Finanzierung für das nächste Jahr gesichert.

Copy highlight starts at "Falls jade Person, ..."

**Comment by valianttry** [comment]
Except it says "dollar" and should say "euro" -- we need someone to confirm the translation once the currency name is changed.

**Comment by lovegushwa** [comment]
@valianttry ... got it, will update the design.

**Comment by lovegushwa** [comment]
@valianttry @ScottDowne @jbuck 
Please see the updated DE snippet. https://github.com/mozilla/donate.mozilla.org/issues/333 @valianttry can show this to MOCO. The translation needs to be confirmed, it's lifted exactly from last years snippet (besides changing dollar to euro).

**Comment by jbuck** [comment]
https://pontoon.mozilla.org/de/fundraising/Snippets/

**Comment by valianttry** [comment]
Looks like the first (shorter) snippet copy was translated. Yay!

in the 2nd paragraph -- there is still "dollar" vs. "euro". @alicoding and/or @jbuck can you make sure "euro" replaces "Dollar" in the translation request?: 

![pontoon](https://cloud.githubusercontent.com/assets/9830371/10148875/eb06b40e-65ea-11e5-906b-2282ca6f1068.png)

**Comment by alicoding** [comment]
Actually we have a longer one translated by Grigorios this morning as well
but just waiting to be committed to the repo and we can use longer version
instead if we want.

**Comment by ScottDowne** [comment]
This is now done.
