### ISSUE TITLE
Stripe Error messages not fed back to the user

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#439]
Walking through my first QA scenario, I was unable to complete a donation on staging.

> Something seems to have gone wrong. Please try again later

* $20 (first button selected)
* Credit Card
* Using Stripe test creds
* Final screen appears to pass validation 

<img width="477" alt="screenshot 2015-09-24 12 47 33" src="https://cloud.githubusercontent.com/assets/1901816/10072572/a969b2ae-62ba-11e5-9bf3-7de4066c56c8.png">

**Comment by adamlofting** [comment]
Investigating further, I had set the CC expiry date to 1/15. 

In this case I suspect we are receiving an error message from Stripe, but we need to surface that message, or convert it into something meaningful for the user. E.g. 'Your payment was not accepted, please double check your card details and try again'.

Is there a known list of Stripe error messages we should be trying to handle in this case?

**Comment by adamlofting** [comment]
Same issue occurs if a donation is above our maximum amount.

**Comment by adamlofting** [comment]
- https://stripe.com/docs/testing

**Comment by ScottDowne** [comment]
Fixed in: https://github.com/mozilla/donate.mozilla.org/commit/4e82eda9a5918f3b1d74edd7a734714694e2b4a1
