### ISSUE TITLE
We should only show decimal places, if they are non-zero

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#440]
<img width="490" alt="screenshot 2015-09-24 13 00 18" src="https://cloud.githubusercontent.com/assets/1901816/10072808/69231de6-62bc-11e5-93f6-e1693c8c1a6a.png">

In the 'amount' that we show throughout the flow (2 examples highlighted in the screenshot) we should only include the decimal places if the user has explicitly entered a donation amount with decimals via the 'other amount' box.

Showing `.00` makes the donation amount look bigger than it really is, and may have a small negative impact on conversion.

**Comment by ScottDowne** [comment]
So, I'm actually thinking we close this.

My reasoning is both Stripe and Paypal display the .00

We could test this, but, kinda feel like doing what Paypal and Stripe do makes this a very very low priority even as a test.

**Comment by adamlofting** [comment]
It might seem small, but this is one of the places where the psychology gets really interesting.

* http://www.nickkolenda.com/psychological-pricing-strategies/

And there's a reason fundraising appeals typically avoid the decimal, unless it's needed for precision:

* http://www.oxfam.org.uk/donate
* http://donate.unhcr.org/gbr/general/

By the time the user gets to Paypal flow, they have made the emotional decision to donate, but before that, this is a place where our design design will likely have an impact on our fundraising. 

It's not a P1 for shipping, but we should keep this ticket open.
