### ISSUE TITLE
Page isn't visible to Facebook

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#442]
Is there somthing about the way we rended this page that would prevent other sites / bots from being able to scrape the content?

Using this example of the [Facebook Linter](https://developers.facebook.com/tools/debug/og/object/), they can't pick up basic things like the HTML title tag.

<img width="978" alt="screenshot 2015-09-24 14 03 06" src="https://cloud.githubusercontent.com/assets/1901816/10074026/1f89a296-62c5-11e5-9fc7-700dd8f5c283.png">

**Comment by alicoding** [comment]
I just tested my local site using ngrok to tunnel it and Facebook able to scrape the info with no problem. I don't know what's wrong with our staging env, but will investigate further.

**Comment by ScottDowne** [comment]
Seems to be working now.

**Comment by alicoding** [comment]
Just want to update that @cadecairos @jbuck and I have been working on this and trying to see what's really happening here...

**Comment by jbuck** [comment]
Looks like we need to add the og:image property

**Comment by alicoding** [comment]
So, for some reason the problem that @cadecairos and I were seeing disappear and I would assume that it was Facebook's bug and they've fixed it. Now, the only thing left for us to do here is to add `og:image` property so that it can display a nicer image for social share.

**Comment by jbuck** [comment]
We're generating a new facebook share image, since it doesn't support SVG

**Comment by alicoding** [comment]
![screen shot 2015-11-22 at 10 29 44 am](https://cloud.githubusercontent.com/assets/4368149/11324597/1c7db17e-9104-11e5-91d1-2621975b527d.png)
