### ISSUE TITLE
Add ourselves to the HSTS preload list

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#464]
Action from #82

**Comment by jbuck** [comment]
We need to upgrade to the latest version of Hapi (v11) before I can do the code for this feature

**Comment by jbuck** [comment]
Support code is in #616

**Comment by jbuck** [comment]
This is blocked on DNS being setup

**Comment by jbuck** [comment]
Okay, it looks like we can't preload donate.mozilla.org, you need to preload the entire mozilla.org domain. Oh well!
