### ISSUE TITLE
Output validation on the server-side

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#467]
Action from #82 

@jbuck @ScottDowne can you elaborate on this task? I'm not sure what that means.

**Comment by ScottDowne** [comment]
From my understanding (and it's new to me) you need to do validation on input values again when it reaches the server. Output from client to server, and keep validating it every time it goes to your server again.

@jbuck does that sound mostly right?

**Comment by jbuck** [comment]
Take a look at "response - validation rules for the outgoing response payload (response body). Can only validate object response:" in the [hapi api](http://hapijs.com/api)

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/501
