### ISSUE TITLE
Ensure that server logs are being stored somewhere we control

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#473]
Action from #82

**Comment by jbuck** [comment]
We'll use one of the Heroku logging add-ons that has a "archive-to-S3" feature so we can do our own analysis.

**Comment by jbuck** [comment]
We'll use Papertrail or Logentries. Not sure which one yet, but both work in the EU and US regions and archive to S3.

**Comment by jbuck** [comment]
I've enabled Logentries on all 4 apps.
