### ISSUE TITLE
Ensure we only allow certain content types to be uploaded

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#474]
Action from #82

**Comment by alicoding** [comment]
The default that we allow right now are the following:

```

    application/json
    application/x-www-form-urlencoded
    application/octet-stream
    text/*
    multipart/form-data
```
@jbuck should we take off `application/octet-stream` & `text/*`?

**Comment by jbuck** [comment]
@alicoding What content types do our forms and paypal callbacks send us right now? We should just limit it to that
