### ISSUE TITLE
Verify that error handling doesn't leak sensitive information to user

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#476]
Action from #82

**Comment by ScottDowne** [comment]
I can confirm it doesn't leak. Stripe does handle this, but I did make a change that would be good just in case.

We only pass the code and type to the client, not the whole error object.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/commit/4d0a3fa5343165a534d8006da5b777f6457c51a5
