### ISSUE TITLE
double opt in

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#478]
Do we need double opt in with exact target?

cc @valianttry @adamlofting

**Comment by ScottDowne** [comment]
Making as a P1 as a get an answer to this question, the actual work, depending on that answer, might make this a P2.

**Comment by adamlofting** [comment]
Donors will be opting into the same MoFo email list (de language version) as we did for the petition.

The double-opt in will be handled in ExactTarget.

#358 is the ticket to track this work.
