### ISSUE TITLE
Google Analytics Dashboard for German Campaign

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#480]
Hey @adamlofting, I bet we can just reuse the one you made last year. Got a link handy to pop in this bug?

**Comment by adamlofting** [comment]
GA dashboards for:

The existing BSD forms (aka sendto.m.o):
* https://www.google.com/analytics/web/?hl=en#dashboard/Pvut_X9rREKMSQK2M9Mgqg/a35433268w64184110p65898710/

The new MoFo hosted forms (production filter so no data yet):
* https://www.google.com/analytics/web/?authuser=0#dashboard/x2x17FAsShuixRj2bK-YpQ/a49796218w101806119p105783219/

Note: once live, our new pages will have significantly better analytics (100% paypal tracking, distinction between one-time and recurring donations, currency conversion for A/B calculations, and distinct from petition traffic so site wide conversion rate metrics will be much more useful).

cc @valianttry @ScottDowne @alicoding @edrushka @lovegushwa  (let me know if any of you don't have access to view these)

**Comment by valianttry** [comment]
adding @bniolet1 so he can join in the bookmarking fun :smile:

**Comment by edrushka** [comment]
@adamlofting can you please give me GA access to this? Turns out I don't have it. Thanks!
