### ISSUE TITLE
Revive the totalizer API

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#481]
Wouldn't it be great to have the totalizer for the German campaign up and running again?

**Comment by adamlofting** [comment]
We don't need this so much for the DE campaign, but let's get organized for EOY.

We also need to add Stripe donations into the transactions DB so these get included in the total.

**Comment by adamlofting** [comment]
Related #623

**Comment by jbuck** [comment]
@adamlofting I'm working on putting this in a Heroku Space so it's easier to manage

**Comment by jbuck** [comment]
Okay, I have the existing code running in Heroku. Now we just need to figure out the web server API bits!

**Comment by jbuck** [comment]
Okay, this is up and running again: https://d3gxuc3bq48qfa.cloudfront.net/eoy-2014-total
