### ISSUE TITLE
turn on a bunch of languages

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#491]
We have a bunch of languages in varying degrees of translated, some I would bet are as complete as our main 5. I'm not sure how to confirm the completeness, though, so I'm just guessing :P

We have a list in our repo to say "we allow these x languages" anything else redirects to en-us, which is pretty obnoxious. Especially if you're a translator working on one of those unsupported but finished languages.

I say we turn these all on, even if not 100%.

I think this is safe as long as we don't link to an unfinished language in the snippet.

@alicoding thoughts?

**Comment by alicoding** [comment]
I would say lets make this dynamic based on what's in locale directory. Also, we could name it to be an env where we can control for prod.

**Comment by adamlofting** [comment]
This sounds great - let's add a short note about this to the docs at the same time as implementing.
