### ISSUE TITLE
Look at translation tooling that is better than simple key/value replacement

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#5]
Our current translation tooling is a fairly simple key/value replacement. This works great for English, but breaks down for things like:

* Number formatting
* Date formatting
* Pluralization

**Comment by adamlofting** [comment]
Have we decided on our translation tooling yet? If yes, can we add this to the documentation:

*  Add Documentation for Localization into README #56

**Comment by alicoding** [comment]
This is done. I'm using React-Intl which uses FormatJS and they supported all the technology bits that we want. I'm going to document this soon.
