### ISSUE TITLE
Create Stripe account

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#506]
When the Stripe contact is finalized, we'll need Ops (Alex) to input our account details.

- [x] Abigail will inform Adam & Erika when contract is signed 
- [x] @jbuck will create a Stripe account and give Alex account login info
- [x] Alex will input banking details and tell Jbuck and @ScottDowne when that's complete
- [ ] Scott will begin QA

Are there other steps to finalize the account set-up?

cc @valianttry @adamlofting

**Comment by ScottDowne** [comment]
We, probably me needs to:
- [ ] Create monthly subscription plans for each currency.

**Comment by jbuck** [comment]
My only question is: Once I create the account, is there anything we need to do to get it associated with the contract we signed?

**Comment by adamlofting** [comment]
Contract has been signed! :hatched_chick:

go go go! 

:shipit:

**Comment by edrushka** [comment]
:racehorse::racehorse::racehorse:

**Comment by ScottDowne** [comment]
:boom:

**Comment by jbuck** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by valianttry** [comment]
Andrea sent credentials to @jbuck as an "American representative" just now.

**Comment by jbuck** [comment]
We have a working Stripe account! :dancer:
