### ISSUE TITLE
Write "we want to include you in our work" variants

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#507]
We need a selection of copy variants to try to increase conversion on the emails signups (pls ignore mixed English and German in graphic below).

![265b11d8-6214-11e5-9165-072c9c39fd66](https://cloud.githubusercontent.com/assets/4515662/10348087/e0134c44-6ceb-11e5-8862-a899bed64a91.png)

@valianttry @KevZawacki

**Comment by KevZawacki** [comment]
@edrushka Perhaps:

- Stay posted on Mozilla and the open Web
- Learn how your donation is making a difference
- Join the conversation
- Join our community

**Comment by valianttry** [comment]
Is this ticket a duplicate? https://github.com/mozilla/donate.mozilla.org/issues/634

If yes, I wrote some alternate variants in this document:
https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

Suggest closing this ticket if it's a duplicate @edrushka (your call)
