### ISSUE TITLE
Identify DE testing opportunities with redesigned form UI

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#508]
Now that @lovegushwa has redesigned the form UI (#436), there are numerous potential tests to run. Let's figure out what we want to learn, and triage the list of tests for the German campaign.

@adamlofting I defer to you for the final decision, but I might suggest:

1) "This really helps us" note for monthly donations on Page 1 of form  (multiple copy variables to try, if having text improves conversion, and we have snippet bandwidth)

2) "We want to include you in our work" note for email signups on Page 3 of form (multiple copy variables to try. Copy ticket [here] (https://github.com/mozilla/donate.mozilla.org/issues/507).)

**Comment by edrushka** [comment]
Another test that requires very little dev work is testing the social share message. Ticket (for English version) here: #353

**Comment by adamlofting** [comment]
Sorry, I think I've duplicated this ticket in #525 

But that might be a better ticket to work from as it focuses on the BSD form. I think we could start with the "this really helps us" test, and maybe some variations of the snippet . 

If I recall correctly, the social share and email sign-up asks don't exist on the BSD flow for DE. These were new features we were building in to the new form.

**Comment by edrushka** [comment]
Closing this ticket, since #525 has pictures!
