### ISSUE TITLE
Currency always defaults to USD

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#520]
Currently we always default to USD for every locale. I'd argue that we should default to a specific currency for each locale, if possible. For example, German should default to EUR.

**Comment by adamlofting** [comment]
:+1:

**Comment by adamlofting** [comment]
not a hard blocker for launch, but this feels important to me so I'm adding it to the next milestone.

**Comment by ScottDowne** [comment]
Fixed: https://github.com/mozilla/donate.mozilla.org/commit/892425d7cf97752c8d9c463562de76f789b76c6b
