### ISSUE TITLE
facebook share link is not translated

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#524]
Go to donate.mofostaging.net/de/share
Click facebook
Expected: share facebook link should be in german
Actual: in English

**Comment by adamlofting** [comment]
This is because Facebook is trying to scrape the meta tags from the 'live' URL donate.mozilla.org/de but that currently redirects to sendto.m.o as it's still on the BSD setup.

This should be solved once the new platform is live.
