### ISSUE TITLE
Discuss Tests we could run on the existing BSD form with limited development investment

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#525]
* New form is currently blocked on Stripe, and may not be live in time for us to learn much this campaign.
* The old form isn't going to have much life going forward so we want to limit the amount of time we invest in working on it.
* However, at this point in the campaign we have enough traffic to run a couple of small tests and learn things that are useful for our fundraising in the future. Development work that results in learning is worth investing in, even if the code doesn't have a long life. 

--

Current User Flow for reference:

Step 1: User sees this variation of the snippet which has been built to work with existing BSD forms:
<img width="676" alt="screenshot 2015-10-09 14 41 12" src="https://cloud.githubusercontent.com/assets/1901816/10395249/c784c1f4-6e93-11e5-8c1e-7f56a7db4434.png">

Opportunities:
* With no dev required: 
 * We can test copy, highlight color, and button amounts
* With some dev (plus review) 
 * we could test adding a monthly option to this form

Step 2: User lands on the form
<img width="700" alt="screenshot 2015-10-09 14 40 16" src="https://cloud.githubusercontent.com/assets/1901816/10395294/10b235d2-6e94-11e5-80c3-8dcb029d520d.png">

Opportunities:
* With no dev: 
 * we can alter copy / make minor design tweaks using Optimizely. But, there's not actually much content to play with. 
* With some dev:
 * We could add in the 'this really helps us' arrow pointing at the monthly check-box. This feels like a potentially high value to low development effort, and gives us info we can transfer to the new forms when they are live.

Please use this ticket to suggest other test ideas so we can prioritize. Traffic is limited so realisticly we're only going to run one or two tests for this campaign. 

cc: @valianttry @edrushka @ScottDowne @alicoding @lovegushwa

**Comment by adamlofting** [comment]
Notes from discussion with @valianttry and @edrushka just now:

We have decided to start by running tests in the existing snippet template so that no extra development work is required. Engineering work can continue to focus on closing the P1s for the new donation form.

**Comment by ScottDowne** [comment]
I'm pretty sure a "this really helps us" arrow in the form, could but done all in optimizely.

Because of the way BSD lands code changes, it's actually easier and less risky doing it in optimizely...

**Comment by adamlofting** [comment]
> I'm pretty sure a "this really helps us" arrow in the form, could but done all in optimizely.

I forgot to note, we decided not to push too heavily on the monthly giving on BSD form because we don't have a nice way to transfer regular donors out of BSD... :crying_cat_face:

**Comment by ScottDowne** [comment]
Ahhh, makes sense.
