### ISSUE TITLE
Generate New URLs for "Donate" links on mozilla.org

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#545]
After meeting with the mozilla.org product management team at MoCo, we have a list of locales for which we'll need to generate new URLs after switching to our Stripe donation form platform and retiring our BSD forms.

**Tier 1 
English 
German
French
Spanish
Polish
PT-BR
Russian
Italian
Hungarian
Japanese
Dutch
Greek
Indonesian
Czech
zh-TW
zh-CN

**Tier 2
Romanian
Vietnamese
Bulgarian
Norwegian
Slovak
Slovenian
Serbian
Korean
Danish

**Comment by valianttry** [comment]
cc @alicoding 
There will be three different links to click on the homepage that will take you to a donation form:

1. A large promo block that is yet to be designed;

2: Topline Navigation

3. Footer

![nous_oeuvrons_a_ameliorer_internet_ _mozilla](https://cloud.githubusercontent.com/assets/9830371/10496808/4f2f1b9a-7277-11e5-8fe2-b201f246f983.png)
![we re_building_a_better_internet_ _mozilla](https://cloud.githubusercontent.com/assets/9830371/10496811/5528cc44-7277-11e5-9405-06cd2481f953.png)

**Comment by alicoding** [comment]
Once we have donate.mozilla.org point to our new form basically it will work based on the language that was set to the browser's preferences. It looks like we have a lot of locales that we do support in common, but anything that we don't support it will be redirect back to en-US at the moment. I can help coordinate on this once we are ready.

**Comment by adamlofting** [comment]
@alicoding the other part that is needed in these URLs is the GA tracking code to identify where the referral came from.

This tool helps us build those URLs:
http://mozilla.github.io/mofo-campaignurl/

**Comment by valianttry** [comment]
@JennyDouglas and @jbertsch so they are looped!

**Comment by jbuck** [comment]
Using @adamlofting's URL builder I get:

* Header - https://donate.mozilla.org/en-US/?ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=header
* Promo - https://donate.mozilla.org/en-US/?ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=promo
* Footer - https://donate.mozilla.org/en-US/?ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=footer

@adamlofting r? :)

**Comment by valianttry** [comment]
@jbuck we need the gift array to be higher given avg gift from homepage is around $28. So we need an array like this (what you see when you click "Donate" from mozilla.org right now):

![sendto_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/10955895/02fbfa04-830c-11e5-9bf7-094d664fd663.png)

**Comment by valianttry** [comment]
Also @jbuck since this link auto-redirects to sendto at the moment, why not ask @jbertsch to update them asap? Then I presume they'll show the new form once the dns switch happens?

**Comment by jbuck** [comment]
Okay, updated URLs:

* Header - https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=50&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=header
* Promo - https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=50&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=promo
* Footer - https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=50ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=footer

This will result in:

![screenshot 2015-11-04 19 12 10](https://cloud.githubusercontent.com/assets/578466/10956266/468943a0-8328-11e5-8edb-f71339fe24f8.png)

Look good?

@valianttry Unfortunately we can't ship the new URLs until the DNS has been changed because the redirect on donate.m.o is a `301 Moved Permanently` which browsers will cache. If a user has that cached then they will always be redirected to sendto.mozilla.org even once we change the DNS.

**Comment by valianttry** [comment]
Hm, @jbuck i try that URL and it renders like this (note the commas between the amounts switched to percentage sign):

https://sendto.mozilla.org/page/contribute/givenow-seq?presets=100%2C50%2C25%2C15&amount=50&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=header#page-1

And it appears to default back to the smaller amounts version. Halp? :sos:

**Comment by ScottDowne** [comment]
@valianttry not sure if this is your issue, but the presets-100,50,25,15 won't work in the old form (sendto).

I forget how or if we did that last year.

**Comment by valianttry** [comment]
oh right. it's redirecting. So there''s no current way to test the URL?

**Comment by jbuck** [comment]
You can test the URL by change "donate.mozilla.org" to "donate.mofoprod.net"
(which is how I got that screenshot)

**Comment by valianttry** [comment]
ok awesome! I'll share this with @jbertsch

**Comment by adamlofting** [comment]
Spotted one small bug in the footer URL. It needs an `&` after the `amount=50`

Repeated here, with the correction:

* Header - https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=50&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=header
* Promo - https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=50&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=promo
* Footer - https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=50&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=mozilla.org&utm_medium=referral&utm_content=footer

**Comment by jbuck** [comment]
@adamlofting Thanks for the catch! And the URL builder :dancer:
