### ISSUE TITLE
Mail completed Thank You cards to donors e.g. "Ship It"

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#553]
cc @edrushka 

Let's mail these 250 - 300 handwritten thank you cards to donors! To do:

- [ ] Order correct sized envelopes (cards are a standard size, not hard)
- [x] Identify a vendor to hand-address and stamp the cards (Andrea suggests TaskRabbit and has asked Michael to OK using them for this task on an ongoing basis)
- [ ] @edrushka to determine the universe that will receive the cards (monthly donors? >$50 in last 6 months?)
- [x] Confirm with @jbuck and @adamlofting that we only have full mailing addresses for donors who donate by credit card and are therefore in BSD
- [x] Pull addresses for selected universe from BSD 
- [x] Put addresses into a spreadsheet for the TaskRabbit or other contractor to address 
- [ ] Schedule contractor to come to San Francisco office and complete task
- [ ] Hand off addressed envelopes to SF mail room
- [ ] @adamlofting determines who we can "tag" the records of donors we mail cards to in Salesforce

**Comment by edrushka** [comment]
AFAIK we only have about 90 completed cards. Did more come in?

**Comment by edrushka** [comment]
Card details as of Aug 6 from this [duplicate ticket] (https://github.com/MozillaFoundation/2015-fundraising/issues/29)

    Total signed cards = 80
    Total useable cards = 77
    Cards with no signature = 2
    Cards in other languages = 2 (Japanese, Indonesian)
    Dated cards = 2
    Cards with hard to use addressee ('Hey guys', 'Dear Dorthy' 'Hi There Insert name' = 3
    Mofo cards = 45
    Moco cards = 33

**Comment by valianttry** [comment]
oy i overestimated. Nick took a stack of maybe 125 to MTV for people to fill out... but right now sitting in my office is what you accounted for ya.

**Comment by edrushka** [comment]
May I suggest we wait until post mozFest and post Nick delivery? Then we'll have a nice stack :)

**Comment by valianttry** [comment]
Mozfest should send from London vs. shipping here

**Comment by edrushka** [comment]
I like the idea of mailing locally (not so much to save money, but to show our global presence).

We'll need to "identify the universe" so we can shortlist our UK donors.

Also, who will address the MozFest cards? The fact that this uses private info means it's not really suitable for MozFest attendees (plus, I think it would be next to impossible to find people to do that in the chaos of the festival).

**Comment by valianttry** [comment]
@edrushka do you think the London office manager or Ops person there might help identify a task company or temp agency? Like taskrabbit in the UK?

**Comment by valianttry** [comment]
Confirmed: We have a Task Rabbit business account and I have the credentials. The plan will be to invite a temp to come to the SF office and hand-address envelopes once we have Nick's MTV stack (just emailed him).

**Comment by adamlofting** [comment]
Identified donors in #650 

Also noting that there were a relatively small handful of Mozfest cards ~20, so I'll post these myself.

**Comment by edrushka** [comment]
Awesome, Adam! Thanks for pulling those donors into a list. @valianttry Any update from Nick?

**Comment by valianttry** [comment]
I have a small stack of additional cards from Nick, maybe 10 or so. We're ready to pull addresses I suppose @edrushka ?

**Comment by adamlofting** [comment]
Addresses are ready in a Google Doc that's been shared with restricted access. I'll resend the link by email.

**Comment by edrushka** [comment]
I will bring the leftover cards to Orlando on the off-chance we'll get a few more signed. That shouldn't stop us from getting started with TaskRabbit before Orlando if you have the bandwidth, @valianttry

**Comment by edrushka** [comment]
Bumping this for January. cc @stephaniemcv
