### ISSUE TITLE
Write EOY snippet variants for 2015

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#557]
In addition to the best performers from 2014, let's draft some new EOY snippet variants this year. Although these will be localized, our biggest EOY contributions come from English locales, so these variants should be written with native English audiences in mind.

For reference:
- here's [2014 EOY snippet copy ideas] (https://old.etherpad-mozilla.org/eoy-snippet-text-variations) 
- and the [five variants we ended up testing] (https://docs.google.com/document/d/1cHEIstdzc-G-Ctbc368pwwkCBfNq8vRBVf2wedvhPWo/edit) last year

Some helpful advice @adamlofting provided in the [bug] (https://bugzilla.mozilla.org/show_bug.cgi?id=1112333) last year: *"to keep the snippet fresh in repeat visitors eyes, I think we need to mix up the opening words a bit: http://www.nngroup.com/articles/first-2-words-a-signal-for-scanning/ "*

Also, let's keep in mind that L10N will have a significant impact on the length:
![20120331_woc931](https://cloud.githubusercontent.com/assets/4515662/10529291/5ffd1b18-7351-11e5-9c56-abdb65b03ea8.png) 
[Source] (http://www.economist.com/blogs/graphicdetail/2012/03/daily-chart-21)

cc @valianttry @KevZawacki

**Comment by edrushka** [comment]
Assigning this to the Nov 6 milestone, but we'll likely have to work on asynchronously due to Andrea's PTO and MozFest travel.

**Comment by valianttry** [comment]
We already began drafting snippet copy in partnership with the Community Engagement team:
https://docs.google.com/document/d/1GrV5AECse92F--4btS24GIdyu7mUq6nAGCtHUveZrRM/edit

**Comment by edrushka** [comment]
Closing, as this done.
