### ISSUE TITLE
Design EOY homepage takeover

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#558]
During the final stretch of our EOY campaign, we get to take over mozilla.org :tada::tada:

Here's what last year's design looked like:
![skitch](https://cloud.githubusercontent.com/assets/4515662/10529572/f97da7ec-7353-11e5-9634-7e63d8ee3c62.png)

We'll need to do something similar this year. Our MoCo contact on this is Jen Bertch, who will hopefully be on Github shortly.

**Comment by adamlofting** [comment]
My ask would be to include the 'Other' input field and the one-off/monthly toggles on this page too to match the form on our donation flow.

Otherwise users will select an amount, and when they land on donate.m.o they will bypass the first screen and never see the option to make a montly gift, or to customise their donation amount.

<img width="383" alt="screenshot 2015-10-23 11 52 39" src="https://cloud.githubusercontent.com/assets/1901816/10690871/b4eb0474-797c-11e5-836e-d51d9e03d2f7.png">

**Comment by lovegushwa** [comment]
cc @natalieworth

**Comment by edrushka** [comment]
Last year's version in PSD form - hopefully this will indicate specs: https://www.dropbox.com/s/3pvwbwty7zz345f/MozOrg_Homepage-EOYFundraiser2014_Takeover-PromoTiles.psd?dl=0

**Comment by edrushka** [comment]
Adding @jbertsch who's on Github! :ok_woman:

**Comment by valianttry** [comment]
Update from @JennyDouglas on our timing -- it's TIGHT! @lovegushwa can @natalieworth move this FW while you're in Mozfest vortex? I'm getting a little worried about meeting these deadlines....

**Homepage Tile Go Live Date: November 15**
Final assets delivered by Nov 10 to MoCo to have 3 days for implementation, stakeholder review and code review.

**Homepage Takeover Go Live Date: December 1**
Final assets due no later than Nov 18 since it's more complex than the tile and Thanksgiving is the week before.

cc @edrushka

**Comment by JennyDouglas** [comment]
One more thing :) Nov 15th is a Sunday, so it will be the 16th.

**Comment by edrushka** [comment]
@cassiemc - your thoughts on @natalieworth taking this on? Deadline is right around the corner.

**Comment by edrushka** [comment]
Due date is Nov 10.

**Comment by valianttry** [comment]
Waiting for Matej's review of copy, but if you want to use it for placeholder in design here it is:

**Mozilla is proudly non-profit — donate today
Join millions around the world who are helping us continue our mission to keep the Web open and free.**


----
Last Year's copy for reference:
Your Gift Helps
People everywhere are helping us build the Internet the world needs — an Internet where the public good comes first.

**Comment by valianttry** [comment]
@natalieworth Adam's comment here outlines the basics of the gift array design: https://github.com/mozilla/donate.mozilla.org/issues/558#issuecomment-150542749

Amounts should be: $100, $50, $25, $10 [other]  *one time *monthly

**Comment by lovegushwa** [comment]
Takeover and tile options, discuss on #559

![takeover-sketch_3](https://cloud.githubusercontent.com/assets/12228435/11042346/7248e45c-870e-11e5-9a56-9529655daaf5.jpg)

**Comment by valianttry** [comment]
I'm putting takeover input in this ticket.
My preference out of these homepage takeover designs is the dino of course :dancers:

I'll suggest minor copy edits to all three in this ticket. We should add the deadline and update the amount arrays to reflect the average gift on mozilla.org. Let's use 100,50,25,15 with default at $50.

![abec118e-870e-11e5-870b-9f8ae97e9765_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11044303/fa3353ae-86d5-11e5-8988-a667f527f729.png)

**Comment by valianttry** [comment]
Suggested copy change for takeover C "Proudly non-profit, thanks to supporters like you. Donate before December 31." + higher gift amounts.

![abec118e-870e-11e5-870b-9f8ae97e9765_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11044493/112cc602-86d7-11e5-8e8a-1bcd92b53550.png)

**Comment by valianttry** [comment]
Takeover A: Mr. Fox
He is a little big, what do you think about reducing his size a bit? I wonder if he'll be distracting at the size he is.
Proposed copy change:
"Proudly non-profit. Donate before December 31."
New gift arrays.
![abec118e-870e-11e5-870b-9f8ae97e9765_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11044601/c2384d40-86d7-11e5-9fc6-955d9a5d90d9.png)

**Comment by natalieworth** [comment]
Hi @valianttry , thanks for the feedback. I've put everything up on redpen too so it's easier for critiques and made some updates based on your feedback: https://redpen.io/gxec41057d237039c9

@lovegushwa I made a couple small adjustments that I've posted on redpen too if I could get your feedback on. Thanks!

**Comment by jbertsch** [comment]
Hi All and @lovegushwa -

I think we are moving forward with C for the www homepage tile.  Please provide the background color and fox & heart icons here:  https://bugzilla.mozilla.org/show_bug.cgi?id=1223622#c2

Thanks!!!

**Comment by natalieworth** [comment]
Hi @jbertsch, I think Jordan is possibly travelling today. I have this .ai file for the tile in the google drive: https://drive.google.com/drive/folders/0B2qu3ExKWIlvVFJDTExyRWQ2Q28 I don't have access to the bug. Let me know if these are the right specifications/ file type. If not, I can create or export anything asap. Thanks!

**Comment by natalieworth** [comment]
@lovegushwa Most recent .ai file is here: https://drive.google.com/open?id=0B2qu3ExKWIlvTXZLRThsbDgwdVE

Redpen link is here: https://redpen.io/p/fq7b05b03cccce05c8

Ping/ email me tomorrow if you need help with anything. It's a Canadian holiday, but I'll just be chillin at home.

cc @valianttry

**Comment by edrushka** [comment]
Re-assigning back to @lovegushwa . Thanks for your help with this last week Natalie!

**Comment by lovegushwa** [comment]
final artwork here:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvTGlhZExDTThWYUE/view?usp=sharing

R+ from Tim and Sean
