### ISSUE TITLE
Design EOY directory tile(s)

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#559]
Happily, we'll get lots of Tiles exposure this year! 

#### A few things to note for 2015:
- Fatigue is an issue - need a few designs to swap in
- Tiles will be localized in top 6-8 tile locales
- Tiles must be PNGs. There's no interactive functionality yet, so we can't try integrating parts of the form right on the tile. However, Tile team is willing to test a specific amount (average for locale) in the design.
- Tile will send people to a version of the form with additional context #550 

#### Resources:
Last year's design: https://bug1076000.bmoattachments.org/attachment.cgi?id=8522356
Most recent tile specs should be here: https://github.com/mozilla/2015.mozillafestival.org/issues/159
Notes from our meeting with Tiles team: https://docs.google.com/document/d/1PzemgAH-Uzq6i0mlkonjSzAMwuDPHbJ22uyorgp6X8k/edit
Current Tiles on staging: http://rlr.github.io/webtiles-previewer-redux/

@lovegushwa To Do: Design ~4 tile variations, one of which contains the average donation amount.

**Comment by valianttry** [comment]
One notable thing is that the Tile team noticed a big lift when the wordmark is prominent, so we should just design every one with a prominent "mozilla" wordmark in the static version, and possibly on rollover as well. And, they said "go bold so it pops".... i suspect @lovegushwa will have fun with that :stuck_out_tongue: 

Here are some copy variants to try on Tile designs (please hack, or add, or veto). They are based on the non-corporate language testing the Marketing team did, and on snippet copy the MoCo Engagement team already put together:

A static: [mozilla] Proudly non-profit, non-corporate and non-compromised.
A on rollover: Every donation helps us stay true to our non-profit mission. Give now.

B static: [mozilla] Dear Firefox users: every donation helps Mozilla stay true to our non-profit mission
B on rollover: If everyone reading this chipped in $X, we would be supported for another year. Donate now.

C static: [mozilla] We're the nonprofit maker of Firefox. We rely on donations.
C on rollover: Our year-end fundraising campaign ends December 31. Donate now. 

D static: [mozilla] Love Firefox? Your year-end gift keeps Mozilla going strong.
D on rollover: Thousands of users like you chip in an average of €5. Will you join them? Donate now.

**Comment by valianttry** [comment]
cc @bniolet1

**Comment by valianttry** [comment]
@KevZawacki Jean just mentioned these might be too long. Want to try coming up with some variations that are shorter? We could also repurpose for social maybe....

**Comment by valianttry** [comment]
FYI Jean and MJ are working on copy here that's shorter:
https://docs.google.com/document/d/1GrV5AECse92F--4btS24GIdyu7mUq6nAGCtHUveZrRM/edit

Kevin if you want to rif or hack some copy too that would be good, i would edit theirs directly but add.

**Comment by cassiemc** [comment]
@natalieworth can probably help with this stuff. We'll need to brief her.

**Comment by edrushka** [comment]
Awesome! I'll book a meeting for next week and we can get her started.

**Comment by edrushka** [comment]
https://public.etherpad-mozilla.org/p/eoy_2015_tiles

**Comment by lovegushwa** [comment]
@natalieworth  check out some new tile and mozilla.org options based on feedback from Sean Martell. @valianttry Can you confirm these need to go to MOCO tomorrow for review? 

@natalieworth please add one more option based on the grid of hearts found in:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvQlhVX0dyWFpWejA/view?usp=sharing

Mozilla.org file is here: (please use it to add a option D then export a similar graphic as below and re-post for @valianttry )
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvMHFBVk9wdm0tYzA/view?usp=sharing


![takeover-sketch_3](https://cloud.githubusercontent.com/assets/12228435/11042384/abec118e-870e-11e5-870b-9f8ae97e9765.jpg)

**Comment by valianttry** [comment]
@lovegushwa these are both dashing and fierce at the same time!! :smiley: REALLY NICE job on these!

I have very little in the way of feedback -- just some copy tweaks that are hopefully easy.

TILE A. I spoke to Tim and Jean also mentioned that it's better to make the static tile almost a "standalone" by itself that is clear about what you are asking people. "Teaser" tiles tend not to work as well according to Jean. So I propose this copy change to Tile A:
Static: Support the non-profit behind firefox
on rollover: Thousands of users like you chip in an average of 5 to Mozilla [DONATE NOW]

![7248e45c-870e-11e5-9a56-9529655daaf5_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11043786/4b8feb02-86d3-11e5-9fd0-9d025469e248.png)

**Comment by valianttry** [comment]
Tile B suggested copy changes:
Static: ONE Internet. Give now. Help protect it.
Active: Stand with Mozilla, the nonprofit behind Firefox.  [DONATE NOW]

I kind of like associating "fight" language with the dino head -- e.g. the "fierce advocate" side of Mozilla, if that makes sense.

![abec118e-870e-11e5-870b-9f8ae97e9765_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11044040/75ab00ce-86d4-11e5-9cf8-84b70ca61e67.png)

**Comment by valianttry** [comment]
My preference out of these homepage takeover designs is the dino of course :dancers: 

I'll suggest minor copy edits to all three , but the dino one is fairly straightforward -- we should add the deadline and update the amount arrays to reflect the average gift on mozilla.org. Let's use 100,50,25,15 with default at $50.

![abec118e-870e-11e5-870b-9f8ae97e9765_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11044248/a60add7e-86d5-11e5-82ae-4e09e14d375b.png)

**Comment by valianttry** [comment]
I like this Tile C as-is (no edits). However, the fox is a different design than the dapper top-hat fox, are we OK having different foxes?

![abec118e-870e-11e5-870b-9f8ae97e9765_jpg__jpeg_image__5000 x 3000_pixels_](https://cloud.githubusercontent.com/assets/9830371/11044408/94c32d04-86d6-11e5-8c73-5796cf909a1b.png)

**Comment by lovegushwa** [comment]
Hi yes two foxes are OK. These are proposed directions / could be tests so
it would be great to see what does best. Word on the street option 1 is
very popular with mofo peeps.

**Comment by lovegushwa** [comment]
@natalieworth can you incorporate copy changed from @valianttry and repost ?

**Comment by valianttry** [comment]
@natalieworth "non-profit" should be hyphenated throughout (sorry I missed this in the Tile C and other places)

**Comment by natalieworth** [comment]
@valianttry @lovegushwa Hey, here's the updates for the EOY takeover pages. I'm still not 100% liking the heart pattern one. I'll keep working on it tonight though and post tomorrow morning if I make better progress on it: 
![takeover-sketch_5-01](https://cloud.githubusercontent.com/assets/14876567/11052101/eea0c8bc-8709-11e5-882a-d8e08eba2b67.png)


@lovegushwa For the 1st (dapper fox) one. I was kind of experimenting with adding some definition to it with shadows. Not sure if it's working yet or if you'd prefer everything to be more iconographic/ flat?

Thanks! :)

**Comment by valianttry** [comment]
@natalieworth  the tiles look good -- FYI I put feedback for the homepage takeover in the ticket here: https://github.com/mozilla/donate.mozilla.org/issues/558#issuecomment-155167708

@lovegushwa is your preference not to use redpen for feedback? I find it a little more difficult to do screengrabs and mark up vs. redpen. If you've got a good reason not to use redpen don't sweat it (just wondering).

**Comment by edrushka** [comment]
These have been shipped! Final Artwork here: https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvZGJ4d1RoNVNnZkk&usp=sharing

Great job, Jordan! :rabbit2::rabbit2::rabbit2: Closing this ticket. Will create new tickets for L10N and design iterations.

**Comment by edrushka** [comment]
Update Tiles without the period after "Dec" https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvZGJ4d1RoNVNnZkk&usp=sharing
