### ISSUE TITLE
Design "Spectacular Snippet" for last critical days of the campaign. 

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#560]
Every year we reserve the last few days of the year for a snippet that users can't ignore, and it has paid off for us. For last year's Spectacular Snippet we switched the Firefox background color to a shade of yellow and used the highest performing text and that snippet yielded over $277,000 in 3.5 days (avg $6 / 1000 impressions). Here's what it looked like:

![about_home_snippet_preview](https://cloud.githubusercontent.com/assets/9830371/10533950/dfd3e65e-7384-11e5-8482-819607441b11.png)

**For 2015's Spectacular Snippet**
- [ ] We need a simple concept (such as reverse text on dark background; or a different background color) @edrushka @adamlofting I'm thinking we might crowdsource some ideas?
- [ ] We also need to write copy variants in EN leading up to EOY @KevZawacki do you want to work on some drafts, maybe borrowing some ideas from Wikipedia's tests, below?
- [ ] We should replicate the disruptive snippet in DE if we can @alicoding 
- [ ] We also need to make sure the MoCo Creative Team, Firefox Product and Marketing teams are looped into our plans and give them opportunity to give feedback, raise flags; etc. @bniolet1 

Below are screen grabs from banners that Wikipedia tested July - September 2015 (found here: https://meta.wikimedia.org/wiki/Fundraising):

## Best performing:
![sept2015bannerex_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533685/9c76062e-7381-11e5-822e-f2f9b529b7df.png)

## Second best performing:
![july2015bannerex_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533699/d9c16fc8-7381-11e5-83ab-7db253fab705.png)

## Others that performed less well (in no particular order):

![treesbannerex_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533713/08876ab0-7382-11e5-9a28-899d0d912b14.png)

![commonsbannerex_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533714/16d3dc5c-7382-11e5-86cf-51d1ecba7a45.png)

![commonsbannerex2_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533716/23dede88-7382-11e5-9e3b-e0f2a96f6a7d.png)

![commonsbannerex3_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533719/2f868a88-7382-11e5-84db-275f87c14d1e.png)

![graphicbannerex_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533721/3ad3bd5c-7382-11e5-8dd3-0edba0ab3f72.png)

![screen_shot_2015-10-09_at_7_46_46_pm_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533730/49e6613c-7382-11e5-867c-e7baf7f56921.png)

![screen_shot_2015-10-09_at_7_46_10_pm_-_fundraising_-_meta](https://cloud.githubusercontent.com/assets/9830371/10533736/577c85ba-7382-11e5-83c9-cd6e73c8d06f.png)

**Comment by valianttry** [comment]
cc @cassiemc this is ripe for crowdsourcing ideas somehow... and potentially will raise up to $350 - $500,000. :smiley_cat:

**Comment by cassiemc** [comment]
This would be a good opportunity to get all the designers together for a brainstorm. I'll set that up. What are the timelines? @valianttry

**Comment by valianttry** [comment]
@edrushka can you help think through the timeline and logistics? We would want to do the same type of strategy as last year: Come up with a few ideas, build 1 - 3 for testing to be completed by December 25, then turn ON the winning snippet for the l last few days of December.

**Comment by edrushka** [comment]
@ScottDowne - we want to limit dev work on this (equivalent to the work needed to do the yellow snippet). Can you provide some guidelines for design?

**Comment by ScottDowne** [comment]
@edrushka Pretty much as much we can leverage of the existing snippets would be best for dev.

We have two right now, and we don't actually know which one is going to be the best non disruptive snippet yet.
- simple: http://scottdowne.github.io/eoy-snippets/simple-snippet/
- updated: http://scottdowne.github.io/eoy-snippets/2015-snippet/
- or another variant if we get time

Being able to modify one of these to be disruptive would be better than something new. It would leverage previous dev work and previous test data. It's a good start.

 I think it would be helpful to make it clear what stuff our snippet can already do without a dev.
- Changing background is easy and requires no dev. Can also use an image.
- Changing colours or buttons, highlight area, and text.
- Button state animations. On hover or a few seconds after page load. We never actually used these last year.

Moving around element positions or sizes in the snippet takes some dev, but for small changes it's fast.

**Comment by edrushka** [comment]
Copy being written here #636 (if we're using something different than normal snippet copy).

**Comment by edrushka** [comment]
Would like to get this rolling when @cassiemc is back from PTO.

**Comment by edrushka** [comment]
cc @natalieworth

**Comment by edrushka** [comment]
Here's a spectacular iOS snippet recently designed by MoCo: 
![ios](https://cloud.githubusercontent.com/assets/4515662/11219668/8045a812-8d10-11e5-9fa1-814a4625d1df.png)

**Comment by edrushka** [comment]
Some of Jordan's ideas for #550 could be modified into a great spectacular snippet design. I'm thinking [branded fox/heart] (https://redpen.io/ave485e6ac3bb9bf6c) idea and the [photo background] (https://redpen.io/oa288e50f46de6dda5) idea.

**Comment by edrushka** [comment]
Update: @natalieworth and @lovegushwa are going to produce 3 sketches this this week to run past @adamlofting. Natalie and @cassiemc will continue to refine next week with the goal of showing MoCo team sooner rather than later.

**Comment by cassiemc** [comment]
Yes, this works. The directions we discussed were 1) simple color change as per wikipedia's examples above 2) a graphic example, as per https://redpen.io/ave485e6ac3bb9bf6c if I'm not mistaken 3) and a last one with a photo as the main element. New ideas might pop up in the interim.

**Comment by lovegushwa** [comment]
@cassiemc @edrushka we also have this silly gold mine from the August work week:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvdjRuREtnYXZNblE&usp=sharing

**Comment by edrushka** [comment]
![img_20150805_142647](https://cloud.githubusercontent.com/assets/4515662/11381771/d82432d6-92b2-11e5-8857-7c414044b302.jpg)
Yes! I forgot about these. IMO, this one ^ is ready to ship!

**Comment by valianttry** [comment]
@edrushka i approve! We can just skip Tim and Sean..... :stuck_out_tongue_winking_eye:

**Comment by lovegushwa** [comment]
lol, (that's what dinosaurs actually looked like.)

**Comment by edrushka** [comment]
Assigning to @natalieworth since she's pushing this forward.

**Comment by natalieworth** [comment]
Updates and a few more iterations are up on redpen: https://redpen.io/p/mue49223c009a1c1d4
cc @cassiemc @lovegushwa @valianttry @edrushka

**Comment by cassiemc** [comment]
These are great @natalieworth. @edrushka what's the timeline on these for getting them built? (will help us figure out when to stop feedback).

My favorite versions in order of preference are:

1. the [black background ascii version](https://redpen.io/ne461b5267beb0d295) – I'd be thrilled if this could go in the dev version as per @valianttry's redpen comment, that'd be awesome
2. the [large heart with hat-tipping fox](https://redpen.io/cmdf663a91d08e96e8)
3. the [" :heart: mozilla" simple version](https://redpen.io/ab954b75dd8d66180a)
4. [the bold text option](https://redpen.io/uj8720d0d6a304e9c1)
5. [the photo version](https://redpen.io/ot296a8b2d711d77ca) – seemed to me from the wikimedia learnings that photos didn't convert as well. Eager to see if this holds up with our audience.

**Comment by edrushka** [comment]
@cassiemc  We need to get MoCo feedback before we build. We don't want to put too much time into a concept the Snippet crew doesn't like, since they have the ultimate signoff. My goal is for us (MoFo) to decide on the concepts we like in Thursday's meeting, do any minor polishing on Thursday/Friday and then send them to the Snippet team for their initial feedback on Friday. Hopefully we can have some convos in Orlando and *maybe* even jam together on finishing 1 or 2 designs. With the snippet team's signoff, we can finalize the design and start the build the week after Orlando. Make sense?

**Comment by cassiemc** [comment]
sounds good @edrushka!

**Comment by natalieworth** [comment]
@edrushka That works! Feel free to ping/ vidyo me too if it's easier for you guys while your in Orlando

**Comment by natalieworth** [comment]
Updates for the spectacular snippet are in this redpen project: https://redpen.io/p/mue49223c009a1c1d4
Here is an overview of the newest snippet designs: https://redpen.io/pk016b921fe89e0fa5
It would be great if we could choose favourites/ preferred and then start refining the 4 from there? Perhaps one of each from the different directions Jordan started these off with (photo-based, ASCII/developer edition, established branding with fox or heart, and typographic option).
Thanks! cc @cassiemc @lovegushwa @valianttry @edrushka

**Comment by cassiemc** [comment]
Feedback from jean's team: 

High-level initial feedback:
A) These designs are bad-ass and out of the box. Great thinking.
B) We have to be careful about some of these designs as it can look like the page was hijacked (the black screen for instance)
C) Firefox has to live somewhere
D) I really don’t think we should move the search box. It’ll be way off the typical UX experience and remember this is a page that is built into the product - most people have it by default.
E) We need to provide an opt-out 
F) Need to include a brand representative into this conversation 
G) I’m thinking for consistency sake - we stick with Dapper Fox as opposed to black screens, pictures, etc. 
H) I know potato gun is friendly, but I don’t think we should use the word gun in there
I) I really do love some of these ideas - we just need to figure out how to make it work for the start page!

**Comment by lovegushwa** [comment]
Lol, potato gun. totally ... We could say "potato cannon" or maybe less
exciting "catapult."

**Comment by cassiemc** [comment]
Update from the meeting – @natalieworth is going to take a stab at these refinements:

1. update this version: https://redpen.io/wh7de28276751c0ff8 with less 'in your face' orange background. afraid it might deter folks

2. try a version of this, if we can make the photo take over less of the page. not sure it'll work with the above layout requirements but somehow we would like to test how a photo does. https://redpen.io/zf08f543ba9259f168

3. possibly if there's time, do a toned down version of https://redpen.io/cmdf663a91d08e96e8. (red and orange full backgrounds are problematic, might scare users)

The black / dark versions we're going to reserve for the Dev edition as a separate task.

**Comment by valianttry** [comment]
Update from Jean Collings: There are UX challenges with Dev Edition that make it a bad time to present this type of big change to those users. We won't be putting any fundraising in the Dev Edition snippet.

Please please hang on to these! I want to use them someday for certain. 

:disappointed:

**Comment by edrushka** [comment]
I moved the Dev Edition designs to this ticket #1060 in Bluesky so we will not lose this great work.

**Comment by valianttry** [comment]
Just pasting a new Wikipedia banner here. I just noticed it while I was looking something up on their site:

![maroon_shining_parrot_-_wikipedia__the_free_encyclopedia](https://cloud.githubusercontent.com/assets/9830371/11620499/6d30ad28-9c68-11e5-86db-9dbe99117b66.png)

What's interesting to me:
* Reverse copy is also something we've tested and worked well
* The phrase "Only a tiny portion of readers give" -- we should test "Only a tiny portion of Firefox users give"
* The black portion is actually a giant arrow pointing at the amounts
* "Please help Wikipedia" above the form fields, we could test "Please help Mozilla"
* They have SO many different amounts! 7 vs. our 4

@adamlofting

**Comment by edrushka** [comment]
@valianttry copy for Spectacular Snippet is here: https://github.com/mozilla/donate.mozilla.org/issues/636  If you want to make changes, please do it in the doc and inform @natalieworth Thanks.

**Comment by natalieworth** [comment]
Hi @valianttry @edrushka @cassiemc , working on revising the previous snippets but have the dapper fox and heart versions (excluding the photograph one) up on redpen: https://redpen.io/p/aq98e22f312df2c903 Main changes include:
* desaturating the orange/ brightness of the backgrounds
* Maintaining the search UI and Firefox logo in normal positions
* I also eliminated the majority of the red (I felt the yellows/ oranges were friendly. In retrospect I feel the red is quite jarring if overused)

**Comment by edrushka** [comment]
These are super @natalieworth! Cassie, Andrea please let me know if we need to eliminate any before we share this with Moco. Also, Andrea - are you good with this copy? Best to get as close as possible before we share with Moco.

**Comment by natalieworth** [comment]
Thanks for the feedback from the fundraising meeting @valianttry @edrushka. I was able to update the Redpen with the final snippets based on the feedback: https://redpen.io/p/kgb47de90492f74e6b I've added the 'x' dismissal too, I wasn't able to find the one from last year (if there was the option to dismiss the message?) so let me know if this one works. If everything's all good, I can put the .ai file together and upload to the google drive. Thanks! :)
cc @cassiemc @lovegushwa

**Comment by edrushka** [comment]
Super!!!  @valianttry please let me know if you have any changes before I share these with Jean for her team's feedback.

@natalieworth let's hold on off exporting the .AI files until we hear back from Jean. She may have some required changes.

**Comment by natalieworth** [comment]
Sounds good!

On Thu, Dec 10, 2015 at 5:19 AM, Erika Drushka <notifications@github.com>
wrote:

> Super!!! @valianttry <https://github.com/valianttry> please let me know
> if you have any changes before I share these with Jean for her team's
> feedback.
>
> @natalieworth <https://github.com/natalieworth> let's hold on off
> exporting the .AI files until we hear back from Jean. She may have some
> required changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/donate.mozilla.org/issues/560#issuecomment-163612020>
> .
>



-- 
Graphic Design Intern, Vancouver
natalie@mozillafoundation.org

**Comment by valianttry** [comment]
I just saw a new variant on Wikipedia. Note how the arrow now points AT the 'Phrase that pays'. Can we add a variant of the "arrow" version that does this @natalieworth ? :
![peccary_-_wikipedia__the_free_encyclopedia](https://cloud.githubusercontent.com/assets/9830371/11731107/1ad81ac8-9f67-11e5-9389-a5525ccc241f.png)

**Comment by natalieworth** [comment]
Hi @valianttry @edrushka I've added 3 more versions with the arrow pointing to the '$3 phrase'. Let me know if they work, or we could try something else too. Thanks! :) https://redpen.io/p/kgb47de90492f74e6b

**Comment by valianttry** [comment]
@natalieworth :tada: :cake: :boom: :clap: :smiley_cat:

**Comment by edrushka** [comment]
Yay! Jean and the snippet team have approved 3 designs for us to build! I'm going to create a separate ticket to design final comps for scott to build. Closing this. Thanks everyone for your hard work and creativity!
