### ISSUE TITLE
Clarify design of snippet opt-out button

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#567]
@lovegushwa can you report here when you have the design specs for this? Thanks.

**Comment by edrushka** [comment]
FYI here's the dev ticket: https://github.com/mozilla/donate.mozilla.org/issues/272

**Comment by lovegushwa** [comment]
@ScottDowne anything need to be done here still or can I close this ticket?

**Comment by ScottDowne** [comment]
Yeah, I think we can close this. This exists, so any new tickets should be improve a specific area or task.
