### ISSUE TITLE
Add more friends to this Repo who are helping with EOY planning

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#568]
More MoCo friends are joining the party:

Jen Bertsch: she says her Github handle is "jbertsch"
Jenny Douglas:  jdouglas@mozilla.com

cc @simonwex

**Comment by edrushka** [comment]
@jbertsch has been added :bowtie:

**Comment by valianttry** [comment]
Jenny's handle is @JennyDouglas

Please add her @edrushka or @simonwex ?

**Comment by adamlofting** [comment]
Added :+1:
