### ISSUE TITLE
Tweak to Stripe Privacy Policy text

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#582]
[Tiny task :smile: ]

In the footer, can we please change the text from...

> We use Stripe for credit card processing. For more information see their Privacy & Terms.

To...

> We use Stripe for credit card processing. For more information see their Privacy Policy.

And link to https://stripe.com/privacy 

(Stripe handles the locale redirects on their end)

**Comment by adamlofting** [comment]
@alicoding I've submitted a [PR](https://github.com/mozilla/donate.mozilla.org/pull/583) to update this in en-US - do I need to do anything to flag this String for update in other locales?

**Comment by alicoding** [comment]
@adamlofting they will eventually see that the string is not translated, but if we want to make sure it gets translate on time we will need to send an email to the dev-l10n list to let them know there are updates to the project.

**Comment by jbuck** [comment]
@adamlofting @alicoding what if you defined it as a new string instead? That way they'll see a new string that needs to be translated
