### ISSUE TITLE
config prod envs

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#584]
I also think this might be a good time to get and test prod paypal creds?

**Comment by jbuck** [comment]
Stripe is working, Paypal isn't.... yet.

**Comment by jbuck** [comment]
Okay, I think the figured out the Paypal error. @ScottDowne wanna try again?

**Comment by ScottDowne** [comment]
@jbuck http://1.bp.blogspot.com/-RpeU0Q5AmBU/VOjJv_Jc2uI/AAAAAAAAHEU/fLrQE1qoGpA/s1600/post-40618-Han-Solo-were-all-fine-here-no-2dLR.gif
