### ISSUE TITLE
Mirror code repo

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#59]
As a backup in case of Github downtime during peak campaign activity.

- [ ] Mirror to a private repo
- [ ] Share admin access to private repo with 2 other Engineers
- [ ] Note this in the readme

Low likelihood of needing to be used, but also a low effort investment to mitigate this risk.

**Comment by jbuck** [comment]
The code repository is mirrored on every developers computer & Heroku.
