### ISSUE TITLE
Write a blog for FMO

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#593]
Write a blog for FMO about your work so far in fundraising.

Bonus points for pictures or screenshots.

On your mark, get set, WRITE! :pencil2::pencil::pencil2::pencil::pencil2:

Nov 6 Milestone. No excuses! ;)

**Comment by ScottDowne** [comment]
I'm thinking a post on how to implement an AB test inside react.

**Comment by edrushka** [comment]
Nice! Will you profile a specific test? Would be cool if you could, and we could share results, which will make the blog relevant to both testing nerds as well as react users.

**Comment by ScottDowne** [comment]
I'm also thinking about a blog post on how to setup a version of the donation form that's re branded.

@edrushka If I got the AB test post first though, it would profile a few tests, and how they fit together, mostly it would be how other tests fit with the new flow test, and where react makes it easier.

**Comment by edrushka** [comment]
ahh, gotcha. cool, that works.

**Comment by ScottDowne** [comment]
Uhh, so I did a brain dump for everything that is new that I want to feedback down into a blog post.

https://public.etherpad-mozilla.org/p/1CjoR7nU0s

I would love for simple feedback like grammar spelling typos etc. But, I would also love for feedback like content and jargon usage.

I should probably add some images?

**Comment by valianttry** [comment]
@ScottDowne did some line editing / copy editing and left a few comments. 

Really great work here! And WOW it's amazing how much you've / we've accomplished!! :fist:

**Comment by ScottDowne** [comment]
lol done
