### ISSUE TITLE
Decide on plans for coping with a hosting failover

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#60]
Assuming our primary hosting fails (e.g. Heroku instances), how quickly can we failover to a backup scenario?

- [ ] Can all deploys to our primary production hosting also deploy to our failover hosting? (e.g. configure as part of Travis deployment)
- [ ] Decide if this is an alternate provider, or an alternate region with the same provider
- [ ] Decide whether we manage this failover at DNS or CDN level
- [ ] Document how to manually switch (in readme, or make a note in readme)
- [ ] Ensure at least 3 engineers know how to do this and have access
- [ ] Can we automate the failover if primary hosting doesn't respond for X minutes?

**Comment by jbuck** [comment]
I filed a ticket with Heroku to see if we can do DNS-based failover between Heroku regions: https://help.heroku.com/tickets/259504

If you can't see this ticket let me know and I'll add you to the shared list!

**Comment by jbuck** [comment]
What we'll do is deploy to both Heroku regions. If we need to fail-over from us to eu or vice-versa, we can simply modify the CloudFront configuration and be up and running in 5-10 minutes. Static pages cached by the front-end will continue to be served, so we'd just need to have some smarts on the client to handle "API is down".

**Comment by jbuck** [comment]
Issue #263 will help polish this off
