### ISSUE TITLE
TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#600]
If we are using latest version of Karma we will get this error because it uses a version of socket.io with broken dependency.

Workaround that we are doing currently is in webpack.config.js we are doing this:

```
    new webpack.ContextReplacementPlugin(/buffer/, require('buffer')),
```

and require a known version of buffer 

```
    "buffer": "3.4.3",
```

We should update this once it has been fixed upstream.

**Comment by jbuck** [comment]
I redid the PR in #615 to see if we can fix this...

**Comment by jbuck** [comment]
There aren't many changes between the two versions of [buffer](https://github.com/feross/buffer/compare/v3.4.3...v3.5.1)

**Comment by jbuck** [comment]
an even smaller change in [3.4.3...3.5.0](https://github.com/feross/buffer/compare/v3.4.3...v3.5.0)

**Comment by jbuck** [comment]
Yeah, this is definitely related to 3.5.0 Using Uint8Array as a backing type for Buffer.

**Comment by adamlofting** [comment]
Am I right in assigning this as a P2 if we have a workaround in place? Feel free to change if it needs to be a P1.

**Comment by alicoding** [comment]
I would say this is a p2 and I would suggest we do nothing until the next greenkeeper update for this package is available

**Comment by jbuck** [comment]
Yes, P2. I need to create a small test case so I can report upstream and get it fixed.

**Comment by jbuck** [comment]
This is filed in https://github.com/feross/buffer/issues/79
