### ISSUE TITLE
Footer needs to use formattedHTML

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#604]
```
Teile dieses Inhalts stehen unter einem ©1998–2015 von einzelnen Mitwirkenden an mozilla.org. Der Inhalt steht unter einer <a href="https://www.mozilla.org/foundation/licensing/website-content/" target="_blank">Creative-Commons-Lizenz</a>.
```

We need to use formattedHTML so that HTML can be parsed correctly here.

**Comment by alicoding** [comment]
![screen shot 2015-10-20 at 18 58 57](https://cloud.githubusercontent.com/assets/4368149/10623390/a072af64-775c-11e5-8da9-d42d71798384.png)

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/609 r?
