### ISSUE TITLE
Test monthly amount options and language on the Snippet

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#617]
Following on from #333 

The new snippet includes a 'Monthly' option which wasn't show last year. We want to run some tests related to this.

- [ ] Test check-box versus radio button inputs
- [ ] Test placement (above and below the amount buttons)
- [ ] Test showing or removing the prompt 'This really helps us'

![snippeta](https://cloud.githubusercontent.com/assets/1901816/10694054/00f7311e-7994-11e5-8318-72a8b4effa71.jpg)
![snippetb](https://cloud.githubusercontent.com/assets/1901816/10694055/00fa048e-7994-11e5-89c1-bc9941795a4d.jpg)

See where this fits in our testing plan here:
https://docs.google.com/spreadsheets/d/1DCRW-zC3Uae5V0ubbHvFD2GCoIiS6nWItQOXKzCChe4/edit#gid=0

Questions:

* @ScottDowne do you think we should make this a single snippet with config flags we can switch in the snippet service? Or several seperate snippets? I'm leaning towards the first.

**Comment by adamlofting** [comment]
Link to the latest version of the build for reference:
http://scottdowne.github.io/eoy-snippets/2015-snippet/

**Comment by edrushka** [comment]
Here is the copy ticket: https://github.com/mozilla/donate.mozilla.org/issues/557

**Comment by ScottDowne** [comment]
@adamlofting I noticed your question late by chance going through ticket lists...

Yes, I think this should be a config if it gives us the ability to ship changes faster without being blocked by other people.

In the list at the top, Here is what's done for dev and what's not:
- [ ] config for check-box versus radio button inputs
- [ ] config for placement (above and below the amount buttons)
- [ ] config for showing or removing the prompt 'This really helps us' do it with a 'thisReallyHelpsUsImage' config and give it a datauri.

**Comment by jbuck** [comment]
@adamlofting Same with this test, if it's not being run feel free to bluesky it!

**Comment by valianttry** [comment]
Initial tests performed poorly, so closing this line of testing down. Monthly isn't a great option for snippet audience, but possibly for other audiences.
