### ISSUE TITLE
Design snippet with form directly embedded

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#620]
See details here: https://github.com/mozilla/donate.mozilla.org/issues/192#issuecomment-150585886

To Do: 
- prioritize this against our other "big" tasks (this seems heavy for both dev and design).
- coordinate with MoCo on who designs and builds
- if they want us to design and build, get clear confirmation they will allow us to run this

cc @valianttry

**Comment by lovegushwa** [comment]
@edrushka I think I have a wire frame already for this as well. https://redpen.io/cwd007076485185767
<img width="724" alt="screen shot 2015-10-28 at 8 35 22 am" src="https://cloud.githubusercontent.com/assets/12228435/10793670/0ed164da-7d4f-11e5-9017-7fd6218034a8.png">

**Comment by edrushka** [comment]
@valianttry and @adamlofting can you let me know when you'd like to try this variant so I can give @lovegushwa an updated deadline to finalize this design (I assume we're adding the monthly option baked in but will clarify when Jordan gets to work on this). It won't take him long to design, but just want to make sure it's prioritized correctly in the queue. I'll talk to @ScottDowne about how long it'll take to code and work backwards from your ideal go-live testing date.

**Comment by ScottDowne** [comment]
My initial thoughts, on this Monday morning with Stripe still not on production yet.

This might be one of the larger chunks of work I'm seeing being considered.

Doing snippet work is already slow going, even for simple things. This would be the most complex snippet we have done. It's doable, but likely I would be 100% focused on this for a number of days, maybe a week. I dunno, maybe I could pull it together faster, but it worries me as a lot of unexplored territory, in a particular had to move in area.

I think if Stripe landed much sooner and we had some german time with the new form, we would be ahead of things and this would worry me less.

If we're going to do this, we need to be fast.

**Comment by adamlofting** [comment]
We decided not to pursue this test this year because the amount of work beyond the development was likely going to take too long (and may not be viable at all). 

The test idea has been moved to the Blue Sky milestone, so I suggest we close this design ticket until a future time when we want to work on that.
