### ISSUE TITLE
Donor History Data Query for Exact Target EOY Emails

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#622]
Follow up ticket to #529

In the future, donor history will be stored in Salesforce CRM, and connected to Exact Target (ET) allowing people sending emails via exact target to personalize messages based on prior activity.

However, this will not be ready in time for our EOY campaign, so instead we will be loading data directly into ET to enable the fundraising team to send more relevant and personalised messages.

We want to query our database of transaction records to get the following data:

* `email address`
* `is regular donor`
* `highest previous gift`
* `total number of gifts`
* `last donation date`

We want to be able to run this query easily, and generate a CSV file formatted correctly for easy loading into Exact Target. 

We will run this query at several points through the campaign before each major send, so that we can exclude donors from repeat asks if they have already donated.

cc: @jbuck @jessilyndavis @valianttry @edrushka

**Comment by jessilyndavis** [comment]
Nice! Thanks Adam! 

I'd like to get DEG into this convo as well in case they have recommendations on the easiest/best way to store this data in ET so that we can use it for all of our EOY emailing needs. Going to start a thread with them in Basecamp to see if/how they can best get in here with us.

**Comment by valianttry** [comment]
I would add country = US -- that data point will let us segment by those who've participated heavily in advocacy this past year (our biggest campaigns and wins with Net Neutrality and USA Freedom targeted our US list only)

**Comment by jessilyndavis** [comment]
Hey Adam!

DEG is working on scoping out the data import + creation of sending data extension so that we can use some sexy conditional content. 

2 things we need:

1) Date by which you'd like to send the 1st email (including the date if you're doing an a/b test).

2) Sample data file on Brick FTP - ideally with people who exist in Master_Subscribers in ET and are subscribed to the Foundation newsletter (That way we can fully test the setup before it's "GO" time).

Thanks!

**Comment by jessilyndavis** [comment]
The plan will be to take the database from Adam with the following fields:

    email address
    is regular donor
    highest previous gift
    total number of gifts
    last donation date

and match them to subscriber data in Master_Subscribers:

    Opt-in to Foundation emails (FOUNDATION_FLG = Y)
    Email Format
    Language (Language_ISO2)
    Country
    First Name
    Last Name

Then we can send emails with conditional content (or segment to a certain audience) based upon any of those attributes.

**Comment by jessilyndavis** [comment]
We can segment by country - no prob. If you'd like - and if Adam can pull it into said data extraction - we can add in a field for: 

     advocate

And mark with a Y if they've been recently active. Then that info can be used for segmentation too.

**Comment by valianttry** [comment]
I created a draft appeal production schedule. There's a column for Audience Segmentation which includes my thinking about how we should personalize based on attributes. Thoughts / input welcome:
https://docs.google.com/spreadsheets/d/1ZMiRmdJhQACzlz9nZeARHBR2LCMrJZYh7MwXsgkhZQ8/edit#gid=5

**Comment by jessilyndavis** [comment]
Nice! Thanks Andrea!

Adam, do you think you can get some sample/test data on Brick FTP for DEG to play with this week?

**Comment by jessilyndavis** [comment]
@adamlofting - just sync'ed with DEG, they need sample data on the FTP by end of day tomorrow (11th) your time to kick off the work on their end Thurs am (or even Wed afternoon).  Is this doable?

**Comment by adamlofting** [comment]
Yes, I'll make this my P1 for tomorrow morning.

(excuse my slow replies on various channels, I'm still catching up after last week)

**Comment by jessilyndavis** [comment]
Sweet. Thanks Adam! (And no worries! I hope you had a lovely MozFest!)

**Comment by adamlofting** [comment]
Just noting that this data has been transferred. Info about this shared via another channel.

**Comment by adamlofting** [comment]
The query currently used is here: https://github.com/jbuck/mofo-transaction-storage/blob/master/sql/adhoc.sql#L26

We'll need to expand this once we're getting Stripe data too. But the format of the CSV file we supply to DEG should remain the same.

**Comment by jessilyndavis** [comment]
Hi Adam!

Sync'ed with Andrea and EOY team, and it looks like we're sending 6 emails from MoFo, 1 from MoCo = 7 emails, each with tests = 14 data pulls (at least).

Are you available to pull the data each time before each test and full email send? (I can share dates specifically)  OR should we explore a way to auto pull this data, post to Brick FTP, and DEG has the ExactTarget automagically pull in the latest import to do the magic with when a new file is posted there?

**Comment by adamlofting** [comment]
Notes:

* @jbuck has been setup with access to BrickFTP to post the data
* The file location is `Root Folder/etl/deg-exacttarget/FoundationDonors`
* We're going to use the file format `donorhistory_YYYYMMDD.csv`

**Comment by jessilyndavis** [comment]
Thanks Adam! I just uploaded the export from Nov 11 there.

**Comment by jbuck** [comment]
@jessilyndavis Could you share the dates here? I think I'm going to spend some time automating this.

**Comment by jessilyndavis** [comment]
@valianttry - can you add in all of the test and full send dates here? (ie every time we'll need to pull the latest donation information before we can launch.)

**Comment by jbuck** [comment]
I did some scripting in https://github.com/mozilla/mofo-transaction-storage/pull/5 . If I add the automation to have Heroku run that script, it'll keep the file updated without our intervention.

**Comment by jessilyndavis** [comment]
Nice! Will Heroku generate a new file with the proper date naming convention?

donorhistory_YYYYMMDD.csv

That way we know what file to bring in (and what file we've recently brought in in the past).

**Comment by jbuck** [comment]
@jessilyndavis I had to modify the date format to include the timestamp because BrickFTP wasn't allowing me to modify the file after it's been uploaded. I changed it to: `donorhistory_YYYY-MM-DDTHH:MM:SSZ.csv`

Will that work?

**Comment by jessilyndavis** [comment]
Will ask DEG to confirm that naming convention will work with ExactTarget's import settings (I'm not sure if the system allows us to get that specific - but they will know!)

**Comment by jessilyndavis** [comment]
Just heard word from DEG: " that shouldn't be a problem at all"  \o/

**Comment by jbuck** [comment]
:tada:

**Comment by jessilyndavis** [comment]
Quick question: How often will the script run to post a new file?

**Comment by jbuck** [comment]
@jessilyndavis At minimum, once a day. But the way the script is written and works with Heroku, it is possible to upload multiple times a day.

**Comment by jessilyndavis** [comment]
Sweet. 

DEG is giving us the drafted blueprint for the import automation this week. When we review the doc, we can work out the details of when the Heroku script should run to make things as seamless as possible.

Sound good?

**Comment by jbuck** [comment]
@jessilyndavis works for me!

To be clear, we could easily make it run every hour if we wanted it to, but it might run more than once in a hour, due to how I wrote the script and how that runtime interacts with Heroku

**Comment by jbuck** [comment]
Just waiting on Matthew to open up the IP whitelist for our automation to work

**Comment by valianttry** [comment]
hi @jbuck just checking in on this -- we'll be doing setup and testing of emails next week. Are we close?

**Comment by jbuck** [comment]
Yeah, this is working great when I run it manually in the office. I need to
get Matthew P to whitelist IP addresses for the Heroku automation to do it
automatically for us though

**Comment by jessilyndavis** [comment]
Excellent. Had a quick sync with Adam and Andrea, and want to follow up in this thread:

The plan is that the import process, and generation of the particular audiences for sending, will be done by clicking a manual button within ExactTarget (this process will be ready to roll by EOD today/Monday, and training with the team on Tuesday, 12/1). The idea is that this import & filtering process would be manually run right before sending (to pull in the latest subscription and donation information available).

It will be up to Andrea to figure out when she'll need/want the latest donation data posted to BrickFTP to be pulled into ExactTarget for filtering before sends. 

I'll let y'all figure out if an automation for daily or hourly will work or if you'd like to sync up to do a manual pull before sending.

**Comment by jbuck** [comment]
We tested the automation today for the email test and it worked great! Hooray for automation.

**Comment by adamlofting** [comment]
Almost... Just received this

> Apologies, I don't think this was called out very well in a previous response, but there is a slight issue with the current naming convention of the file. The input file cannot contain the : character in its name. Currently we've renamed the files replacing : with a dash in order to import, but could you please adjust that on your end at your earliest convenience?

> Example:
existing delivery name = donorhistory_2015-12-01T14:29:13Z.csv 
new desired name = donorhistory_2015-12-01T14-29-13Z.csv

**Comment by jbuck** [comment]
Yes, I can make this fix easily

**Comment by jbuck** [comment]
Done in https://github.com/mozilla/mofo-transaction-storage/commit/1205e03596dfefdf54bfc8bf70c095456d31ce98
