### ISSUE TITLE
Add Stripe data to transactions db

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#623]
Part of #622 

We currently use the API to extract PayPal donation history into a transactions database that is useful for analysis and to generate our end of year campaign totalizer.

This year, we will also be processing payments in Stripe, so will need to include these transactions in the database.

**Comment by jbuck** [comment]
![bmhlbng](https://cloud.githubusercontent.com/assets/578466/10733550/bae3d616-7bd5-11e5-9509-de92748135d4.png)

**Comment by jbuck** [comment]
Code is in https://github.com/jbuck/mofo-transaction-storage
