### ISSUE TITLE
Can optimizely handle a multiple url test flow

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#627]
Question, likely for @adamlofting 

I noticed if you're in the sequential page, optimizely is going to send you to either the new flow or the baseline, as a test.

After the donation, it'll send you to either thank-you or share page, which both also have a new flow.

Can optimizely retain this throughout a multi page flow? Or do we need to do this on our end?

Or do we want a segmented experience like this?

**Comment by adamlofting** [comment]
I'm not quite following the description here - what do you mean by `the baseline` and `new flow`? Is that BSD versus new form. Or new form with two style variations? (e.g. Jordan's new UI)?

If you mean the latter - we can set optimizely to match several URLs (e.g. seq and thank-you) and apply the modification (e.g. new CSS class) to all pages in the match consistently per user.

**Comment by ScottDowne** [comment]
Yeah, new-flow is Jordan's designs, and baseline is the react forms with the old designs. Not BSD.

Examples (without url query strings, but using the classname modification):

https://donate.mofostaging.net/en-US/?test=new-flow-test -> https://donate.mofostaging.net/en-US/thank-you/?test=new-flow-test

https://donate.mofostaging.net/en-US/thank-you/ - > https://donate.mofostaging.net/en-US/thank-you/

Can we persist the "new-flow-test" across urls, and if we can, do we want to?

**Comment by adamlofting** [comment]
Cool, and yes, we'll be able to run this OK.

In the optimizely test we'll set a regex for which pages to apply the test to (or maybe this example actually works across all pages). And for the users who get allocated to the new variation, we apply the classname modification for all pages they view.

**Comment by ScottDowne** [comment]
Great, I see no reason to keep this open.
