### ISSUE TITLE
Write copy for "additional info" variant of form

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#633]
We're designing a version of the form for audiences (e.g. Tiles) that will land on it without additional context (such as snippet text, email copy etc). We need to add a bit of copy to the form itself, to let them know why/what we're asking for. Should be short-ish or the design will look weird.

Design ticket #550

**Comment by valianttry** [comment]
I wrote some custom copy variants for this form here:
https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

**Comment by valianttry** [comment]
Copy is here: https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

Matej Novak (of MoCo) reviewed and edited the copy in the doc, so these should be GTG!

I am definitely open to more suggestions here... from cooler kids than me :smile_cat: 

cc @lovegushwa @edrushka
