### ISSUE TITLE
Write 'friendly nudge' copy for email opt-in

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#634]
Need a few variants of the 'friendly nudge' copy to test. https://github.com/mozilla/donate.mozilla.org/issues/352

**Comment by valianttry** [comment]
@edrushka can you provide more context? Which "nudge" copy is this? Monthly giving?

**Comment by valianttry** [comment]
I drafted some nudge copy here:
https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

**Comment by valianttry** [comment]
Copy is here: https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

Matej Novak (of MoCo) reviewed and edited the copy in the doc, so these should be GTG!

I am definitely open to more suggestions here... from cooler kids than me :smile_cat: 

cc @lovegushwa @edrushka
