### ISSUE TITLE
Write copy for thank you page video variant

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#635]
Write a line or two of copy for the version of the thank you page with the video (design here: 572)
Reminder that people seeing this page will have already signed up for email on Page 3 of the form.

@ScottDowne can you put the staging links on here, please? Page 3 of form with email signup and Thank You page where vid will go.

**Comment by valianttry** [comment]
Copy is here: https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

Matej Novak (of MoCo) reviewed and edited the copy in the doc, so these should be GTG!

I am definitely open to more suggestions here... from cooler kids than me :smile_cat: 

cc @lovegushwa @edrushka
