### ISSUE TITLE
Write 'further monthly ask' copy for popup

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#637]
One test we're running is the 'further monthly ask' pop-up window if donors choose to make one-time donation. We need to copy for the pop-up.

Test ticket: #166 
Example of popup design (shows basic amount of text): https://redpen.io/nb59dfbb743a108d28

**Comment by valianttry** [comment]
I drafted 2 variants (long and short) in this Google doc:
https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#
