### ISSUE TITLE
Design pop-up for 'further monthly ask'

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#638]
Testing a pop-up prompt asking people to who select one-time to switch to monthly actually has potentially high impact, according to [Adam's chart] (https://docs.google.com/spreadsheets/d/1DCRW-zC3Uae5V0ubbHvFD2GCoIiS6nWItQOXKzCChe4/edit#gid=0), so let's make sure we pay attention to the design.
Test ticket here: #166
Copy ticket here: #637
Basic idea of the pop-up here: https://redpen.io/nb59dfbb743a108d28

This will one of the first design things prioritized post-MozFest.

**Comment by edrushka** [comment]
Copy 

#### Variant A “Short”
Before we process your donation, will you consider stretching your contribution by converting it to a monthly gift of $##?

[Yes! Convert my one-time gift to an automatic monthly donation of $##]

[No thanks — please continue with my one-time gift of $##]

#### Variant B “Long”
Thank you for your support!

Before we process your donation, will you consider stretching your contribution by converting it to a monthly gift of $##?

By becoming a monthly supporter of Mozilla, you join a very special community whose automatic monthly gifts sustain our mission to build the Internet as a public resource accessible to everyone.

[Yes! Convert my one-time gift to an automatic monthly donation of $##]

[No thanks — please just continue with my one-time gift of $##]

**Comment by lovegushwa** [comment]
@edrushka @adamlofting @valianttry @ScottDowne check out pop-up for 'further monthly ask' options here:
https://redpen.io/p/vba9a7e9b3946c38c3

**Comment by lovegushwa** [comment]
@edrushka @adamlofting  @ScottDowne updated 'further monthly ask' options here:
@valianttry decided we should convert the monthly ask to amount to $5 as a baseline for testing.

https://redpen.io/p/fa731213a5e7e68a97

**Comment by lovegushwa** [comment]
@valianttry @edrushka any other thoughts on this? Can we create a build ticket and close?

**Comment by valianttry** [comment]
@lovegushwa this looks good to me. I'd love @adamlofting to give his OK but I don't think he is a blocker -- this is def. good enough for a test I think.

**Comment by adamlofting** [comment]
This looks great. In the build ticket it would help to give some rules about who this is shown too, and how much the ask is for. Ie if someone is donating $3 asking for $5/month seems a bit much.

**Comment by edrushka** [comment]
Closing this as design is done. Build ticket is #944. Thanks Jordan!
