### ISSUE TITLE
Write copy for social share graphics

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#639]
Note, this ticket is for copy incorporated into the graphics only, not the actual tweets or FB posts. Only need a couple variants with minimal character count. I know we can't localize our official FB or Twitter, but some phrases (e.g. I love/J'aime...) are pretty recognizable if we want to do our top languages.

**Comment by edrushka** [comment]
We can also let the designers lead on this, and only write copy if they require it.

**Comment by valianttry** [comment]
Started some variants here:
https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

**Comment by valianttry** [comment]
Matej Novak (of MoCo) reviewed and edited the copy in the doc, so these should be GTG!

I am definitely open to more suggestions here... from cooler kids than me :smile_cat: 

cc @lovegushwa @edrushka

**Comment by edrushka** [comment]
Closing. This is done :+1:
