### ISSUE TITLE
Write variant copy for baseline thank you page

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#640]
One of our tests is to simply tweak the copy on our current (baseline) thank you page: #167

Please write a couple variants.

**Comment by valianttry** [comment]
Variants are in this document:
https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#

Matej Novak (of MoCo) reviewed and edited this copy so these should be GTG!

cc @lovegushwa @edrushka
