### ISSUE TITLE
Tweak L10N to capture other en locales (inc en-gb)

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#643]
@alicoding - what are your thoughts on this? Do we just duplicate the strings, or can we set this automatically somewhere to re-use the en-us strings? That might be easier for maintenance.

--

As a start, what can we do to setup an en-gb locale?

This thank you page sends me straight to the social share, but actually anyone who speaks an en variant (including the :crown: 's English) is a valid candidate to join our mailing list.
https://donate.mofostaging.net/en-GB/thank-you/

Also, should we setup an en-gb locale so that we can default the currency to £GBP for people in the UK. And even en-ie to default to €EUR?

**Comment by alicoding** [comment]
First thing I would do here is to allow `en-*` to see the mailing list there and then create more en- locales such as en-GB where most of the strings would be default to English copy we have anyway and we can change them as we see. That way we can then start mapping currency with the locales we support.
