### ISSUE TITLE
Write EOY email appeal series

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#646]
These are the emails that will go out with Mozilla signatories like Mark & Mitchell, directly asking for donations. These will follow the [Impact emails] (https://github.com/mozilla/donate.mozilla.org/issues/570) set to launch in mid-November.

**Comment by edrushka** [comment]
It's possible @KevZawacki might have some capacity to help post-MozFest.

**Comment by valianttry** [comment]
Email production schedule is here:
https://docs.google.com/spreadsheets/d/1ZMiRmdJhQACzlz9nZeARHBR2LCMrJZYh7MwXsgkhZQ8/edit#gid=5

Launch / Draft Due
4-Dec / 19-Nov
8-Dec / 23-Nov
15-Dec / 27-Nov
23-Dec / 27-Nov
28-Dec / 27-Nov
30-Dec / 27-Nov

**Comment by edrushka** [comment]
We're slipping behind on this. @KevZawacki can help after Dec 7 but that's well past the deadline. Do you want me to try to take a pass, @valianttry or is there someone else we can call in? Matej? MJ?  Annoying reminder: it takes forever to get exec signoff on these.

**Comment by valianttry** [comment]
@edrushka and @KevZawacki I wrote a draft for appeal #1:
https://docs.google.com/document/d/18eaF4c0eFR-5kyMGNIAQXRhCTIzprDWooWuoXYfRQO0/edit

Would love your eyeballs on this Monday so we can use it for our ExactTarget workshop on Tuesday morning PST.

**Comment by edrushka** [comment]
Added my comments in the doc.

**Comment by adamlofting** [comment]
I don't have edit rights, but can we add `regular donors` to the exclusion list.

The following is just an opinion:

* I don't like calling the web 'fragile' (given the technology is deliberately designed to be a resilient network). I'd prefer to say 'under threat'.

**Comment by valianttry** [comment]
@adamlofting you do have edit rights! Especially when you have good ideas :clap: 

I removed "fragile" and i think your reason is a good one not to use it further. 

I will add "regular donors" to the exclusion list to make sure this is clear. Thanks!

Here's a cool eagle (following @edrushka 's theme)
![american-flag-eagle-870x400](https://cloud.githubusercontent.com/assets/9830371/11582174/02bf30dc-9a00-11e5-986c-bcf601dcea71.jpg)

**Comment by edrushka** [comment]
Update on send dates (note, there will only be 5 now)

Appeal 1: Dec 10 or 11
Appeal 2: Dec 15
Appeal 3: Dec 23 
Appeal 4: Dec 28 
Appeal 5: Dec 30

**Comment by valianttry** [comment]
Draft for appeal #2 is now in the doc:
https://docs.google.com/document/d/18eaF4c0eFR-5kyMGNIAQXRhCTIzprDWooWuoXYfRQO0/edit#

@KevZawacki  and @edrushka  -- do you both want to take a first critical read?

**Comment by valianttry** [comment]
Appeal #3 is now ready for a very quick review. It's simply a re-send of message #2 with a "lift note" at the top from Mark:
https://docs.google.com/document/d/18eaF4c0eFR-5kyMGNIAQXRhCTIzprDWooWuoXYfRQO0/edit#

@KevZawacki and @edrushka please take a look (will take you <5 min)

**Comment by valianttry** [comment]
Message #4 of 4 has been sent to Mitchell Baker for review, feedback, and approval:
https://docs.google.com/document/d/1p27IfSHqZK1UF_mYGdmv00PiVm04Sji5ai6Btwks534/edit#heading=h.bqq6qadsyguv

Mark reviewed and I incorporated his suggested edits before sending to Mitchell. Thank you @KevZawacki for the awesome research! That helped a LOT.

**Comment by KevZawacki** [comment]
@valianttry Just reviewed Mark's preface to appeal 3 -- looks great! Left a few minor suggestions.

**Comment by edrushka** [comment]
I've reviewed appeal 3.

**Comment by valianttry** [comment]
Mitchell reviewed and approved appeal #4 with NO CHANGES! 

That means all email copy has been reviewed and approved. We are sending 4 appeals total (down from 6).
