### ISSUE TITLE
Setup Customer Support in Desk.com for donors and email list members

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#648]
@adamlofting currently we receive email from list members who reply to askjoin@ and donate@ email addresses in an unmonitored inbox. We also receive donate@ emails from people who click the link to email us on our donation forms. This is obviously sub-optimal customer service!

* Can we use desk.com to manage our incoming customer email?
* How do we set up a system to triage, route, and resolve issues?
* What sort of staffing would be required? What can be automated?
* Can we also provide support in our top locales (DE, FR, PTBR, ES)? Would this require us to set up separate emails for those locales -- or how can we route customer support to localizers?

**Comment by adamlofting** [comment]
> Can we use desk.com to manage our incoming customer email?

Yes, I now have admin access and have added accounts for you and @edrushka 

> How do we set up a system to triage, route, and resolve issues?

* We'll need to setup rules and filters based on incoming email in desk.com
* This inbox is shared with Webmaker and Teach teams, but as a starting point we can auto assign labels and staff to emails that come from askjoin@ or dontate@
* I can help with the setup, but will need your requirements

> What sort of staffing would be required? What can be automated?

* That's up to you. Who is going to be monitoring the inbox and answering the questions?
* We can store 'canned responses' in the admin section to make it easier to reply

> Can we also provide support in our top locales (DE, FR, PTBR, ES)? Would this require us to set up separate emails for those locales -- or how can we route customer support to localizers?

* Anyone answering questions would need a desk.com account - we pay per account, but with flex accounts we only paid for the time used. Do we have people to do this support? 
* We could add seperate email addresses per locale, or we assign based on language when we're triaging the inbox.

**Comment by cassiemc** [comment]
Once this is setup, would be awesome to surface these kinds of support requests to the team at large at demos and otherwise.

**Comment by valianttry** [comment]
Great! @adamlofting I signed in and am looking around. Thanks!

**Comment by adamlofting** [comment]
> Once this is setup, would be awesome to surface these kinds of support requests to the team at large at demos and otherwise.

Yes, we had a version of this on the daily EOY stand-ups last year which was great.

Another note:

- [ ] When we're worked through the points above, we'll need to update email config settings to enable replies from desk.com to be sent out from donate@moz... (currently all replies are from help@webmaker.org)

**Comment by adamlofting** [comment]
Note to investigate spam issues: https://support.desk.com/customer/portal/articles/1649402-how-to-handle-spam-email

**Comment by adamlofting** [comment]
@valianttry I've promoted your desk.com account to use one of our 'full time' licences rather than the 'flex licence'. 

For now you'll be logged into this more than most other users so this is more cost effective, but if this repsonsibility switches to someone else just let me know and we can move around the licence allocation.

**Comment by adamlofting** [comment]
In order to maintain the benefits of the gmail spam filtering which is currently working well (and not flood the shared inbox with unfiltered noise) I think we should use the option of forwarding the emails from gmail to our desk.com support inbox:

* https://support.desk.com/customer/portal/articles/1345743#Forward
* https://support.google.com/mail/answer/10957?hl=en

I'll work with @valianttry to get this setup in gmail.

**Comment by valianttry** [comment]
@adamlofting any update on this? I expect the emails to start flooding in Friday.....

**Comment by adamlofting** [comment]
Chasing down our internal owner of the email config now, but until this is live we still have access to the inbox and can reply directly.

**Comment by jbuck** [comment]
@adamlofting you'll want to talk to https://phonebook.mozilla.org/#search/limed

**Comment by valianttry** [comment]
@adamlofting have you found the cheese at the end of the maze? :mouse: 

Also, I'd like to add Stephanie McVicker as a recipient for our emails... so if you can find the Big Cheese ask them to please add her... it's OK to set her up so she receives the Donate@ emails directly in her gmail inbox like I do. Once we move to Desk.com, Steph will need a login.

**Comment by adamlofting** [comment]
We didn't get to the Roquefort Papillon of cheeses, but I've setup the sliced plastic burger cheese version of this today. (Also importantly, why is there no cheese emoji?).

Now that multiple people are looking at this a shared inbox feels like the most valuable thing.

All donate emails are now forwarding to desk.com (but without gmail spam filtering) and I've setup an account for Stephanie. I'll send an email about this now too.

**Comment by edrushka** [comment]
FYI, the fact that we've been living in a **CHEESE EMOJI VACUUM** has been noticed by others on the web. Thankfully there's a workaround: 
![screenshot 2015-12-04 14 02 21](https://cloud.githubusercontent.com/assets/4515662/11602550/fed38e60-9a8f-11e5-9e8e-0c279448280b.png)

**Comment by adamlofting** [comment]
:smile: :+1:
