### ISSUE TITLE
Trigger alerts for 5xx HTTP errors

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#65]

**Comment by adamlofting** [comment]
See also #299

**Comment by jbuck** [comment]
I created a dashboard in AWS/mofo-projects: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=donate-mozilla-org-Cloudfront-Stats

I also created two alarms in AWS/mofo-projects:
* donate.mozilla.org 4xx rate > 10%
* donate.mozilla.org 5xx rate > 0%
