### ISSUE TITLE
Identify donors for thank you cards

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#650]
@adamlofting, for this first round of cards, can we please sort by:
- have a full mailing address (so this will be CC donors via BSD)
- live in USA or UK
- have donated within past 6 months
- upper limit is $1000 USD (anything more needs personalized contact)

**Comment by adamlofting** [comment]
There are 381 active recurring credit card donors with US contact addresses in BSD who would it would be great to send these thank you cards too. 

@edrushka I think that's more than we have cards for, so shall we start with this as the existing set?

I can do a similar selection to send out the small batch of cards I have here in the UK.
