### ISSUE TITLE
Set up email receipt for donors through Stripe

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#661]
We have standard language we must include in every receipt emailed to donors. Current Stripe options are very limited, and may not allow us to include this text:

*Contributions go to the Mozilla Foundation, a 501(c)(3) organization, to be used in its discretion for its charitable purposes. They are tax-deductible in the U.S. to the fullest extent permitted by law. Mozilla did not provide any goods or services in return for this donation.
For more information see the about page. (http://www.mozilla.org/about/)

Mozilla Foundation Tax ID 20-0097189*

Current receipt looks like this:

![your_mozilla_foundation_receipt___0000-0000__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/10920180/bd95bf1a-8223-11e5-8c80-373679cff3f5.png)

**Comment by valianttry** [comment]
@jbuck looking at the dashboard, looks like we can only update an icon -- it is possible we will need to skipe Stripe's automatic receipt altogether and just set this up in ExactTarget so we are in legal compliance.

**Comment by adamlofting** [comment]
The work to fix this is scoped in https://github.com/mozilla/donate.mozilla.org/issues/359

We said it wasn't a blocker for launching as the 75% of donors who go through PayPal aren't currently getting this message. 

If we P1 the ticket #359 I think we could get that launched in time to catch most of the EOY traffic this year.

**Comment by valianttry** [comment]
3 options:

A. Crappy auto-email that doesn't provide much customization
B. Journey Builder in ExactTarget ? @jbuck will explore.
C. Something more robust like Sawmill

**Comment by adamlofting** [comment]
> B. Journey Builder in ExactTarget ? @jbuck will explore.

* This isn't an option yet - MoCo haven't bought / implemented the Journey Builder functionality.

I think we've switched on the basic Stripe auto-email (#360) which gives us a minimum viable level of service, and think our next effort is best spent on Sawmill as it's proven infrastructure with localization options already in place.

**Comment by valianttry** [comment]
New copy is written: https://github.com/mozilla/donate.mozilla.org/issues/686

cc @jbuck

**Comment by jbuck** [comment]
This is done, pending verification of the donate@mozilla.org email address

![screaming intensifies](https://cloud.githubusercontent.com/assets/578466/11050684/175c5544-8716-11e5-977a-433ba77b213d.gif)

**Comment by jbuck** [comment]
This is good to go on staging, just need to do a prod push before we enable it on production tomorrow.

**Comment by valianttry** [comment]
@jbuck found a weird problem when I test -- in the receipt, there's no decimal. I selected $5.00 monthly and my receipt looks like $500 monthly:

![thank_you_for_your_gift_to_mozilla_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/11051976/1b6e1742-8709-11e5-9f01-159e219e0906.png)

**Comment by jbuck** [comment]
@valianttry nice catch! I'll fix that up

**Comment by jbuck** [comment]
Fixed in https://github.com/mozilla/sawmill/commit/12495118fa061ce805ff7e39293ad33806e99904

Going to push this change to production now

**Comment by jbuck** [comment]
All good now. I disabled the Stripe-sent payment emails, but I'm going to leave the Stripe refund emails on until we implement our own.
