### ISSUE TITLE
Notify us via email if large donation occurs

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#666]

**Comment by jbuck** [comment]
Our first fraudulent charge! $1000: https://dashboard.stripe.com/payments/ch_176UuTG8Mmx3htnxsHOl34tZ

**Comment by valianttry** [comment]
@jbuck let's make sure everyone knows what to do in a case like this -- e.g. do we need to click "report fraudulent charge"? Or ignore and let Stripe handle it somehow? Should we reach out to Stripe for a walkthrough? (Eric seemed happy to help us figure this early stuff out).

**Comment by valianttry** [comment]
also -- are we sure it's fraudulent??

**Comment by jbuck** [comment]
I wouldn't bet on it being legit, but of course we don't know for sure.

**Comment by valianttry** [comment]
I'm alerting Erik Lasker over at Stripe to help teach us how to handle these.

**Comment by jbuck** [comment]
@valianttry Now you'll get email notifications for donations over $115 USD!

**Comment by valianttry** [comment]
Hey @jbuck, i see a few donations that are larger than 115 but I only have 1 alert ... i searched my inbox. Whzup?

**Comment by cadecairos** [comment]
@jbuck Did we forget to add the oxr API key to sawmill?

**Comment by jbuck** [comment]
Nah it's there.... not sure what's up

**Comment by valianttry** [comment]
I seem to be getting them now. Not sure what was up?

![donate_mozilla_org_-_a_large_stripe_charge_was_generated_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11319897/92d67284-903c-11e5-816a-767c096061fe.png)

**Comment by cadecairos** [comment]
Should we call this resolved? SES does sometimes appear to lag every now and then.
