### ISSUE TITLE
Decide how we scale hosting with traffic

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#67]
And if this can be automated.

**Comment by jbuck** [comment]
I see several options for us:

1) #69 - Over-engineer for the Germany campaign and have a static, unchanging amount of dynos, according to our predicted load + some margin
2) Schedule based on time using https://elements.heroku.com/addons/process-scheduler
3) Schedule based on load/response times using https://elements.heroku.com/addons/adept-scale or https://www.hirefire.io/

We should start with 1 for now, and investigate 2 and 3 during the Germany campaign
