### ISSUE TITLE
id/share page isn't fully translated

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#670]
I know this is a fairly low priority, so instead of fixing, I filed.

https://donate.mozilla.org/id/share/ <- not translated.

Not sure if that's a bug, or if it's simply missing those translations.

**Comment by jbuck** [comment]
@edrushka Can you get Kontextor to do this page?

**Comment by jbuck** [comment]
It'd to be to complete this page for any 2016 campaigns, but it's not a priority for the EOY

**Comment by edrushka** [comment]
I'm going to re-assign this to @alicoding to finish through Pontoon.

**Comment by alicoding** [comment]
This is not a priority, but just want to flag @bennychandra @kelimuttu @rodin about this. 

English strings:

```
tell_your_friends=Tell your friends
help_spread_the_word=We need your help to spread the word.
```

Thanks.

**Comment by kelimuttu** [comment]
hi @alicoding 

tell_your_friends=Sebarkan ke teman-teman
help_spread_the_word=Kami perlu bantuanmu untuk menyebarkan  ke teman-teman

**Comment by alicoding** [comment]
@kelimuttu Thank you very much :D

**Comment by kelimuttu** [comment]
Pleasure! (;
