### ISSUE TITLE
Digit count in CVC error ignores AMEX reality

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#671]
AMEX has a four-digit CVC on the front of the card (vs. Visa and MC, which have a three-digit CVC on the back).

Could we do this to fix?
Customize the message if people use AMEX vs. Visa or MC. New text for AMEX would say: "You can find your four-digit CVC on the front of your AMEX card" and we would need a new image that shows location on an AMEX with arrow.

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/10951817/71ccc836-82f4-11e5-8505-2b33f39d0913.png)

**Comment by valianttry** [comment]
Image examples:
![cvvcode](https://cloud.githubusercontent.com/assets/9830371/10952011/5d41de1e-82f5-11e5-87c6-13a81f25a103.jpg)

**Comment by jbuck** [comment]
It's possible to do client-side credit card type detection. Should we do
that and vary the text based on the type of credit card?

**Comment by ScottDowne** [comment]
@jbuck we are already detecting card type, so this is a fairly easy fix.

Hardest part is getting an image that works well in that space and translating the text.

**Comment by valianttry** [comment]
Did @sabrinang design that little card in the (?) message? This one:
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/10960921/d1bdfe06-833d-11e5-8926-6ada4278566f.png)

This is an image of where the CID is on an AMEX:
![amex-pop](https://cloud.githubusercontent.com/assets/9830371/10960958/413aa4e6-833e-11e5-9f93-d93001869706.jpg)

The language should be:
"You can find your four-digit CID number on the front of your card"
