### ISSUE TITLE
Strange error pops up when Stripe payment tokens are reused

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#674]
![inspect_network_request_and_donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/10952999/6a43642a-82fa-11e5-86be-2d2122f4df61.png)

**Comment by jbuck** [comment]
https://github.com/mozilla/donate.mozilla.org/blob/d27b861dfec1381cef422670dc512b23047bf6e4/routes/index.js#L73-L76 is the relevant line of code

**Comment by jbuck** [comment]
I looked at the Stripe logs, and the problem was that the payment token was getting reused.

**Comment by ScottDowne** [comment]
@jbuck I'm fairly convinced this was due to staging key nonsense.

I say we close until we have something else to tell us this is actually going to happen in a real life scenario.

**Comment by jbuck** [comment]
Sounds like a plan, Stan.
