### ISSUE TITLE
When i select "PayPal" it seems like there should be a loading bar or reassuring "loading" animation

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#675]
on
https://donate.mofoprod.net/en-US/?test=new-flow-test

If I select "PayPal" nothing happens for 1 - 2 seconds. Loading bars have proven in other testing to prevent abandonment (esp. during heavy usage periods that cause longer than average load times).

**Comment by adamlofting** [comment]
Closing this as a dupe of #415 and completely agree we should add this.
