### ISSUE TITLE
Review and update the FAQ in EN

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#679]
Review this copy:
https://wiki.mozilla.org/Donate

Make any needed tweaks in English (US)

**Comment by jbuck** [comment]
@valianttry What would you think of moving the FAQ directly to donate.mozilla.org at some point? Then we could get it translated!

**Comment by valianttry** [comment]
@jbuck i think that works fine -- the only reason it's in wiki is because a wiki is very easy to update. How easy will it be to update, say, donate.mozilla.org/faq?

**Comment by valianttry** [comment]
@edrushka can you review this? We should also share with Angela and Pamela.

https://docs.google.com/document/d/1YzgIahdG3q3LbQtCKHTzs0N0X8_JTQHmZn61yYmCs_8/edit#

**Comment by jbuck** [comment]
@valianttry definitely harder to update donate. Not much harder, but definitely something we can do later

**Comment by edrushka** [comment]
@KevZawacki wrote some updates to the FAQ in this ticket #871 and ported the changes to the wiki. Closing this one as it became a duplicate.
