### ISSUE TITLE
Ensure enough staff can reboot hosting in emergency

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#68]
- [ ] document this in readme
- [ ] at least 3 engineers should know how to do this, and have permission

**Comment by adamlofting** [comment]
Relates to #74

**Comment by jbuck** [comment]
Issue #263 will help polish this off

**Comment by jbuck** [comment]
What we need to do here is take the tooling and documentation I've written up and improve it to the point where @adamlofting @alicoding @ScottDowne can do it reliably and with confidence

**Comment by jbuck** [comment]
The tech check-in today also suggested, "Document all the possible failure points and mitigation"

**Comment by adamlofting** [comment]
@jbuck I think this is good to close?

**Comment by jbuck** [comment]
Yeah
