### ISSUE TITLE
Access to Google Analytics dashboard for donate.m.o

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#687]
@adamlofting could you give access to https://www.google.com/analytics/web/?authuser=0#dashboard/x2x17FAsShuixRj2bK-YpQ/a49796218w101806119p105783219/ for Andrea and I?

**Comment by valianttry** [comment]
here's a full list of folks who'd probably want to see the dashboard at some point during the campaign:
me
erika
ben niolet
jean collings

not sure if you have to grant individual access but those are the folks off the top of my head who might need to see this report.

**Comment by adamlofting** [comment]
I've requested admin access to this profile today as I can't currently add users / manage settings. I'll add these people as soon as that's solved.

(+ moving this ticket out of the launch milestone as it shouldn't block go live)

**Comment by adamlofting** [comment]
I filed to bugzilla bug to get these people added: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1222673

**Comment by valianttry** [comment]
Chris More closed the Bugzilla ticket, everyone should have access.
