### ISSUE TITLE
Over-engineer hosting for German campaign, then review the data to plan for EOY

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#69]
For our initial test campaign(s): 

- [ ] use many more dynos than we expect we need to handle the traffic. 
- [ ] make sure we have good metrics on traffic and dyno usage
- [ ] analyse after campaign to make good plans for EOY

**Comment by jbuck** [comment]
Blocked on #84

**Comment by jbuck** [comment]
Easy to do with Heroku!
