### ISSUE TITLE
Form is not showing up in Safari and Safari Mobile

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#691]
This is what i see at donate.mofoprod.net on my iPhone 6s using Chrome:

![img_1242](https://cloud.githubusercontent.com/assets/9830371/10984779/cd7f1ca6-83d0-11e5-8a17-d497618ee942.PNG)

**Comment by valianttry** [comment]
Note same sadness ensues when I us Chrome on iOS to see donate.mofostaging.net as well. :cry:

**Comment by adamlofting** [comment]
Just checked, and I get the same on Safari on iPhone.

**Comment by jbuck** [comment]
It won't work on Safari because our Intl polyfill is not being loaded

**Comment by jbuck** [comment]
We're good now: https://www.dropbox.com/s/bj33cddpl9rx5ju/Screenshot%202015-11-06%2014.24.50.png?dl=0
