### ISSUE TITLE
Margin issues using iPhone 6s

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#700]
Viewing the form on my iPhone 6s in Chrome -- the edges are off-screen:

![img_1251](https://cloud.githubusercontent.com/assets/9830371/11007398/71f4da2a-847e-11e5-8509-d16ab8f84601.PNG)

![img_1248](https://cloud.githubusercontent.com/assets/9830371/11007399/72108cb6-847e-11e5-982d-c797c5b309da.PNG)

![img_1247](https://cloud.githubusercontent.com/assets/9830371/11007402/723e621c-847e-11e5-8e5d-29068e33f031.PNG)

![img_1243](https://cloud.githubusercontent.com/assets/9830371/11007401/723deb52-847e-11e5-9fff-39e3c2fba5ca.PNG)

**Comment by jbuck** [comment]
This is happening because the iPhone zooms in when you click on a dropdown, the currency selector dropdown in this case. I don't think we should disallow zooming here, so closing
