### ISSUE TITLE
"Next" button shows little margin lines in iPhone 6s

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#701]
![img_1246](https://cloud.githubusercontent.com/assets/9830371/11007507/31228640-847f-11e5-9e8a-687ee9551976.PNG)

**Comment by ScottDowne** [comment]
@valianttry can you check this against the new flow?

donate.mofoprod.net/?test=new-flow-test

**Comment by valianttry** [comment]
@ScottDowne I used the form at mozilla.org (live form) and still see the little lines:

![img_1326_png](https://cloud.githubusercontent.com/assets/9830371/11049958/03c1a0ee-86f7-11e5-8282-46808dc068b5.png)

**Comment by ScottDowne** [comment]
I tested this on an ipad, and I saw it in the old flow, but it was gone in donate.mozilla.org/?test=new-flow-test

**Comment by ScottDowne** [comment]
Fixed, should be on staging soon.
