### ISSUE TITLE
Design new callouts for 2015 email fundraising appeals

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#702]
In each fundraising email, we include an image in the upper right corner of the email body that's a "callout" image. It is clickable and receives a high % of clicks in fundraising emails. 

Schedule for email launch is here: https://docs.google.com/spreadsheets/d/1ZMiRmdJhQACzlz9nZeARHBR2LCMrJZYh7MwXsgkhZQ8/edit#gid=4

Callouts are needed by Nov 19 for all messages in the appeals series.

![_sample__important__the_last_email_this_year_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11007963/55a75cd6-8482-11e5-900a-a60cb6877ff1.png)

**Comment by valianttry** [comment]
cc @lovegushwa @natalieworth @cassiemc

**Comment by edrushka** [comment]
I'm going to assign @natalieworth to this one. Gear Store promo https://github.com/MozillaFoundation/2015-fundraising/issues/51 is our first email. The rest are logged here: https://docs.google.com/spreadsheets/d/1ZMiRmdJhQACzlz9nZeARHBR2LCMrJZYh7MwXsgkhZQ8/edit#gid=4

@natalieworth would it be easier for me to create individual tickets for each email?

**Comment by natalieworth** [comment]
Hey @edrushka, I think this one ticket should be fine. I'll probably try and have cohesive layouts that I can just attach here for these. If it's easier on your end though, I'm good with individual tickets too. Thanks for checking :)

**Comment by edrushka** [comment]
Ok, let's just keep this one for now. I created a column in the [email spreadsheet] (https://docs.google.com/spreadsheets/d/1ZMiRmdJhQACzlz9nZeARHBR2LCMrJZYh7MwXsgkhZQ8/edit#gid=4) where we can log the individual graphic files.

**Comment by natalieworth** [comment]
@lovegushwa Could you link me to the final files of your EOY designs, thanks! :)

**Comment by natalieworth** [comment]
Hey @edrushka @valianttry here are the first iterations for call-outs. Also wondering if there is copy that is required for these? Or is that coming tomorrow? Google drive says Nov. 19 for finalized copy, but wasn't sure if issue #703 was for these? (Also do we need over 6?) Thanks
https://redpen.io/p/hs67f7f34951ab9c54

cc @lovegushwa

**Comment by edrushka** [comment]
The 19th is the date for final email copy, not graphics copy. Like the social share stuff, I think we should minimize copy in the actual graphic. I'll let @valianttry be the final decision-maker on what, if any, copy we need in the graphic.

**Comment by valianttry** [comment]
@natalieworth I only see the social share graphics when I click the redpen in your last comment. The callouts are square orientation -- did i miss them? I updated the copy ticket with actual copy for you!
https://github.com/mozilla/donate.mozilla.org/issues/703#issuecomment-157961974

Let me know if you have questions! Thank you!! :dancers:

**Comment by natalieworth** [comment]
Hi @valianttry sorry I forgot to add the other link: https://redpen.io/p/npc29dacd3ad00ee8e
I'll update too with the new copy from #703 Thanks!

**Comment by natalieworth** [comment]
Hey @valianttry @edrushka @lovegushwa updates on these are up on redpen. I've included variations of the buttons, but I could do less of the 'Give before Dec 31' if we are going to be testing them? Thanks :) https://redpen.io/p/npc29dacd3ad00ee8e

cc @cassiemc

**Comment by lovegushwa** [comment]
@edrushka @valianttry @KevZawacki @natalieworth

You can download the final email callout images here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvYjBKbmJCVHlwRjg&usp=sharing

this issue is ready to close.

**Comment by edrushka** [comment]
Dapper Fox looks very handsome in square format. Excellent job. Thank you!

**Comment by valianttry** [comment]
@lovegushwa or @natalieworth I just noticed that "Web" is not capitalized in the 3rd callout variant -- mind updating? Thank you!

**Comment by cassiemc** [comment]
Reopening, looks like one final update needed from @natalieworth

**Comment by natalieworth** [comment]
Hi @valianttry @cassiemc Updated this with the capital 'W' and added it to Jordan's file on the drive: https://drive.google.com/drive/folders/0B2qu3ExKWIlvYjBKbmJCVHlwRjg

**Comment by edrushka** [comment]
Thanks @natalieworth!

**Comment by valianttry** [comment]
One last thing! Sorry forgot to mention this feedback from Jessilyn Davis who's helping us with setup and training in ExactTarget: THe images render as blurry / un-optimized when they are resized for email. 

ExactTarget design for email doc here:
https://www.exacttarget.com/products/email-marketing/email-design-toolkit

I'm not sure exactly what this calls for?

**Comment by natalieworth** [comment]
Hey @valianttry , does Jessilyn have the resolutions needed? If it's for email, it would be great to get the exact resolution needed to accommodate retina, but if it's not availalble I could try exporting them again at double resolution in case this is the problem.

**Comment by edrushka** [comment]
I've emailed jess to get some more details.

**Comment by edrushka** [comment]
@natalieworth can you please do an additional export at 200x200? I think that's about the size Jess needs.

**Comment by natalieworth** [comment]
Hi @valianttry @edrushka , I've uploaded versions at 200px with 300 dpi. They're quite high resolution for web, so they hopefully shouldn't be pixelated. If Jessilyn provides other resolutions/ sizes I can definitely export those too if it'll be easier for implementation :)
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0QzZPdXV4RTBKU0U&usp=drive_web&ddrp=1#

**Comment by lovegushwa** [comment]
Hey @edrushka @valianttry can we close this ticket?

**Comment by edrushka** [comment]
I think so. The first email goes out today and I haven't heard anything from @stephaniemcv or Jess. I'll reopen this if they need something.
