### ISSUE TITLE
Write copy for new callouts for fundraising emails

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#703]
Blocks: https://github.com/mozilla/donate.mozilla.org/issues/702

**Comment by valianttry** [comment]
CALLOUT 1:
Help protect the open Web 
[DONATE NOW] 
Give before Dec 31.

CALLOUT 2:
Your support makes Mozilla's 
important work possible.
[DONATE NOW] 
Give before Dec 31.

CALLOUT 3:
Love the Web? 
Help protect it for generations.
[DONATE NOW] 
Give before Dec 31.

CALLOUT 4:
[DONATE NOW] 
Only days left to donate.
Deadline: Dec 31

CALLOUT 4:
[DONATE NOW] 
Only hours left.
Deadline: Dec 31

**Comment by natalieworth** [comment]
Updates/ V2 for these are up on redpen with the new copy from Andrea added:
https://redpen.io/p/npc29dacd3ad00ee8e
cc @valianttry @lovegushwa @edrushka @HPaulJohnson @cassiemc

**Comment by edrushka** [comment]
Closing this as copy is done and graphics are about to ship: https://redpen.io/hk2f4a932f26891663
