### ISSUE TITLE
Design homepage tile promo (static)

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#704]
I believe @sabrinang designed this promo for 2014 and may have some specs or redpens to share.

![we re_building_a_better_internet_ _mozilla](https://cloud.githubusercontent.com/assets/9830371/11009081/991c067c-8489-11e5-9aee-b686ecf7093e.png)

**Comment by valianttry** [comment]
Found out @natalieworth has already designed one of these so she's good as gold. Hazaa! :clap:

**Comment by edrushka** [comment]
@natalieworth - @lovegushwa will post the Directory tile and homepage takeover design very soon, which should give you all the visual direction you need for this.

**Comment by edrushka** [comment]
Closing this as Jen's team received the assets for the tile last week.
