### ISSUE TITLE
Decide where we use SQS, and setup backups

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#71]
- [ ] Have a list of multiple queues we can use (including direct browser POST)
- [ ] And we can have queues in multiple regions too

**Comment by jbuck** [comment]
We could use SQS with Stripe payments easily enough but since Paypal requires a server-side authorization process we could only use SQS for one part of the Paypal process.

**Comment by adamlofting** [comment]
We should also consider for email subscriptions on the thank you page. But that might be over engineering.

**Comment by jbuck** [comment]
Oops! yes, that's a good point we could add that too

**Comment by jbuck** [comment]
Yeah we're gonna do this

**Comment by jbuck** [comment]
Oops wrong issue to close

**Comment by adamlofting** [comment]
I think the only place we should consider this is for email sign-up on the thank you page.

Can we estimate the amount of work needed, plus impact on local dev somehow to use SQS to queue email subscriptions which would eventually talk to basket?

Then we can make a judgement call about whether the effort is worthwhile.

**Comment by jbuck** [comment]
Probably an hour or two, since we can just re-use sawmill and [hatchet](https://github.com/jbuck/hatchet) which will solve local dev for us.

**Comment by adamlofting** [comment]
We have a seperate ticking for implementing this work.
