### ISSUE TITLE
Set up a dashboard for donors to modify or stop recurring gifts via Stripe

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#713]
Here is the BSD example:
https://sendto.mozilla.org/page/recurring/

![sendto_mozilla_org](https://cloud.githubusercontent.com/assets/9830371/11050067/b259fb1a-86f7-11e5-9aa4-80ae462c4671.png)

**Comment by jbuck** [comment]
https://github.com/mozilla/donate.mozilla.org/issues/362 was the previous issue we filed on this

**Comment by valianttry** [comment]
closing since this is a duplicate.
