### ISSUE TITLE
Implement country detection via geoip lookup

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#715]
I sent an email to IT to ask if we could use geo.mozilla.org. If not, we'll need to implement our own API.

**Comment by ScottDowne** [comment]
Actually, I would be fine with doing a guess based on locale if we cannot use geo.mozilla.org.

This would be accurate for the snippets because snippets are already based on location, then we set the locale to coincide with that. So we can just reverse that.

**Comment by jbuck** [comment]
@ScottDowne https://location.services.mozilla.com/v1/country is the API to use. Your idea is a good fallback detection though.

I filed a bug to request enabling CORS on that endpoint so we can use it: https://github.com/mozilla/ichnaea/issues/468

**Comment by jbuck** [comment]
Ali, Scott, and I decided to not do this because the country detection via locale that we're doing now is sufficient for EOY.
