### ISSUE TITLE
Generate URLs for new locales & update mozilla.org/snippet

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#718]
Locales:

* de
* fr
* pt-BR
* es

**Comment by valianttry** [comment]
Filed a new bug for mozilla.org URLs here: https://bugzilla.mozilla.org/show_bug.cgi?id=1223570

**Comment by valianttry** [comment]
URLs were generated and added to Bugzilla bug noted above. Closing this.
