### ISSUE TITLE
Reduce Heroku dyno boot times

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#720]
I [wrote a patch](https://github.com/mozilla/donate.mozilla.org/commit/6a2884c60a108667c260ca488da31f104020480a) to rebuild the front-end on every boot to fix an issue where [production would use the staging environment](https://github.com/mozilla/donate.mozilla.org/issues/385) built into the front-end.

The problem with my fix is that boot times frequently exceed 60 seconds which causes a boot timeout. We need a fix that:
- Allows us to modify environment variables and have the run-time environment change
- Boots dynos quickly

**Comment by jbuck** [comment]
Ideas:

* What if the dyno boot process wrote a config json file out to disk?
* Start the server before the JS build runs
  * Downside here is that we might serve up stale/no javascript

**Comment by jbuck** [comment]
Temporary fix will be to not use the Heroku promote button.

**Comment by jbuck** [comment]
Temporary fix in https://github.com/mozilla/donate.mozilla.org/commit/eeee6316256e275814447551d6a3eb6e50810263

**Comment by jbuck** [comment]
Another downside of this fix is that we can't change the config and have it rebuild.

**Comment by ScottDowne** [comment]
From triage: can we file this with Heroku?

**Comment by cadecairos** [comment]
cleaning out the closet.
