### ISSUE TITLE
Make front-end longterm cache-friendly

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#721]
We are not doing a great job of having our CDN cache take the hit for static files. I suspect this is because we're not using Cache-Control headers. What I'd like to do is put the file hash in the filename, and set a very long Cache-Control header for linked content, and a relatively short Cache-Control header for the html file(s).

**Comment by alicoding** [comment]
Can you maybe list those long term cache files? By using webpack, we might be able to solve the problem for main.js and possibly for our CSS file as well, but for those assets such as images or a small internal js files we could manually add a timestamp or something ?

I've read a bit last night and it seems like we only need to do this on production anyway, so I guess this needs to be a configurable thing here.

**Comment by jbuck** [comment]
Focusing on main.js and the CSS file makes the most sense to me

**Comment by jbuck** [comment]
I also don't think it should be an option, we should do it every build

**Comment by jbuck** [comment]
#790 is a work in progress

**Comment by jbuck** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/806 is nearly done!

**Comment by jbuck** [comment]
And it's landed
