### ISSUE TITLE
Create a special Firefox Lightweight Theme for donors

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#728]
See: https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes

Spoke with Gregg Linden and Matt Grimes in User Advocacy -- joined by @bniolet1 and they had the brilliant idea to give away a FREE Firefox theme to donors. What does this accomplish?

**First** -- It gives Firefox users who donate a really awesome "special gift" when they donate that we ONLY promote to donors. This will be delightful and likely improve retention / increase the likelihood of a repeat gift.

**Second and most importantly** -- This allows us to treat the people who have this theme as a "cohort" among Firefox users. This helps us answer important Qs we've been unable to answer previously, such as:
* Do donors have a lower attrition rate than non-donors who use Firefox?
* Do donors keep their Firefox browser updated in higher #s than non donors?
* etc 

Tasks:
- [ ] Design a kick-ass theme that donors will love -- e.g. a Firefox logo treatment that is special; a big gold star added to their homepage etc; -- this doesn't necessarily have to be done by MoFo designers. I could reach out to Blake Winton (of whimsycorn fame) for help since our designers are pretty much tapped.
- [ ] Build a mechanism to offer the theme to donors right after they give -- decide where to put it in the flow;
- [ ] Work with User Advocacy on shared metrics / dashboard to track behavior over time for this cohort + compared to other Firefox users.

cc: @adamlofting @edrushka

**Comment by valianttry** [comment]
I sent a note to Blake Winton to ask if he'd like to help out.

**Comment by adamlofting** [comment]
I absolutely love this idea. Some of Jordan's campaign visuals would make great content for a theme.

**Comment by valianttry** [comment]
This is a duplicate of https://github.com/mozilla/donate.mozilla.org/issues/732, moving essentials over and closing.
