### ISSUE TITLE
Add non-English stripe charge succeeded email to sawmill

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#733]
https://pontoon.mozilla.org/de/fundraising/Emails/

There's a bunch of locales here that someone could load into webmaker-mailroom.

**Comment by jbuck** [comment]
@ScottDowne here's what you'll need to do:

1. Visit a Pontoon locale for the translated email, for example https://pontoon.mozilla.org/de/fundraising/Emails/
2. You'll need to create a json file with the new locale data. Take a look at my initial patch for what it should look like: https://github.com/mozilla/webmaker-mailroom/commit/a0d298a738ec878ad0a4a974d19ebe3f6773dd8f . The only thing you'll need to do is make sure you use the same key for each string, convert the `%% variables %%` to `{{ variables }}` and add a test in https://github.com/mozilla/webmaker-mailroom/commit/a0d298a738ec878ad0a4a974d19ebe3f6773dd8f#diff-ec891e4e77162d7611ac4c5badfa1acfR27 for the new locale

**Comment by ScottDowne** [comment]
Landed: https://github.com/mozilla/webmaker-mailroom/pull/48#event-466014007
