### ISSUE TITLE
Currency dropdown doesn't look like a button

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/donate.mozilla.org#734]
... it looks like a textbox. When I click on it, it's obviously a dropdown, but I wasn't really encouraged to interact with it — just got curious.

<img width="430" alt="screenshot 2015-11-11 16 30 19" src="https://cloud.githubusercontent.com/assets/403231/11103624/91e3949a-8891-11e5-949c-c4996f8ee13f.png">

**Comment by valianttry** [comment]
@secretrobotron what is your browser; etc? I'm on FF on Mac and see:

![donate_mozilla_org___spenden_sie_noch_heute_an_mozilla](https://cloud.githubusercontent.com/assets/9830371/11103912/88d03dc0-887a-11e5-9019-9b6d23357bc8.png)

**Comment by secretrobotron** [comment]
@valianttry Chrome!

**Comment by valianttry** [comment]
@secretrobotron TRAITOR!

**Comment by secretrobotron** [comment]
:boom:

**Comment by valianttry** [comment]
:dancers:

**Comment by secretrobotron** [comment]
Fixed by https://github.com/mozilla/donate.mozilla.org/pull/736
Thanks @ScottDowne
