### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/donate.mozilla.org#735]
During `npm install`:
```
npm WARN deprecated babel-core@5.8.25: Babel 5 is no longer being maintained. Upgrade to Babel 6.
```
... which is probably bad.

**Comment by jbuck** [comment]
@k88hudson says that the upgrade to Babel 6 is annoying. But you're right, we should do it!

**Comment by secretrobotron** [comment]
@alicoding why was this closed? Did an upgrade happen?

**Comment by alicoding** [comment]
@secretrobotron yup! sorry forgot to link to the commit https://github.com/mozilla/donate.mozilla.org/commit/32b143fdaa56750f751a0e1620c746d0ed7120bc

**Comment by secretrobotron** [comment]
:+1:
