### ISSUE TITLE
Setup front-end sendto.m.o redirects to donate.m.o

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#739]
When we're happy with the performance of donate.m.o we should add redirects from sendto.m.o to donate.m.o.

We also need to figure out what to do about BSD signups.

**Comment by adamlofting** [comment]
I think this is just adding a line of JavaScript into the BSD form to forward traffic to our new form?

﻿We had this much traffic still landing on sendto in the last week:
<img width="385" alt="screenshot 2015-12-03 15 33 15" src="https://cloud.githubusercontent.com/assets/1901816/11564853/4855daec-99d3-11e5-93f5-5155b12a1dcb.png">

These traffic sources fall into the 'haven't had much info' category, so I think we should forward this page to:

* https://donate.mozilla.org/about/?ref=sendtoforward

**Comment by adamlofting** [comment]
Suggesting this is a P1 because it delivers good impact for a tiny effort.

**Comment by alicoding** [comment]
I added a `<meta>` tag to redirect the traffic as a quick workaround and it is now being redirect to donate.mozilla.org.

**Comment by adamlofting** [comment]
:ghost:

**Comment by jbuck** [comment]
I think @adamlofting did a fix for this!
