### ISSUE TITLE
Find and terminate any sendto.m.o links

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#740]
Find and terminate any sendto.m.o links living on mozilla.org and other sites we care about

**Comment by valianttry** [comment]
![arnold-schwarzenegger-the-terminator_jpg__jpeg_image__634 x 344_pixels_](https://cloud.githubusercontent.com/assets/9830371/11106332/2ac3bcc4-888a-11e5-821f-5bf5ed5a3c24.png)

**Comment by valianttry** [comment]
I pulled a report from BSD of all sources for donations:
https://docs.google.com/a/mozilla.com/spreadsheets/d/1OzOn16eyqEXkphYWQngwLp5C7N9AHb2sa_O-hJTTy6g/edit?usp=sharing

I'm now going to whittle this big list down to a short list of page sources where we actually need to update the donate URL.

**Comment by valianttry** [comment]
OK here is the list:

**Need to update "donate" links on these pages:**
* https://sendto.mozilla.org/page/contribute/givenow-seq?source=base_url
* https://www.mozilla.org/en-US/contribute/
* https://wiki.mozilla.org/Ways_to_Give
* Fundraising.mozilla.org
* http://openbadges.org/

**Also:**
* Firefox + You Newsletter: evergreen fundraising link - provide new URL to MJ or @bniolet1 
* Tabzilla is still live on some pages - update or take down if little traffic? - ask @jbertsch 
* Directory Tile that is evergreen (non-EOY) - update with Jessica Vondrak
* Evergreen Facebook, Twitter for both Firefox and Mozilla accounts (non-EOY) - alert Jessica Vondrak

**Puzzles:**
* source = "thunderbird_about" (could not locate a Thunderbird About page with a donation link)
* source = "getting started" but I cannot precisely identify the web page, maybe: https://support.mozilla.org/en-US/kb/get-started-firefox-overview-main-features

**Comment by adamlofting** [comment]
I think the two puzzles may be in-product links. 

E.g. the 'About Thunderbird' may be like the 'About Firefox' window here:

<img width="637" alt="screenshot 2015-11-12 09 39 14" src="https://cloud.githubusercontent.com/assets/1901816/11115131/53ac6ea0-8921-11e5-8a16-b6749bdef1e0.png">

`getting started` might be somewhere in the first run experience for new Firefox users, but I'm guessing a bit here.

**Comment by valianttry** [comment]
@adamlofting I found a few others when i researched this bug: https://github.com/mozilla/donate.mozilla.org/issues/780

**Comment by edrushka** [comment]
Mike Alexis is going to file bugzilla bugs with appropriate teams for some of these. I'll try to cross-reference those back here once that's done.

**Comment by adamlofting** [comment]
I'm going to P2 this. It's important for when we switch off BSD. But it's not urgent to EOY (as we have front-end redirects in place).

**Comment by ScottDowne** [comment]
@valianttry friendly ping on this seeing how we've been talking all things bsd.

The link (at the least) that adam screenshoted still exists.

**Comment by valianttry** [comment]
We're about to kill BSD dead. So we'll have a hard redirect soon.
