### ISSUE TITLE
Write copy for short survey of donors (EN only)

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#746]
Scoped in https://github.com/mozilla/donate.mozilla.org/issues/292

Draft copy for a user flow and language for a brief survey to present to a segment of donors immediately after they give:
https://docs.google.com/document/d/1L_GONC8Wb4QMCxAtndVbZNzdau-AhBvdWnuYzaqqQN8/edit

cc @edrushka  cc @bniolet1

**Comment by valianttry** [comment]
@gregglind @MattGrimes check out this draft copy for a survey (and where it would sit in the user flow). Are you two the right people to review this language? Who do we give it to once we've finalized?

**Comment by valianttry** [comment]
@adamlofting what do you think about the language I've drafted here:
https://docs.google.com/document/d/1L_GONC8Wb4QMCxAtndVbZNzdau-AhBvdWnuYzaqqQN8/edit

**Comment by adamlofting** [comment]
This is great. I'm really curious to see the results.

The only other thing that might be valuable is to add a free text box for feedback/comments. It would be great to have more 'donor voice' we can learn from share with the wider team.

**Comment by valianttry** [comment]
@adamlofting I incorporated your suggestions into the Google Doc. Thanks!

@edrushka or @bniolet1 any major concerns or edits?

**Comment by bniolet1** [comment]
So this is great and we'd learn a lot from this form. But now allow me to poke it with a stick: 

I'm obviously not a data science type, but what would be the impact of making it a "choose multiple" form? My first impression with "choose one" is that we're trying to oversimplify something that may be more complex and could unfairly skew the results. (fact is people probably have lots of reasons for why they do what they do).

If we had a choose multiple would we still see some patterns emerge or would there be too much of a change that people would just pick both and submit? 

What if we got slightly more granular (this is veering into push polling: like I said, I'm not a scientist): 

[] I like the stance Mozilla takes on important issues.

[] I like the work Mozilla does to teach the web.

[] Firefox is valuable to me. 

[] Other

**Comment by valianttry** [comment]
@bniolet1 true, there is nuance we'd miss with the super simple approach. Here's my thinking....and why I kept it SUPER simple....

Right now, as we've discussed we know :goat: about our Firefox donors (goat = zero zilch nada). If the hypothesis is to find out, on a high level initially, WHY people give, I err on side of a simpler approach. What we find out will inform next-level-down survey.

**Comment by bniolet1** [comment]
Makes perfect sense. Go forth and measure!!

**Comment by edrushka** [comment]
I agree it makes sense to start with a simpler approach (I like the "other" option and comment box). You'll be able to check both (or all 3, I suppose), correct?

**Comment by valianttry** [comment]
@edrushka i'm suggesting we force people to choose between mozilla, firefox or other (only 1 of those 3) then they can also leave a comment. On this initial iteration of a survey, I'm interested in forcing people to answer here -- as a survey tactic it gives you a little higher quality data on a user's true choice. We may see people complain in the comments that they feel "forced to choose, but i love both the mission and Firefox!" and that would be an interesting finding! After we get some data, then we can consider how we build the next iteration. E.g. if we get a LOT of "Mozilla Mission" responses, we can follow Ben's suggestion and break out Mozilla's major programs for reaction.

**Comment by edrushka** [comment]
OK, that works for me, @valianttry 

If we're putting this as a pop-up after the 3rd step of the form, do we want those people to see the thank you/confirmation page as well, or just go directly to the social share page?

Also, I'm unclear on who designs this. It should visually fit into the rest of the flow. Can Gregg's team take that on, or should I look for a designer on our end?

**Comment by valianttry** [comment]
@adamlofting do we have access to SurveyGizmo so that we can set this up ourselves? I'm looping @gregglind @MattGrimes back in to ask if they can help set this up or if we should just set this up on our own in SurveyGizmo.

**Comment by adamlofting** [comment]
I don't have access to Survey Gizmo, and haven't seen MoFo use it anywhere else yet, so I think we'll need support in setting up this first Survey.

I would be good to get access so that we can watch the results and feedback coming in anyway.

**Comment by MattGrimes** [comment]
Hey Adam. We are happy to help. @TylerDowner is putting the survey together right now. You should be able to proof it later today.

**Comment by TylerDowner** [comment]
Here is the survey, https://www.surveygizmo.com/s3/2472227/Mozilla-Donor-Survey

I've left it in a plain white style, if you'd like it to look differently (like https://www.surveygizmo.com/s3/2410652/Mozlando-Pitches) I can do that.

**Comment by valianttry** [comment]
@TylerDowner this is really solid. Thank you! :clap:  For "look" can you borrow font, background sandstone, and wordmark from our donation form design: https://donate.mozilla.org/en-US/

I assume we'll have the option to make this appear as a "popup" vs. a web page?

**Comment by TylerDowner** [comment]
If there is someone on your team who can edit the theme, then i can give them access to edit the theme.

As for a pop-up, I'm not entirely sure what it takes to do that, again, your web-dev resources may be able to help.

**Comment by adamlofting** [comment]
I think we can setup the pop-up like this:
http://help.surveygizmo.com/help/article/link/website-popup

I'm happy to work through that if you can add me to survey gizmo (my first name @mozillafoundation.org)

In the pop-up version, we might need less extra styling work.

**Comment by TylerDowner** [comment]
Sorry for the delay, you now have an account.

**Comment by valianttry** [comment]
@adamlofting do you think you'll have some time to set up this survey for a segment of donors?

**Comment by adamlofting** [comment]
:+1:
