### ISSUE TITLE
If a payment provider is down, ability to hide that provider in flow

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#75]
E.g. If PayPal is down, we can switch off PayPal and users only see the option to donate by Credit Card.

Or if Stripe is down, users only see the option to donate by PayPal.

The same can apply if we added in further providers.

**We don't need to fully perfect the UX in these scenarios**

Just route as much traffic as possible into systems that are working at that moment in time to limit impact (if this happened on 31 Dec for example).

Because the likelihood of this is low, I suggest we don't use it as a reason to change how we build pages. I.e. if we're building from our repo to static HTML pages, it's OK for the 'off switch' to be managed in the repo and deployed by making a new commit to the repo. 

Let's not switch to a dynamic site specifically to cope with this configuration option if it would have a negative impact on page load / stability for all the time when these systems are working fine.

cc @jbuck

**Comment by adamlofting** [comment]
This is a nice to have enhancement.

**Comment by jbuck** [comment]
#961
