### ISSUE TITLE
analytics.js needs to be called after `ga` is defined

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#750]
Initial look at #742 

We are tracking our ecommerce transactions using this code:
https://github.com/mozilla/donate.mozilla.org/blob/master/public/js/analytics.js

However, this code is being loaded on the thank you page via this import:
https://github.com/mozilla/donate.mozilla.org/blob/master/pages/thank-you.jsx#L13

We actually need to fire the ecommernce transaction code after `ga` is defined in `ga.js`
https://github.com/mozilla/donate.mozilla.org/blob/master/pages/index.jsx#L43

**Comment by adamlofting** [comment]
@ScottDowne @jbuck @alicoding I'm not entirely sure of the load order for when the code in `thank-you.jsx` is called, so need your recommendation on which of these options is best:

1. Move the current loading of `ga.js` somewhere higher up in the order so this is called before `thank-you.jsx` is called. 
2. Put the contents of `analytics.js` into `ga.js` which will definitely work for tracking, but would be running this code on everypage (not just the thank you page). The perf hit should just be the regex test to see if the query string parameters exist so it shouldn't be significant.
3. Remove `analytics.js` from `thankyou.jsx` and add it back into the head of `index.jsx` as a regular script tag below `ga.js`. But somehow include this conditionally only on the thank you page.

I'm leaning towards 2 for simplicity and reliability, but what do you think?

I'm offline now but if we could ship one of these it would be helpful for our early insights with the DE campaign.

**Comment by ScottDowne** [comment]
On thing I want to add is on this line: https://github.com/mozilla/donate.mozilla.org/blob/master/pages/thank-you.jsx#L13

Is not actually firing the function there (or is not not supposed to), it's just creating the function, we call it later inside componentDidMount  https://github.com/mozilla/donate.mozilla.org/blob/master/pages/thank-you.jsx#L18

Which happens really late in the load order, if ga is not defined yet, ga is happening really late as is. We should be putting ga up in the process.

**Comment by ScottDowne** [comment]
I kinda like solution 1.

https://github.com/mozilla/donate.mozilla.org/pull/756/files

We're adding ga too late imo. analytics.js is right where we want it.

**Comment by ScottDowne** [comment]
We merged #756

@adamlofting I'm closing this, so feel free to take a look when you get a chance and don't hesitate to reopen or file another bug if you find something you don't like about the solution.

**Comment by adamlofting** [comment]
:sparkles:
