### ISSUE TITLE
Make sure page loads correctly if Optimizely is down, or responding slowly 

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#76]
- [ ] Can we automate this test somehow? Yeah, maybe modify hosts file and see what happens, or run dummy servers to simulate badly behaving servers

**Comment by ScottDowne** [comment]
This is fine with what the browser does, and nothing we can do that can be better than that.

If it's down or not there, the browser just ignores it and keeps going. If it's slow, it times out and keeps going.

We could do the same thing, time out for slow or skip if not there.

Closing.
