### ISSUE TITLE
Paypal transaction stats do not take currency values into account

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#761]
@cadecairos found this bug. Basically, given the following transaction:

```
  AMT: '5.00',
  CURRENCYCODE: 'GBP',
  SETTLEAMT: '7.03',
  SETTLEAMTCURRENCYCODE: 'USD',
```

We're calculating totals based on the AMT, instead of the SETTLEAMT. Ooooooooooooooops

**Comment by adamlofting** [comment]
Just checking... is this in the transaction db / totalizer API, or somewhere else?

**Comment by jbuck** [comment]
both of those, yeah. fortunately it only affects a small percentage of transactions, but still good to fix!

**Comment by jbuck** [comment]
Patch in https://github.com/mozilla/mofo-transaction-storage/pull/3, needs review

**Comment by jbuck** [comment]
This landed!
