### ISSUE TITLE
Move ga.js script to the bottom of the <head>

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#762]
In order to verify Webmaster Tools and also for good practices we should move ga.js to the bottom of `<head>` tag.

**Comment by adamlofting** [comment]
Replying from my phone so excuse lack of detail but please see ticket filed today about ga.js load order #750 to make sure this doesn't undo that fix.

Ga.js should be fine anywhere in the head for the purpose of webmaster tools.

**Comment by ScottDowne** [comment]
Yeah, bottom of head should be fine, just so long as it's before main.js.
