### ISSUE TITLE
Implement autoscaling for Heroku

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#763]
Rather than paging on-call to manually scale donate.mozilla.org, we should have a computer do it.

@cadecairos Do you think Adept Scale would fit the bill here?

**Comment by ScottDowne** [comment]
From our triage: Adept Scale wouldn't be good here because it only cares about average response times which is not useful to us.

**Comment by cadecairos** [comment]
Also from triage: we're going to try adpet scale and see how it responds to load next week.

**Comment by cadecairos** [comment]
I've added the adept scale corvette ($36) plan to eu and us apps.

Based on data from log entries, Our average service time is under 100ms our 95th percentile falls under 300ms and our 99th percentile is 1-2 seconds. Based on this, I've set it to scale up to a max of 8 dynos, 1 dyno at a time, if the average response time goes above 1000ms.
