### ISSUE TITLE
How can we improve our Intl + data polyfill?

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#765]
Currently we're using [polyfill-service](https://github.com/Financial-Times/polyfill-service) for the Intl polyfill & data for 5 locales.

I had a look at the Logentries data for our .js files and found that the polyservice-service is 10x slower on average than the static js files:

![screenshot 2015-11-12 17 04 27](https://cloud.githubusercontent.com/assets/578466/11132746/bc44e706-895f-11e5-95ab-e0b1d6d9b070.png)

We're not doing caching for this path, but it looks like [caching on User-Agent is not recommended](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-user-agent-header). Better than not caching at all though.

@alicoding Do you think we could do something like build a per-locale main.js file that includes the Intl polyfill & locale data?

**Comment by alicoding** [comment]
@jbuck I've done some research and building main.js per-locale seems to be the most common one and the most optimized one as well, so I will take a look as how to do this using webpack or better yet, just have that path to be one locale only.

**Comment by jbuck** [comment]
@alicoding did some nice improvements here: https://github.com/mozilla/donate.mozilla.org/pull/813

Lets do some more measurements after this is on production

**Comment by jbuck** [comment]
Fixing in #978

**Comment by jbuck** [comment]
This is as good as we're going to make it unless we include the polyfill within main.js for every browser.
