### ISSUE TITLE
Names are not being captured

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#778]
Looking at the most recent payments, the first name and last name are not being captured anymore: https://dashboard.stripe.com/payments/ch_176Y3rG8Mmx3htnxJiikYuI4

@ScottDowne Any ideas?

**Comment by jbuck** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/commit/c2b60594314b6d5cd95148553ea1666f0a1bb7a8

**Comment by ScottDowne** [comment]
Good catch
