### ISSUE TITLE
Update thank you email to include how to cancel your recurring donation

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#779]
@alicoding I'll need to also add this to the email translation; is it as easy as updating email.properties and Pontoon picks it up?

Copy is: "If you would like to cancel your recurring donation, send your request in an email to donate@mozilla.org."

**Comment by alicoding** [comment]
Yup, once you update that file, Pontoon should picks that up and if we need this to be translated very soon we should also email dev-l10n list which I think this time we should do that because we just launched the form on production and its a good idea to let them know at the same time

**Comment by jbuck** [comment]
I've landed the patch, now I need to wait for translations to start rolling in.

**Comment by jbuck** [comment]
Substantially done in https://github.com/mozilla/webmaker-mailroom/commit/c20136b58c04551cae35d13879b67dc5c355391b and https://github.com/mozilla/sawmill/commit/a18a9998ce5f40957b71f5766b9311f9b68c689d

I'll continue to update these locales as we receive translations.
