### ISSUE TITLE
Write a list of automated API Tests we should run

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#78]
See also #13 

- [x] Make sure Travis is configured to run tests when we try to merge new PRs

**Comment by adamlofting** [comment]
Travis is setup to run tests, but we haven't written the tests.

Can we start by making a list of useful things we should be testing?

**Comment by edrushka** [comment]
Is this useful? https://docs.google.com/drawings/d/125P93oubUTUD0d2J1u7HuFhcXd_lnN6PFYfQjoDMCEk/edit

**Comment by adamlofting** [comment]
> Is this useful? https://docs.google.com/drawings/d/125P93oubUTUD0d2J1u7HuFhcXd_lnN6PFYfQjoDMCEk/edit

@edrushka this ticket is tracking a different kind of test. These tests check that each time we commit new code, we don't break existing functionality.
