### ISSUE TITLE
Improve the top four results on Google search for "donate mozilla" or "donation mozilla"

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#780]
I did a simple Google search for "donate mozilla". Here's the screengrab of what I saw:

![donate_mozilla_-_google_search](https://cloud.githubusercontent.com/assets/9830371/11139595/56b8f572-8986-11e5-9b8a-6027695cf6a7.png)

**A.** We should replace this page with a redirect as soon as possible, it's the #1 result

**B.** Update the "Donate" URL on this page: https://www.mozilla.org/en-US/foundation/
(and maybe make the "donate" link more noticeable? Bold? Brigher?) It gets over $1000/ month in donations!

**C.** We should add a more prominent "Donate here" link (Andrea can do this) DONE

**D.** We should either delete this (really ugly) page or make sure it redirects to our new donation form:
https://join.mozilla.org/faq.en.html

**Comment by valianttry** [comment]
Related bug: https://github.com/mozilla/donate.mozilla.org/issues/740

**Comment by valianttry** [comment]
cc @alicoding and @jbuck

**Comment by valianttry** [comment]
C is fixed, i made an all-caps link to the donation form more prominent on the donate FAQ wiki.

**Comment by valianttry** [comment]
a search for "donation mozilla" resulted in the exact same top results.

**Comment by alicoding** [comment]
This one really needs to wait until we do `301` redirect for `sendto.mozilla.org` then it will be fixed by itself. I don't think we can do anything or need to do anything more here.
