### ISSUE TITLE
Improve search results for Yahoo search

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#781]
Searched for "donate mozilla" at yahoo.com. 

This is so sad. There may be nothing we can do @alicoding .... but we are a whole screen scroll down!

![donate_mozilla_-_yahoo_search_results](https://cloud.githubusercontent.com/assets/9830371/11140232/24fe6470-898d-11e5-8dfa-2c8d7d57c427.png)

**Comment by valianttry** [comment]
Here are search results on Yahoo for "donation mozilla":

![donation_mozilla_-_yahoo_search_results](https://cloud.githubusercontent.com/assets/9830371/11140256/69c19e06-898d-11e5-9758-73bd6f7c44d3.png)

**Comment by valianttry** [comment]
cc @alicoding

**Comment by alicoding** [comment]
And so for yahoo \o/ 
![screen shot 2015-12-16 at 1 14 17 pm](https://cloud.githubusercontent.com/assets/4368149/11849666/fbc92516-a3f6-11e5-9fc7-8f88979e42df.png)
