### ISSUE TITLE
Improve search results for Bing search for "donate mozilla" or "donation mozilla"

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#782]
Search on Bing had the best, most useful results! Look:

![donate_mozilla_-_bing](https://cloud.githubusercontent.com/assets/9830371/11140316/085dddea-898e-11e5-9add-9d382fd43a96.png)

**Comment by alicoding** [comment]
We are now back to the top \o/ 
![screen shot 2015-12-16 at 1 13 22 pm](https://cloud.githubusercontent.com/assets/4368149/11849644/dbc246f8-a3f6-11e5-98ff-07d1d723ce09.png)
