### ISSUE TITLE
Add EOY fundraising appeal to post Heartbeat landing page

### ISSUE THREAD

**Issue by bniolet1** [mozilla/donate.mozilla.org#787]
This is an attempt to keep in sync with a bug request I filed on this in Bugzilla. 

The bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1224614

The text: 

As we ramp up for the EOY foundation fundraising push, we'd like to add a call to action to donate to Mozilla to the landing page that appears for users who submit a 4- or 5-star rating on Heartbeat. 

I will allow Andrea to chime in, but I think we're looking for something that's a relatively light lift for the team. A small section of content, that MoFo can provide that takes users to the existing donation form. (https://donate.mozilla.org).

An important question here, obviously, is for what languages do we want to expose this CTA. I don't want to speak for MoFo, but I'll try anyway. This ask isn't a P1 for the fundraising campaign but it's definitely a "nice-to-have" from both a fundraising standpoint and a research standpoint. 

English is by far the largest market for fundraising and would be an obvious language to support for this.

**Comment by bniolet1** [comment]
@edrushka No idea if I did this right. My first github issue, so be kind.

**Comment by bniolet1** [comment]
Hi team, here's the reply from Jen Bertsch from the bug: 

*Thanks for riding herd on this one, Ben!

I'd definitely recommend, given the time frame, that we stick with en-US only.

What do you need from the www/creative team?  Design, copy, and coding?  Or just review for brand compliance and coding?

If just brand compliance and coding, it would be great if we could have 5 business days to turn this around.  We have a lot on our plates and a lot of folks in and out of the office due to the upcoming holidays etc etc.*

I have asked for the URL for the page we want to make changes to. When I get it, I'll post here and we can try to figure out the best approach, creatively for making this happen.

**Comment by edrushka** [comment]
Hey @bniolet1! Would the text be in addition to what's here, or replacing it? https://www.mozilla.org/en-US/firefox/feedback?score=5

**Comment by bniolet1** [comment]
I think we're fine to replace it if that's what you want to do.

**Comment by edrushka** [comment]
I'd suggest copy along the lines of:
Thank you for your feedback!
We're so glad you're happy with Firefox.
Did you know that Mozilla is the non-profit organization behind Firefox? We rely on donations to carry out our mission of keeping the web free, open and accessible to all. Will you donate to support our work?
Donate Now button.

**Comment by edrushka** [comment]
heh. Just noticed that Andrea wrote almost the identical thing in Bugzilla. Let's close this and work in Bugzilla only.
