### ISSUE TITLE
Decide what browsers we are supporting

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#79]
- [x] @adamlofting to find /compile this list
- [ ] then we need to decide how we test properly for each change to the code

**Comment by adamlofting** [comment]
@jbuck @ScottDowne @alicoding 

How does this list look for browser support.

<img width="586" alt="screenshot 2015-08-28 14 05 03" src="https://cloud.githubusercontent.com/assets/1901816/9546833/e0b14b74-4d8d-11e5-8495-7e4db3e645ef.png">

Looking at the numbers, it's worth investing time to cover these as it results in a big enough % of donations to justify the effort. [Here are the numbers](https://docs.google.com/spreadsheets/d/1v1BUTANKza-hw7rBWkLW7Vhg3B4XvL6fRuRZOezKbpo/edit#gid=1336362551) I was looking at.

If this works for you, I'll add it to the QA script.

**Comment by alicoding** [comment]
Work for me and seem doable anyway :+1:

**Comment by jbuck** [comment]
I am very concerned by supporting IE8, much less concerned about IE9+, but the higher the version of IE the better

**Comment by adamlofting** [comment]
Following call, IE8 is the only real concern here.

IE9 and 10 don't really register on the stats as those users got upgrated to IE11. But IE8 gets enough traffic that's it's worth making something work.

Next steps:

* See how broken IE8 is with our current build - and estimate effort to make it work
* If the effort is too high, let's ship a simple fall back such as browser detection for IE routes users to our static HTML back-up form.

I'll file bugs for these tasks.
