### ISSUE TITLE
Make sure DE Thank You receipt is working correctly

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#799]
Hi Jbuck -- I received an email from someone with a DE address in the donate@ Inbox, but I noticed it was in English vs. German. I just want to make sure the DE email receipt / auto-reply is working properly. 
![re__thank_you_so_much_for_your_gift_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11165604/a6fce640-8ac8-11e5-902c-cfb6800368b1.png)

**Comment by jbuck** [comment]
Can you provide a link to their charge in Stripe? I suspect the reason they got the EN email is they visited donate.m.o/de/, but we can easily confirm that by look at the charge in Stripe.

**Comment by valianttry** [comment]
hi @jbuck -- isn't that when a donor should get an email in german, they donate via the /DE form? 

I just tried to search for her name in "customers" and it didn't turn up anyone?

Now i'm really confused.

**Comment by jbuck** [comment]
Errrrrrrrr let me try that again

Can you provide a link to their charge in Stripe? I suspect the reason they got the EN email is they visited donate.m.o/en-US/, but we can easily confirm that by look at the charge in Stripe. Search by their email

**Comment by valianttry** [comment]
hi @jbuck -- I tried to search for her in Stripe but couldn't find her (sorry if that wasn't clear).

**Comment by jbuck** [comment]
Looking at the formatting of the address (it has a `,` in it), I think this person donated via BSD. Could you search for her email in there?

**Comment by jbuck** [comment]
I propose that we add the Stripe transaction id to the thank you email so it's easier to find transaction: https://github.com/mozilla/donate.mozilla.org/pull/802

**Comment by valianttry** [comment]
Yup she was in BSD -- 

![roswitha_lasser___constituent_record](https://cloud.githubusercontent.com/assets/9830371/11171166/f4870870-8b9d-11e5-8653-eec8afb34e56.png)

**Comment by valianttry** [comment]
since this is an open repo, please advise if i'm including too much information in this ticket.

**Comment by jbuck** [comment]
Nah, I think you're good! That's actually one reason I want to add the transaction id to the email, so we can easily share that in the open without revealing who donated it publicly.

Filed all of the follow-ups:

* https://github.com/mozilla/donate.mozilla.org/pull/802
* https://github.com/mozilla/webmaker-mailroom/pull/47
  * Should we add the transaction id to the email before it's been translated into German?
* https://github.com/mozilla/sawmill/pull/64

**Comment by jbuck** [comment]
@valianttry I have a question for you: Should I send the email with the string "Transaction ID" untranslated, or should I wait for that to be translated?
