### ISSUE TITLE
Setup the email opt-in page hosted on the new system, but it will still talk to BSD to store the subscriptions

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#8]

**Comment by ScottDowne** [comment]
Sign up now working: https://github.com/mozilla/donate.mozilla.org/commit/a691f6c3a4fee4c0c344a65f1c6972baf3f1a7d8

However, I couldn't get it to link to a not BSD page yet, so it still links to the BSD share page and not the new one which does exist. I'll file it as a post whistler bug.

**Comment by adamlofting** [comment]
If you're posting to the BSD form, we can simply update the 'thank you redirect URL' in the config for that form in BSD.

I think you can also submit the post as an xhr request, then check the thank you page content if you want to manage the redirect. I think that's what happens [here](https://welcome.webmaker.org/pledge/teach-the-web/)
