### ISSUE TITLE
NEW auto-reply for incoming email to donate@ - for setup in Desk.com

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#801]
If a donor sends an email to donate@mozilla.org, we should set up an immediate auto-reply that:

* Is warm and friendly and thanks them for their support
* Answers the most frequently asked questions directly in the auto-reply and links to an FAQ for less frequent questions, in case they can help themselves (likely in many cases).
* Says we will try to respond within 48 hours

Both this email and the FAQ should be localized. Localization ticked for donation FAQ is https://github.com/mozilla/donate.mozilla.org/issues/437

Working on draft auto-email here:
https://docs.google.com/a/mozilla.com/document/d/1Nrk0f2Z64Qa0e-VlBMhVy5mdvXFoMCYIiZUD9T08hg0/edit?usp=sharing

**Comment by jbuck** [comment]
I hope desk.com has the auto-responder built-in :x

**Comment by adamlofting** [comment]
> I hope desk.com has the auto-responder built-in :x

It does :+1: 

@valianttry 
> Both this email and the FAQ should be localized. 

desk.com doesn't do language detection on inbound emails. I think the options are:

* Setup email addresses for all locales we will support (adds quite a bit of setup and maintenance)
* Include locale links in the EN auto responder pointing to the localised FAQs `En français` etc.

**Comment by adamlofting** [comment]
When this copy is ready I can set this up in desk.com

**Comment by valianttry** [comment]
@adamlofting I have updated the email, here:
https://docs.google.com/document/d/1Nrk0f2Z64Qa0e-VlBMhVy5mdvXFoMCYIiZUD9T08hg0/edit#

I would love for @edrushka  and Stephanie to take a look before you implement this in Desk.com.

**Comment by edrushka** [comment]
Made a few minor suggestions. Looks good!

**Comment by KevZawacki** [comment]
@valianttry Just proofed, as well. Looks good!

**Comment by adamlofting** [comment]
This is now live :+1: 

Future tweaks to the copy can be made here: https://webmaker.desk.com/admin/channels/email/auto-acknowledgements

**Comment by valianttry** [comment]
@adamlofting we're seeing very appreciative emails in response to the auto-reply! This guy wanted our mailing address and had this reply after getting the automated msg including our address:

![_2332__robert_tin](https://cloud.githubusercontent.com/assets/9830371/11988689/97029f2e-a9a8-11e5-8f9b-4b6938e1d0e5.png)

Yay for saving work and making people happy :tada:
