### ISSUE TITLE
Design Twitter graphics for EOY

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#807]
We need a selection of twitter graphic for the EOY campaign, based off the designs in#558 and #559. As we iterate on those two assets, we'll add additional twitter graphics. This ticket is just for the first set.

Assigning to @natalieworth with a deadline of EOD Friday Nov 20. Let me know if that's too tight a timeline, Natalie!

cc @lovegushwa @valianttry @cassiemc

**Comment by edrushka** [comment]
I found some "official" copy you can use if it works:

Variant A
I :purple_heart: the Web.
I gave to Mozilla.
You should too.

Variant B
:purple_heart: the Web? Give Mozilla some :purple_heart:.

Variant C
I just donated. So should you.

Variant D
I gave to Mozilla b/c I :purple_heart: the Web.

Variant E
:purple_heart: Mozilla? Give $!

Variant F
:purple_heart: the Web? Give Mozilla some $ like I just did.

**Comment by natalieworth** [comment]
Awesome, this is helpful! Thanks @edrushka

**Comment by edrushka** [comment]
Some further details on how we'll localize these:
1) try to keep most of the designs free of copy. we'll add the text in the tweet itself.
2) We can do a localized variant of  "I :purple_heart: the Web" in our top locales:
es
pt-br
it
id
de
fr

**Comment by edrushka** [comment]
":purple_heart: Mozilla? Give $!" could also work for those locales if we add the correct currency

**Comment by natalieworth** [comment]
Okay awesome thanks!

**Comment by edrushka** [comment]
cc @HPaulJohnson @KevZawacki

**Comment by KevZawacki** [comment]
@edrushka I like the variations with the :purple_heart: 

Is "Internet" more globally recognizable than "Web"?

**Comment by edrushka** [comment]
MoCo is shifting towards using "Internet" over "Web". Most of our EOY stuff was written before that was known. I don't mind using Internet on these social assets, but I realize character counts are pretty limited, so Web is fine too if it works better design-wise.

**Comment by KevZawacki** [comment]
@edrushka Ah, gotcha. Maybe sticking with "Web" is best, then.

**Comment by natalieworth** [comment]
@lovegushwa @valianttry Updates for the EOY tiles are here too for you guys to view on redpen: https://redpen.io/p/npc29dacd3ad00ee8e

**Comment by lovegushwa** [comment]
@edrushka @valianttry @KevZawacki @natalieworth

You can download the final twitter share images here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvOXVBaFJFN3dYU0k&usp=sharing

This issue is ready to close.

**Comment by edrushka** [comment]
Fantastic! I especially love the playful peeking Dapper Fox, and of course, the introduction of Flower Fox! Thanks @natalieworth @lovegushwa!
