### ISSUE TITLE
Design Facebook graphics for EOY

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#808]
We need a selection of Facebook graphic for the EOY campaign, based off the designs in#558 and #559. As we iterate on those two assets, we can create additional facebook graphics. This ticket is just for the first set.

Assigning to @natalieworth with a deadline of EOD Friday Nov 20. 

cc @lovegushwa @valianttry @cassiemc

**Comment by lovegushwa** [comment]
@edrushka @natalieworth @valianttry  we also created new unused facebook graphics early on in the Germany campaign. #168 

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvZTljV29rek11Vnc&usp=sharing

**Comment by edrushka** [comment]
I totally forgot about these!!!  Could we maybe exchange the red heart for our EOY orange/yellow heart? Or are there other ways to reuse these that will visually tie in with the campaign?

**Comment by natalieworth** [comment]
Hey @edrushka, for this issue do we need similar graphics to those in the issue @lovegushwa listed above? Are they just images with the Mozilla logo or is there any content that we should include on these? Thanks

**Comment by edrushka** [comment]
I found some "official" copy you can use if it works:

Variant A 
I 💜 the Web.
I gave to Mozilla.
You should too.

Variant B
💜 the Web? Give Mozilla some 💜.

Variant C
I just donated. So should you.

Variant D
I gave to Mozilla b/c I 💜 the Web.

Variant E
💜 Mozilla? Give $!

Variant F
💜 the Web? Give Mozilla some $ like I just did.

**Comment by edrushka** [comment]
Note that the emoji hearts are intentional (although they don't have to be purple).

**Comment by edrushka** [comment]
If you're doing any graphic-based designs (i.e. no photo), here's the details for how we'll localize:


Some further details on how we'll localize these:
1) try to keep most of the designs free of copy. we'll add the text in the fb post itself.
2) We can do a localized variant of "I :purple_heart: the Web" and 
":purple_heart: Mozilla? Give $!" (with correct currency sign) in our top locales:
es
pt-br
it
id
de
fr

**Comment by edrushka** [comment]
cc @KevZawacki @HPaulJohnson

**Comment by natalieworth** [comment]
Hi @edrushka here are the first iterations. I did a bunch hoping that we could refine maybe 6 depending on how many we need? Let me know if I'm on the right track with the emoji you suggested too above. 
https://redpen.io/p/hs67f7f34951ab9c54
Thanks!

cc @valianttry @lovegushwa @HPaulJohnson

**Comment by natalieworth** [comment]
Was just going to post that the V2 designs, but I see everyone is already in the redpen already! :D 
https://redpen.io/p/hs67f7f34951ab9c54
cc @valianttry @lovegushwa @edrushka  @HPaulJohnson
Just working on finishing the V2 for the EOY call-outs and will post soon.

**Comment by lovegushwa** [comment]
@ScottDowne @alicoding @jbuck 

You can download v1 of the facebook share here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvNGVlNE1NcmZ4dGM&usp=sharing
Same text as mockup below but change the address to DONATE.MOZILLA.ORG

![-1](https://cloud.githubusercontent.com/assets/12228435/11316053/7c015edc-8fb2-11e5-9238-fdd56e13d6cb.jpg)

**Comment by lovegushwa** [comment]
@cassiemc @sabrinang R? 
Can you review Twitter, Facebook and Email visual design for EOY?
We need to ship by end of day. (including all production work)

@natalieworth did great work getting these moving. We met with @valianttry on Friday and made a selection from the huge amount of options, then made final tweaks.

https://redpen.io/p/wq572fdb24204d8f68

**Comment by cassiemc** [comment]
these are rad @lovegushwa and @natalieworth!

**Comment by sabrinang** [comment]
super fun social graphics! great work :+1:

**Comment by lovegushwa** [comment]
Thank you @cassiemc @sabrinang 
I'll dig through redpen comments, fix and ship!

**Comment by valianttry** [comment]
srsly these are so awesome! :clap: @lovegushwa and @natalieworth !!

**Comment by lovegushwa** [comment]
@edrushka @valianttry @KevZawacki 

You can download the final facebook share images here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvU3o0dzV4cGhIMVk&usp=sharing

**Comment by edrushka** [comment]
Excellent job, y'all. These are lovely. Thank you!
