### ISSUE TITLE
Design a lovely January thank you email to donors

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#810]
Last year we sent a text-only email from Mark, and that can be our fall-back for this year, but it would be nice to add a little more flair. 

@natalieworth @lovegushwa and @cassiemc would love your ideas on how we can send a really lovely thank you. Design a beautiful template? Incorporate a graphic? A video? 

This might be a good project to work on in Orlando. @natalieworth would you like to take the lead on this?

**Comment by natalieworth** [comment]
Okay @edrushka, is it similar to issue https://github.com/MozillaFoundation/Design/issues/54 ?
I think we were perhaps thinking about tying the holiday thank-you into EOY which would work well

**Comment by edrushka** [comment]
Yah, there could definitely be some overlap with that ticket!

 @valianttry can you provide:
1) aprx # of people this email will be sent to
2) any design limitations you're currently aware of with Exact Target

**Comment by lovegushwa** [comment]
@edrushka can you post a link to Mark's letter from last year? I think it could help set the tone / provide context.

**Comment by edrushka** [comment]
![screenshot 2015-11-17 09 52 56](https://cloud.githubusercontent.com/assets/4515662/11219747/0b5cbeae-8d11-11e5-8b68-933780a4012e.png)

And here's the 2014 text: https://public.etherpad-mozilla.org/p/text_from_EOY_2014_thankyou_email

**Comment by edrushka** [comment]
This bug https://github.com/mozilla/donate.mozilla.org/issues/430 outlines some ideas for thank you videos and gifs. Please note that creating a new video is out of scope for this project. If Rainer's MozFest video works, we can use it but if not, the most we can do is a staff cheer (maybe at Orlando?)

**Comment by natalieworth** [comment]
@cassiemc Could I tie this in with issue https://github.com/MozillaFoundation/Design/issues/54? Not sure if they should be independent or if they are for the same thing?

**Comment by natalieworth** [comment]
Hi @cassiemc @edrushka, saw the milestone for this moved up a bit. I was wanting to get a start on this (although I don't believe we have confirmed copy for it). Based on the ET email for the gear store Mavis created, I believe this design track should be feasible for a thank-you email + video for donors: https://redpen.io/yb2214e299d07ad804

**Comment by edrushka** [comment]
Lovely! I've written a copy ticket here #1026 and we need to decide if we are using the video or not @valianttry

**Comment by cassiemc** [comment]
Sorry I missed the above comment awhile back. This looks great @natalieworth, thanks for jumping on it!

**Comment by natalieworth** [comment]
@edrushka @valianttry @cassiemc I'll be working on this next week and the simple thank-you webpage. Are there any requirements that you were wanting me to include for that or is it fairly open right now in terms of content and design?

**Comment by edrushka** [comment]
Updates on this:
- confirmed with Andrea we will *not* use the video in the January thank-you email
- also determined we don't need any additional bells and whistles. This should be a "simple" thank you email from Mark. It doesn't need to have heavy EOY branding. The most important thing is that it feels heartfelt and genuine.

I met with @natalieworth on Friday to discuss this and she'll do another iteration. We'll save the snazzy design in the redpen for another email. 

Changing milestone to Dec 11.

**Comment by valianttry** [comment]
I'm wondering if this ticket time is better spent updating our "general" mozilla template as seen in https://github.com/mozilla/donate.mozilla.org/issues/810#issuecomment-157452467. I know the "teach" email template got a nice update... since this is the first email of the new year, it might be time for a fresh start?

**Comment by edrushka** [comment]
Ohh that could be a good idea. @cassiemc care to weigh in?

**Comment by cassiemc** [comment]
wfm @edrushka

**Comment by edrushka** [comment]
OK. I'm going to close this and file a new ticket for an updated "general" template. @cassiemc can you and @natalieworth figure out a good way to preserve the work Natalie did on the "lovely" template in case we want to use it in 2016 e.g. for advocacy? I don't want it to get lost in the bowels of github ;)

**Comment by natalieworth** [comment]
Thanks @edrushka, I can post a link here of the source files for the previous template that we could hopefully use in future

**Comment by natalieworth** [comment]
Source file for the January thank you email based on the 2015 EOY Fundraising Campaign (note that the .ai file was a draft and would have to be updated with appropriate content if used): https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0X3dmWUJxRHdPTm8/view
