### ISSUE TITLE
Localize a design asset on Pontoon

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#812]
Let's use Directory Tiles as the first experiment on localizing design assets.

@lovegushwa can you link to the files here with a quick description of what you've done.

cc @alicoding

**Comment by edrushka** [comment]
Priority locales for this experiment:
Germany-DE 
France-FR 
Latin America-ES 
Brazil-PTBR 
Italy-IT 
Russia-RU 
India-IN 
Indonesia-ID

**Comment by edrushka** [comment]
Will you pls let me know when this is up on Pontoon, @alicoding - I need to report to other teams. Thanks!

**Comment by lovegushwa** [comment]
note to self: https://donate.mofostaging.net/fr/directory-tiles/  ... change "fr" to other languages to access tile copy.

**Comment by edrushka** [comment]
Germany-DE: https://donate.mofostaging.net/de/directory-tiles/ 
France-FR: https://donate.mofostaging.net/fr/directory-tiles/ 
Latin America-ES: https://donate.mofostaging.net/es/directory-tiles/ 
Italy-IT: https://donate.mofostaging.net/it/directory-tiles/ 


Russia-RU: not done yet
India-IN: not done yet
Indonesia-ID: not done yet
Brazil-PTBR: not done yet

**Comment by edrushka** [comment]
I'm just going to raise a glass here :cocktail: to the fact that this worked. This is actually really cool!

**Comment by edrushka** [comment]
cc-ing @sabrinang for reference
