### ISSUE TITLE
Localize "this really helps us"

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#815]
We need this line of text localized for the snippet and the funnel tests:

This really helps us!

@lovegushwa will throw up a design to provide context. @alicoding can you please put on Pontoon?

cc @ScottDowne

**Comment by edrushka** [comment]
Additional priority locales:
Germany-DE 
Italy-IT 
Russia-RU 
India-IN 
Indonesia-ID 
--

We'll probably want these eventually:
Spanish
Polish
Hungarian
Japanese
Dutch
Greek
Czech
zh-TW
zh-CN

**Comment by lovegushwa** [comment]
@ScottDowne @edrushka we might also need:
"Wir mochten sie auf dem laufenden halten" ... I don't remember what that says in German but I think we pulled it from a string so perhaps is already in the translation pipeline?

<img width="847" alt="screen shot 2015-11-17 at 2 58 59 pm" src="https://cloud.githubusercontent.com/assets/12228435/11227646/04bbc88a-8d3c-11e5-8770-02b95cfb6ada.png">

**Comment by ScottDowne** [comment]
@edrushka yeah, been seeing a lot of talk today about other locales.

Today I have heard "it, ru, pl, in, id"

So we should file off some tickets to investigate any issue we may have with new locales we want to start pushing.

@lovegushwa "Wir mochten sie auf dem laufenden halten" is not in the repo, so it's not translated afaik.

**Comment by lovegushwa** [comment]
@ScottDowne @alicoding @edrushka 
These are the languages we are creating payment funnels for according to Ali:
 es, pt-br, en-us, it, id, de, fr

@edrushka did we agree today not to worry about languages were not already localizing the funnel for?

**Comment by edrushka** [comment]
You're right, sorry.

So all we need then is
it
id 
de

**Comment by ScottDowne** [comment]
fr: Cela nous aide vraiment !
es: ¡Nos ayuda mucho!
pt-BR: Isso realmente nos ajuda!
de: Das hilft uns wirklich weiter!
it: La tua donazione ci è davvero di grande aiuto!

We don't have id.

**Comment by lovegushwa** [comment]
@ScottDowne @edrushka regarding the other string "Wir mochten sie auf dem laufenden halten"
it was something like "We want to include you in our work." on the email signup page. We need to finalize copy for this in EN-US and then translate.

<img width="647" alt="screen shot 2015-11-17 at 3 14 52 pm" src="https://cloud.githubusercontent.com/assets/12228435/11227926/00011dd4-8d3e-11e5-8294-d1fa56e0bd0a.png">

**Comment by edrushka** [comment]
I'll create another ticket for that. Otherwise things are going to get even more chaotic! ;)

**Comment by ScottDowne** [comment]
We should use this for just the string in id? Looks like we have the rest.

**Comment by ScottDowne** [comment]
Actually, we could also just get it done in a bunch of languages just in case.

**Comment by edrushka** [comment]
There are some variants of this string we'll need when we run this test #352

“Get important news and updates”
“Please allow us to keep in touch”
“We want you to stay informed”
“This helps us reach you”
“This means we can reach you”
“Don’t miss updates”

Might want to localize these variants now, so we're not in a rush for them later if the testing in EN US proves conclusive.

**Comment by alicoding** [comment]
@edrushka do we need another ticket for adding all those?

**Comment by edrushka** [comment]
You tell me! Whatever is easiest for you.

**Comment by alicoding** [comment]
let's have another ticket to track the work for adding those then.

**Comment by alicoding** [comment]
Also, what else is left to do in this ticket?

**Comment by edrushka** [comment]
ok. We'll leave this one open until we get Id.

**Comment by alicoding** [comment]
@edrushka I think it is a good idea to send an email to the list again about our change to the form that way we can get their attention.

**Comment by edrushka** [comment]
ok - can you do that? I'm confused about when we email them, when Flod emails them....

**Comment by alicoding** [comment]
@edrushka sure can do. Actually, the emailing part should always be us doing it in term of project prospective.

**Comment by edrushka** [comment]
Great! I'm just aware that we're going to be adding a lot of strings in the next two weeks or so.

**Comment by alicoding** [comment]
I feel like `id` is not very super active on Pontoon or we need to reach out to the community somewhere to get their attention to let them know that we are launching and we need their help here. Or, maybe it is time for us to start thinking about getting Kontextor to help with this language if we are in a tight deadline here.

**Comment by valianttry** [comment]
Just noting that there are two "nudges" discussed in this bug, not just one:

**"Monthly nudge"** = "this really helps us" and a few more nudge variants we want to test to see if we increase the proportion of donors that choose monthly with the goal of increasing net revenue;

**"Optin nudge"** = "get important news and updates" and a few more variants to see if we can improve our optin percentage (currently ~18%)

**NOTE:** We only need to TEST each nudge variant in English, testing in other languages will get crazy complicated. We should test in English first, then whatever variant wins, we apply the test winner to other locales.

**Comment by ScottDowne** [comment]
@valianttry omg good call.

This was my fault, I requested the images in another bug in our primary languages, looking too far ahead and not seeing what's right in front.

I say let's leave this open, but not P1 it.

**Comment by alicoding** [comment]
This ticket is actually done :)

https://github.com/mozilla/donate.mozilla.org/search?utf8=%E2%9C%93&q=%3Dthis_really_help_us
