### ISSUE TITLE
Opening up IT as a locale

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#816]
In order to do this, we have some UI issues.

![snippet17](https://cloud.githubusercontent.com/assets/197334/11225221/05367e94-8d47-11e5-867d-1a8802fe1ff1.png)

The currency dropdown falls to the next line, and the text is pretty long.
![snippet18](https://cloud.githubusercontent.com/assets/197334/11225252/2c4657f2-8d47-11e5-8f89-3bb57f91a1aa.png)

The secure bit is too close to the text.
![snippet19](https://cloud.githubusercontent.com/assets/197334/11225265/39e54f9e-8d47-11e5-92d4-4dec4b145eaf.png)

![snippet20](https://cloud.githubusercontent.com/assets/197334/11225292/6b324214-8d47-11e5-93de-2405556b76b0.png)

@lovegushwa thoughts?

**Comment by ScottDowne** [comment]
Looking at it now, it might be confusing, because I cropped it... The issue in question is not the cut off edges.

**Comment by lovegushwa** [comment]
@ScottDowne @alicoding @edrushka I think these are not UI issues, they are translation issues.
All the translated copy that ends up running to long. Kontextor?

**Comment by lovegushwa** [comment]
@ScottDowne problems 2 and 3 could be fixed with a forced line break.

**Comment by lovegushwa** [comment]
problem 4 could simple be "registro" (register) or possibly "presentare regitration" (submit registration.)

**Comment by lovegushwa** [comment]
@ScottDowne @alicoding @edrushka we need some way verifying good translations before design bugs get issued. Let's discuss how to do this at the Thursday meeting if possible.

problem 1 could be "Dona ora" (donate now)
<img width="1195" alt="screen shot 2015-11-17 at 2 38 17 pm" src="https://cloud.githubusercontent.com/assets/12228435/11227110/faddbaec-8d38-11e5-9569-587af3d70eeb.png">

**Comment by edrushka** [comment]
Agree that these are localizing issues, and not design. We can help by providing max char counts, though.

**Comment by ScottDowne** [comment]
@lovegushwa That's fine, I'm not super concerned with how to fix it yet. UI was just a guess, I was more concerned with having it filed.

**Comment by flodolo** [comment]
I strongly disagree, these are design issues ;-)

Each language should be able to pick the best translation possible, and there seems to be plenty of space to fit longer translations. Having said that...

## Donation form
Fixed in
https://github.com/mozilla/donate.mozilla.org/commit/8d4bd402e4b9b72f16d52422ece4377e890133ea
https://donate.mofostaging.net/it/

## Snippet
Per IRC discussion, sharing the same string for a title and a button label is not a good idea, something to keep in mind for the future. If `Fai subito una donazione` doesn't fit in the button, `Dona subito` is an acceptable alternative.

## Registration form
I've just fixed it in Pontoon (`Registrati subito`), should export within 15 minutes.

**Comment by edrushka** [comment]
Thank you @flodolo :it:

**Comment by flodolo** [comment]
String landed https://github.com/mozilla/donate.mozilla.org/commit/09f06700bd96061717aef88f317f204949373733

Not sure where to test the registration form, and how frequently the staging server is updated.

**Comment by ScottDowne** [comment]
This strikes me as the last snag on IT.

![italian](https://cloud.githubusercontent.com/assets/197334/11982483/91fdbfe2-a979-11e5-9ccd-88ac504a0767.png)

Not sure at all which string we want in this button. It's never been explicitly localized for that button, but I still think we have button sizing issues here. In general we have very little space for this. Amount buttons are an issue too, but that's another problem.

I'm in no rush to solve this.

**Comment by flodolo** [comment]
`Dona subito` is a good alternative here too if we don't have space to fit `Fai una donazione`

**Comment by ScottDowne** [comment]
Putting this into bluesky (which is where next year's plan is going to be built from)
