### ISSUE TITLE
Should we be loading stripe.js and stripe checkout?

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#818]
My understanding is that we're using stripe.js for the sequential donation form and stripe checkout for the one page donation form. Would it be possible to only load one or the other based on what page is being rendered?

**Comment by jbuck** [comment]
Scott agrees that we should fix this, but isn't sure how best to do this selective loading. My gut instinct is that we could do it based on the page URL

**Comment by ScottDowne** [comment]
I differ from jbuck here, I think we should use something that loads the script inside the components that use stripe, and not in the index based on the url. I just think checking the url is going to be hard to get right for all cases, and hard to maintain.

**Comment by jbuck** [comment]
It'd be more beneficial to load it based on the URL because then we can put the JS at the bottom of the page so it doesn't block page loading.

**Comment by ScottDowne** [comment]
Doing it in the component would also not block page loading, it would be async.

**Comment by jbuck** [comment]
Given that we're removing the sequential form, we can simply remove stripe.js

**Comment by cadecairos** [comment]
Is this blocked until we switch over to the one-page flow?

**Comment by jbuck** [comment]
Yes, I'd wait for that issue to land... @ScottDowne which issue is that?

**Comment by jbuck** [comment]
It's https://github.com/mozilla/donate.mozilla.org/pull/963

**Comment by jbuck** [comment]
The dependent PR landed, so go forth and strip js

**Comment by jbuck** [comment]
@cadecairos delete this line https://github.com/mozilla/donate.mozilla.org/blob/db573aad6eead39537c029653b23cde663645f51/pages/index.jsx#L67 and I think we should consider making the script below it async too, since we only need it once we click the button

**Comment by jbuck** [comment]
I backed out this patch because we were seeing "StripeCheckout is not defined" errors

**Comment by cadecairos** [comment]
> I backed out this patch because we were seeing "StripeCheckout is not defined" errors

@jbuck do you have any idea how to get this error?

**Comment by jbuck** [comment]
@cadecairos I saw it on production myself

**Comment by ScottDowne** [comment]
@cadecairos I just ran it, and saw it too.

**Comment by jbuck** [comment]
Fixed in #1145
