### ISSUE TITLE
Complete Sec Review of New Donation Pages

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#82]
Filing this so the ticket is noted.

But I don't think we should work through this until the bulk of the work is done.

**Comment by adamlofting** [comment]
Let's pick a date when we think the core code base is ready for our first pass review. Then book in some time to make this happen.

**Comment by jbuck** [comment]
https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines

**Comment by valianttry** [comment]
@ScottDowne @jbuck can you pick a date to aim for first pass review (or if that's already passed, can you note it here)? This is something we can't forget :ribbon:

**Comment by jbuck** [comment]
@valianttry We'll do it tomorrow! (Sept 29)

**Comment by jbuck** [comment]
**Notes**:
- We're not using any cookies for data storage
- All of our pages are served over HTTPS, have HTTP-to-HTTPS redirects, and we use HSTS to force HTTPS
- We have no authentication on donate.m.o
- We have no sessions on donate.m.o that we control (GA and Optimizely)
- We have no access control on donate.m.o in the sense that there are only anonymous users
- We implement X-Frame-Options on production already
- We're using HTTPS for everything
- We're using CSP
- We have no admin login pages
- We don't allow uploads

**Issues to file**:
- Add ourselves to the HSTS preload list
- We need to add user data validation for query parameters, headers, and payload body
  - Applied to all user controlled data 
    - Form data
    - URL parameters
    - Hidden fields
    - Cookie data
    - HTTP Headers
    - Essentially anything in the HTTP request
  - Define the type of data (String, Number, etc)
  - Define the minimum & maximum length of the data
  - Must be done client-side and server-side
- Can anything be done with paypal info/email passed into query string?
- Output validation on the server-side
- CSRF protection needs to be implemented to protect against evilsite.com initiating a paypal/stripe donation or email signup
- Ensure any third-party scripts that are used are hosted locally and not dynamically referenced from a third party site
- Implement [subresource integrity](https://srihash.org/) where possible
- Ensure the "tweet this" or "like this" button does not generate a request to the 3rd party site simply by loading the Mozilla webpage the button is on (e.g. no requests to third party site without user's intent via clicking on the button) 
- Ensure Content Security Policy is up to date and has the minimum amount of whitelisted sites
- Ensure that server logs are being stored somewhere we control
- Ensure we only allow certain content types to be uploaded
- Ensure we have a maximum payload size we allow
- Verify that error handling doesn't leak sensitive information to user

**Comment by valianttry** [comment]
:cla

**Comment by valianttry** [comment]
:clap:
