### ISSUE TITLE
Could we combine some JS files?

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#825]
Would it be possible to combine some JS files?

* analytics.js
* ga.js
* main.js

Maybe roll the two into main.js?

**Comment by adamlofting** [comment]
Just double checking, do you mean [`analytics.js`](https://github.com/mozilla/donate.mozilla.org/blob/master/public/js/ga.js#L4) as served from google-analytics.com? We also have a file [`analytics.js`](https://github.com/mozilla/donate.mozilla.org/blob/master/public/js/analytics.js) which is compiled into `main.js`.

AFAIK, the reason `ga.js` is a seperate file is to avoide the CSP issue of inline code, but it would remove one extra request if we could put [this code](https://github.com/mozilla/donate.mozilla.org/blob/master/public/js/ga.js#L1-L7) directly [in the head](https://github.com/mozilla/donate.mozilla.org/blob/master/pages/index.jsx#L33)?

**Comment by jbuck** [comment]
Oops, you're totally right about analytics.js. Sorry!

I'll see what we can do about ga.js then

**Comment by jbuck** [comment]
We need to do some more research here, but we should consider putting ga.js code back into the head, since Optimizely requires that same CSP rules to be relaxed.
