### ISSUE TITLE
Test l10n code is working correctly

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#83]
See #37

**Comment by alicoding** [comment]
Been testing it everyday and everytime when we have new patch landed, but moving this to next heartbeat. I'm still working on Pontoon and will be working on currency switching stuff.

**Comment by adamlofting** [comment]
Let's decide if there is any kind of automated testing we can add here?

If not, let's clsoe this ticket.

**Comment by alicoding** [comment]
Nothing really can be automate here, but I might file few tickets for optimization mostly.
