### ISSUE TITLE
Localize variants of "this really helps us"

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#835]
These are the variants:
Get important news and updates
Please allow us to keep in touch
We want you to stay informed
This helps us reach you
This means we can reach you
Don’t miss updates

Need these in:
es, pt-br, it, id, de, fr

**Comment by alicoding** [comment]
@edrushka I will send an email to the list once this gets merged.

**Comment by lovegushwa** [comment]
@edrushka @alicoding @ScottDowne Hey all. Please take a look and confirm this is what we need to build, I don't want to make all these PNGs twice! :)

![screen shot 2015-11-19 at 2 44 39 pm](https://cloud.githubusercontent.com/assets/12228435/11286823/1b6df314-8ecc-11e5-9996-f6d646254fdd.png)

For context:
![screen shot 2015-11-19 at 2 47 32 pm](https://cloud.githubusercontent.com/assets/12228435/11286883/82d9cb40-8ecc-11e5-9720-06afb4d2b068.png)
SNIPPET

![screen shot 2015-11-19 at 2 46 56 pm](https://cloud.githubusercontent.com/assets/12228435/11286888/89998056-8ecc-11e5-8dde-cfe1e7cbe0e4.png)
FUNNEL page 1

![screen shot 2015-11-19 at 2 47 03 pm](https://cloud.githubusercontent.com/assets/12228435/11286903/b053e11e-8ecc-11e5-96a9-cb11cafc5ee7.png)
FUNNEL page 3

**Comment by edrushka** [comment]
flagging @valianttry to take a look in case any of these can be cut. That's a lot of variants in a lot of languages!

**Comment by lovegushwa** [comment]
@edrushka @valianttry 

@ScottDowne suggested testing the email signup ask in EN - US  first and then localizing the one that performs best for all other languages. ... We could also just localize one ... like "Don't miss updates" until the test runs.

**Comment by valianttry** [comment]
Yes, we will be doing all our testing in EN. It's just easier that way. No localizing these until our test is complete, and we'll use Kontextor for that.

**Comment by edrushka** [comment]
ok. that's fine. In this morning's meeting were got on the "let's translate all the things in one go!" train (which is the L10N community's preference) but if we're using Kontextor, then localizing these only when we need them works for me.

**Comment by edrushka** [comment]
I think we can close this again. Will re-open if/when we localize these strings.
