### ISSUE TITLE
Load testing of new pages

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#84]

**Comment by adamlofting** [comment]
Marking as blocked.

There's no point load testing until our infra and code is where we want it to be.

**Comment by jbuck** [comment]
Heroku recommended looking at Blitz or Blaze meter for load testing (in addition to our current favourite Load Impact). They also recommended trying various sizes (1X, 2X and PX) of dynos in varying numbers so we can get an idea of how much load we can handle. A specific use case they recommended is using PX dynos with the node cluster module enabled so we can run multiple copies of the node app on a single dyno with dedicated hardware.

**Comment by adamlofting** [comment]
:+1:
