### ISSUE TITLE
investigate why npm-run-all fail on version 1.3.0

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#846]
```
ERROR: build:l10njson: None-Zero Exit(7);
```

**Comment by jbuck** [comment]
This was fixed in #847

**Comment by alicoding** [comment]
Sadly this is still a problem :(

**Comment by ScottDowne** [comment]
Leaving this open until it's fixed upstream.

**Comment by jbuck** [comment]
https://github.com/mysticatea/npm-run-all/issues/14 is the upstream issue

**Comment by lewiscowper** [comment]
For first aid, the breaking change has been reverted and published as version `1.3.1`.

**Comment by jbuck** [comment]
@lewiscowper great, thank you!

**Comment by jbuck** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/pull/863
