### ISSUE TITLE
Make sure users know they are using Stripe

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#85]
This is a follow up task from Legal and Privacy review:

- [ ] Make sure users know they are using Stripe (same logic applies to any 3rd party payment provider)
- [ ] Make sure there is a link to the Stripe Privacy Policy before a user enters any data that would be sent to stripe

How we address this impacts how we integrate with Stripe. 

* Using Stripe Checkout and Stripe JavaScript forms will include this automatically
* But if we're using our own form and talking to Stripe via the API we need to make sure this is clear to the user

--

@ScottDowne @jbuck @alicoding @valianttry << please add any thoughts to this ticket :+1:

**Comment by ScottDowne** [comment]
I'm thinking just link to stripe's policy in the footer next to our mozilla privacy policy.

**Comment by ScottDowne** [comment]
This is it in the footer: https://github.com/mozilla/donate.mozilla.org/pull/135
![infooter](https://cloud.githubusercontent.com/assets/197334/8995569/3f5d07fe-36e0-11e5-8909-023c5c0105b4.png)

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/136
I like this one more.
![stripe2](https://cloud.githubusercontent.com/assets/197334/8995865/35e79804-36e2-11e5-839c-380087ccd083.png)

**Comment by ScottDowne** [comment]
Obviously, the copy is not final.

But, thoughts?

**Comment by adamlofting** [comment]
I like the language of the second one, because it explains who Stripe are and what we use them for. 

Could we put this text below the credit card form, so we only show it to people who are choosing that payment option. That will reduce the amount of distracting links for the rest of the donors.

<img width="541" alt="screenshot 2015-07-31 09 49 33" src="https://cloud.githubusercontent.com/assets/1901816/9003870/a7b9ad28-3769-11e5-941f-93aba087ca36.png">


Suggested language:

> We use a company called Stripe to securely process your credit card transaction. Stripe's privacy policy and terms of service can be found ***here***. 

This is also an approach we can use if we add in further payment providers for other locales in the future.

**Comment by ScottDowne** [comment]
I want to add it in one link with the word "here" but I did actually find two links and wasn't sure if I needed both or not. They are not the same links.

I think it's fine in the location you are proposing, although it is going to be more prominent, for less people.

I could keep it where I suggested, but only display it after cc is selected. For whatever reason I thought it had to be displayed all the time.

Also, I think this should probably get copy, design, and some sort of legal review? Or are the two of us enough?

**Comment by adamlofting** [comment]
> I could keep it where I suggested, but only display it after cc is selected. For whatever reason I thought it had to be displayed all the time.

Let's do that.

> Also, I think this should probably get copy, design, and some sort of legal review? Or are the two of us enough?

Yep. I'll get these done, but it'll be easiest to explain in context. 

Copy + Design are open to  A/B testing.
Legal know about this, but I'll check final wording before we go live.

**Comment by adamlofting** [comment]
Interestingly, Stripe's website has a single link titled `Privacy & Terms`, but the docs has links to two separate links `Terms of Service` and `Privacy Policy`. 

Let's start with a single link as Stripe do on their main site, but I'll check that with legal.

**Comment by ScottDowne** [comment]
I ran this by Ricardo.

He said showing it in the grey area, and having it all the time made the most sense.

Having it appear in the grey area after they click credit card is going to draw their attention with the movement.

Having it in the form area is also far to prominent.

I'm thinking something like this, all the time:

![stripe3](https://cloud.githubusercontent.com/assets/197334/9011717/0afae132-377d-11e5-936d-181ab8024465.png)

**Comment by adamlofting** [comment]
I'm really keen not to show this to all users all the time.

75% of transactions use PayPal and don't need to see this, and every extra link we add can have a negative impact on conversion rate. Basically, all extra links are possible distractions.

If we don't want this footer area to change, I'd go back to the plan above where it appears in the white space.

**Comment by ScottDowne** [comment]
I prefer having it appear in the grey area, even if it does appear after credit card is clicked, and is a distraction for 25%, than have it in the white area.

We can try getting the transition in a nice place where it's not as distracting?

Is this worth AB testing?

**Comment by adamlofting** [comment]
> Is this worth AB testing?

Yep, just file it with the `A/B Test Proposal` label and we can keep track of it.

But for now, let's get a default version in the grey area, shown after the credit card is clicked.

**Comment by ScottDowne** [comment]
merged: https://github.com/mozilla/donate.mozilla.org/pull/148/files

and: https://github.com/mozilla/donate.mozilla.org/pull/136
