### ISSUE TITLE
Donation URLs for localized FF&Y Lead Story

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#852]
@bniolet1 needs links for: ES, PL, FR, DE, RU, ID, PT-BR

FF&Y December Lead Story links:

EN-US:
https://donate.mozilla.org/en-US/?&currency=USD&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

FR:
https://donate.mozilla.org/fr/?&currency=eur&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

DE:
https://donate.mozilla.org/de/?&currency=eur&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

PTBR:
https://donate.mozilla.org/pt-BR/?&currency=BRL&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

ES-ES:
https://donate.mozilla.org/es/?&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

**Not yet fully translated:**
PL:
https://donate.mozilla.org/?&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

RU:
https://donate.mozilla.org/?&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=newsletter-moco&utm_medium=email&utm_content=FFY_lead

**Comment by jbuck** [comment]
@valianttry r+ !

**Comment by bniolet1** [comment]
Perfect! Thanks!
