### ISSUE TITLE
Cross-reference localized channels with localized donation experience

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#868]
@jbuck @alicoding @edrushka 

There may be remaining translations that we need to ask L10N / Kontextor for ASAP and this bug will help us get a handle on what our needs are exactly.
I am having a lot of difficulty keeping track of what languages are available in which channels, and which languages we have translations+currencies for. These data points are scattered across Pontoon, Github, Stripe, and spreadsheets. I'm trying to gather the needed information here:
https://docs.google.com/spreadsheets/d/17mIHMKHoEm_Icdl1hEBjUZ4aL8nAhIdEgSY5yqdmsAk/edit#gid=210982514

@jbuck can you turn cells green in Row 20 for those locales we have localized and functional Thank You email reply? (I could not find this in Pontoon)
@alicoding can you turn cells green in Row 19 for all locales where we have localized Thank You page? (I could not find this in Pontoon)
@bniolet1 can you help make sure I have correct target locales for moco channels?

Thanks everyone! This is a P1 for Thursday --

**Comment by alicoding** [comment]
Right now we don't have translation for `ru`, `pl`, and `in`? I don't know what we are trying to focus for `in` here? There are many languages spoken in India, but the most popular one would be Hindi, Bengali, Gujarati, Panjabi and Telugu. We need to decide where one is the most popular one based on our GA and focus on one or two here.

For `id` there are few strings left to be translated on thank-you page.

**Comment by bniolet1** [comment]
I've got cells updated for moco social and email. I'll get Snippet and Tile teams to look at it when the sun comes up in their time zones.

**Comment by bniolet1** [comment]
In product checked in. MoCo languages are all correctly represented on the sheet.

**Comment by jbuck** [comment]
I've got cells updated for Auto-Reply Email Receipt Localized

**Comment by valianttry** [comment]
Great, this is helpful. Ali ru and in are P2. I know IN is complex, but we
get requests from IN donors. If we can't offer either that's fine. PL came
up because as you can see a few MoCo channels serve PL. I am trying to see
where we can send donation ask right now vs later vs not  at all.

On Thursday, November 19, 2015, Jon Buckley <notifications@github.com>
wrote:

> I've got cells updated for Auto-Reply Email Receipt Localized
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/donate.mozilla.org/issues/868#issuecomment-158103520>
> .
>


-- 
Sent from a phone

**Comment by edrushka** [comment]
@alicoding any updates on this? I feel like work might be happening in other tickets? If so, can you cross-reference them here so I can see the progress? This one's a P1 so I want to make sure we're moving on it. Thanks!

**Comment by alicoding** [comment]
I'm not sure what I have to do in this ticket ?

**Comment by edrushka** [comment]
Oops, my mistake. I thought there was more to do regarding IN. I'm going to close this now, since that spreadsheet is all filled in.
