### ISSUE TITLE
Update f.m.o with 2015 design style

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#873]
MVP - change the banner
@alicoding can I assign this to you? If you provide specs for the banner, I'll put a designer on it. Thanks!

cc @valianttry

**Comment by edrushka** [comment]
@natalieworth might you have time to take this on next week? We'll need the banner at the top of fundraising.mozilla.org to be updated with this year's visual design. Might add a rolling dollar amount, too (see #898). @alicoding will provide banner specs.

**Comment by natalieworth** [comment]
@edrushka Yes! Next week sounds good for updating this. I'll have time.
cc @alicoding

**Comment by edrushka** [comment]
![screenshot 2015-11-23 14 59 45](https://cloud.githubusercontent.com/assets/4515662/11352733/ff3c6d40-91f2-11e5-813b-efe5919151f5.png)

^ Here's the current banner on fundraising.mozilla.org
According to ali, it's made up of 3 elements: yellow background, the crowd image and the text overlay. We need to: 
- update the background colour and image to align with this year's design
- keep the donate button
- add the totalizer (this is a dev thing #898, but need to take it into account for design). Here's the totalizer in action: http://web.archive.org/web/20141216005946/http://fundraising.mozilla.org/ -- note that we *don't* want the line of copy underneath publishing our campaign goal.

**Comment by natalieworth** [comment]
@edrushka @alicoding Is there copy for this or are we using the same from last year?

**Comment by edrushka** [comment]
@natalieworth same as last year should work (except for removing that line of copy under the totalizer talking about our final $ goal. we're not making that so public this year).

**Comment by natalieworth** [comment]
Hi @edrushka @alicoding Just had a couple questions for this:
* Are we only implementing the 'totalizer' design this year or should I also design a version without the 'totalizer?' 
* How should I build/ separate the layers for development?
* Is it required again to have a filled button, or can I do an outlined button (similar to EOY call-outs)?
* Is this priority over the homepage snippet? This shouldn't take long if you're needing it asap. 
Thanks! :) 
I've attached just a really basic layout for the banner here to give you a sense of the layout/ size:
![snippet_examples-04](https://cloud.githubusercontent.com/assets/14876567/11431396/e9c12568-944b-11e5-9eb4-5e648d7c24b1.png)

**Comment by edrushka** [comment]
- Please design a version with *and* without the totalizer. We'll use the version without in January (and beyond) once we stop receiving money.
- I don't know how you build separate layers for development. Maybe @sabrinang can advise as she built this last year.
- Filled button isn't a requirement for design. Maybe for dev but I can't see why that would be.
- If you can finish this up fairly quickly, let's just get this ticket out of the way. F.M.O becomes increasingly important as the campaign moves on. If there's slowness or blockers due to Thanksgiving, you can pause this and pick it up again early next week, though.

Love the basic sketch above. This is exactly what I had in mind. @valianttry can you confirm that the copy should say End of Year Campaign and not something like "Mozilla Fundraising"?

**Comment by valianttry** [comment]
I love this @natalieworth ! I honestly only have minor tweaks. I really like the "donate now" outline button as it is here. Here is what I'm thinking (pardon the awful font, but you hopefully can get the gist). I think we can just have the non-campaigning version exactly the same, but without the "end of year campaign" and totalizer:

![e9c12568-944b-11e5-9eb4-5e648d7c24b1_png__png_image__2004 x 838_pixels__-_scaled__59__](https://cloud.githubusercontent.com/assets/9830371/11431731/e3f26ece-9452-11e5-8596-cfc5c6e92cba.png)

**Comment by jbuck** [comment]
@valianttry You're right, I think FMO could definitely use a little more Comic Sans:

![e9c12568-944b-11e5-9eb4-5e648d7c24b1](https://cloud.githubusercontent.com/assets/578466/11431785/3af2fac6-946d-11e5-8364-8b291ae0a8dd.png)

**Comment by valianttry** [comment]
AHAHAHAHAHAHHA @jbuck don't freak our the designers! We need them!

**Comment by edrushka** [comment]
oh crud @natalieworth - the link I gave you doesn't actually seem to show the totalizer in action (which is weird, I could have sworn it did???). @valianttry do you have a screen cap of what it actually looks like when it's animated?

**Comment by valianttry** [comment]
Oh dear. ... @mmmavis or @sabrinang would have a screengrab for that I hope... I don't really have anything showing the animation. I'm open to new ideas for showing the "in motion" state of the numbers, but of course I assume it's easier to re-use our "flipping numbers" from last year.

**Comment by edrushka** [comment]
If you explore different dates in the waybackmachine it will show the animation.

**Comment by sabrinang** [comment]
this gif is a bit slow but it shows the animation: http://g.recordit.co/KJHFdk8Cab.gif

**Comment by natalieworth** [comment]
Hey @alicoding @edrushka @cassiemc , I have 3 different iterations for these. *Note that there are the V1 and V2 of each design (with and without the totalizer) in each redpen: https://redpen.io/p/jn19dd1a23e3b637f5 Thanks!

**Comment by edrushka** [comment]
Let's go with Version 1 on the redpen (big heart with yellow background)

**Comment by natalieworth** [comment]
Hi @alicoding @edrushka, I made updates to the preferred/ yellow version of the banners: 
1. Banner: https://redpen.io/wr6493079565193a87
2. Banner with totalizer: https://redpen.io/pt50386b4ff9d4cc6d

cc @cassiemc 

Thanks!

**Comment by natalieworth** [comment]
Small updates for these are on redpen:
1. Banner: https://redpen.io/fu9f15e575a0661208
2. Totalizer Banner: https://redpen.io/tv684cf9686273a044
For the 2nd, I included some different options for the type that reads 'end of year campaign.' Thanks!
cc @cassiemc @valianttry @edrushka @alicoding

**Comment by cassiemc** [comment]
Look great to me @natalieworth!

**Comment by edrushka** [comment]
@valianttry can you sign off so Natalie can export the assets and we can make this live?

**Comment by valianttry** [comment]
r+ i :heart: it let's get it live!

**Comment by natalieworth** [comment]
@alicoding Designs and the .ai file can be found here: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0Nkhub2VxLXlIc1k/view
I've separated all the layers, but let me know if you need help with exporting anything together for dev. Thanks!
cc @edrushka @cassiemc @valianttry

**Comment by alicoding** [comment]
@natalieworth Can you actually give me the image separately for the heart on the left and right + the fox? I will manually do the background, text and the button here.

**Comment by alicoding** [comment]
Also if you can give me `svg` if that's possible. Thanks @natalieworth :)

**Comment by natalieworth** [comment]
For sure @alicoding , for the svg's, did you want all the images exported separately?

**Comment by alicoding** [comment]
@natalieworth If possible just 3 SVGs 1. Right heart, 2. Left heart (behind the fox), 3. The fox.

**Comment by natalieworth** [comment]
Okay, I can do that! Thanks!

**Comment by natalieworth** [comment]
Hi @alicoding: exported the svg's. I made them at the same resolution/ dimensions as the banner. Let me know if you need anything different sizes: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0Ni1yVGlzc0FicDg Thanks!

**Comment by natalieworth** [comment]
Hey @alicoding , svgs of the heart and fox for the totalizer are in the drive: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0Ni1yVGlzc0FicDg Just ping me if you need anything else :)

**Comment by alicoding** [comment]
landed https://fundraising.mozilla.org \o/

**Comment by natalieworth** [comment]
:+1: Thanks @alicoding!

**Comment by mmmavis** [comment]
great job team! really love the banner :heart: it's CUTEEE
