### ISSUE TITLE
Donor reports a non-descript error when trying to donate

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#874]
I searched for him in Stripe, and nothing came up. 

![error_at_your_web_site_for_donation_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11283627/7cf85b4a-8eba-11e5-9688-074d56604fdd.png)

**Comment by jbuck** [comment]
I haven't been able to find him either :/

**Comment by ScottDowne** [comment]
I cannot find it either, I found one that was close, but it ended up being this morning, which means after this email.

That error comes when we cannot make a connection to stripe, so maybe there was something blocking stripe from the network? Just a guess.

**Comment by jbuck** [comment]
Scott and I looked at the possible Stripe errors and we found that there are some communication errors we're not handling yet. Scott is going to add error messages for those.

**Comment by ScottDowne** [comment]
It's most likely a "api_connection_error 	Failure to connect to Stripe's API."

I'm thinking we can display a message for that, but I don't want to use that message...

We can also do something like: "Something seems to have gone wrong. Please try again later. [api_connection_error]"

This way if stripe sends us an unknown error and the user screen shots it, we can have a bit more info to debug.

**Comment by jbuck** [comment]
@ScottDowne Maybe ask the user if they have any blocking scripts running or something?

**Comment by ScottDowne** [comment]
@jbuck or under a public network?

**Comment by ScottDowne** [comment]
I'm thinking we need a specific message for connection error.

Something like "Sorry there was a connection error. Please try again later."

Thoughts?

**Comment by valianttry** [comment]
"Something seems to have gone wrong. Please try again later. [api_connection_error]"
Would be my preference, since "connection error" could signal they need to plug their ethernet cord in or something.

**Comment by edrushka** [comment]
Just noting that when I had my "rotating cog forever" problem, it was also using Mastercard.
