### ISSUE TITLE
Donation URLs needed for localized Directory Tiles

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#879]
FR:
https://donate.mozilla.org/fr/?currency=eur&amount=5&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=directory-tiles&utm_medium=tiles&utm_content=dapper_v1_fr

DE:
https://donate.mozilla.org/de/?currency=eur&amount=5&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=directory-tiles&utm_medium=tiles&utm_content=dapper_v1_de

PTBR:
https://donate.mozilla.org/pt-BR/?currency=BRL&amount=25&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=directory-tiles&utm_medium=tiles&utm_content=dapper_v1_ptbr

ES-ES:
https://donate.mozilla.org/es/?currency=eur&amount=5&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=directory-tiles&utm_medium=tiles&utm_content=dapper_v1_es

IT:
https://donate.mozilla.org/it/?currency=eur&amount=5&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=directory-tiles&utm_medium=tiles&utm_content=dapper_v1_it

**Comment by jbuck** [comment]
@valianttry At the beginning of the URL, you just want `?currency`, not `?&currency`
