### ISSUE TITLE
Design more directory tile variants

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#880]
We've delivered two (beautiful!) tiles: #559

We need to deliver 2-4 more. Perhaps we can do two more variations of the first set with @kristinashu's flower fox and chubby dino (maybe against a different background colour/heart)?

If that's too heavy a design lift, I'm open to other suggestions. I can't 100% guarantee these will be used (these additional designs are to counter fatigue) so let's not invest a *huge* amount of design time here.

@lovegushwa do you think you can create a first draft early next week, with the aim to ship a final design with sign offs from @valianttry by EOD Wednesday Nov 25?

@valianttry are you ok with flower fox and chubby dino, if Jordan wants to pursue that direction? Do you want different copy in these tiles or can we just reuse the copy from the first set?

**Comment by lovegushwa** [comment]
@edrushka sounds like a plan, using the same copy helps us ship by Wednesday without localizing.

**Comment by lovegushwa** [comment]
@natalieworth I got a bit of a start here this afternoon, so glad you can jump in on these!
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvLUdxa29yTGlwd0k/view?usp=sharing

- Jump in and work with @edrushka to finish up some more options. 

- Once the new directions are approved you can localize with @alicoding by giving him tile images with no copy like this:https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvRG5jRmdSdmdMUGc&usp=sharing

- use this file to build new localizes tiles:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvdW9yNkNWN3RZcUE/view?usp=sharing

- create a new folder in EXPORT for the new tiles and follow the convention established in folder "v1_v2"
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvZGJ4d1RoNVNnZkk&usp=sharing


<img width="649" alt="screen shot 2015-11-25 at 6 20 59 pm" src="https://cloud.githubusercontent.com/assets/12228435/11413718/54e2c9a6-93a1-11e5-9028-f90335cb3584.png">

**Comment by natalieworth** [comment]
Just assigned this to myself since @lovegushwa's on PTO for a bit. Easier for me to keep track of everything! I can assign back later if that works :)

**Comment by natalieworth** [comment]
Hey @edrushka, just posted the tile (static and rollover) variants based off of the file Jordan provided: https://redpen.io/p/xs220787d8385b41c5 Let me know if these are on the right track or if the tiles/ fundraising team is wanting something a little more different. I saw above you mentioned the Kristina's dino, but I wasn't sure if this would deviate too far from the other deliverables:
https://redpen.io/p/xs220787d8385b41c5

cc @cassiemc @lovegushwa @valianttry

**Comment by natalieworth** [comment]
Hi, @edrushka @cassiemc @lovegushwa @valianttryUpdates on redpen for the second iterations of static/ rollover directory tiles (https://redpen.io/p/xs220787d8385b41c5):
V5. https://redpen.io/ps3446c6a2ede3aa76
V6. https://redpen.io/rs17150b97464ce835
V7. https://redpen.io/cf91d6164b18a0933e
V8. https://redpen.io/qj9b9a2ee19c7e9b43
V9. https://redpen.io/qz70a88c3b0fafd6e8

**Comment by cassiemc** [comment]
These all look good to me, design-wise @natalieworth, thanks!

**Comment by natalieworth** [comment]
Thanks @edrushka @cassiemc @lovegushwa @valianttry Here's a final overview file for the tile variants on redpen: https://redpen.io/ovfa3b594168f5fbc3 (of the different exported versions).
@alicoding Jordan mentioned above that these tiles will also have to be localized. I've exported a .ai file along with .png's in this google drive folder: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0XzVDQnY5V1c4RGc Let me know how I can assist with this! I'll be around this afternoon and also all of next week while everyone's at Mozlando, so feel free to contact/ ping me if I can help out with these in anyway. Thanks.

**Comment by edrushka** [comment]
I'll connect with Jean to get her final approval and then I'll file the L10N bug.

**Comment by edrushka** [comment]
WOOT! Approved by the tiles team! https://bugzilla.mozilla.org/show_bug.cgi?id=1224719

Closing this now. I'll file a separate bug for L10N.

Thanks @natalieworth! 
:honeybee: :hibiscus: :sunflower: :hibiscus: :honeybee:

**Comment by natalieworth** [comment]
:+1: Yay!
