### ISSUE TITLE
Content of thank you email doesn't show up on iPhone

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#881]
![iphone_email](https://cloud.githubusercontent.com/assets/1901816/11300188/020cdb74-8f85-11e5-8ce7-e77ed607c70a.jpg)

**Comment by adamlofting** [comment]
It renders in gmail desktop, but this was the only email not rendering on my phone. The email text was showing up in inbox preview, so I had downloaded the content. It just wasn't rendering. Maybe some mark-up has gone awry.

**Comment by jbuck** [comment]
Confirmed. Woah, this is weird

**Comment by jbuck** [comment]
All of the text is white on a white background. Wha...?

**Comment by jbuck** [comment]
I fixed it with https://github.com/mozilla/webmaker-mailroom/commit/869b54f893c0980f5cae81831cc3cd3e7df0b8b3

Nice catch @adamlofting !
