### ISSUE TITLE
Test donations and receipts for tax purposes

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#89]
I was thinking, end of year campaign works so well because it's tax time

If so, wouldn't it make sense to optimize for that?

We do nothing to explain or reassure people that they'll even get a receipt.

I'm just thinking out a rough idea as to where I'm going, but maybe just a little "donations are tax refundable" and/or "we'll send you a receipt for your donation for tax purposes" on step two maybe?

It also has the benefit of helping people that might not know donations are tax refundable but were thinking of making a donation anyway.

We could AB test this change if we decide it's worth a shot. Could test a bunch of different placement and copy for this.

**Comment by jbuck** [comment]
One thing we didn't do last year was send a "Thank you for you donation email" for Paypal donations

**Comment by valianttry** [comment]
![img_9114_jpg](https://cloud.githubusercontent.com/assets/9830371/18594647/0555cf8a-7c0f-11e6-8277-269c1efe5bc0.png)

**Comment by ScottDowne** [comment]
Migrated to https://github.com/MozillaFoundation/Advocacy/issues/380
