### ISSUE TITLE
Update "Donate now" button on fundraising.mozilla.org 

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate.mozilla.org#890]
https://github.com/mozilla/eoy-fundraising

The "Donate now" button links to sendto, and should probably now link to donate.mozilla.org

**Comment by ScottDowne** [comment]
We probably want to update it to "https://donate.mozilla.org/en-US/?amount=50&presets=100%2C50%2C25%2C15&source=FMO&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=FMO&utm_medium=referral&utm_content=FMO_redbutton"

**Comment by valianttry** [comment]
@cadecairos this is a duplicate of https://github.com/mozilla/donate.mozilla.org/issues/740#issuecomment-155998791

closing this one, but prioritizing the link updates for next week.

**Comment by alicoding** [comment]
I can give @cadecairos access or I can do it

**Comment by alicoding** [comment]
https://github.com/mozilla/eoy-fundraising/pull/17

**Comment by alicoding** [comment]
landed https://fundraising.mozilla.org \o/
