### ISSUE TITLE
Figure out why Paypal transactions timed out instead of returning 4xx/5xx error

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#892]
When we messed up the test/production credentials on production earlier today we found that Paypal transactions timed out instead of immediately returning a 4xx/5xx error. Lets find out why!

**Comment by cadecairos** [comment]
@jbuck I have a hunch this is the [request](https://github.com/request/request) module not aborting the HTTP request to paypal before the Heroku router closes its' connection to the dyno. The deploy/change in env vars could have had something to do with it?

**Comment by jbuck** [comment]
Might have something to do with this not-great error handling: https://github.com/mozilla/donate.mozilla.org/blob/086142987b44e40b9bfd46c4f7d274012a4bc890/routes/index.js#L131

**Comment by cadecairos** [comment]
hahaha yup.

**Comment by jbuck** [comment]
We had this happen again. We should:

* Audit and fix error handling
* Add our own HTTP request timeouts (25s?)
* Add our own good heroku reporter
* Add request id that heroku sends to our logging
* Add logging to external API requests

**Comment by cadecairos** [comment]
> Audit and fix error handling

This might require some front-end work to give us a place to redirect the user-agent to when something goes wrong

> Add our own HTTP request timeouts (25s?)

I'll take this on next

> Add our own good heroku reporter
> Add request id that heroku sends to our logging
> Add logging to external API requests

These three handled in #920

**Comment by jbuck** [comment]
We've landed all of this. Go @cadecairos !
