### ISSUE TITLE
Ensure graphs on f.m.o are pulling 2015 data

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#897]
We've currently got 2 graphs on http://fundraising.mozilla.org/ : donors by country and donors by source.

@ScottDowne can you outline what needs to happen to pull in 2015 data? Let me know if there's someone else I should assign this to.

cc @valianttry

**Comment by ScottDowne** [comment]
Blarg, I don't know where to begin yet.

**Comment by adamlofting** [comment]
Adding some notes.

Donors by country polls the totalizer API. Probably needs some updates to group the Stripe and Paypal data together: https://github.com/mozilla/mofo-transaction-storage/blob/master/server.js

Donors by source is GA data. This is currently serving a saved static snapshot from the end of last year, but now might need to combine the ga account for sendto and donate... https://github.com/adamlofting/transformtogeckoboard/tree/master/lib I can look at this in the coming days, but might be best to hide the 2014 data on f.m.o in the meantime.

**Comment by jbuck** [comment]
I made the donors by country working. Over to Adam for GA stuff!

**Comment by adamlofting** [comment]
Donors by source is now working too.

This combines transactions on the old sendto.m.o GA with regular updated data from the new donate.m.o GA profile.
