### ISSUE TITLE
Add totalizer to f.m.o.

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#898]
@valianttry confirming you still want to do this before I assign dev and design.

**Comment by valianttry** [comment]
Yes please! We should update the totalizer and make sure the charts work with the new data from Stripe (referring to: #897 and #873 )

**Comment by edrushka** [comment]
Will assign this after today's call. I'm not sure which dev should work on f.m.o.

**Comment by jbuck** [comment]
The API is working great, just need to get ali to add the totalizer back

**Comment by alicoding** [comment]
landed https://fundraising.mozilla.org \o/
