### ISSUE TITLE
Write EN posts/tweets for social

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#899]
Write the English copy for our @mozilla fb posts and tweets (accompanying graphics can be found in #807 and #808) and create a basic schedule for posting.

Reminder: Gear Store can have a bit more space until Dec 14.

Thanks @KevZawacki!!

**Comment by edrushka** [comment]
Notes from our meeting: https://public.etherpad-mozilla.org/p/Social-FR2015

**Comment by edrushka** [comment]
@KevZawacki is a hero! https://docs.google.com/document/d/1zDvy0bhm3O8hHbT-dC35XI4S5yGROkD7BHNvv4wHq4E/edit

Closing this.

**Comment by KevZawacki** [comment]
@edrushka [I prefer "legend" to "hero."](https://www.youtube.com/watch?v=ix8s_TUYVW8)

**Comment by edrushka** [comment]
Legends never die!!!
