### ISSUE TITLE
Work on improving page load times globally

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#9]

**Comment by adamlofting** [comment]
This is important, but I don't think we should work on this Optimization until we're happy with the rest of the build.

**Comment by adamlofting** [comment]
Task from #4 : 

- [ ] optimize our page load using Google PageSpeed & YSlow

**Comment by ScottDowne** [comment]
Our worst culprit here is lacking magnification and that we have too many scripts.

So removing jquery looks like a good place to start.

**Comment by adamlofting** [comment]
@ScottDowne just checking... do you mean minification?

**Comment by ScottDowne** [comment]
@adamlofting haha, yes, yes I did.

**Comment by adamlofting** [comment]
Let's screenshot results of the latest tests against staging and then close this ticket.

**Comment by ScottDowne** [comment]
We need to screenshot from prod, or a local tunnel that is configured like prod, which is what I have been doing.

![screen shot 2015-10-22 at 12 38 20](https://cloud.githubusercontent.com/assets/197334/10671676/f6109cfc-78b9-11e5-827b-7ea303f51bed.png)
![screen shot 2015-10-22 at 12 38 03](https://cloud.githubusercontent.com/assets/197334/10671677/f7ff4162-78b9-11e5-93af-71373ab66a15.png)
