### ISSUE TITLE
Singapore postal code problem

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#902]
**Sent to donate@:**

Hi
Tried to donate but won't process because it won't recognize Singapore's postal code.   It's the correct postal code given but it kept saying it's invalid postal code.

Just to let you know perhaps others might experience the same issues and you would have lesser donation if this issue is not resolved.
Best regards

**Comment by ScottDowne** [comment]
I just tried a Singapore postal code after googling what it looked like, and it worked on our end, but sounds like Stripe rejected it for whatever reason. Not sure what to do with this yet.

**Comment by jbuck** [comment]
@valianttry Can you find their attempted charge in Stripe? I see there are other charges from Singapore in Stripe, so it must be something else that failed

**Comment by valianttry** [comment]
I searched for her email and her name in Stripe dashboard and didn't find her. Am I searching in the right area?

**Comment by ScottDowne** [comment]
It's probably an error in the logs, but it wouldn't be a customer or charge, so I don't think it would come up on a search. It's also likely a failure in creating the token.

@jbuck we're probably going to need to figure out a way to search these error logs if we want them to be useful.

**Comment by ScottDowne** [comment]
After thinking about this, I'm fairly convinced this is stripe rejecting the postal code because it wasn't the right postal code, and not because it was an invalid formatted postal code.

The only error we have for that field is triggered by stripe, we do nothing else there and accept all characters.

**Comment by ScottDowne** [comment]
I'm going to close this as I'm sure enough it's the same as #914
