### ISSUE TITLE
Receipt email is not translated in French

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#903]
ID: ch_179RqDG8Mmx3htnxCqj6zT8a

The donor writes: "write in French please .

Cordially."

![donate_post_from_provence132000_yahoo_fr_requires_approval_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11316664/06b976a6-8fc5-11e5-89de-3ead96179f09.png)

**Comment by jbuck** [comment]
The locale here is listed as fr, I wonder why it didn't translate... https://dashboard.stripe.com/payments/ch_179RqDG8Mmx3htnxCqj6zT8a

**Comment by valianttry** [comment]
Received email from a second French donor who did not receive a translated Thank You email:

ch_179eXQG8Mmx3htnxNOBEnuSD

**Comment by jbuck** [comment]
Gah, programmer error. Fixed in https://github.com/mozilla/sawmill/commit/fdadcaa32982894310ec3d6f967846c3ee821878
