### ISSUE TITLE
It feels strange when the standard amounts are wildly different depending on currency

### ISSUE THREAD

**Issue by simonwex** [mozilla/donate.mozilla.org#906]
In the test I was in, the donation defaulted to USD:
![image](https://cloud.githubusercontent.com/assets/25260/11320498/b4ccc64c-904e-11e5-91cc-b4df78a14103.png)

After switching to CAD, the amounts are much, much higher:
![image](https://cloud.githubusercontent.com/assets/25260/11320494/990652ac-904e-11e5-87f9-b10c31941913.png)

This was both surprising and off-putting as a donor.

**Comment by valianttry** [comment]
Note: This is for monthly donation. Just checked and the average Canada gift size is just under $10. Let's match the CA monthly gift array to the US gift array: 

10,5,3,2

**Comment by adamlofting** [comment]
@valianttry there's an open ticket here to check all the locale amounts: #518

**Comment by jbuck** [comment]
Fixed by #949
