### ISSUE TITLE
Comma not allowed for BRL "other" amount field

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#910]
ID: 
    card_179iwTG8Mmx3htnxufSiIYkF

* I have given him a full refund for the 300 Real. 
* I also realize he accessed the FAQ and clicked on the link to "manage my recurring donation" -- which still points to the BSD page. I just edited the FAQ telling donors to contact donate@ instead of linking to the BSD form (since we don't yet have #791 )
* He said he had trouble understanding the "comma" vs. "decimal" in the "other amount" box for Real... it's a good point. Anything we could do to help? Configure that box so formatting is correct for Real vs. USD?

Message is below:
![support_about_recurring_donation_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11321378/a4c20a50-9071-11e5-84fe-f60b0f100093.png)

**Comment by ScottDowne** [comment]
It gets tricky quickly when we consider all the currencies. Worth investigating how complex it is, but if we do it just for BRL, maybe it's not so bad? Maybe it's not so bad for eur either.

We didn't do this initially because we thought it wasn't critical, but, sounds like people care.

**Comment by valianttry** [comment]
@ScottDowne it is just 1 person so far... can we explore options and then discuss before investing too much time?

**Comment by ScottDowne** [comment]
Monday I'll invest time to see how hard it would be, I won't go into actually doing it. It'll be a few minutes of work.

**Comment by ScottDowne** [comment]
This landed, so I think closing this.

Now what it does is if you're in a comma based system, it does not allow a decimal, and if you're in a decimal based system, it does not allow a comma.
