### ISSUE TITLE
Mexico conversion is very low, but traffic is high. Default correct currency?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#911]
We are getting a LOT of traffic from Mexico, but conversion is low. Is it possible to default to MXN if we detect that locale? They are seeing Euro default because our ES form is ES-ES (Spain). But we're actually seeing a lot more traffic from Mexico than Spain!

![location_-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/11321411/7e68dbfc-9073-11e5-885f-55a6bf45b644.png)

**Comment by jbuck** [comment]
Hrm, I think this will be tricky because we don't have an es-MX locale to
set data for. I think we'll need to think about how best to do per-locale
overrides when we don't have a locale available.

**Comment by ScottDowne** [comment]
We have en-CA and en-GB.

Setting up an es-MX wouldn't be any more work, and should remove a lot of the tricky ness, right?

**Comment by edrushka** [comment]
Changing this to P2 since a few other issues (INR and currency defaults) are more pressing.

**Comment by ScottDowne** [comment]
Question about this, are we shipping an es-MX snippet too?

Our conversion is high because we have some es-MX space, but, if we default to MXN we'll need to match that with a snippet to MXN.

This just occurred to me...

**Comment by adamlofting** [comment]
I've gone round in a few circles thinking about this...

Here's an equivilent scenario. 

Here in the UK I see the en-US snippet, and it takes me to the en-US form. 
<img width="832" alt="screenshot 2015-11-26 10 50 04" src="https://cloud.githubusercontent.com/assets/1901816/11421299/cdb940a0-942b-11e5-8803-b9e55c99f795.png">

The trouble with auto-switching to GBP for me is I may have already made a decision about my donation amount based on the $USD buttons I'd seen on the snippet (auto switching to GBP could trick me into donating more than I wanted too if I don't notice the change). Once I'm on that page though, it's relatively easy to change the currency.

### Two things we can do

I think as @ScottDowne mentions, we should address this at source by creating snippets in more locales. (including en-gb please! :yum:)

Another issue might be that the currency switcher isn't obvious to people in es-MX who don't recognise the currency code 'EUR' (we've all got used to this UI now but our audience don't have the same knowledge). Should we test adding the currency *symbols* back into that drop-down to make it more explicit what it does.

**Comment by ScottDowne** [comment]
@adamlofting adding currency symbols might help, and it's a really easy patch, but I'm thinking an en-MX snippet would pay off more. We could create less friction.

**Comment by adamlofting** [comment]
@ScottDowne agreed *if* people in MX have their locale set to es-MX. I don't know if people do that, or they just use any version in the right language (my browsers are a mix of en-GB and en-US).

**Comment by adamlofting** [comment]
Follow up tasks have been filed.
