### ISSUE TITLE
Reduce default amount on snippet >> donation form for BRL

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#912]
The PTBR form has a relatively low conversion rate of 7 - 8% compared to other locales. I suggest we reduce the default selected amount on the snippet and donation form to R$25 (about $6 USD). Right now it's R$50 - or about $14 USD. 

![about_home_snippet_preview](https://cloud.githubusercontent.com/assets/9830371/11321448/96dd8b3c-9074-11e5-841a-4c54edc0b53e.png)

![donate_mozilla_org___doe_a_mozilla_hoje](https://cloud.githubusercontent.com/assets/9830371/11321449/9d0a3e92-9074-11e5-819e-e8f60107b3c2.png)

**Comment by valianttry** [comment]
closing this, Jean made the change so it is now: 50, 25*, 15, 10

**Comment by ScottDowne** [comment]
Actually, we just changed which was selected, we didn't update the presets themseelves. So it's now 100, 50, 25*, 10.

https://snippets.mozilla.com/show/5487/

**Comment by adamlofting** [comment]
See also #518
