### ISSUE TITLE
Delete PayPal for IDR and INR form - CC only

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#915]
We're seeing a large amount of India traffic (13% of all traffic during the India daytime). For INR, Wikipedia removes payment processor options, limits it to credit card only on their form (see screengrabs below). Can we produce an /in/ form that removes PP alltogether and just show the CC option since Stripe accepts INR?

![make_your_donation_now_-_donate](https://cloud.githubusercontent.com/assets/9830371/11322290/d82a0e42-9099-11e5-8508-6078261f508d.png)

![make_your_donation_now_-_donate](https://cloud.githubusercontent.com/assets/9830371/11322291/e1373dca-9099-11e5-8061-d1811ba25b7a.png)

**Comment by valianttry** [comment]
NOTE: I think as an initial hack we could just keep the EN language, but default to INR currency. I believe the traffic is from Indians using EN locale anyway. We just can't accept INR / rupee so they are abandoning. (This is my current theory.)

**Comment by ScottDowne** [comment]
I would say let's have this trigger not on /in/ but instead trigger removing the paypal option when the currency is INR (or any other not paypal accepted paymet)

I see this as a seamless switch of two slightly different step 2 pages, new one with credit card info expanded, and no paypal button, and have the amex/visa/mastercard logos make good use of the leftover space.

Once we have a finished /in/ we can have that select INR like we do with the other de -> eur,  pt-BR -> brl, etc, and everything should just fall into place.

We can do this for a bunch of currencies paypal doesn't accept, when we're ready.

React should make this pretty easy.

**Comment by ScottDowne** [comment]
@valianttry 

For INR presets, what values do we want to start with?

I'm thinking:

```
    minAmount: '130',
    presets: {
      single: ['1300', '650', '330', '200'],
      monthly: ['650', '330', '200', '130']
    }
```

As rough conversions from our USD values.

**Comment by valianttry** [comment]
@thecount that seems like a good set.

**Comment by edrushka** [comment]
ccing myself

**Comment by ScottDowne** [comment]
I have a WIP patch for this, I wanted to get to it today, but didn't get a chance.

**Comment by valianttry** [comment]
For further motivation (this is one of several emails we've gotten like this to donate@):

![indian_rupee_is_not_available_in_the_list_of_currencies_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11359372/4850fce8-9230-11e5-9a09-4cc1a5f7eca6.png)

**Comment by valianttry** [comment]
Another, this person includes some interesting intel:

**Hi Mozilla team, xxx here, i would love to pitch in but i live in India and i didn't see an option for the Indian Rupee and an option for a debit card (most of us Indians abhor the use of a credit card [ well atleast the sensible ones, i mean why pay in credits when you have cash in the first place, right?]), so please bring those two above mentioned options and i will gladly pitch in and support the cause if not just wait for me to get a credit card. :D**

**Comment by ScottDowne** [comment]
@valianttry The way I have this working, can unlock ANY stripe currency that paypal doesn't support.

Here is the list we now have access to: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1

^^ Anything under group 1 and group 2.

I don't think we should enable all of those, it'll make an unwieldy confusing dropdown that's impossible to find what you want, but, if there are other ones on your mind let's consider adding them too.

**Comment by valianttry** [comment]
WHOA

This is rad. This is how Wikipedia tackles this problem:

https://wikimediafoundation.org/wiki/Ways_to_Give

Notice they group by continent >> country >> localized currency form

I would focus on our Firefox usage stats as a guide, those are:

**Tier 1
English
German
French
Spanish (es-mx, es-es)
Polish
PT-BR
Russian
Italian
Hungarian
Japanese
Dutch
Greek
Indonesian
Czech
zh-TW
zh-CN

**Tier 2
Romanian
Vietnamese
Bulgarian
Norwegian
Slovak
Slovenian
Serbian
Korean
Danish

**Comment by valianttry** [comment]
NOTE: I would P1 MXN and INR based on direct donor feedback... the above is P2 IMHO, but it would be good to get this up and running for as many locales as possible before mid-december? Possible?

**Comment by valianttry** [comment]
@lovegushwa YES v 3 and 4 are the Ones! We've tested an image before and it didn't work very well....

**Comment by valianttry** [comment]
Here is what my inbox looks like re: INR requests :moneybag: 

![search_results_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11419110/1d8b43b4-93da-11e5-8b39-9b84712010f9.png)

**Comment by ScottDowne** [comment]
INR is coming first, I suspect we can ship it today, and keep an eye on it.

I'll ping you when it's on staging and production.

**Comment by ScottDowne** [comment]
I just merged INR, should be on staging very soon. IDR and the rest can be another patch.

**Comment by ScottDowne** [comment]
We are currently missing and can enable for Stripe without paypal:

From the tier 1 list:
CNY (China)
IDR (Indonesia)

From the tier 2 list:
ROM (Romania)
VND (Vietnam)
BGN (Bulgarian)
RSD (Serbian)
KRW (Korean)

So, I guess I'll go do that.

Officially switched to EUR
Slovak
Slovenian

**Comment by valianttry** [comment]
Awesome, i have about 15 emails in donate@ that I want to reply to when INR becomes available. 

@ScottDowne if it is less work to just do Tier 1 (CNY and IDR) I think it's OK to forego working in Tier 2, if we have other P1 bugs. If you can just take care of all these in one swoop then ignore this -- just prioritizing what we have to do given the snippet is going up to 50% in priority locales Tuesday.

**Comment by ScottDowne** [comment]
@valianttry it's the same amount of work to add it to the list, but getting a list of presets and min amount is where tier 2 is more work.

I'll do CNY and IDR. INR is already on staging, shipping any minute now.

**Comment by ScottDowne** [comment]
CNY, INR, and IDR are all shipped now. Along with locale pages for them.

https://donate.mozilla.org/zh-CN/ https://donate.mozilla.org/id/ https://donate.mozilla.org/zh-CN/ https://donate.mozilla.org/pa-IN/

Closing this, and going to file a new one for the tier 2s just to reduce noise.

**Comment by ScottDowne** [comment]
Filed for the tier 2s https://github.com/mozilla/donate.mozilla.org/issues/970
