### ISSUE TITLE
Change "Credit card" to "Credit / debit card" in our form design?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#916]
I just received an email from a donor that asked if we accept Visa debit card. Wikipedia's CC button says "Debit/credit card" but ours only says "Credit card":

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/11325958/a20dae96-9110-11e5-81cc-209bfb48ad0b.png)
Wondering if it's worth it to add "/debit" to make that clearer? Or would it hurt conversion overall.... @jbuck is there a way to tell in Stripe what % of people use credit vs. debit?

**Comment by jbuck** [comment]
Yep, we can get that data from Stripe

**Comment by adamlofting** [comment]
I can't imagine this hurting conversion (it might even increase it given that donor feedback) but we could always A/B test this later if we want to double check.

**Comment by ScottDowne** [comment]
@adamlofting I would be willing to test this after the fact.

We don't have time to test this given other possible high value tests, but I'm fine with good guesses now, and tests later.

Is this something we can do if warranted?

**Comment by ScottDowne** [comment]
There are a few areas where we say credit card, which we should consider as well, but can fix in a separate patch:

placeholder: 
![cc](https://cloud.githubusercontent.com/assets/197334/11401107/ef1331ca-935e-11e5-99e1-df2b34d848d4.png)
cvc info:
![cc1](https://cloud.githubusercontent.com/assets/197334/11401110/f4558764-935e-11e5-964a-2d4f76f0e90a.png)
stripe notice:
![cc2](https://cloud.githubusercontent.com/assets/197334/11401117/fa3e4cc4-935e-11e5-95b6-c1e563b368b4.png)
And in two error messages.
```
invalid_number=Invalid credit card number
incorrect_number=Incorrect credit card number
```

Should we update these to either specifically say credit/debit or, maybe just say card, and only specify credit/debit card once on the initial button?

**Comment by ScottDowne** [comment]
I have a pull request for this: https://github.com/mozilla/donate.mozilla.org/pull/932

**Comment by ScottDowne** [comment]
Merged it for just the button.

**Comment by ScottDowne** [comment]
@valianttry I added the space in the string, so "Credit/debit card" is now "Credit / debit card".

I think we can close this now.
