### ISSUE TITLE
erm... apparently there are no postal codes in Bolivia?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#925]
More of an "FYI" as we have received $0 from Bolivia (but maybe this is part of the reason why?)

![i_tried_to_donate__10u_s__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11359533/c74dfafe-9231-11e5-9778-ce627e1a7aa9.png)

**Comment by jbuck** [comment]
I think this will actually be pretty easy to fix. There's a [list of countries postal codes](https://en.wikipedia.org/wiki/List_of_postal_codes) so we just need to make it an optional field or not based on the selected country.

**Comment by cadecairos** [comment]
@ScottDowne I have literally no idea how to implement this

**Comment by cadecairos** [comment]
We're moving do default to the one-page flow, so this is no longer going to be our issue.

**Comment by cadecairos** [comment]
This is an issue in Stripe Checkout too!

I've notified their enginneering team via email and they're investigating. They are planning to update me with a timeline for a fix.

**Comment by valianttry** [comment]
FYI just got similar complaint from Panama:

![donation_electronic_formula_stupidity_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11448918/11aec864-9519-11e5-892e-9362123fe11a.png)

**Comment by cadecairos** [comment]
Is that also an issue with stripe checkout?

**Comment by cadecairos** [comment]
I took a look just now, stripe checkout appears to handle Panama correctly

**Comment by valianttry** [comment]
OK @jbuck or @cadecairos you think we can close this ticket? Seems like WONTFIX
