### ISSUE TITLE
Locale negotiation

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#927]
Our current UX/design for displaying the locale is like this:

1. If the user visit the URL without locale in it e.g. [https://donate.mozilla.org/share/](https://donate.mozilla.org/share/)
  We will check their locale in `navigator.language` and if we support that language we will redirect them to that locale and replace the URL with the new one e.g. `navigator.language='de'` then the URL will now be [https://donate.mozilla.org/de/share/](https://donate.mozilla.org/de/share/).

2. If the user visit the URL with the locale in it [https://donate.mozilla.org/de/share/
(https://donate.mozilla.org/de/share/).
  We will do nothing here since they intentionally asking for that locale.

Now this design is okay, but what if the case for number 1 we don't support that locale? Right now it will just redirect to our default locale which is `en-US`. This is fine, but what if we do support the locale they've requested, but in another version? The example for this case would be:

List of currently supported locale in our app (this is just some of them)

```
de
it
fr
en-US
en-GB
pt-BR
pt-PT
```

So, if the user visit the site with `navigator.language=pt` what's going to happen here? Right now it will be redirect to `en-US` instead of choosing one of the `pt-*` for them. Another thing we also need to implement here is when there are multiple languages set in the user's language preferences. 

1. If the user set their languages to `navigator.languages=['de','fr','en-GB']`.
  What we need to do here is check the first item in the array of `navigator.languages` and redirect to the first possible locale, and if we don't support that locale then we'll move to the next item until we find a possible match supported locale otherwise will default to `en-US`. The example above is simple because we do support all 3 languages.

2. If the user set their languages to `navigator.languages=['he','fr-FR','en']`.
  Now the first language we currently don't support, but `fr-FR` is a possible locale to match with our current support language `fr` so we could redirect them to that locale.

note: 

`navigator.language` is whatever you have set your first language in your browser preferences. (Chrome doesn't work well with this option.)
`navigator.languages` is the list of languages in order in your browser preferences.

**Comment by alicoding** [comment]
@jbuck @ScottDowne @edrushka @valianttry 

This is a P1 in my opinion, but I don't know what you all think here? Maybe @adamlofting can tell us how many people will visit the URL without locale here?

**Comment by ScottDowne** [comment]
This is important, can get us more money, and very much should be worked on.

However, I don't think p1 is about importance. It's about emergency. I want a drop everything and work on this bug Label. If that's not p1, I don't know what is.

The more p1s we have, the less important they become.

**Comment by alicoding** [comment]
@ScottDowne the reason I asked if this is a P1 because I don't know our data not because I don't know how important is p1 label. We might be getting 1% of our traffic on no-locale URL or it could be more. But, knowing the number will tell us if this bug is a drop everything you're working on and do this now or not.

**Comment by ScottDowne** [comment]
@alicoding this should enable es-MX to preselect MXN and Mexico for currency and country?

**Comment by alicoding** [comment]
Wasn't planning to but I think we can teach either client to do that or server can just handle that.

**Comment by ScottDowne** [comment]
@alicoding We just need to do with es-MX what we do with en-CA, it's not different, so it should do that.

**Comment by alicoding** [comment]
Then I guess no extra work here except adding that locale on the directory.

**Comment by valianttry** [comment]
@alicoding thanks so much for the research, and that explanation actually helped me a lot.

I can see in Google Analytics that we have locale for 100% of donors (or close to 100% -- i can't find any category that has no locale?) probably because most donors are from Firefox and I assume locale is set automatically somehow? 

![language_-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/11408545/c47531e2-936e-11e5-84b3-5fded165b113.png)

**Comment by alicoding** [comment]
@valianttry actually what we want to see in the GA would be a url that they've visit the page to know exactly if they have locale in the URL or not.

**Comment by adamlofting** [comment]
Sorry for my slow reply here. I've taken a look at the numbers and recommend this is a P2. There are other tasks which will potentially raise much more money in the next 30 days. 

Here is my analysis.

This issue affects users who land on the site without a locale in the string. This is 8% of users, which seems like a lot.
<img width="209" alt="screenshot 2015-11-26 10 24 44" src="https://cloud.githubusercontent.com/assets/1901816/11420795/63db5f2c-9428-11e5-972b-27e2df5ce4a5.png">

But if we look at the browser languages for people in that 8%, they are almost all using a language we have already localized.
<img width="924" alt="screenshot 2015-11-26 10 25 49" src="https://cloud.githubusercontent.com/assets/1901816/11420807/7d23299c-9428-11e5-9a95-a36ec14e31e0.png">

--

@alicoding one idea on the issue you've outlined above is to check `navigator.langauges` first for an exact match, and if there is no exact match then accept any partial match. Then, if no partial matches default to en-US.

**Comment by alicoding** [comment]
Fixing in #968
