### ISSUE TITLE
list of sendto.mozilla.org on fundraising.mozilla.org

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#928]
* https://sendto.mozilla.org/page/s/sign-up-for-mozilla/
* https://sendto.mozilla.org/page/contribute/givenow-seq?preset=2&source=FMO&ref=EOYFR2014&utm_campaign=EOYFR2014&utm_source=FMO&utm_medium=referral&utm_content=FMO_donateTXT
* https://sendto.mozilla.org/page/contribute/givenow-seq?preset=2&source=FMO&ref=EOYFR2014&utm_campaign=EOYFR2014&utm_source=FMO&utm_medium=referral&utm_content=FMO_redbutton
* https://sendto.mozilla.org/page/contribute/givenow-seq?preset=2&source=FMO&ref=EOYFR2014&utm_campaign=EOYFR2014&utm_source=FMO&utm_medium=referral&utm_content=FMO_redbutton
* https://sendto.mozilla.org/page/s/sign-up-for-mozilla/
* https://sendto.mozilla.org/page/contribute/EOYFR2013-newdefault?source=viewsource_redbutton

I'm trying to update these URLs to donate.mozilla.org but some of them I don't know if we've implemented the page for e.g. mailing list signup form.

@valianttry @edrushka @ScottDowne Can anyone of you help regenerate the URL so that I can put that up on f.m.o site?

**Comment by ScottDowne** [comment]
I think the seq pages are easy, they just need to retain or update their ga queries, and the the presets need to be updated to match whatever preset=2 used to do.

I don't know about the other links at a glance.

**Comment by valianttry** [comment]
#740 addresses a couple of these

The links that go to an optin or signup form are not fundraising related and we haven't implemented. We don't need to update them right now. URL builder is here: http://mozilla.github.io/mofo-campaignurl/

**Comment by adamlofting** [comment]
As Andrea said, the email sign-up form isn't urgent, but when we do get to it we'll want to switch the sign-up to talk to Basket rather than BSD. The API and list is setup and ready for when we have a minute to make this update.

**Comment by valianttry** [comment]
@alicoding Here are two new URLs for the donate form:

Red Button in header:
https://donate.mozilla.org/?ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=fundraising.mozilla.org&utm_medium=referral&utm_content=FMO_redbutton

https://donate.mozilla.org/?ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=fundraising.mozilla.org&utm_medium=referral&utm_content=FMO_textlink

**Comment by valianttry** [comment]
@alicoding I believe you've updated all the FMO links? I'm closing this but re-open if i'm wrong.
