### ISSUE TITLE
Add MoFo JavaScript Style Guide to the repo

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#93]
@ScottDowne @alicoding ?

Should we be using this:
https://github.com/MozillaFoundation/javascript-style-guide

**Comment by ScottDowne** [comment]
Yeah, we should, but not sure about this heartbeat.

**Comment by alicoding** [comment]
If I finished my l10n related bug soon I could take this bug if there is no other urgent bugs to take on.

**Comment by ScottDowne** [comment]
@alicoding I would start with https://github.com/mozilla/donate.mozilla.org/issues/99 instead.

Thoughts on priority @adamlofting ?

**Comment by adamlofting** [comment]
Thanks.

I've just filed a few P1s around localization which definitely take priority.

I'll put this in the backlog, now that it's confirmed thing we should be working on.
