### ISSUE TITLE
preserve a query on a redirect

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#930]
right now if you visit an unknown locale like this

https://donate.mozilla.org/th/?currency=thb

it will redirect you to https://donate.mozilla.org/en-US/ because `th` is not supported, but we lost the query for that which we want in this case since `thb` is a supported currency.

**Comment by edrushka** [comment]
Can I assign this to you ali? I want to make sure all P1 bugs are assigned.

**Comment by alicoding** [comment]
Sure thing. But I'm not sure I'll get this done soon since there are other one that I really want to make sure I get to it first.

**Comment by adamlofting** [comment]
@alicoding is this just the redirect that happens on the root? 

If so, I think we can P2 this. I had a look in GA at the langauges used by people who are hitting the root URL, and it's mostly en-US and other locales we do have setup:

<img width="1307" alt="screenshot 2015-11-26 09 51 33" src="https://cloud.githubusercontent.com/assets/1901816/11420031/5297e42e-9423-11e5-858b-3456287b3342.png">

**Comment by ScottDowne** [comment]
Moving this up to a P1 as it'll make integrating with mozilla.org locales much easier.

**Comment by alicoding** [comment]
Fixing in #968

**Comment by alicoding** [comment]
#968 landed \o/
