### ISSUE TITLE
Use Exact Target to send receipt emails

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#935]
I'm getting a few emails like below from ISPs because our Thank You emails are triggering some "spam" warnings... we run the risk of being blacklisted -- worst case scenario: Our donors no longer receive receipts.

What are options for mitigation? @adamlofting @jbuck 

![email_feedback_report_for_ip_54_240_8_18_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11407546/58228036-9368-11e5-91ec-dd1c0b0724c2.png)

**Comment by jbuck** [comment]
This probably stems from our use of AWS SES. @simonwex do you know of any other transactional email vendors we could use here? Mostly I'm worried about vendor review.

**Comment by jbuck** [comment]
The obvious question to ask is "Why not use Exact Target?" The answer is that the use of transactional email with Exact Target is not as straight forward as every other transactional email provider.

With ET we'll need to rebuild the email template within ET, possibly per-locale. Then for each receipt we'll need to run an API call to add the users transaction data to a data extension somewhere, and then trigger the email send. Not impossible, but not the easiest thing either.

**Comment by jbuck** [comment]
I did some more looking at their API and we may actually have a solution: https://help.exacttarget.com/en/documentation/exacttarget/interactions/triggered_emails/sending_exacttarget_emails_via_smtp_relay/

If all that's required is to give us credentials for SMTP, this would be a breeze to integrate!

**Comment by jessilyndavis** [comment]
3 options:

1) ET SMTP - email help@exacttarget.com and cc me. I'm unsure what needs to happen to give you credentials for SMTP (or if our current account setup allows for it?)

2) SocketLabs - email Wil Clouser for more info

3) Amazon web services - Cloud Services (FxAccounts) uses this for their transactional email sends. Email  - Ryan Feeley might know more about who has the keys.

**Comment by simonwex** [comment]
@pmclanahan do you know if we have SMTP access to ET already set up?

**Comment by jessilyndavis** [comment]
SMTP access is there:
https://help.exacttarget.com/en-US/documentation/exacttarget/interactions/triggered_emails/sending_exacttarget_emails_via_smtp_relay/

There are a few ways you can set it up - including passing through all of the HTML you want to send.

**Comment by jessilyndavis** [comment]
I don't know if/how basket API would be used for this - @pmclanahan  can chime in - or if you'd configure your calls to go directly to ExactTarget.

**Comment by jessilyndavis** [comment]
Okay! I've set up a sample text-only, no tracking, trigger in ExactTarget Production.

The external ID:  donation_receipt

You should be able to use ExactTarget's API (either by calling it directly with your username + Password of someone who has API access - or potentially using some code from Basket?) to replace the content of this email with what you want it to say (complete with individualized receipt information that you send in the text).

Here are the details:
https://help.exacttarget.com/en-US/documentation/exacttarget/interactions/triggered_emails/sending_exacttarget_emails_via_smtp_relay/

That's what I know. Everything else is in unknown territory for me/Basket.

**Comment by jessilyndavis** [comment]
@simonwex , @jbuck  - your ET logins are enabled with API access in case you want to give calling ET's API directly a try.  You can reset your password with your username and email address here:

https://members.exacttarget.com/Login.aspx

**Comment by jbuck** [comment]
Apparently AWS SES got added to a DNS blacklist: https://www.reddit.com/r/aws/comments/3u7i4a/amazon_ses_ips_listed_in_dnsbls/

**Comment by jbuck** [comment]
I've asked ET support where I can obtain working SMTP credentials, since my ET account credentials don't seem to work.

**Comment by jessilyndavis** [comment]
Thanks @jbuck - I just saw the support request and have asked to have this featured enabled on our account. I've included you on the email thread there.

**Comment by jbuck** [comment]
SMTP relay is in closed beta until December 32nd so we can't use Exact Target for sending email until it's in GA. Moving to Blue Sky

**Comment by valianttry** [comment]
:cry:

**Comment by ScottDowne** [comment]
Moving to https://github.com/MozillaFoundation/Advocacy/issues/395

**Comment by jcromualdo** [comment]
Literally working on this at the moment and we are doing it via API and Trigger, last night we tried sending a few emails from our ERP > ExactTarget > Customer (email) and we are not receiving those emails. The spam warnings make a lot of sense with what we are experiencing. 

Is ExactTarget suitable for Transactional Emails? We need to send 10K+ daily from our ERP to this application and finally the customer.

**Comment by jessilyndavis** [comment]
Oh hai! Good to see this project moving again. Lots have changed in the years since we started this project. Let's get on the same page with context & goals of this project and we can better answer your excellent question.

Can you file an email project request form? http://bugzilla.mozilla.org/form.crm

That gets this project on our* radar and into our pipeline to help triage and support.

*Our = Lifecycle Marketing cross-functional team = the platform keepers of ExactTarget -> now called Salesforce Marketing Cloud

Thanks!
