### ISSUE TITLE
other amount currency symbol is no longer centered

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#936]
![other-symbol](https://cloud.githubusercontent.com/assets/197334/11407960/fd07e8dc-9383-11e5-8133-ab71230a1e30.png)

Has this always been like this, or did we break something?

**Comment by KasperChristensen** [comment]
https://github.com/mozilla/donate.mozilla.org/commit/937652fd5b3d1df61109dd265f1d1ad360348d3f#diff-c5786860e11375aed83e0b24e313690e

It changed here:
in less/shared.less padding: 6px 12px; is changed to padding: 6px 0;

**Comment by ScottDowne** [comment]
Interesting, that's exactly when I noticed it break too.

**Comment by ScottDowne** [comment]
Boom fixed! closing! Thanks @KasperChristensen

Just in time for a production ship! Should be live in a few minutes.

**Comment by valianttry** [comment]
@KasperChristensen it's so awesome to see a contributor's help with fundraising! Thank you so much! :+1:
