### ISSUE TITLE
Trouble with PayPal 2-factor auth with monthly gift

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#938]
We received the email below from a donor. @jbuck can you just double check that we are getting monthly donations through PayPal? I just did a test and it seemed to work fine, but I don't have 2-factor auth turned on. (I have no idea what % of PP users have 2-factor turned on... it might not be a large number)

![can_t_do_monthly_donation_with_paypal__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11418150/199adc54-93d2-11e5-899e-fcceddc1fcaa.png)

**Comment by jbuck** [comment]
I think this is a combination of #981 and #984.
