### ISSUE TITLE
Project doesn't build / run

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#94]
@ScottDowne @alicoding 

I just pulled the code from master, ran the commands in the README and the project doesn't run for me locally.

> 0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'server' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info preserver donate.mozilla.org@0.0.1
6 info server donate.mozilla.org@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info donate.mozilla.org@0.0.1 Failed to exec server script
9 verbose stack Error: donate.mozilla.org@0.0.1 server: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid donate.mozilla.org@0.0.1
11 verbose cwd /Users/alofting-10317/Sites/donate.mozilla.org
12 error Darwin 14.4.0
13 error argv "node" "/usr/local/bin/npm" "run-script" "server"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error donate.mozilla.org@0.0.1 server: `node server.js`
17 error Exit status 1
18 error Failed at the donate.mozilla.org@0.0.1 server script 'node server.js'.
18 error This is most likely a problem with the donate.mozilla.org package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls donate.mozilla.org
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Is this broken code, or just missing documentation about something else I need to setup / configure?

**Comment by adamlofting** [comment]
Package `request` wasn't being installed. This should be fixed in: #95

**Comment by ScottDowne** [comment]
I must have had require in the node_modules from working on the PayPal changes which is why it worked for me.
