### ISSUE TITLE
Build 'additional info' variant

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#941]
#### Design
@lovegushwa has completed design in #550. 

#### Copy
Copy has been finalized in #633. We'll use (approved) Copy Variant A “non-corporate” to start:
Mozilla is proudly non-profit, non-corporate and non-compromised. Thousands of people like you help us stand up for an open Web for all. We rely on donations to carry out our mission to keep the Web open and free. Will you give today? 

#### A/B Test
Testing ticket is #370 (I believe this is the right one, @adamlofting please correct if I'm mistaken)

**Comment by adamlofting** [comment]
:+1:

**Comment by ScottDowne** [comment]
From the design ticket:

Download the heart SVG:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvN0VydkR2RF9FZDg/view?usp=sharing

<img width="993" alt="screen shot 2015-11-24 at 3 18 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/11383775/56134522-92bf-11e5-8627-7617f389676e.png">

<img width="994" alt="screen shot 2015-11-24 at 3 18 29 pm" src="https://cloud.githubusercontent.com/assets/12228435/11383783/5e90fdac-92bf-11e5-9287-6f234561438c.png">

**Comment by alicoding** [comment]
FYI: The word Mozilla (hopefully not an image) might be a problem with localization here. I actually don't know if we want to localize this, too? Or, will this be tested for English users only?

I'm just worried that when we localized this the word **Mozilla** will be moved and not align with the heart image here.

**Comment by ScottDowne** [comment]
@edrushka I forget what you said about the copy during our call. Can you sum it up in this ticket?

**Comment by jbuck** [comment]
@ScottDowne the copy would be changed to include "We're " at the beginning so it'd read:

{Mozilla wordmark} We're the non-profit behind Firefox working continuously to protect the Web.

@edrushka right?

**Comment by ScottDowne** [comment]
@jbuck no, that would be an update based on the copy in the design, which is not the copy we're actually using. I know, super confusing.

It would be based on the copy in the first comment.

**Comment by ScottDowne** [comment]
As a temp value, I'm going with "We're proudly non-profit, non-corporate and non-compromised..."

**Comment by edrushka** [comment]
Sorry for the delay. The final, approved copy (Variant A - [see here] (https://docs.google.com/document/d/1NXhuYivnZH4pWnNz49DieRmIiwQpwXTaO0DPqHEbFIs/edit#) is:

[Mozilla graphic] We are proudly non-profit, non-corporate and non-compromised. Thousands of people like you help us stand up for an open Web for all. We rely on donations to carry out our mission to keep the Web open and free. Will you give today?

**Comment by ScottDowne** [comment]
Landed on staging.
