### ISSUE TITLE
Design Dapper Fox sticker for Orlando

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#943]
The people have spoken: they demand Dapper Fox in sticker format! Strong sticker opinions were expressed during EOY stand-up call. Assigning @natalieworth to the difficult task of appeasing MoFo sticker aficionados ;)

Natalie, I'm labeling this as a P1 so we can get the stickers printed without paying rush fees but hopefully this won't take too much time. Let me know if you need help prioritizing this work. It would be wonderful if this could be done by EOD Friday but if that's not doable, just let me know.

cc @cassiemc

**Comment by valianttry** [comment]
Just confirming this is NOT the exclusive team sticker? This is a public sticker?

**Comment by edrushka** [comment]
Yup. Public sticker for the masses. They :heart: Dapper Fox!

**Comment by edrushka** [comment]
FYI, I got our Top Secret Project printing costs reduced, so we should still be on budget, even with the stickers.

**Comment by natalieworth** [comment]
Quickly put together a couple of sticker options with Dapper Fox in the redpen: https://redpen.io/uz5617888b99dd5e03

**Comment by natalieworth** [comment]
@edrushka V2 of Dapper Fox body and Dapper Fox's head are up on redpen: https://redpen.io/bf36f783db45a75145
Feel free to have our dev friends take a look again! They'll be the one's primarily using these :)
cc @flukeout @sabrinang @kristinashu @cassiemc

**Comment by edrushka** [comment]
Stickers have been ordered! Hurray! Thanks @natalieworth

**Comment by edrushka** [comment]
FYI, final artwork here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0YnBqMTNWSlAyTVU

**Comment by natalieworth** [comment]
:+1:
