### ISSUE TITLE
Build 'Further Monthly Ask' popup

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#944]
#### Design
@lovegushwa created 2 variants in #638 
[Variant A "short"] (https://redpen.io/cm9a658825a369335d)
[Variant B "long"] (https://redpen.io/yxdac62db58e998649)

#### Copy
Copy was finalized in #637 
##### Variant A “short”
Before we process your donation, will you consider stretching your contribution by converting it to a monthly gift of $##?
[Yes! Convert my one-time gift to an automatic monthly donation of $##]
[No thanks — please continue with my one-time gift of $##]

##### Variant B “long”
Thank you for your support!
Before we process your donation, will you consider stretching your contribution by converting it to a monthly gift of $##?
By becoming a monthly supporter of Mozilla, you join a very special community whose automatic monthly gifts sustain our mission to build the Internet as a public resource accessible to everyone.
[Yes! Convert my one-time gift to an automatic monthly donation of $##]
[No thanks — please just continue with my one-time gift of $##]

#### Testing 
Test ticket: #166 

#### Implementation notes
This should only go to donors who enter $5 or more. It doesn't make sense to ask a $3 one-time donor to upgrade to a $5 monthly donation.

**Comment by adamlofting** [comment]
Just for clarity :gem: 

> This should only go to donors who enter $5 or more.

This should only go to *one time* donors who enter $5 or more.

**Comment by ScottDowne** [comment]
I wasn't looking at this closely enough, and it comes to me as a surprise that this is in the snippet. That's... harder to land. I can build it though.

**Comment by adamlofting** [comment]
I think we should implement this on the landing page when a user clicks the stripe or Paypal button. Especially for the first test.

**Comment by ScottDowne** [comment]
Perfect. I was hoping that could be the compromise :)mozilla/donate.mozilla.org wrote:I think we should implement this on the landing page when a user clicks the stripe or Paypal button. Especially for the first test.

**Comment by edrushka** [comment]
Re-assigning to Ali.

**Comment by ScottDowne** [comment]
@alicoding Here was how far I got before mozlando pulled me away: https://github.com/mozilla/donate.mozilla.org/pull/1137/files

**Comment by ScottDowne** [comment]
*yoink*  :space_invader: :space_invader: :space_invader:

**Comment by adamlofting** [comment]
For the sake of this initial test and managing the scope of work, we should only present the pop-up to:

* People making one one-off donation > $5 and < $50 paying in USD.
* Also to manage the scope, let's just start with Variant A "short"

If it's not too much work, we could aslo extend this to CAD and GBP (>5 && <50)

**Comment by alicoding** [comment]
Landed here https://github.com/mozilla/donate.mozilla.org/commit/0ba9c6c3066106db6a43e75514491a0d43c2268d staging URL https://donate.mofostaging.net/en-US/one-page-monthly/ and once @jbuck pushed this to prod @adamlofting can enable this test \o/

**Comment by edrushka** [comment]
Woooo! Yay @alicoding :star: :star: :star:

**Comment by jbuck** [comment]
Landed on production https://donate.mozilla.org/en-US/one-page-monthly/

**Comment by ScottDowne** [comment]
Test is running now.
