### ISSUE TITLE
Build emails for the Gear Store fall campaign

### ISSUE THREAD

**Issue by mmmavis** [mozilla/donate.mozilla.org#950]
for details see: https://github.com/MozillaFoundation/2015-fundraising/issues/50

design: https://github.com/MozillaFoundation/2015-fundraising/issues/50#issuecomment-159450037 (both versions need to be built)

**Comment by mmmavis** [comment]
Email has been built and sent. I'm not sure where to store the final code. This repo or do we create a separate one just for the Salesforce email module (ET)? /cc @adamlofting

**Comment by adamlofting** [comment]
Let's use the mofo-crm repo for this: https://github.com/MozillaFoundation/mofo-crm

I've just added you to that repo. It's currently empty (other than for issues) but we can setup a folder for email templates in there.

(Great work on that email by the way - it looked excellent)

**Comment by valianttry** [comment]
Closing this ticket, re-open if I'm wrong. :smiling_imp:
