### ISSUE TITLE
Improve copy and logo in Stripe checkout flow

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#952]
Our Stripe checkout flow currently looks a little drab without a logo, and with the text chopped off. 

<img width="642" alt="screenshot 2015-11-27 11 59 09" src="https://cloud.githubusercontent.com/assets/1901816/11440895/593398d8-94fe-11e5-8a91-d2d9974b4c22.png">

It's possible to add a logo, and tweak the text to look nicer like this:
<img width="623" alt="screenshot 2015-11-27 12 02 52" src="https://cloud.githubusercontent.com/assets/1901816/11440936/d785b194-94fe-11e5-971b-1d75ddc744ef.png">

Image Spec Here:
https://stripe.com/docs/checkout#integration-options-image

**Comment by adamlofting** [comment]
This is a pretty small task, but flagging so it can be assigned the right priority :smile:

**Comment by jbuck** [comment]
@edrushka Do you have an idea for the charge description? Currently Mozilla Foundation Donation.

**Comment by edrushka** [comment]
I suggest "Mozilla Donation" but @valianttry should confirm.

**Comment by edrushka** [comment]
@cassiemc now that we can no longer use the "m" logo, is there something square we could use to brand our Stripe checkout page. Requirements are: *A relative or absolute URL pointing to a square image of your brand or product. The recommended minimum size is 128x128px. The recommended image types are .gif, .jpeg, and .png.*

**Comment by valianttry** [comment]
I think "Mozilla Donation" or "Donation to Mozilla" are both good. Maybe we could incorporate a red heart for the logo?

**Comment by adamlofting** [comment]
I think the logo always ends up in a circle like the screenshot example above.

**Comment by edrushka** [comment]
Created a design ticket here: #995

**Comment by edrushka** [comment]
Design is done in #995. Re-assigning to @jbuck to implement.

**Comment by jbuck** [comment]
docs are in https://stripe.com/docs/checkout#integration-custom

**Comment by jbuck** [comment]
PR up in https://github.com/mozilla/donate.mozilla.org/pull/1119

**Comment by jbuck** [comment]
This has landed on staging
