### ISSUE TITLE
Make One-page flow the new default

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#953]
@valianttry @edrushka @ScottDowne @alicoding @jbuck @cadecairos 

We've concluded our first A/B of 2015! :boom: 

https://fundraising.mozilla.org/ab-test-three-page-vs-one-page-donation-flow/

This didn't have any impact on revenue (it performs the same as our sequential flow) but it has significant impacts on our code. By switching to the Stripe checkout flow we can dramatically reduce the amount of testing and integration code we need to maintain in our own repo, and make further use of the form as developed and tested by Stripe.

Now, let's test our planned process for making this the new default.
https://github.com/mozilla/donate.mozilla.org/blob/master/docs/Metrics.md#ending-the-test

* The default URLs (https://donate.mofostaging.net/en-US/) where our traffic is currently landing should keep the same URL but be replaced with the `one-page` form. 
* The test forms hosted at https://donate.mofostaging.net/en-US/one-page should then be taken down, and redirects setup to route any lagging traffic back to our default form.

Also, in light of this, we might be able to close some existing bugs that relate to our own form.

**Comment by alicoding** [comment]
For code maintenance this will be a huge win and huge lift to our existing super complex codebase because of the 3 pages flow. Will be nice to see how can we further improve the one page flow here.

**Comment by ScottDowne** [comment]
One thought, We were going to test signups in the donation flow, but with stripe checkout, I don't know if that's possible.

**Comment by adamlofting** [comment]
@ScottDowne I think that was only valuable while we were asking for email address anyway. Let's put our energy into optimizing the thank you email sign-up form instead. I suspect we can make the same gains.

**Comment by valianttry** [comment]
Yes! This is really great news. :smile_cat:

**Comment by ScottDowne** [comment]
This is done.
