### ISSUE TITLE
Test: New UI

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#954]
We plan to roll out our new UI, but we want to A/B test this to understand / double-check if it has an impact on conversion rate.

Design and build tracked in #436

**Comment by adamlofting** [comment]
This test is live, and you can track the results here:
http://app.optimizely.com/l/yEn16U?token=1e7e0924e04bc51d51d3#view=2

@valianttry @edrushka @lovegushwa @thecount @alicoding

**Comment by cassiemc** [comment]
This is awesome to see, thanks @adamlofting (I'm always interested in UI or UX test results, please do loop me in anytime as well!)

**Comment by adamlofting** [comment]
The results are in:
https://fundraising.mozilla.org/ab-test-new-ui-no-news-is-good-news/
