### ISSUE TITLE
Travis test should check the project runs

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#96]
[This PR](https://github.com/mozilla/donate.mozilla.org/pull/92) passed [the CI test](https://travis-ci.org/mozilla/donate.mozilla.org/builds/72901143), but it doesn't actually run.

Running `npm start` would have caused an error like #94 

As a result, this pushed the broken build to staging:

<img width="747" alt="screenshot 2015-07-28 12 07 58" src="https://cloud.githubusercontent.com/assets/1901816/8929939/31d3de3e-3521-11e5-90be-ea016f2582a9.png">

**Comment by ScottDowne** [comment]
Something to do with cache.

That specific node module was already built so when it ran it, it didn't fail.

If it was a module that didn't exist it would have failed as expected.

Now why it existed is another question. I suspect it has something to do with the fact I also loaded that module in another patch.

**Comment by ScottDowne** [comment]
Scratch all that. I don't think it is cache, it looks like Travis doesn't actually run the server, so it's never going to fail for things like this yet.

**Comment by ScottDowne** [comment]
Just a drive by through my email, and took a closer look at this. Man, I totally cruise controlled your initial comment. You had the issue figured out right off the bat.

The only thing I need to figure out is if we need to turn off the server, and if so... how.

We do need the ability to turn it off for tests too, so maybe worth adding anyway.

**Comment by adamlofting** [comment]
Thanks, that makes sense (and no worries about the drive by :car: )

I've marked this ticket as a P2, because it wouldn't block testing next week. So if needed it can slip to next heartbeat.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/132/files
it also gets fixed by:
https://github.com/mozilla/donate.mozilla.org/commit/2638eb81f580ab5db3442293e1b422e82fcf0171

They'll also catch other things.
Can never have two much tests.
