### ISSUE TITLE
Add currency symbols to currency switcher

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#960]
Following the discussion in #911 it might help some users if they can see currency symbols in the currency switcher:

> Another issue might be that the currency switcher isn't obvious to people in es-MX who don't recognise the currency code 'EUR' (we've all got used to this UI now but our audience don't have the same knowledge). Should we test adding the currency symbols back into that drop-down to make it more explicit what it does. 

Filing this as a follow up task.

**Comment by ScottDowne** [comment]
I suggest pushing this out a milestone or two.
