### ISSUE TITLE
FA secure icon is broken

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#97]
(locally at least).

<img width="411" alt="screenshot 2015-07-28 12 12 51" src="https://cloud.githubusercontent.com/assets/1901816/8930019/eeef6fb0-3521-11e5-95cd-40ba162e658e.png">

I can't check on staging at the moment as staging is the broken build.

**Comment by adamlofting** [comment]
Also applies to share icons:

<img width="452" alt="screenshot 2015-07-28 14 16 55" src="https://cloud.githubusercontent.com/assets/1901816/8932167/3985d134-3533-11e5-98d7-35371c064770.png">

**Comment by ScottDowne** [comment]
Yeah, I never got around to moving assets from BSD to this.

Shouldn't be hard.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/120/files

**Comment by adamlofting** [comment]
:star2:
