### ISSUE TITLE
Swap in a sexy new Twitter graphic for the Twitter Card

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#971]
Let's swap in the graphic that says "I <3 the Web. I gave to Mozilla" for the current Facebook one:
https://twitter.com/real7a/status/670359233783865344

Here are awesome Twitter graphics that have already shipped:

https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2qu3ExKWIlvOXVBaFJFN3dYU0k&usp=sharing#

copying @lovegushwa and @natalieworth just in case we need to modify the size / dimensions a bit to fit a Twitter card spec.

**Comment by jbuck** [comment]
For twitter we can implement one of two card types:

1. [Summary Card](https://dev.twitter.com/cards/types/summary) has a small square image that's atleast 120x120.
2. [Summary Card with Large Image](https://dev.twitter.com/cards/types/summary-large-image) has a larger 1.86:1 ratio image, with a minimum size of 280x150.

It's very easy to switch between the two types, so go with whatever looks better!

**Comment by natalieworth** [comment]
@jbuck Are you needing help with design on this one? Not sure if there is already a design ticket open for this? I can definitely help if you do! Shouldn't take long.

**Comment by jbuck** [comment]
@natalieworth If you think we should use the Summary Card with Large Image I can probably just use the existing images, but if we're going to use the square Summary Card image I think I'll need some guidance

**Comment by cassiemc** [comment]
@natalieworth @jbuck Are we going with the large summary card or do you still need design help here?

**Comment by jbuck** [comment]
@cassiemc I'll let @valianttry decided!

**Comment by valianttry** [comment]
large summary card is fine by me! Let's make sure the dimensions are correct so there's no resizing weirdness... and i can help QA. Let's use the version that says "I <3 the Web. I gave to Mozilla"

**Comment by jbuck** [comment]
Landed https://github.com/mozilla/donate.mozilla.org/commit/13a14ac2c348d2cc462850be65e747c8b585d525 and here's what it looks like:

![screenshot 2015-12-01 14 39 49](https://cloud.githubusercontent.com/assets/578466/11512035/3a8ebb62-983a-11e5-9782-948b325de9e1.png)
