### ISSUE TITLE
Design form variant with 'thank you' line before donation

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#973]
@lovegushwa this one should be pretty simple. Can you please design the variant outlined in #159

**Comment by edrushka** [comment]
Copy being finalized in #974

**Comment by edrushka** [comment]
Holding on this until we hear from @adamlofting if we'll run this test before Dec 31.

**Comment by adamlofting** [comment]
I think we can make this a P2 as there are plenty of other bigger tests lined up, and we're getting through the month quite quickly now.

**Comment by edrushka** [comment]
Thanks Adam. I'm actually going to Bluesky this for now. We can put in the Dec 23rd milestone if we have some extra time next week (ha!)
