### ISSUE TITLE
File a list of important dates for Pager Duty crew

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#977]
Increases in snippet traffic
Emails sent
Anything else that could impact donation volume

**Comment by jbuck** [comment]
- December 1st (tomorrow!)
  - Snippet goes from 25% to 50% rotation, so expect a doubling in traffic

**Comment by edrushka** [comment]
Snippet goes to 100% on Monday Dec 21
Next appeal email is Dec 23
