### ISSUE TITLE
Move Secret Key (test key) to environment variable

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#98]
<img width="487" alt="screenshot 2015-07-28 12 14 47" src="https://cloud.githubusercontent.com/assets/1901816/8930042/2c8be45c-3522-11e5-8f69-634b29a8c5d3.png">

And include the test key in the documentation.

**Comment by ScottDowne** [comment]
Merged: https://github.com/mozilla/donate.mozilla.org/commit/49292c739778bf98f997c5b181fe596a3fe5fbed
