### ISSUE TITLE
Uncaught error: Cannot read property 'name' of undefined at /app/routes/index.js:244:40

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#980]
This is from some Heroku logs, line is https://github.com/mozilla/donate.mozilla.org/blob/master/routes/index.js#L244

```
        paypal.completeSingleCheckout(checkoutDetails.response, function(err, data) {
          var paypal_checkout_payment_service = data.paypal_checkout_payment_service;
          if (err) {
            request.log(['error', 'paypal', 'checkout-payment', frequency], {
              request_id,
              paypal_checkout_payment_service,
              // https://developer.paypal.com/docs/api/#errors
              error_name: data.response.name, //                       <-- error was here
              error_message: data.response.message,
              details: data.response.details
            });
            return reply(boom.badRequest('donation failed', err));
          }

          request.log(['paypal', 'checkout', frequency], {
            request_id,
            paypal_checkout_payment_service
          });

          reply.redirect(`${locale}/thank-you/?frequency=${frequency}&tx=${data.txn.PAYMENTINFO_0_TRANSACTIONID}&amt=${data.txn.PAYMENTREQUEST_0_AMT}&cc=${data.txn.CURRENCYCODE}`);
        });
```

**Comment by alicoding** [comment]
If there is an error usually `data` will be `null` or `undefined` which means that line will throw an error, right?

**Comment by ScottDowne** [comment]
In this case, `data` was an object, and `response` was undefined, so `name` failed.

**Comment by alicoding** [comment]
their API is really weird...

**Comment by jbuck** [comment]
I wonder if this was the request module sending a timeout error

**Comment by jbuck** [comment]
@cadecairos I bet the response object isn't available at that point

**Comment by cadecairos** [comment]
Lame, their docs indicated out would be. I thought we were going to test this on staging until Monday...?

**Comment by jbuck** [comment]
I decided the value of the additional logging would be worth the risk of
taking it to production!

Also, I think the problem here might be the request timeout returning an
error...

**Comment by ScottDowne** [comment]
A few more of these today, and also some "Paypal donation failed: ETIMEDOUT"

There were 16 in total, and all clumped together between 12:14:31-12:32:19 today.

Just got another while typing this.

**Comment by ScottDowne** [comment]
A bunch of "Paypal donation failed: read ECONNRESET" now.

**Comment by ScottDowne** [comment]
When hitting up PayPal in  test, it took a long time to redirect to the log in page.

Found this? Looks like paypal is having issues this morning: https://www.paypal-notify.com/main_home

**Comment by alicoding** [comment]
![screen shot 2015-11-29 at 8 11 19 am](https://cloud.githubusercontent.com/assets/4368149/11457205/e16272a6-9670-11e5-856e-ede76651a951.png)

**Comment by ScottDowne** [comment]
Hard to log in and actually get to the alert, but eventually found this:

"Live Site Status Update
Notification: We are experiencing a system issue which may be affecting PayPal APIs and PayPal Website on the PayPal Live Site.

Users may be experiencing timeout errors while going through the PayPal checkout flow and/or accessing https://www.paypal.com. Some merchants would be noticing an increase in timeouts connecting to API endpoints.

Our technical teams have been engaged and are actively working on fixing the same."

**Comment by ScottDowne** [comment]
I'm moving paypal issues to https://github.com/mozilla/donate.mozilla.org/issues/984

**Comment by alicoding** [comment]
Just have to use their search and look for today's event https://www.paypal-notify.com/eventnotification/search 
<img width="660" alt="screen shot 2015-11-29 at 8 23 05 am" src="https://cloud.githubusercontent.com/assets/4368149/11457273/7c4cb7da-9672-11e5-8f06-53547af80d49.png">
