### ISSUE TITLE
Paypal issues Nov 29th and 30th

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#984]
PayPal is experiencing issues, but some donations are still going through:

"Live Site Status Update
Notification: We are experiencing a system issue which may be affecting PayPal APIs and PayPal Website on the PayPal Live Site.

Users may be experiencing timeout errors while going through the PayPal checkout flow and/or accessing https://www.paypal.com. Some merchants would be noticing an increase in timeouts connecting to API endpoints.

Our technical teams have been engaged and are actively working on fixing the same."

**Comment by ScottDowne** [comment]
Have not seen a PayPal timeout in Heroku logs for about 50 minutes.

**Comment by ScottDowne** [comment]
From about 7 to about 9 we had 91 timeouts.

**Comment by jbuck** [comment]
Here's the link to the downtime notification: https://www.paypal-notify.com//eventnotification/event_details?eventId=6923

**Comment by edrushka** [comment]
Do we know what error message people receive when their attempt times out? I.e. does Paypal tell them there's an issue, or does it just....not work.

**Comment by valianttry** [comment]
I'm seeing a couple of donate@ emails about this, here's one:

![redirect_failures_when_trying_to_make_a_donation_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11460279/ea82929e-969d-11e5-849e-0fa9d8474097.png)

**Comment by valianttry** [comment]
@jbuck i'm having trouble logging in for updates, can you drop the latest here?

**Comment by jbuck** [comment]
They're having more issues today: https://www.paypal-notify.com/eventnotification/event_details_popup?eventId=6925

**Comment by jbuck** [comment]
The issues have been resolved

**Comment by ScottDowne** [comment]
We've been talking about the positives and negatives of combinations of displaying a warning for paypal when it's having issues, and maybe disabling but not hiding the button or removing it completely without a warning.

I'm leaning towards displaying a message if it's slow or not working at all, but only disabling it if paypal is 100% down which is unlikely, and never hiding the button.

**Comment by ScottDowne** [comment]
@jbuck there was some paypal downtime yesterday, looks to be concentrated from 4am to 6am, some exceptions, but no incidents in pagerduty.

**Comment by alicoding** [comment]
Also nothing reported on PayPal's alert dashboard
