### ISSUE TITLE
How do I correct a customer address in Stripe?

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#988]
evt_17CLiEG8Mmx3htnx3q9UH1sj

She accidentally selected "United Arab Emirates" not "United States" for country. How do I go in to make these kinds of edits for customers? I get them on occasion in donate@.

**Comment by adamlofting** [comment]
I'm not sure if the country is being stored in Stripe (it might just be for processing the payment):

But this is where you look up a customer: https://dashboard.stripe.com/customers

**Comment by jbuck** [comment]
@valianttry you can edit their country by searching for their customer object in Stripe, and then editing the card card details to the correct country
