### ISSUE TITLE
Is the redirect to 'share' done via React?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#991]
@ScottDowne @alicoding 

We're not seeing much GA traffic reported for our social share page, but I think this is to do with React affecting GA tracking. 

For context: 

This is thank you page views
<img width="494" alt="screenshot 2015-11-30 14 46 29" src="https://cloud.githubusercontent.com/assets/1901816/11474672/6a44fb38-9771-11e5-9d0c-173db5d064aa.png">

This is share views (according to GA)
<img width="565" alt="screenshot 2015-11-30 14 46 55" src="https://cloud.githubusercontent.com/assets/1901816/11474685/80ebf4ea-9771-11e5-8abc-cf4906dfb274.png">

I suspect React is updating the DOM, and the URL, but not triggering a full reload of the page. Would that make sense? 

I was setting up an Optimizely test here, but think we might need to add some custom code to trigger the GA tracking and to start the Optimizely experiment.

**Comment by ScottDowne** [comment]
Hm, the thank you page and share page are redirected in the exact same way.

Why one would work, and the other does not, strikes me as there is more we still don't understand about this.

**Comment by adamlofting** [comment]
Most of the thank you page traffic goes out to paypal and gets referred back again, so I suspect that's triggering the pageview being recorded in GA.

**Comment by ScottDowne** [comment]
Right, so I suspect the thank-you is busted for stripe too.

**Comment by adamlofting** [comment]
I'll poke around at this this morning.

**Comment by adamlofting** [comment]
Confirmed. Stripe thank-you page pageviews are not being captured, but the Stripe ecommerce transactions are being recorded (which is good as this is the most important part for our metrics).

<img width="1185" alt="screenshot 2015-12-01 12 11 50" src="https://cloud.githubusercontent.com/assets/1901816/11500410/deca6840-9824-11e5-8adb-d749598db4e5.png">
<img width="1183" alt="screenshot 2015-12-01 12 11 56" src="https://cloud.githubusercontent.com/assets/1901816/11500411/dee29abe-9824-11e5-9e34-0b90282b65b4.png">

**Comment by adamlofting** [comment]
I'm happy with the fix by @alicoding to record the page view before the `transitionTo`. I might need to add another some further js to trigger optimizely experiments too, but I'll file that as a follow up.
