### ISSUE TITLE
How to check number of new email subscribers from EOY campaign?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#992]
@jessilyndavis what's the best way to look up this number in Exact Target?

Does this require running a query against master subscribers?

For reference, these subscribers will have the source URL set to: `https://donate.mozilla.org/`

**Comment by jessilyndavis** [comment]
Heyo!

2 options:

1) Create a filter on Master_Subscribers to filter by SOURCE_URL, and FOUNDATION_FLG_DATE. Run that filter and it will auto-populate the data extension with results.

2) Create a SQL query on Master_Subscribers and have the data go into a new data extension that you create.

I recommend we hop on a 30 min call to walk through it (might be easier and less scary). Big thing is to *NOT* overwrite Master_Subscribers - which is kinda easy to do you aren't careful.

**Comment by valianttry** [comment]
@adamlofting this sounds a bit tricky -- how will we be able to see results when we test optin variants?

**Comment by adamlofting** [comment]
> how will we be able to see results when we test optin variants?

For the opt-in variants we can use optimizely to track conversion between the form and the thank you page.
