### ISSUE TITLE
How to enable new-flow-test CSS

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#993]
@ScottDowne I'm setting up this Optimizely test now, but need some help.

I can switch the experiment on/off by adding the URL parameter like so:

* https://donate.mofostaging.net/en-GB/
* https://donate.mofostaging.net/en-GB/?test=new-flow-test

I've setup Optimizely on Staging to test this out, but because this is implemented as a redirect, there is a tiny flash of the old content in the variation. 

Can I enable this new UI by setting a class on the something like the body tag? I had a quick look at the code, but I think this is switched on/off in many locations, is that right? (ie in many components).

**Comment by ScottDowne** [comment]
@adamlofting yes, you can add the new-flow-test class to the div right inside `#my-app`.

The div has a `.row` class and should be the only div inside `#my-app`

You'll need to setup this on thank-you and share, but it's the same deal for those too.

**Comment by ScottDowne** [comment]
If we want we can add a more specific classname to the div we need, like `test-container` or something.

**Comment by adamlofting** [comment]
Thanks @ScottDowne this answers my question, so I'm closing this.
