### ISSUE TITLE
Design circular logo for Stripe checkout

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#995]
See issue #952 

Requirements are: A relative or absolute URL pointing to a square image of your brand or product. The recommended minimum size is 128x128px. The recommended image types are .gif, .jpeg, and .png.

Even though that says square, the logo appears in a circle, which is....confusing. See #952 for examples.

**Comment by natalieworth** [comment]
@edrushka Will this be a completely new logo, or should I be formatting something from fundraising/ mozilla into the circle shape? Thanks

**Comment by cassiemc** [comment]
@natalieworth There's a nice screenshot in https://github.com/mozilla/donate.mozilla.org/issues/952 for reference. We should prob just use a mozilla logo. I think the circle is big enough to be able to read the whole word at that size, but we should double check that in a comp. (we shouldn't be using just an 'm' in a circle, and we should avoid creating a new logo for this)

**Comment by edrushka** [comment]
Agree this shouldn't be a completely new logo. Would be good to use a known mozilla asset like the wordmark or mozilla heart. Keep in mind this logo will remain on the form after the EOY campaign, so it shouldn't be tied to our EOY visual design.

**Comment by natalieworth** [comment]
Hey @cassiemc @edrushka @valianttry  I've got 2 versions of the logo up on redpen: https://redpen.io/p/btb6fcfe826208f532 Thanks!

**Comment by natalieworth** [comment]
@cassiemc @edrushka @valianttry Updated versions for the logo is here: https://redpen.io/uo61240e2139bb7d17 and the mockup here: https://redpen.io/vmc6db06ec7166348e

**Comment by natalieworth** [comment]
Updates on the final logo are on Redpen:
01. Mockup: https://redpen.io/sp053bf5dcccac802b
02. Logo: https://redpen.io/fc43ff3b06ee1dd001
I removed the shadows around the 'Mozilla' logo, but have left the shadow around the blue background to fit in with the UI and button Stripe examples. If it's good to go I can link to final .ai file
cc @cassiemc @edrushka @valianttry

**Comment by cassiemc** [comment]
Looks good, R+!

**Comment by natalieworth** [comment]
@edrushka @jbuck Final files for the logo are here: https://docs.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0SGdhOVNZdjBqcW8&usp=drive_web Thanks and let me know if there is anything else I can export for this logo! :)

**Comment by jbuck** [comment]
:tada:
