### ISSUE TITLE
Send receipt emails to recurring donors that didn't receive one

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#998]
In https://github.com/mozilla/donate.mozilla.org/issues/972 I fixed the receipt emails so they work again, but @valianttry wants to go through the donor experience to make sure it's good with the delayed email. We should figure out:

- How many people were affected?

**Comment by valianttry** [comment]
Other Qs:
-- What locales? (in case we have to localize any new content)
-- Did they receive any correspondence at all from us? (e.g. did they receive a PayPal receipt or Stripe receipt?)
-- What will we send them? Just a receipt and it'll appear to be delayed? Will we send all of the owed receipts at the same time? What's the deadline -- e.g. when will they get their 2nd receipt for their 2nd monthly gift? We should send their first one well ahead of the second one.

**Comment by jbuck** [comment]
* All locales are already translated, thankfully enough
* They wouldn't have received any correspondence from us unless they signed up for the mailing list
* Yes, we'd just attempt to resend the email receipt. There's only one email backlog, for donations between when we started the stripe account and yesterday.
* The deadline would be... December 9th? Hrm, shit.

**Comment by valianttry** [comment]
According to Google Analytics we're talking about 1,622 individuals. 
Plan A:
How long before we can send these donors their first receipt? If it's something we can do really soon, like before Mozlando, let's do that!
Plan B:
Q: IS it possible to combine receipts for donation #1 with the donation #2 receipt email? E.g. it would look something like:
---------
TRANSACTION RECEIPT FOR YOUR RECORDS:
Roger Rabbit
Monthly gift amount: $3 (11/09/2015)
Monthly gift amount: $3 (12/09/2015)
Transaction ID: ch_12345abcdefjghipop
1234 American Dream Blvd Apt. F
Big City 33134
United States

**Comment by valianttry** [comment]
whoa. crazy formatting glitch.

**Comment by jbuck** [comment]
I like plan A better!

**Comment by jbuck** [comment]
Charges before 2015-11-28T03:50:58Z

**Comment by jbuck** [comment]
Done!
